#!/bin/bash

set -e

export iOSOpenDevPath="/opt/iOSOpenDev"
runThis="$iOSOpenDevPath/bin/iod-setup-sdk"

if [[ -f "$runThis" ]]; then
	echo "Running $runThis..."
	"$runThis" -sdk iphoneos
	"$runThis" -sdk iphonesimulator
else
	echo "Missing $runThis"
	exit 1
fi

exit 0