/**
 * This header is generated by class-dump-z 0.2b.
 *
 * Source: (null)
 */




@protocol AFUIUtteranceViewDelegate <NSObject>
@optional
- (BOOL)utteranceViewTextShouldPreventCorrection:(id)utteranceViewText;
- (void)utteranceViewTextWillBeginCorrecting:(id)utteranceViewText;
- (void)utteranceViewTextDidChange:(id)utteranceViewText;
- (void)utteranceViewTextDidFinishCorrecting:(id)utteranceViewText;
- (void)utteranceViewInfoButtonHit:(id)hit;
@end

