/**
 * This header is generated by class-dump-z 0.2b.
 *
 * Source: (null)
 */

#import "SBUnknownSuperclass.h"
#import "SpringBoard-Structs.h"

@class UIView;

@interface SBActivationView : SBUnknownSuperclass {
	UIView *_backgroundView;	// 48 = 0x30
	int _mode;	// 52 = 0x34
}
@property(readonly, assign) int mode;	// G=0xc219d; converted property
- (id)initWithFrame:(CGRect)frame mode:(int)mode;	// 0xc21f9
// converted property getter: - (int)mode;	// 0xc219d
- (void)dealloc;	// 0xc21ad
@end
