/**
 * This header is generated by class-dump-z 0.2b.
 *
 * Source: (null)
 */

#import "SBUnknownSuperclass.h"

@class NSMutableDictionary;

@interface SBAceClassMap : SBUnknownSuperclass {
	NSMutableDictionary *_classMap;	// 4 = 0x4
}
- (id)init;	// 0x133bd5
- (void)dealloc;	// 0x133e29
- (void)addBundle:(id)bundle objCClassName:(id)name forAceClass:(id)aceClass inGroup:(id)group;	// 0x133d35
- (id)entryForAceClass:(id)aceClass inGroup:(id)group;	// 0x133cfd
- (id)bundleForAceClass:(id)aceClass inGroup:(id)group;	// 0x133cc9
- (id)classNameForAceClass:(id)aceClass inGroup:(id)group;	// 0x133c95
- (id)description;	// 0x133c39
@end
