/**
 * This header is generated by class-dump-z 0.2b.
 *
 * Source: (null)
 */

#import "SBUnknownSuperclass.h"
#import "SpringBoard-Structs.h"

@class UIButton, UISlider, UIView;

@interface SBAirPlayBarView : SBUnknownSuperclass {
	UIView *_speakerIcon;	// 48 = 0x30
	UIButton *_airPlayButton;	// 52 = 0x34
	UISlider *_volumeSlider;	// 56 = 0x38
	BOOL _airPlayEnabled;	// 60 = 0x3c
}
@property(readonly, assign, nonatomic) UISlider *volumeSlider;	// G=0x12c895; @synthesize=_volumeSlider
@property(readonly, assign, nonatomic) UIButton *airPlayButton;	// G=0x12c885; @synthesize=_airPlayButton
@property(assign, nonatomic, getter=isAirPlayEnabled) BOOL airPlayEnabled;	// G=0x12c875; S=0x12cd2d; 
- (id)initWithFrame:(CGRect)frame;	// 0x12c8a5
- (void)layoutSubviews;	// 0x12cd41
// declared property getter: - (BOOL)isAirPlayEnabled;	// 0x12c875
// declared property setter: - (void)setAirPlayEnabled:(BOOL)enabled;	// 0x12cd2d
- (void)setAirPlayEnabled:(BOOL)enabled animated:(BOOL)animated;	// 0x12cb71
// declared property getter: - (id)airPlayButton;	// 0x12c885
// declared property getter: - (id)volumeSlider;	// 0x12c895
@end
