/**
 * This header is generated by class-dump-z 0.2b.
 *
 * Source: (null)
 */

#import "SBDisplay.h"
#import "SpringBoard-Structs.h"

@class NSMutableDictionary, SBAlertWindow, SBAlertDisplay;

@interface SBAlert : SBDisplay {
	SBAlertDisplay *_display;	// 48 = 0x30
	NSMutableDictionary *_dictionary;	// 52 = 0x34
	SBAlertWindow *_deferredAlertWindow;	// 56 = 0x38
}
@property(retain) SBAlertDisplay *display;	// G=0x33a8d; S=0x33afd; converted property
+ (void)registerForAlerts;	// 0x33a75
+ (id)alertWindow;	// 0x33a79
+ (void)test;	// 0x33a89
+ (void)activateAlertForController:(id)controller animated:(BOOL)animated animateCurrentDisplayOut:(BOOL)anOut withDelay:(BOOL)delay isSlidingDisplay:(BOOL)display;	// 0x34209
+ (void)deactivateAlertForController:(id)controller animated:(BOOL)animated animateOldDisplayInWithStyle:(int)style isSlidingDisplay:(BOOL)display;	// 0x33f35
+ (void)alertAdapterDisplayDidDisappear:(id)alertAdapterDisplay;	// 0x33dfd
+ (id)_adapterForController:(id)controller;	// 0x33e8d
- (void)dealloc;	// 0x33ea9
// converted property getter: - (id)display;	// 0x33a8d
// converted property setter: - (void)setDisplay:(id)display;	// 0x33afd
- (id)alertDisplayViewWithSize:(CGSize)size;	// 0x33a9d
- (void)setObject:(id)object forKey:(id)key;	// 0x33b59
- (id)objectForKey:(id)key;	// 0x33bd1
- (void)removeObjectForKey:(id)key;	// 0x33bf5
- (BOOL)allowsStackingOfAlert:(id)alert;	// 0x33aa1
- (BOOL)undimsDisplay;	// 0x33aa5
- (BOOL)showsSpringBoardStatusBar;	// 0x33aa9
- (float)finalAlpha;	// 0x33aad
- (CGRect)alertWindowRect;	// 0x349a5
- (Class)alertWindowClass;	// 0x33c19
- (void)_updateStatusBarLockAndTime;	// 0x33c35
- (int)statusBarStyleOverridesToCancel;	// 0x33ab5
- (void)activate;	// 0x34749
- (void)tearDownAlertWindow:(id)window;	// 0x33cc1
- (int)interfaceOrientationForActivation;	// 0x33d79
- (void)removeFromView;	// 0x344a9
- (void)deactivate;	// 0x34371
- (int)effectiveStatusBarStyle;	// 0x33dad
- (double)autoDimTime;	// 0x33abd
- (int)statusBarStyle;	// 0x33ac9
- (void)didAnimateLockKeypadIn;	// 0x33acd
- (void)didAnimateLockKeypadOut;	// 0x33ad1
- (void)didFinishAnimatingIn;	// 0x33ad5
- (void)didFinishAnimatingOut;	// 0x33ad9
- (BOOL)handleMenuButtonTap;	// 0x33add
- (BOOL)shouldDeactivateAlertItemsOnActivation;	// 0x33ae1
- (BOOL)hasTranslucentBackground;	// 0x33ae5
- (BOOL)handleLockButtonPressed;	// 0x33ae9
- (BOOL)handleVolumeUpButtonPressed;	// 0x33aed
- (BOOL)handleVolumeDownButtonPressed;	// 0x33af1
- (BOOL)handleHeadsetButtonPressed:(BOOL)pressed;	// 0x33af5
- (BOOL)suppressesNotifications;	// 0x33af9
@end

