/**
 * This header is generated by class-dump-z 0.2b.
 *
 * Source: (null)
 */

#import "SBUnknownSuperclass.h"
#import "SpringBoard-Structs.h"

@class UIImageView, UILabel;

@interface SBAlertImageView : SBUnknownSuperclass {
	UIImageView *_imageView;	// 48 = 0x30
	UILabel *_labelView;	// 52 = 0x34
}
- (id)initWithFrame:(CGRect)frame errorString:(id)string;	// 0xd27cd
- (void)dealloc;	// 0xd2665
- (void)layoutSubviews;	// 0xd26c5
@end
