/**
 * This header is generated by class-dump-z 0.2b.
 *
 * Source: (null)
 */

#import "SBUnknownSuperclass.h"


@interface SBAmbientLightSensorInterface : SBUnknownSuperclass {
}
+ (void)disableAutoBrightness;	// 0x1a4ffd
+ (void)enableAutoBrightness;	// 0x1a4fe9
+ (void)enableAutoBrightnessWithOptions:(int)options;	// 0x1a50ad
@end
