/**
 * This header is generated by class-dump-z 0.2b.
 *
 * Source: (null)
 */

#import "SBUnknownSuperclass.h"

@class CADisplayLink, NSArray, UIView;

@interface SBAnimationStepper : SBUnknownSuperclass {
	id m_delegate;	// 4 = 0x4
	UIView *m_view;	// 8 = 0x8
	NSArray *m_animatingSubviews;	// 12 = 0xc
	double m_duration;	// 16 = 0x10
	float m_percentage;	// 24 = 0x18
	CADisplayLink *m_displayLink;	// 28 = 0x1c
	double m_finishBackwardTimestamp;	// 32 = 0x20
	double m_finishBackwardDuration;	// 40 = 0x28
	float m_finishBackwardPercentage;	// 48 = 0x30
}
@property(assign, nonatomic) id delegate;	// G=0x132731; S=0x132741; @synthesize=m_delegate
@property(retain, nonatomic) UIView *view;	// G=0x132721; S=0x13277d; @synthesize=m_view
@property(copy, nonatomic) NSArray *animatingSubviews;	// G=0x132711; S=0x1327a5; @synthesize=m_animatingSubviews
@property(assign, nonatomic) double duration;	// G=0x1326e5; S=0x1326fd; @synthesize=m_duration
@property(assign, nonatomic) float percentage;	// G=0x1326d5; S=0x132b7d; @synthesize=m_percentage
- (id)init;	// 0x132751
- (void)dealloc;	// 0x132d19
- (void)stepAnimationsInView:(id)view animatingSubviews:(id)subviews duration:(double)duration;	// 0x132c39
// declared property setter: - (void)setPercentage:(float)percentage;	// 0x132b7d
- (void)finishForwardToEnd;	// 0x132b21
- (void)finishBackwardToStart;	// 0x1329f9
- (void)updateFinishBackwardToStart:(id)start;	// 0x1327c9
// declared property getter: - (float)percentage;	// 0x1326d5
// declared property getter: - (double)duration;	// 0x1326e5
// declared property setter: - (void)setDuration:(double)duration;	// 0x1326fd
// declared property getter: - (id)animatingSubviews;	// 0x132711
// declared property setter: - (void)setAnimatingSubviews:(id)subviews;	// 0x1327a5
// declared property getter: - (id)view;	// 0x132721
// declared property setter: - (void)setView:(id)view;	// 0x13277d
// declared property getter: - (id)delegate;	// 0x132731
// declared property setter: - (void)setDelegate:(id)delegate;	// 0x132741
@end
