/**
 * This header is generated by class-dump-z 0.2b.
 *
 * Source: (null)
 */

#import "SBUnknownSuperclass.h"
#import "SpringBoard-Structs.h"

@class NSMutableDictionary, NSString, NSMutableArray, SBAppContextHostView;

@interface SBAppContextHostManager : SBUnknownSuperclass {
	SBAppContextHostView *_contextHostView;	// 4 = 0x4
	NSString *_appBundleID;	// 8 = 0x8
	NSMutableArray *_contexts;	// 12 = 0xc
	BOOL _hostingEnabled;	// 16 = 0x10
	NSMutableArray *_hostRequesters;	// 20 = 0x14
	NSMutableDictionary *_hostRequesterInfo;	// 24 = 0x18
}
@property(copy, nonatomic) NSString *appBundleID;	// G=0xdbf94; S=0xdc250; @synthesize=_appBundleID
@property(readonly, assign, nonatomic, getter=isHostingEnabled) BOOL hostingEnabled;	// G=0xdbf7c; @synthesize=_hostingEnabled
@property(readonly, assign, nonatomic) unsigned contextCount;	// G=0xdd0e0; 
- (id)init;	// 0xdc0ec
- (void)dealloc;	// 0xde14c
- (id)description;	// 0xde09c
- (id)hostViewForRequester:(id)requester;	// 0xde070
- (void)enableHostingForRequester:(id)requester orderFront:(BOOL)front;	// 0xddd2c
- (void)disableHostingForRequester:(id)requester;	// 0xdd9f8
- (void)disableHostingForAllRequesters;	// 0xdd8d4
- (void)orderRequesterFront:(id)front;	// 0xdd6e8
- (void)setContextId:(unsigned)anId hidden:(BOOL)hidden forRequester:(id)requester;	// 0xdd538
- (id)_realContextHostViewWhichIReallyNeedToAccessAndIKnowWhatImDoingISwear;	// 0xdbf68
- (void)_notePropertiesSetOnRealContextHostViewWhichIReallyNeedToChangeAndIKnowWhatImDoingISwear:(id)changeAndIKnowWhatImDoingISwear originalProperties:(id)properties forRequester:(id)requester;	// 0xdd4e0
- (BOOL)_requesterIsFrontmost:(id)frontmost;	// 0xdd454
- (id)_infoForRequester:(id)requester;	// 0xdd3ac
- (void)_applyRequesterInfo:(id)info;	// 0xdd1d8
- (void)_removeRequesterInfo:(id)info;	// 0xdd174
- (void)_setContext:(id)context hidden:(BOOL)hidden;	// 0xdd120
// declared property getter: - (unsigned)contextCount;	// 0xdd0e0
- (void)willOrderInContextWithId:(unsigned)anId windowLevel:(float)level windowOutput:(int)output flush:(BOOL)flush;	// 0xdcb50
- (void)didOrderOutContextWithId:(unsigned)anId;	// 0xdc878
- (void)setOrderOutPending:(BOOL)pending forContextId:(unsigned)contextId;	// 0xdc744
- (void *)createIOSurfaceForFrame:(CGRect)frame;	// 0xdc70c
- (void *)createIOSurfaceForFrame:(CGRect)frame outTransform:(CGAffineTransform *)transform;	// 0xdc6cc
- (void *)createIOSurfaceForFrame:(CGRect)frame excludeContext:(unsigned)context outTransform:(CGAffineTransform *)transform;	// 0xdc67c
- (void *)createIOSurfaceForFrame:(CGRect)frame excludeContext:(unsigned)context usePurpleGfx:(BOOL)gfx outTransform:(CGAffineTransform *)transform;	// 0xdc45c
- (void)_adjustLayerFrameAndTransform:(id)transform;	// 0xdc284
// declared property getter: - (BOOL)isHostingEnabled;	// 0xdbf7c
// declared property getter: - (id)appBundleID;	// 0xdbf94
// declared property setter: - (void)setAppBundleID:(id)anId;	// 0xdc250
@end
