/**
 * This header is generated by class-dump-z 0.2b.
 *
 * Source: (null)
 */

#import "SBUnknownSuperclass.h"
#import "SpringBoard-Structs.h"

@class SBAppContextHostManager;

@interface SBAppContextHostView : SBUnknownSuperclass {
	SBAppContextHostManager *_manager;	// 48 = 0x30
}
@property(assign, nonatomic) SBAppContextHostManager *manager;	// G=0xdbfb0; S=0xdbfc4; @synthesize=_manager
- (id)initWithDefaultSize;	// 0xde3b0
- (id)initWithFrame:(CGRect)frame;	// 0xde2dc
- (id)description;	// 0xde234
- (id)hitTest:(CGPoint)test withEvent:(id)event;	// 0xdbfa8
// declared property getter: - (id)manager;	// 0xdbfb0
// declared property setter: - (void)setManager:(id)manager;	// 0xdbfc4
@end
