/**
 * This header is generated by class-dump-z 0.2b.
 *
 * Source: (null)
 */

#import "SBUnknownSuperclass.h"


@interface SBAppRatingsAlertSheet : SBUnknownSuperclass {
}
- (void)layout;	// 0xdef45
@end
