/**
 * This header is generated by class-dump-z 0.2b.
 *
 * Source: (null)
 */

#import "SpringBoard-Structs.h"
#import "SBNewsstandItemIconViewBase.h"


@interface SBAppSwitcherNewsstandItemIconView : SBNewsstandItemIconViewBase {
}
+ (BOOL)allowsRecycling;	// 0x147ce5
+ (id)createBadgeLabelImageAndGetTextCenterPoint:(CGPoint *)point;	// 0x149d99
+ (float)_badgeLabelFontSize;	// 0x149ec9
+ (CGPoint)badgeLabelCenterPoint;	// 0x149e41
- (void)positionCloseBoxOfType:(int)type;	// 0x14a391
- (void)positionIconImageView;	// 0x14a111
- (float)_badgeHorizontalPadding;	// 0x149f11
- (float)_badgeVerticalPadding;	// 0x14a09d
- (id)_superviewForBadge;	// 0x149d89
- (id)_overriddenBadgeTextForText:(id)text;	// 0x147ce9
@end

