/**
 * This header is generated by class-dump-z 0.2b.
 *
 * Source: (null)
 */

#import "SBUnknownSuperclass.h"

@class NSMutableSet, NSMutableDictionary, NSOperationQueue, SBProcess, CPDistributedNotificationCenter, NSLock, NSDictionary;

@interface SBApplicationController : SBUnknownSuperclass {
	NSDictionary *_pendingApplicationDictionaries;	// 4 = 0x4
	NSMutableDictionary *_applications;	// 8 = 0x8
	NSMutableDictionary *_applicationsByBundleIdentifer;	// 12 = 0xc
	NSMutableSet *_applicationsPlayingMutedAudioSinceLastLock;	// 16 = 0x10
	SBProcess *_processCurrentlyRecordingAudio;	// 20 = 0x14
	BOOL _isLocationInUse;	// 24 = 0x18
	NSDictionary *_backgroundDisplayDict;	// 28 = 0x1c
	unsigned _ignoreUninstallationEventCount;	// 32 = 0x20
	CPDistributedNotificationCenter *_appStateNotificationCenter;	// 36 = 0x24
	NSOperationQueue *_backgroundOperationQueue;	// 40 = 0x28
	NSLock *_applicationsLock;	// 44 = 0x2c
	NSMutableDictionary *_systemAppsVisibilityOverrides;	// 48 = 0x30
}
@property(retain) NSDictionary *pendingApplicationDictionaries;	// G=0xcbc39; S=0xcbc15; @synthesize=_pendingApplicationDictionaries
@property(readonly, assign) BOOL isLocationInUse;	// G=0xca8f5; converted property
+ (id)_sharedInstanceCreateIfNecessary:(BOOL)necessary;	// 0xcbb9d
+ (id)sharedInstance;	// 0xcbb41
+ (id)sharedInstanceIfExists;	// 0xcbb55
- (id)init;	// 0xcec59
- (void)dealloc;	// 0xceae5
- (void)_unregisterForAVSystemControllerNotifications;	// 0xca981
- (void)_registerForAVSystemControllerNotifications;	// 0xcaa15
- (void)_mediaServerConnectionDied:(id)died;	// 0xcabb1
- (void)_recordingStateChanged:(id)changed;	// 0xce8fd
- (void)_unusuallyMutedAudioPlaying:(id)playing;	// 0xcabdd
- (void)_lockStateChanged:(id)changed;	// 0xcad51
- (void)_updateLocationState;	// 0xce88d
- (void)buildLocationState;	// 0xce835
// converted property getter: - (BOOL)isLocationInUse;	// 0xca8f5
- (id)allApplications;	// 0xcae1d
- (id)applicationsWithBundleIdentifier:(id)bundleIdentifier;	// 0xce6bd
- (id)applicationsWithPid:(int)pid;	// 0xce5bd
- (id)processWithPid:(int)pid;	// 0xce4e9
- (id)applicationWithDisplayIdentifier:(id)displayIdentifier;	// 0xcae79
- (id)applicationWithPid:(int)pid;	// 0xce4e1
- (id)iPod;	// 0xcaf1d
- (id)applicationCurrentlyRecordingAudio;	// 0xcaf81
- (id)dataActivation;	// 0xcafc9
- (id)setupApplication;	// 0xcafe5
- (id)webApplications;	// 0xce3ed
- (id)newsstandApps;	// 0xce2d9
- (void)_preLoadApplications;	// 0xcb001
- (void)_sendInstalledAppsDidChangeNotification:(id)_sendInstalledApps removed:(id)removed modified:(id)modified;	// 0xce155
- (void)_postLoadApplications:(id)applications removed:(id)removed modified:(id)modified updateRestrictions:(BOOL)restrictions;	// 0xcb011
- (void)_loadApplication:(id)application dictionary:(id)dictionary;	// 0xcb071
- (void)_loadApplication:(id)application dictionary:(id)dictionary allowDemoOnly:(BOOL)only;	// 0xcb0dd
- (id)_loadApplications:(BOOL)applications;	// 0xcda49
- (BOOL)loadApplication:(id)application;	// 0xcd779
- (id)loadApplications;	// 0xcb379
- (void)loadApplicationsAndIcons:(id)icons reveal:(BOOL)reveal popIn:(BOOL)anIn reloadAllIcons:(BOOL)icons4;	// 0xcd511
- (void)removeApplicationsFromModelWithBundleIdentifier:(id)bundleIdentifier;	// 0xcd385
- (void)uninstallApplication:(id)application;	// 0xcb38d
- (void)_decrementUninstallationEventCount;	// 0xca905
- (void)waitForOperationsToComplete;	// 0xcb709
- (Class)applicationClassForInfoDictionary:(id)infoDictionary;	// 0xcb729
- (void)loadApplicationsWithBundle:(id)bundle bundlePath:(id)path isSystemApplication:(BOOL)application defaultTags:(id)tags signerIdentity:(id)identity provisioningProfileValidated:(BOOL)validated seatbeltEnvironmentVariables:(id)variables;	// 0xcca0d
- (BOOL)_hasRequiredCapabilities:(id)capabilities;	// 0xcc909
- (void)updateSchemesForInfoDictionary:(id)infoDictionary displayIdentifier:(id)identifier application:(id)application;	// 0xcc3bd
- (void)_applicationInstallationCallback:(id)callback;	// 0xcb839
- (void)_handleInstalledApplicationDictionaryIfReceived;	// 0xcc379
- (void)processPendingInstalls;	// 0xcb955
- (void)applicationStateChanged:(id)changed state:(unsigned)state;	// 0xcbf51
- (void)_reloadBackgroundIDsDict;	// 0xcbead
- (void)_setSuspendTypeForApp:(id)app;	// 0xcb981
- (void)updateBackgroundAppPrefs;	// 0xcbdc1
- (int)appVisibilityOverrideForBundleIdentifier:(id)bundleIdentifier;	// 0xcbaf9
- (BOOL)_updateAppIconVisibilityOverrides;	// 0xcbc51
// declared property getter: - (id)pendingApplicationDictionaries;	// 0xcbc39
// declared property setter: - (void)setPendingApplicationDictionaries:(id)dictionaries;	// 0xcbc15
@end
