/**
 * This header is generated by class-dump-z 0.2b.
 *
 * Source: (null)
 */

#import "SBAppToAppTransitionView.h"


@interface SBAppShuffleView : SBAppToAppTransitionView {
}
- (void)beginTransition;	// 0x120c8d
- (void)endTransition;	// 0x120289
@end

