/**
 * This header is generated by class-dump-z 0.2b.
 *
 * Source: (null)
 */

#import "SpringBoard-Structs.h"
#import "UIScrollViewDelegate.h"


@protocol SBAppSwitcherScrollViewDelegate <UIScrollViewDelegate>
- (BOOL)scrollView:(id)view shouldCancelInContentForView:(id)view2;
@end

