/**
 * This header is generated by class-dump-z 0.2b.
 *
 * Source: (null)
 */

#import "SpringBoard-Structs.h"
#import "SBSystemLocalNotificationAlertDelegate.h"
#import "SBDisplay.h"

@class NSDate, PCPersistentTimer, UILocalNotification, SBCFBundle, SBAppContextHostManager, NSTimer, NSArray, NSDictionary, UIRemoteApplication, SBProcessAssertion, NSString, SBProcess, NSMutableArray;

@interface SBApplication : SBDisplay <SBSystemLocalNotificationAlertDelegate> {
	NSString *_bundleIdentifier;	// 48 = 0x30
	NSString *_displayIdentifier;	// 52 = 0x34
	NSString *_path;	// 56 = 0x38
	NSString *_bundleVersion;	// 60 = 0x3c
	NSString *_longDisplayName;	// 64 = 0x40
	NSString *_defaultImageName;	// 68 = 0x44
	NSString *_author;	// 72 = 0x48
	NSArray *_folderNames;	// 76 = 0x4c
	NSString *_fallbackFolderName;	// 80 = 0x50
	NSDictionary *_searchDomainLaunchInfo;	// 84 = 0x54
	SBCFBundle *_cachedBundle;	// 88 = 0x58
	SBProcess *_process;	// 92 = 0x5c
	id _processObserver;	// 96 = 0x60
	SBProcessAssertion *_resumeProcessAssertion;	// 100 = 0x64
	SBProcessAssertion *_suspendingProcessAssertion;	// 104 = 0x68
	double _modificationDate;	// 108 = 0x6c
	SBAppContextHostManager *_contextHostManager;	// 116 = 0x74
	NSString *_displayName;	// 120 = 0x78
	NSMutableArray *_tags;	// 124 = 0x7c
	UIRemoteApplication *_remoteApplication;	// 128 = 0x80
	NSDictionary *_seatbeltEnvVars;	// 132 = 0x84
	NSString *_signerIdentity;	// 136 = 0x88
	unsigned _activationEventSequenceNumber;	// 140 = 0x8c
	NSTimer *_watchdogTimer;	// 144 = 0x90
	double _userLaunchEventTime;	// 148 = 0x94
	unsigned _monitoringLocaleAndTimeChanges : 1;	// 156 = 0x9c
	unsigned _watchdogType : 4;	// 156 = 0x9c
	unsigned _doingBackgroundNetworking : 16;	// 156 = 0x9c
	unsigned _failedLaunchCount : 8;	// 158 = 0x9e
	unsigned _provisioningProfileValidated : 1;	// 159 = 0x9f
	unsigned _enabled : 1;	// 159 = 0x9f
	unsigned _isSystemApplication : 1;	// 159 = 0x9f
	unsigned _isSystemProvisioningApplication : 1;	// 160 = 0xa0
	unsigned _hasMiniAlerts : 1;	// 160 = 0xa0
	unsigned _lastExitWasAbnormal : 1;	// 160 = 0xa0
	unsigned _suspendedEventsOnly : 1;	// 160 = 0xa0
	unsigned _lastSuspendWasSEOUnderLock : 1;	// 160 = 0xa0
	unsigned _usingLocation : 1;	// 160 = 0xa0
	unsigned _disallowsLocationBadge : 1;	// 160 = 0xa0
	unsigned _deactivatingForForcedExit : 1;	// 160 = 0xa0
	unsigned _isUnsupportediBooks : 1;	// 161 = 0xa1
	unsigned _isRevealable : 1;	// 161 = 0xa1
	unsigned _dataFlagsIsSet : 1;	// 161 = 0xa1
	unsigned _isClassic : 1;	// 161 = 0xa1
	unsigned _isGameCenterEnabled : 1;	// 161 = 0xa1
	unsigned _wasGameCenterEverEnabled : 1;	// 161 = 0xa1
	unsigned _wantsAggressiveJetsamDuringActivation : 1;	// 161 = 0xa1
	unsigned _backgroundContinuationEnabled : 1;	// 161 = 0xa1
	unsigned _backgroundContinuationEnabledValid : 1;	// 162 = 0xa2
	unsigned _supportsAudioBackgroundMode : 1;	// 162 = 0xa2
	unsigned _supportsLocationBackgroundMode : 1;	// 162 = 0xa2
	unsigned _supportsVOIPBackgroundMode : 1;	// 162 = 0xa2
	unsigned _supportsEABackgroundMode : 1;	// 162 = 0xa2
	unsigned _supportsContinuousBackgroundMode : 1;	// 162 = 0xa2
	unsigned _supportsNewsstandContentBackgroundMode : 1;	// 162 = 0xa2
	unsigned _wantsUnboundedTaskCompletionAssertions : 1;	// 162 = 0xa2
	unsigned _prefersSavedSnapshots : 1;	// 163 = 0xa3
	unsigned _hasBeenFrontmost : 1;	// 163 = 0xa3
	unsigned _requiresHiDPI : 1;	// 163 = 0xa3
	unsigned _hasWatchdogAssertions : 1;	// 163 = 0xa3
	unsigned _supportsPortraitOrientation : 1;	// 163 = 0xa3
	unsigned _supportsPortraitUpsideDownOrientation : 1;	// 163 = 0xa3
	unsigned _supportsLandscapeLeftOrientation : 1;	// 163 = 0xa3
	unsigned _supportsLandscapeRightOrientation : 1;	// 163 = 0xa3
	unsigned _terminationAssertions : 8;	// 164 = 0xa4
	unsigned _terminationAssertionsForCacheCleaning : 8;	// 165 = 0xa5
	unsigned _defaultStatusBarStyle : 8;	// 166 = 0xa6
	BOOL _defaultStatusBarHidden;	// 167 = 0xa7
	unsigned _defaultInterfaceOrientation : 8;	// 168 = 0xa8
	unsigned _defaultInterfaceOrientationOverride : 8;	// 169 = 0xa9
	unsigned _interfaceOrientationOverrideSet : 1;	// 170 = 0xaa
	unsigned _sbUsesNetwork : 8;	// 170 = 0xaa
	unsigned _dataFlags : 8;	// 171 = 0xab
	unsigned _hasShownDataPlanAlertSinceLock : 1;	// 172 = 0xac
	unsigned _launchAlerts : 8;	// 172 = 0xac
	unsigned _suspendType : 8;	// 173 = 0xad
	unsigned _uninstalled : 1;	// 174 = 0xae
	unsigned _isLaunchableDuringSetup : 1;	// 174 = 0xae
	int _preferredBackgroundJetsamPriority;	// 176 = 0xb0
	int _ratingRank;	// 180 = 0xb4
	Class _iconClass;	// 184 = 0xb8
	NSArray *_customMachServices;	// 188 = 0xbc
	NSArray *_externalAccessoryProtocols;	// 192 = 0xc0
	NSDictionary *_customSpotlightIconPaths;	// 196 = 0xc4
	NSArray *_cachedLocalNotifications;	// 200 = 0xc8
	NSTimer *_terminateIfRunningTimer;	// 204 = 0xcc
	unsigned _cachedApplicationState;	// 208 = 0xd0
	opaque_pthread_mutex_t _appStateMutex;	// 212 = 0xd4
	NSDate *_nextApplicationWakeDate;	// 256 = 0x100
	PCPersistentTimer *_applicationWakeTimer;	// 260 = 0x104
	PCPersistentTimer *_localNotificationTimer;	// 264 = 0x108
	UILocalNotification *_pendingLocalNotification;	// 268 = 0x10c
	SBProcessAssertion *_transientProcessAssertion;	// 272 = 0x110
	NSTimer *_transientSuspendTimer;	// 276 = 0x114
	int _transientAssertionType;	// 280 = 0x118
	SBProcessAssertion *_periodicWakeProcessAssertion;	// 284 = 0x11c
	NSTimer *_periodicWakeSuspendTimer;	// 288 = 0x120
	SBProcessAssertion *_continuousBackgroundProcessAssertion;	// 292 = 0x124
	SBProcessAssertion *_simpleRemoteActionProcessAssertion;	// 296 = 0x128
}
@property(retain, nonatomic) SBProcess *process;	// G=0x35045; S=0x36e05; @synthesize=_process
@property(copy) NSString *displayIdentifier;	// G=0x36185; S=0x3615d; @synthesize=_displayIdentifier
@property(assign, getter=isUsingLocation) BOOL usingLocation;	// G=0x35011; S=0x37101; 
@property(assign) BOOL enabled;	// G=0x34aa9; S=0x34abd; converted property
@property(retain) NSMutableArray *tags;	// G=0x34af1; S=0x3543d; converted property
@property(assign) BOOL hasMiniAlerts;	// G=0x34b01; S=0x34b15; converted property
@property(assign) BOOL hasShownDataPlanAlertSinceLock;	// G=0x34b71; S=0x34b85; converted property
@property(assign) BOOL isUnsupportediBooks;	// G=0x34c79; S=0x34c8d; converted property
@property(retain) NSString *displayName;	// G=0x34cfd; S=0x3e361; converted property
@property(assign) BOOL isClassic;	// G=0x34d79; S=0x3bcf9; converted property
@property(assign) BOOL backgroundContinuationEnabled;	// G=0x34dd1; S=0x34de5; converted property
@property(retain) id applicationNextWakeDate;	// G=0x3b6e5; S=0x3b639; converted property
@property(retain) id seatbeltEnvironmentVariables;	// G=0x34e09; S=0x386b5; converted property
@property(assign) BOOL hasBeenFrontmost;	// G=0x34e19; S=0x34e2d; converted property
@property(readonly, retain) NSString *bundleIdentifier;	// G=0x34a61; converted property
@property(readonly, retain) NSString *path;	// G=0x34a71; converted property
@property(readonly, retain) NSString *bundleVersion;	// G=0x34a99; converted property
@property(readonly, retain) NSString *longDisplayName;	// G=0x34d0d; converted property
@property(readonly, retain) NSString *author;	// G=0x34d1d; converted property
@property(readonly, retain) NSArray *folderNames;	// G=0x3e169; converted property
@property(readonly, retain) NSString *fallbackFolderName;	// G=0x3e0f1; converted property
@property(readonly, assign) double modificationDate;	// G=0x34a81; converted property
@property(readonly, retain) SBAppContextHostManager *contextHostManager;	// G=0x34df9; converted property
@property(readonly, retain) UIRemoteApplication *remoteApplication;	// G=0x379e1; converted property
@property(readonly, retain) NSString *signerIdentity;	// G=0x34f41; converted property
@property(readonly, assign) unsigned activationEventSequenceNumber;	// G=0x34a51; converted property
@property(readonly, assign) BOOL defaultStatusBarHidden;	// G=0x3bee9; converted property
@property(readonly, assign) int preferredBackgroundJetsamPriority;	// G=0x34de9; converted property
@property(readonly, assign) int ratingRank;	// G=0x34d2d; converted property
@property(readonly, assign) Class iconClass;	// G=0x3e3a9; converted property
@property(readonly, retain) NSArray *externalAccessoryProtocols;	// G=0x34f65; converted property
@property(readonly, assign) unsigned cachedApplicationState;	// G=0x38439; converted property
+ (void)initialize;	// 0x360a9
+ (BOOL)multitaskingIsSupported;	// 0x36069
+ (id)systemSnapshotsDirectory;	// 0x36029
+ (void *)cachedSnapshotSurfaceForPath:(id)path;	// 0x35ff1
+ (void)setCachedSnapshotSurface:(void *)surface forPath:(id)path;	// 0x35fb5
+ (void)removeCachedSnapshotSurface:(void *)surface forPath:(id)path;	// 0x35f55
+ (void)removeCachedSnapshotsMatchingPath:(id)path;	// 0x35ec9
+ (void)flushLaunchAlertsOfType:(int)type;	// 0x35df5
- (void)_configureDisplayNameForInfoDictionary:(id)infoDictionary atBundlePath:(id)bundlePath;	// 0x35055
- (id)initWithBundleIdentifier:(id)bundleIdentifier webClip:(id)clip path:(id)path bundle:(id)bundle infoDictionary:(id)dictionary isSystemApplication:(BOOL)application signerIdentity:(id)identity provisioningProfileValidated:(BOOL)validated;	// 0x40245
- (void)_watchdogFired;	// 0x35125
- (void)_startWatchdogTimerType:(int)type;	// 0x40049
- (void)_cancelWatchdogTimer;	// 0x35249
- (void)_watchdogFiredFired;	// 0x352a1
- (void)startWatchdogTimerForPhoneSlideIfNecessary;	// 0x35351
- (void)_scheduleWatchdogAssertionWithTimeout:(double *)timeout token:(unsigned)token;	// 0x3fd79
- (unsigned)addWatchdogAssertionWithTimeout:(double *)timeout;	// 0x3537d
- (void)renewWatchdogAssertionWithToken:(unsigned)token timeout:(double *)timeout;	// 0x353a5
- (void)_clearWatchdogAssertions;	// 0x3fca1
- (void)removeWatchdogAssertionWithToken:(unsigned)token;	// 0x3fc41
- (void)_watchdogAssertExpired:(id)expired;	// 0x353bd
- (BOOL)shouldWatchdog;	// 0x3fbd9
- (double)autoDimTime;	// 0x3fb75
- (double)autoLockTime;	// 0x3fb11
- (void)dealloc;	// 0x3f775
// converted property getter: - (unsigned)activationEventSequenceNumber;	// 0x34a51
- (BOOL)isSameExecutableAsApplication:(id)application;	// 0x353cd
// converted property getter: - (id)bundleIdentifier;	// 0x34a61
// converted property getter: - (id)path;	// 0x34a71
- (id)containerPath;	// 0x35415
// converted property getter: - (double)modificationDate;	// 0x34a81
- (id)bundle;	// 0x3f6cd
- (void)purgeBundleCaches;	// 0x3f685
// converted property getter: - (id)bundleVersion;	// 0x34a99
// converted property getter: - (BOOL)enabled;	// 0x34aa9
// converted property setter: - (void)setEnabled:(BOOL)enabled;	// 0x34abd
- (BOOL)suspendedEventsOnly;	// 0x34add
// converted property setter: - (void)setTags:(id)tags;	// 0x3543d
// converted property getter: - (id)tags;	// 0x34af1
- (void)_addInternalDebugVariablesToEnvironment;	// 0x35485
// converted property getter: - (BOOL)hasMiniAlerts;	// 0x34b01
// converted property setter: - (void)setHasMiniAlerts:(BOOL)alerts;	// 0x34b15
- (int)dataUsage;	// 0x34b35
// converted property getter: - (BOOL)hasShownDataPlanAlertSinceLock;	// 0x34b71
// converted property setter: - (void)setHasShownDataPlanAlertSinceLock:(BOOL)lock;	// 0x34b85
- (void)_setDataUsage:(int)usage;	// 0x359c1
- (void)setUsesBackgroundNetwork:(BOOL)network;	// 0x35ad5
- (unsigned)_doingBackgroundNetworking;	// 0x34bad
- (void)_setDoingBackgroundNetworking:(unsigned)networking;	// 0x34bc9
- (void)setUsesEdgeNetwork:(BOOL)network;	// 0x35ba5
- (void)setUsesWiFiNetwork:(BOOL)network;	// 0x35bed
- (void)_resetDataUsage;	// 0x34bf9
- (BOOL)isSystemApplication;	// 0x34c11
- (BOOL)isInternalApplication;	// 0x35c35
- (BOOL)isSystemProvisioningApplication;	// 0x34c25
- (BOOL)isWebApplication;	// 0x34c39
- (id)webClip;	// 0x34c3d
- (BOOL)isNewsstandApplication;	// 0x34c41
- (BOOL)isNowRecordingApplication;	// 0x3f649
- (BOOL)isUserRatable;	// 0x35c6d
- (BOOL)hasGameCenterData;	// 0x34c45
// converted property getter: - (BOOL)isUnsupportediBooks;	// 0x34c79
// converted property setter: - (void)setIsUnsupportediBooks:(BOOL)books;	// 0x34c8d
- (BOOL)isLaunchableDuringSetup;	// 0x34ca9
- (BOOL)wantsAggressiveJetsamDuringActivation;	// 0x34cbd
- (void)validateSystemProvisioningEntitlements:(XXStruct_kUSYWB *)entitlements;	// 0x3f5c9
- (id)customSpotlightIconPathsForKey:(id)key;	// 0x35d01
- (id)appSnapshotPath;	// 0x3f56d
- (void)flushSnapshots;	// 0x35d25
- (BOOL)shouldLaunchPNGless;	// 0x3f471
- (id)_additionalDisplayQualification;	// 0x3f3a1
- (id)_pathIfFileExistsAtPath:(id)path;	// 0x3f361
- (BOOL)_useLosslessSnapshotsForScale:(float)scale;	// 0x34cd1
- (id)_dynamicSnapshotSuffixForScale:(float)scale;	// 0x3f32d
- (BOOL)isSnapshotPresentForLaunchingInterfaceOrientation:(int)launchingInterfaceOrientation;	// 0x3f2a5
- (id)defaultImage:(BOOL *)image preferredScale:(float)scale originalOrientation:(int *)orientation currentOrientation:(int *)orientation4;	// 0x3f279
- (id)defaultImage:(BOOL *)image preferredScale:(float)scale originalOrientation:(int *)orientation currentOrientation:(int *)orientation4 canUseIOSurface:(BOOL)surface;	// 0x3f201
- (BOOL)canFindDefaultImage:(BOOL *)image preferredScale:(float)scale originalOrientation:(int *)orientation currentOrientation:(int *)orientation4 launchingInterfaceOrientation:(int)orientation5 canUseIOSurface:(BOOL)surface imagePointer:(id *)pointer;	// 0x3e52d
- (id)_defaultImagePathInBundle:(id)bundle baseResourceName:(id)name ofType:(id)type scale:(float *)scale;	// 0x3e479
// converted property getter: - (Class)iconClass;	// 0x3e3a9
- (BOOL)isRevealable;	// 0x34ce9
// converted property getter: - (id)displayName;	// 0x34cfd
// converted property setter: - (void)setDisplayName:(id)name;	// 0x3e361
// converted property getter: - (id)longDisplayName;	// 0x34d0d
// converted property getter: - (id)author;	// 0x34d1d
// converted property getter: - (int)ratingRank;	// 0x34d2d
// converted property getter: - (id)folderNames;	// 0x3e169
// converted property getter: - (id)fallbackFolderName;	// 0x3e0f1
- (void)markUserLaunchInitiationTime;	// 0x3e0a1
- (void)launch;	// 0x3d805
- (void)activate;	// 0x3d04d
- (void)deactivate;	// 0x3cb15
- (void)deactivated;	// 0x3ca39
- (void)kill;	// 0x3ca21
- (BOOL)_shouldAutoLaunchForVoIP;	// 0x3c955
- (void)_setAutoLaunchForVoIP:(BOOL)voIP;	// 0x3c88d
- (BOOL)_shouldAutoRelaunchForEA;	// 0x3c845
- (BOOL)_shouldAutoLaunchOnBootOrInstall:(BOOL)install;	// 0x3c361
- (void)autoLaunchIfNecessaryOnBootOrInstall:(BOOL)install;	// 0x3c321
- (void)_cancelAutoRelaunch;	// 0x3c2e1
- (void)_relaunchAfterExitIfNecessary;	// 0x3c229
- (int)statusBarStyle;	// 0x3c1e1
- (int)defaultStatusBarStyle;	// 0x3c0d9
- (int)statusBarStyleOverridesToCancel;	// 0x3c051
// converted property getter: - (BOOL)defaultStatusBarHidden;	// 0x3bee9
- (void)overrideDefaultInterfaceOrientation:(int)orientation;	// 0x34d3d
- (void)removeDefaultInterfaceOrientationOverride;	// 0x34d61
- (int)launchingInterfaceOrientationForCurrentOrientation:(int)currentOrientation;	// 0x3bd69
// converted property getter: - (BOOL)isClassic;	// 0x34d79
// converted property setter: - (void)setIsClassic:(BOOL)classic;	// 0x3bcf9
- (BOOL)classicAppZoomedIn;	// 0x3bc61
- (BOOL)classicAppRequiresHiDPI;	// 0x34d8d
- (BOOL)classicAppZoomedInOrRequiresHiDPI;	// 0x3bc21
- (BOOL)classicDefaultStatusBarHidden;	// 0x34dc1
- (BOOL)backgroundContinuationSupported;	// 0x3bbbd
// converted property getter: - (BOOL)backgroundContinuationEnabled;	// 0x34dd1
// converted property setter: - (void)setBackgroundContinuationEnabled:(BOOL)enabled;	// 0x34de5
- (BOOL)backgroundContinuationAvailable;	// 0x3bb69
- (void)exitedCommon;	// 0x3b851
- (void)exitedAbnormally;	// 0x3b7b1
- (void)exitedNormally;	// 0x3b75d
// converted property getter: - (int)preferredBackgroundJetsamPriority;	// 0x34de9
- (int)effectiveBackgroundJetsamPriority;	// 0x3b725
// converted property getter: - (id)applicationNextWakeDate;	// 0x3b6e5
// converted property setter: - (void)setApplicationNextWakeDate:(id)date;	// 0x3b639
- (void)_updateApplicationWakeTimers;	// 0x3b505
- (void)wakeTimerFired;	// 0x3b47d
- (void)spdResumeForTrafficRequested;	// 0x3b451
- (void)sendOpenURL:(id)url;	// 0x3b41d
- (id)loggingIdentifier;	// 0x3b40d
- (void)_setupLocalNotificationLogging;	// 0x3b1cd
- (id)_scheduledLocalNotifications;	// 0x3b10d
- (void)_setScheduledLocalNotifications:(id)notifications;	// 0x3b049
- (id)_copyUnexpiredScheduledLocalNotifications;	// 0x3aec5
- (void)_setPendingLocalNotificationFromBulletin:(id)bulletin;	// 0x3ae49
- (id)scheduledLocalNotifications;	// 0x3ae21
- (void)scheduleLocalNotifications:(id)notifications replaceExistingNotifications:(BOOL)notifications2;	// 0x3a8a1
- (void)cancelLocalNotification:(id)notification;	// 0x3a681
- (BOOL)usesLocalNotifications;	// 0x3a601
- (void)noteBadgeSetLocally;	// 0x3a4f9
- (BOOL)badgeHasBeenSetLocally;	// 0x3a46d
- (void)_dismissAllSystemLocalNotificationAlerts;	// 0x3a205
- (void)_setLastLocalNotificationFireDate:(id)date;	// 0x3a199
- (id)_lastLocalNotificationFireDate;	// 0x3a0ad
- (void)_setMonitoringForLocaleAndTimeChanges:(BOOL)localeAndTimeChanges;	// 0x39fbd
- (void)_updateLocalNotificationTimers;	// 0x39749
- (void)localNotificationTimerFired;	// 0x391cd
- (void)_fireNotification:(id)notification;	// 0x38e89
- (void)systemLocalNotificationAlertShouldLaunch:(id)systemLocalNotificationAlert forApplication:(id)application;	// 0x38c5d
- (void)systemLocalNotificationAlertShouldSnooze:(id)systemLocalNotificationAlert forApplication:(id)application;	// 0x3899d
- (id)getPendingLocalNotification;	// 0x3896d
- (void)_purgeCachedLocalNotifications;	// 0x38941
- (BOOL)isContextHostingEnabled;	// 0x3891d
- (id)contextHostViewForRequester:(id)requester;	// 0x388f9
- (id)contextHostViewForRequester:(id)requester enableAndOrderFront:(BOOL)front;	// 0x388c9
- (void)enableContextHostingForRequester:(id)requester orderFront:(BOOL)front;	// 0x3889d
- (void)disableContextHostingForRequester:(id)requester;	// 0x38879
// converted property getter: - (id)contextHostManager;	// 0x34df9
- (void)_clearContextHostManager;	// 0x38839
- (void)_setContextHostManager:(id)manager;	// 0x387f1
- (void)hideContextHostViewForRequester:(id)requester;	// 0x38781
- (void)_unregisterRemoteViewsAndSheets;	// 0x38725
- (id)launchdJobLabel;	// 0x386fd
// converted property getter: - (id)seatbeltEnvironmentVariables;	// 0x34e09
// converted property setter: - (void)setSeatbeltEnvironmentVariables:(id)variables;	// 0x386b5
- (id)sandboxPath;	// 0x3867d
- (id)preferenceDomain;	// 0x385c9
- (unsigned)applicationState;	// 0x38541
- (void)_updateCachedApplicationState;	// 0x3846d
// converted property getter: - (unsigned)cachedApplicationState;	// 0x38439
// converted property getter: - (BOOL)hasBeenFrontmost;	// 0x34e19
// converted property setter: - (void)setHasBeenFrontmost:(BOOL)frontmost;	// 0x34e2d
- (void)_sendApplicationStateChangedNotification:(unsigned)notification;	// 0x383fd
- (void)setSuspendType:(int)type;	// 0x34e4d
- (int)suspensionType;	// 0x34e79
- (BOOL)supportsAudioBackgroundMode;	// 0x34e95
- (BOOL)supportsLocationBackgroundMode;	// 0x34ea9
- (BOOL)supportsVOIPBackgroundMode;	// 0x34ebd
- (BOOL)supportsEABackgroundMode;	// 0x34ed1
- (BOOL)supportsContinuousBackgroundMode;	// 0x34ee5
- (BOOL)supportsNewsstandContentBackgroundMode;	// 0x34f19
- (BOOL)wantsUnboundedTaskCompletionAssertions;	// 0x34f2d
// converted property getter: - (id)signerIdentity;	// 0x34f41
- (int)applicationSignatureState;	// 0x3837d
- (BOOL)_signatureNeedsExplicitUserTrust;	// 0x381f5
- (BOOL)_doesProfileMatchSignerIdentity:(MISProfileRef)identity;	// 0x38105
- (id)_expirationDateForProvisioningProfile;	// 0x37f81
- (void)markApplicationIdentityAsTrusted;	// 0x37e91
- (BOOL)provisioningProfileValidated;	// 0x34f51
// converted property getter: - (id)externalAccessoryProtocols;	// 0x34f65
- (void)launchSucceeded:(BOOL)succeeded;	// 0x37b65
- (void)prepareForUninstallation;	// 0x37a39
// converted property getter: - (id)remoteApplication;	// 0x379e1
- (void)_purgeRemoteApplication;	// 0x379b5
- (BOOL)showLaunchAlertForType:(int)type;	// 0x37861
- (void)resetLaunchAlertForType:(int)type;	// 0x34f75
- (BOOL)isAnyTerminationAssertionHeld;	// 0x34fb5
- (BOOL)isCacheCleaningTerminationAssertionHeld;	// 0x34fcd
- (void)incrementTerminationAssertionCountForReason:(unsigned char)reason;	// 0x37799
- (void)decrementTerminationAssertionCountForReason:(unsigned char)reason;	// 0x375e5
- (void)notifyResignActiveForReason:(int)reason;	// 0x375ad
- (void)notifyResumeActiveForReason:(int)reason;	// 0x37575
- (void)notifyResignActive;	// 0x37541
- (void)notifyResumeActive;	// 0x3750d
- (void)notifyOfTaskResume;	// 0x374d9
- (void)notifyOfImminentProcessAssertionExpiration;	// 0x374a5
- (void)process:(id)process didAddAssertion:(id)assertion;	// 0x34fe5
- (void)resumeToQuit;	// 0x37491
- (void)resumeForContentAvailable;	// 0x3747d
- (id)_transientIdentifier;	// 0x373e1
- (double)_resumeDurationForTransientType:(int)transientType;	// 0x34fe9
- (void)_transientResumeForType:(int)type;	// 0x371d5
- (void)_transientSuspendForTimerFired:(id)timerFired;	// 0x371c5
- (void)setNowPlayingWithAudio:(BOOL)audio;	// 0x37199
// declared property getter: - (BOOL)isUsingLocation;	// 0x35011
// declared property setter: - (void)setUsingLocation:(BOOL)location;	// 0x37101
- (void)takeAssertionWithTimeoutForSimpleRemoteAction;	// 0x37001
- (void)sendSimpleRemoteAction:(int)action;	// 0x36fc1
- (void)_setProcess:(id)process;	// 0x36e15
// declared property setter: - (void)setProcess:(id)process;	// 0x36e05
- (void)_cancelProcessAssertionForSimpleRemoteAction;	// 0x36dc5
- (void)_dropTransientProcessAssertion;	// 0x36d39
- (id)_copyApplicationMetadata;	// 0x36cd5
- (id)_localizedGenreNameForID:(int)anId;	// 0x36a31
- (id)_localizedGenreFromDictionary:(id)dictionary;	// 0x36915
- (void)_takeResumeProcessAssertion;	// 0x367c9
- (void)_takeSuspendingProcessAssertion;	// 0x36709
- (void)_dropResumeProcessAssertion;	// 0x366b1
- (void)_dropSuspendingProcessAssertion;	// 0x36659
- (void)_resumeForPeriodicWakeWithReason:(id)reason;	// 0x364f1
- (void)_dropPeriodicWakeProcessAssertion;	// 0x3645d
- (void)_suspendForPeriodicWakeTimerFired:(id)periodicWakeTimerFired;	// 0x3644d
- (id)_currentDefaultPNGName;	// 0x362e5
- (id)defaultImagePathForCurrentOrientationWithName:(id)name;	// 0x3619d
// declared property getter: - (id)displayIdentifier;	// 0x36185
// declared property setter: - (void)setDisplayIdentifier:(id)identifier;	// 0x3615d
// declared property getter: - (id)process;	// 0x35045
@end

