/**
 * This header is generated by class-dump-z 0.2b.
 *
 * Source: (null)
 */

#import "SBUnknownSuperclass.h"
#import "UIAlertViewDelegate.h"

@class SBUserInstalledApplicationIcon, UIButton;

@interface SBAppRatingsAlertItem : SBUnknownSuperclass <UIAlertViewDelegate> {
	SBUserInstalledApplicationIcon *_icon;	// 16 = 0x10
	UIButton *_rateButton;	// 20 = 0x14
	BOOL _uninstallOnDismiss;	// 24 = 0x18
}
- (id)initWithIcon:(id)icon uninstallOnDismiss:(BOOL)dismiss;	// 0xde9dd
- (void)dealloc;	// 0xdeee5
- (Class)alertSheetClass;	// 0xdeec9
- (void)alertView:(id)view clickedButtonAtIndex:(int)index;	// 0xded5d
- (void)configure:(BOOL)configure requirePasscodeForActions:(BOOL)actions;	// 0xdeab5
- (void)_starsControlValueChanged:(id)changed;	// 0xdea45
- (BOOL)shouldShowInLockScreen;	// 0xde9c5
- (BOOL)dismissOnLock;	// 0xde9c9
@end
