/**
 * This header is generated by class-dump-z 0.2b.
 *
 * Source: (null)
 */

#import "SBUnknownSuperclass.h"


@interface SBApplicationDataLookupOperation : SBUnknownSuperclass {
}
- (void)main;	// 0xcb8dd
@end
