/**
 * This header is generated by class-dump-z 0.2b.
 *
 * Source: (null)
 */

#import "SBAppToAppTransitionView.h"


@interface SBAppDosadoView : SBAppToAppTransitionView {
}
- (void)beginTransition;	// 0x1202a9
- (void)endTransition;	// 0x120269
@end

