/**
 * This header is generated by class-dump-z 0.2b.
 *
 * Source: (null)
 */

#import "SpringBoard-Structs.h"
#import "SBAppSwitcherScrollViewDelegate.h"
#import "SBUnknownSuperclass.h"

@class SBAppSwitcherScrollView, SBLinenView, UIView, NSMutableArray;
@protocol SBAppSwitcherBarViewDelegate;

@interface SBAppSwitcherBarView : SBUnknownSuperclass <SBAppSwitcherScrollViewDelegate> {
	id<SBAppSwitcherBarViewDelegate> _delegate;	// 48 = 0x30
	NSMutableArray *_appIcons;	// 52 = 0x34
	UIView *_contentView;	// 56 = 0x38
	SBLinenView *_backgroundView;	// 60 = 0x3c
	NSMutableArray *_auxViews;	// 64 = 0x40
	SBAppSwitcherScrollView *_scrollView;	// 68 = 0x44
	BOOL _animateContentReflow;	// 72 = 0x48
	BOOL _animatedScrolling;	// 73 = 0x49
	int _lastPageIndex;	// 76 = 0x4c
	BOOL _isVisible;	// 80 = 0x50
	CGPoint _savedPositionForSuspendGesture;	// 84 = 0x54
}
@property(assign, nonatomic) id<SBAppSwitcherBarViewDelegate> delegate;	// G=0x11d979; S=0x11d989; @synthesize=_delegate
+ (unsigned)iconsPerPage:(int)page;	// 0x11dda5
+ (CGSize)viewSize:(int)size;	// 0x11e151
+ (float)edgePaddingForWidth:(float)width;	// 0x11e0ad
- (id)initWithFrame:(CGRect)frame;	// 0x11ddf5
- (void)dealloc;	// 0x11f759
- (void)prepareIconViewsForDisplay:(id)display showFirstPage:(BOOL)page;	// 0x11f499
- (id)iconViews;	// 0x11d965
- (void)setEditing:(BOOL)editing;	// 0x11d975
- (BOOL)isScrolling;	// 0x11d9f9
- (void)addIcon:(id)icon;	// 0x11da59
- (void)removeIcon:(id)icon;	// 0x11f365
- (void)replaceIcons:(id)icons with:(id)with;	// 0x11f241
- (void)addAuxiliaryViews:(id)views;	// 0x11f05d
- (BOOL)nowPlayingControlsVisible;	// 0x11efe1
- (BOOL)airPlayControlsVisible;	// 0x11ef01
- (void)viewWillAppear;	// 0x11ee41
- (void)viewWillDisappear;	// 0x11dae1
- (void)_iconRemoveDidStop:(id)_iconRemove finished:(id)finished context:(id)context;	// 0x11db2d
- (void)_reflowContent:(BOOL)content;	// 0x11ec81
- (void)_adjustContentOffsetForReflow:(BOOL)reflow;	// 0x11eb41
- (void)_adjustContentOffsetForResizeFromOldOffset:(CGPoint)oldOffset andOldSize:(CGSize)size toNewSize:(CGSize)newSize;	// 0x11e9ed
- (void)_adjustScrollContentSize;	// 0x11e985
- (void)_positionAtFirstPage:(BOOL)firstPage;	// 0x11e909
- (void)layoutSubviews;	// 0x11e6b5
- (CGRect)_iconFrameForIndex:(unsigned)index withSize:(CGSize)size;	// 0x11e55d
- (unsigned)_pageCount;	// 0x11e4b5
- (unsigned)_iconCountForWidth:(float)width;	// 0x11e41d
- (CGPoint)_firstPageOffset:(CGSize)offset;	// 0x11db85
- (int)_pageForOffset:(CGPoint)offset withSize:(CGSize)size;	// 0x11e389
- (int)_pageForIndex:(unsigned)index;	// 0x11e349
- (void)didMoveToSuperview;	// 0x11dbe5
- (void)scrollViewDidScroll:(id)scrollView;	// 0x11e26d
- (void)scrollViewDidEndScrollingAnimation:(id)scrollView;	// 0x11dc25
- (void)scrollViewDidEndDragging:(id)scrollView willDecelerate:(BOOL)decelerate;	// 0x11dc89
- (void)scrollViewDidEndDecelerating:(id)scrollView;	// 0x11dcd5
- (BOOL)scrollView:(id)view shouldCancelInContentForView:(id)view2;	// 0x11dd19
- (void)saveScrollPositionBeforeSuspendGesture;	// 0x11e21d
- (void)restoreScrollPositionAfterSuspendGesture;	// 0x11dd51
// declared property getter: - (id)delegate;	// 0x11d979
// declared property setter: - (void)setDelegate:(id)delegate;	// 0x11d989
@end
