/**
 * This header is generated by class-dump-z 0.2b.
 *
 * Source: (null)
 */

#import "SBUnknownSuperclass.h"
#import "SpringBoard-Structs.h"

@class CATransformLayer, CALayer, UIView, SBApplication;

@interface SBAppToAppTransitionView : SBUnknownSuperclass {
	id _delegate;	// 48 = 0x30
	SBApplication *_toApplication;	// 52 = 0x34
	CATransformLayer *_transformLayer;	// 56 = 0x38
	CALayer *_startLayer;	// 60 = 0x3c
	CALayer *_stopLayer;	// 64 = 0x40
	UIView *_fromView;	// 68 = 0x44
	UIView *_toView;	// 72 = 0x48
	BOOL _animating;	// 76 = 0x4c
	BOOL _workspaceIsReadyForAnimationCleanup;	// 77 = 0x4d
	int _orientation;	// 80 = 0x50
}
@property(assign, nonatomic) id delegate;	// G=0x11f881; S=0x11f891; @synthesize=_delegate
@property(retain, nonatomic) SBApplication *toApp;	// G=0x11f871; S=0x11f9d1; @synthesize=_toApplication
@property(assign, nonatomic) int orientation;	// G=0x11f851; S=0x11f861; @synthesize=_orientation
- (id)initWithFrame:(CGRect)frame;	// 0x11f8a1
- (void)dealloc;	// 0x1201b9
- (void)setFromView:(id)view;	// 0x11ff21
- (void)setToView:(id)view;	// 0x11fc01
- (void)beginTransition;	// 0x11fb79
- (void)endTransition;	// 0x11faf1
- (void)noteWorkspaceIsReadyForAnimationCleanupWithActivatingApp:(id)activatingApp;	// 0x11fa45
- (void)animationDidStop:(id)animation finished:(BOOL)finished;	// 0x11f9f9
- (id)_rotationValueFunction;	// 0x11f7e1
- (float)_rotationRadians;	// 0x11f815
- (void)_transitionBegun:(double)begun;	// 0x11f83d
// declared property getter: - (int)orientation;	// 0x11f851
// declared property setter: - (void)setOrientation:(int)orientation;	// 0x11f861
// declared property getter: - (id)toApp;	// 0x11f871
// declared property setter: - (void)setToApp:(id)app;	// 0x11f9d1
// declared property getter: - (id)delegate;	// 0x11f881
// declared property setter: - (void)setDelegate:(id)delegate;	// 0x11f891
@end
