/**
 * This header is generated by class-dump-z 0.2b.
 *
 * Source: (null)
 */

#import "UIAlertViewDelegate.h"
#import "SBUnknownSuperclass.h"

@class SBApplicationIcon;

@interface SBAppProfileNotTrustedAlertItem : SBUnknownSuperclass <UIAlertViewDelegate> {
	SBApplicationIcon *_icon;	// 16 = 0x10
	BOOL _launchApp;	// 20 = 0x14
}
- (id)initWithIcon:(id)icon;	// 0xd2d11
- (void)dealloc;	// 0xd3091
- (void)alertView:(id)view clickedButtonAtIndex:(int)index;	// 0xd2d51
- (void)didDeactivateForReason:(int)reason;	// 0xd2dbd
- (void)configure:(BOOL)configure requirePasscodeForActions:(BOOL)actions;	// 0xd2eb1
- (BOOL)shouldShowInLockScreen;	// 0xd2d09
- (BOOL)dismissOnLock;	// 0xd2d0d
@end
