/**
 * This header is generated by class-dump-z 0.2b.
 *
 * Source: (null)
 */

#import "SBUnknownSuperclass.h"

@class NSString;

@interface SBApplicationUninstallationOperation : SBUnknownSuperclass {
	NSString *_bundleIdentifier;	// 12 = 0xc
}
- (id)initWithBundleIdentifier:(id)bundleIdentifier;	// 0xcb6b1
- (void)dealloc;	// 0xcb665
- (void)main;	// 0xcb611
@end
