/**
 * This header is generated by class-dump-z 0.2b.
 *
 * Source: (null)
 */

#import "SpringBoard-Structs.h"
#import "SBUnknownSuperclass.h"


@interface SBAppWindow : SBUnknownSuperclass {
}
+ (CGRect)constrainFrameToScreen:(CGRect)screen;	// 0x4f65
@end
