/**
 * This header is generated by class-dump-z 0.2b.
 *
 * Source: (null)
 */

#import "SBLeafIcon.h"

@class NSString;

@interface SBApplicationIcon : SBLeafIcon {
	NSString *_displayIdentifier;	// 68 = 0x44
	unsigned _appIsBeingCleaned : 1;	// 72 = 0x48
}
- (id)initWithApplication:(id)application;	// 0x250c9
- (void)dealloc;	// 0x25b45
- (id)application;	// 0x25249
- (id)__loadIconImage:(id)image format:(int)format scale:(float)scale;	// 0x2528d
- (void)generateIconImageInBackground:(id)background;	// 0x252ad
- (void)generateIconImageInBackgroundForFormat:(int)format complete:(id)complete;	// 0x25a71
- (BOOL)canGenerateGhostlyImageInBackground;	// 0x250b1
- (id)generateIconImage:(int)image;	// 0x259a9
- (id)displayName;	// 0x252e5
- (id)leafIdentifier;	// 0x250b5
- (BOOL)canEllipsizeLabel;	// 0x25375
- (id)tags;	// 0x253a9
- (id)automationID;	// 0x253d1
- (BOOL)launchEnabled;	// 0x253f9
- (void)_setAppIsBeingCleanedFlag;	// 0x25445
- (void)_terminationAssertionDidChange;	// 0x254b9
- (void)launch;	// 0x2558d
- (void)launchFromViewSwitcher;	// 0x255dd
- (void)setBadge:(id)badge;	// 0x25639
- (void)_setBadge:(id)badge;	// 0x25839
- (id)folderTitleOptions;	// 0x256fd
- (id)folderFallbackTitle;	// 0x25725
- (id)applicationBundleID;	// 0x25791
- (BOOL)shouldCacheImageForFormat:(int)format;	// 0x257f5
@end

