/**
 * This header is generated by class-dump-z 0.2b.
 *
 * Source: (null)
 */

#import "SBUnknownSuperclass.h"
#import "SpringBoard-Structs.h"

@class NSMutableArray;

@interface SBAppRatingsStarControl : SBUnknownSuperclass {
	NSMutableArray *_stars;	// 72 = 0x48
	int _currentIndex;	// 76 = 0x4c
}
@property(readonly, assign) int currentIndex;	// G=0xde9cd; converted property
- (id)initWithFrame:(CGRect)frame;	// 0xdf4fd
- (void)dealloc;	// 0xdf4b1
- (float)firstStarOffset;	// 0xdf411
- (void)layoutSubviews;	// 0xdf2fd
- (void)handleTouches:(id)touches withEvent:(id)event;	// 0xdf15d
- (void)touchesBegan:(id)began withEvent:(id)event;	// 0xdf14d
- (void)touchesMoved:(id)moved withEvent:(id)event;	// 0xdf13d
- (void)touchesEnded:(id)ended withEvent:(id)event;	// 0xdf12d
// converted property getter: - (int)currentIndex;	// 0xde9cd
@end
