/**
 * This header is generated by class-dump-z 0.2b.
 *
 * Source: (null)
 */

#import "SBUnknownSuperclass.h"

@class SBAssistantController;

@interface SBAssistantFullyRevealedState : SBUnknownSuperclass {
	SBAssistantController *_controller;	// 4 = 0x4
	id _block;	// 8 = 0x8
}
@property(retain, nonatomic) SBAssistantController *controller;	// G=0x1a7705; S=0x1a7bdd; @synthesize=_controller
@property(retain, nonatomic) id block;	// G=0x1a76f5; S=0x1a7ac1; @synthesize=_block
+ (id)stateWithController:(id)controller block:(id)block;	// 0x1a7b69
// declared property setter: - (void)setBlock:(id)block;	// 0x1a7ac1
- (void)dealloc;	// 0x1a7b09
// declared property getter: - (id)block;	// 0x1a76f5
// declared property getter: - (id)controller;	// 0x1a7705
// declared property setter: - (void)setController:(id)controller;	// 0x1a7bdd
@end
