/**
 * This header is generated by class-dump-z 0.2b.
 *
 * Source: (null)
 */

#import "SpringBoard-Structs.h"
#import "UIScrollViewDelegate.h"
#import "SBUnknownSuperclass.h"
#import "SBAssistantMicButtonProtocol.h"
#import "UISearchBarDelegate.h"

@class UIControl, UIScrollView, SBDeviceLockView, UISearchBar, UIButton, UITableView, UIView, UIImageView, UIStatusBar, UILabel, SBAssistantUnavailableView, SBAssistantMicButtonView;
@protocol SBAssistantViewDelegate;

@interface SBAssistantView : SBUnknownSuperclass <UISearchBarDelegate, UIScrollViewDelegate, SBAssistantMicButtonProtocol> {
	id<SBAssistantViewDelegate> _delegate;	// 48 = 0x30
	UIScrollView *_statusScrollView;	// 52 = 0x34
	UISearchBar *_searchBar;	// 56 = 0x38
	UIView *_statusBar;	// 60 = 0x3c
	UILabel *_statusLabel;	// 64 = 0x40
	UITableView *_tableView;	// 68 = 0x44
	UIButton *_tryAgainButton;	// 72 = 0x48
	UIView *_contentView;	// 76 = 0x4c
	UIImageView *_backgroundImageView;	// 80 = 0x50
	UIImageView *_magicPocketView;	// 84 = 0x54
	SBAssistantMicButtonView *_micButtonView;	// 88 = 0x58
	SBAssistantUnavailableView *_unavailableView;	// 92 = 0x5c
	SBDeviceLockView *_deviceLockView;	// 96 = 0x60
	UIStatusBar *_fakeStatusBar;	// 100 = 0x64
	UIImageView *_statusShadowView;	// 104 = 0x68
	int _state;	// 108 = 0x6c
	BOOL _animating;	// 112 = 0x70
	BOOL _initialQuery;	// 113 = 0x71
	BOOL _showingGuide;	// 114 = 0x72
	BOOL _ignoringTableInteraction;	// 115 = 0x73
	BOOL _scrolling;	// 116 = 0x74
	int _scrollCellIndex;	// 120 = 0x78
}
@property(assign, nonatomic) id<SBAssistantViewDelegate> delegate;	// G=0x172a91; S=0x172aa1; @synthesize=_delegate
@property(readonly, assign, nonatomic) UIButton *tryAgainButton;	// G=0x172a81; @synthesize=_tryAgainButton
@property(readonly, assign, nonatomic) UITableView *tableView;	// G=0x172a71; @synthesize=_tableView
@property(assign, nonatomic, getter=isShowingGuide) BOOL showingGuide;	// G=0x172a61; S=0x173cf1; @synthesize=_showingGuide
@property(readonly, assign, nonatomic) SBDeviceLockView *deviceLockView;	// G=0x172a51; @synthesize=_deviceLockView
@property(readonly, assign, nonatomic) BOOL scrolling;	// G=0x172a41; @synthesize=_scrolling
@property(assign, nonatomic, getter=isModal) BOOL modal;	// G=0x173d7d; S=0x173dad; 
@property(assign, nonatomic) int assistantState;	// G=0x172a05; S=0x1745a9; 
@property(readonly, assign, nonatomic) UIControl *micButton;	// G=0x1729e1; 
@property(assign) BOOL magicPocketDisabled;	// G=0x173d35; S=0x173d59; converted property
+ (float)bottomBarHeight;	// 0x172c6d
+ (float)gridHeight;	// 0x1729d9
- (id)initWithFrame:(CGRect)frame;	// 0x174dbd
- (void)dealloc;	// 0x172ab1
- (void)reloadConversation;	// 0x174d9d
// declared property getter: - (id)micButton;	// 0x1729e1
- (void)_setSpeechEnabled:(BOOL)enabled;	// 0x174d31
- (void)showButton:(BOOL)button;	// 0x174c79
- (void)reset;	// 0x174b71
- (BOOL)isBeingQuiet;	// 0x174b35
- (void)endInput;	// 0x174af5
- (void)setSearchText:(id)text;	// 0x174ad1
- (void)_updateMagicPocketAlpha;	// 0x1748b5
- (void)_updateAlphaForSnippets;	// 0x174741
- (CGRect)statusBarFrame;	// 0x1746fd
- (void)noteScrollViewDidScroll;	// 0x1746d1
- (void)noteScrollAnimationDidEnd;	// 0x1729f1
// declared property setter: - (void)setAssistantState:(int)state;	// 0x1745a9
// declared property getter: - (int)assistantState;	// 0x172a05
- (void)setTransactionComplete:(BOOL)complete;	// 0x172a15
- (UIEdgeInsets)_standardInsets;	// 0x174509
- (CGRect)_defaultTableFrame;	// 0x174499
- (void)_setupForInitialQuery:(BOOL)initialQuery animated:(BOOL)animated;	// 0x174181
- (BOOL)_showAssistantStatusBar;	// 0x174145
- (void)scheduleScrollToCell:(int)cell;	// 0x1740dd
- (void)cancelScrollToCell;	// 0x17407d
- (void)_scrollToPendingCell;	// 0x173ded
- (void)forceScrollToCell;	// 0x173ddd
// declared property setter: - (void)setModal:(BOOL)modal;	// 0x173dad
// declared property getter: - (BOOL)isModal;	// 0x173d7d
// converted property setter: - (void)setMagicPocketDisabled:(BOOL)disabled;	// 0x173d59
// converted property getter: - (BOOL)magicPocketDisabled;	// 0x173d35
// declared property setter: - (void)setShowingGuide:(BOOL)guide;	// 0x173cf1
- (void)setConnectionAvailable:(BOOL)available;	// 0x173b81
- (void)appendContentInsetsToStandardInsets:(UIEdgeInsets)standardInsets;	// 0x173ae5
- (void)showFakeStatusBar:(BOOL)bar;	// 0x173a01
- (void)ignoreTableInteraction;	// 0x1739bd
- (void)restoreTableInteractionIfNecessary;	// 0x173979
- (BOOL)isTableInteractionIgnored;	// 0x172a19
- (float)_tossAngleForCell:(id)cell;	// 0x1737e1
- (void)_tossSnippetFromAboveMagicPocket:(id)aboveMagicPocket distanceToBottom:(float)bottom;	// 0x1733e5
- (void)_tossSnippetFromBelowMagicPocket:(id)belowMagicPocket distanceToBottom:(float)bottom;	// 0x173249
- (void)tossSnippet:(id)snippet;	// 0x1730ed
- (void)setShowDeviceLockKeypad:(BOOL)keypad;	// 0x172dbd
- (BOOL)isDeviceLockKeypadShowing;	// 0x172a29
- (void)scrollViewDidEndDecelerating:(id)scrollView;	// 0x172d15
- (void)searchBarSearchButtonClicked:(id)clicked;	// 0x172ca9
- (float)assistantMicButtonGimmeAudioLevel:(id)level;	// 0x172c89
// declared property getter: - (BOOL)scrolling;	// 0x172a41
// declared property getter: - (id)deviceLockView;	// 0x172a51
// declared property getter: - (BOOL)isShowingGuide;	// 0x172a61
// declared property getter: - (id)tableView;	// 0x172a71
// declared property getter: - (id)tryAgainButton;	// 0x172a81
// declared property getter: - (id)delegate;	// 0x172a91
// declared property setter: - (void)setDelegate:(id)delegate;	// 0x172aa1
@end
