/**
 * This header is generated by class-dump-z 0.2b.
 *
 * Source: (null)
 */

#import "SBUnknownSuperclass.h"

@class SBAssistantConfirmView, SAUIConfirmationOptions;

@interface SBAssistantConfirmController : SBUnknownSuperclass {
	SBAssistantConfirmView *_view;	// 12 = 0xc
	SAUIConfirmationOptions *_model;	// 16 = 0x10
	int _confirmTrigger;	// 20 = 0x14
}
@property(readonly, retain) SBAssistantConfirmView *view;	// G=0x145825; converted property
- (id)initWithAceObject:(id)aceObject delegate:(id)delegate;	// 0x14566d
- (void)dealloc;	// 0x145a71
- (BOOL)_wantsStaticPresentation;	// 0x1455c1
// converted property getter: - (id)view;	// 0x145825
- (void)_sendCommandsAndDismiss:(id)dismiss stampingMostRecentSnippetWithCancel:(BOOL)cancel;	// 0x145719
- (void)_cancelButtonHit:(id)hit;	// 0x1455c5
- (void)_confirmButtonHit:(id)hit;	// 0x145619
@end
