/**
 * This header is generated by class-dump-z 0.2b.
 *
 * Source: (null)
 */

#import "SpringBoard-Structs.h"
#import "SBUnknownSuperclass.h"

@class AFUIServerUtteranceView, AFUIUtteranceView, UIImageView, UILabel, UIButton, UIView, NSString, UITableView;

@interface SBAssistantTourGuideView : SBUnknownSuperclass {
	AFUIServerUtteranceView *_utteranceView;	// 48 = 0x30
	UIView *_clippingView;	// 52 = 0x34
	UIImageView *_backgroundView;	// 56 = 0x38
	UITableView *_domainTableView;	// 60 = 0x3c
	UITableView *_sectionTableView;	// 64 = 0x40
	UIImageView *_topLineView;	// 68 = 0x44
	UIImageView *_bottomLineView;	// 72 = 0x48
	UIImageView *_topShadow;	// 76 = 0x4c
	UIImageView *_bottomShadow;	// 80 = 0x50
	UIButton *_backButton;	// 84 = 0x54
	UILabel *_domainLabel;	// 88 = 0x58
	NSString *_serverUtteranceText;	// 92 = 0x5c
	BOOL _sectionShowing;	// 96 = 0x60
	int _mode;	// 100 = 0x64
}
@property(readonly, assign, nonatomic) AFUIUtteranceView *utteranceView;	// G=0x19f2ed; @synthesize=_utteranceView
@property(readonly, assign, nonatomic) UITableView *domainTableView;	// G=0x19f2dd; @synthesize=_domainTableView
@property(readonly, assign, nonatomic) UITableView *sectionTableView;	// G=0x19f2cd; @synthesize=_sectionTableView
@property(readonly, assign, nonatomic) UIButton *backButton;	// G=0x19f2bd; @synthesize=_backButton
@property(assign, nonatomic) int mode;	// G=0x19f2ad; S=0x19f4bd; @synthesize=_mode
- (id)initWithFrame:(CGRect)frame;	// 0x1a0045
- (void)dealloc;	// 0x19f2fd
- (CGSize)sizeThatFits:(CGSize)fits;	// 0x19ff61
- (void)layoutSubviews;	// 0x19f825
- (float)utteranceHeight;	// 0x19f7e5
- (void)_updateUtteranceText;	// 0x19f6f5
- (void)setUtteranceText:(id)text;	// 0x19f69d
- (void)showDisplay:(int)display;	// 0x19f58d
- (void)setDomainName:(id)name;	// 0x19f53d
// declared property setter: - (void)setMode:(int)mode;	// 0x19f4bd
- (void)setFrame:(CGRect)frame;	// 0x19f425
// declared property getter: - (int)mode;	// 0x19f2ad
// declared property getter: - (id)backButton;	// 0x19f2bd
// declared property getter: - (id)sectionTableView;	// 0x19f2cd
// declared property getter: - (id)domainTableView;	// 0x19f2dd
// declared property getter: - (id)utteranceView;	// 0x19f2ed
@end
