/**
 * This header is generated by class-dump-z 0.2b.
 *
 * Source: (null)
 */

#import "SBUnknownSuperclass.h"

@class NSMutableArray, NSArray, NSString;

@interface SBAssistantGuideSectionModel : SBUnknownSuperclass {
	NSString *_title;	// 4 = 0x4
	NSMutableArray *_phrases;	// 8 = 0x8
}
@property(retain, nonatomic) NSString *title;	// G=0x19ad9d; S=0x19c12d; @synthesize=_title
@property(retain, nonatomic) NSArray *phrases;	// G=0x19ad8d; S=0x19c155; @synthesize=_phrases
- (id)init;	// 0x19c0c9
- (void)dealloc;	// 0x19c17d
// declared property getter: - (id)phrases;	// 0x19ad8d
// declared property setter: - (void)setPhrases:(id)phrases;	// 0x19c155
// declared property getter: - (id)title;	// 0x19ad9d
// declared property setter: - (void)setTitle:(id)title;	// 0x19c12d
@end
