/**
 * This header is generated by class-dump-z 0.2b.
 *
 * Source: (null)
 */

#import "SBUnknownSuperclass.h"

@class AFUISnippetController, NSString;
@protocol SBAssistantTableViewCellDelegate;

@interface SBAssistantTableViewCell : SBUnknownSuperclass {
	id<SBAssistantTableViewCellDelegate> _delegate;	// 244 = 0xf4
	AFUISnippetController *_controller;	// 248 = 0xf8
	NSString *_animationName;	// 252 = 0xfc
}
@property(assign, nonatomic) id<SBAssistantTableViewCellDelegate> delegate;	// G=0x159541; S=0x159551; @synthesize=_delegate
@property(retain, nonatomic) AFUISnippetController *controller;	// G=0x159531; S=0x159561; @synthesize=_controller
@property(readonly, assign, nonatomic) NSString *animationName;	// G=0x159521; @synthesize=_animationName
+ (float)defaultSnippetViewInset;	// 0x159519
- (void)dealloc;	// 0x159919
// declared property setter: - (void)setController:(id)controller;	// 0x159561
- (void)setController:(id)controller parentingViewInCell:(BOOL)cell;	// 0x159575
- (void)parentViewInCell;	// 0x1596d5
- (BOOL)isViewInCell;	// 0x159725
- (void)layoutSubviews;	// 0x159a75
- (void)removeFromSuperview;	// 0x1599d1
- (id)description;	// 0x159979
- (void)addSnippetAnimation:(id)animation named:(id)named;	// 0x159779
- (void)animationDidStop:(id)animation finished:(BOOL)finished;	// 0x159859
// declared property getter: - (id)animationName;	// 0x159521
// declared property getter: - (id)controller;	// 0x159531
// declared property getter: - (id)delegate;	// 0x159541
// declared property setter: - (void)setDelegate:(id)delegate;	// 0x159551
@end
