/**
 * This header is generated by class-dump-z 0.2b.
 *
 * Source: (null)
 */

#import "SBUnknownSuperclass.h"

@class NSMutableArray, NSArray, NSString;

@interface SBAssistantGuideDomainModel : SBUnknownSuperclass {
	NSString *_name;	// 4 = 0x4
	NSString *_tagPhrase;	// 8 = 0x8
	NSString *_displayIdentifier;	// 12 = 0xc
	NSString *_bundleIdentifier;	// 16 = 0x10
	NSMutableArray *_requiredApps;	// 20 = 0x14
	NSMutableArray *_requiredCapabilities;	// 24 = 0x18
	NSString *_sectionFilename;	// 28 = 0x1c
	NSMutableArray *_sections;	// 32 = 0x20
}
@property(retain, nonatomic) NSString *name;	// G=0x19ad7d; S=0x19b8dd; @synthesize=_name
@property(retain, nonatomic) NSString *tagPhrase;	// G=0x19ad6d; S=0x19b905; @synthesize=_tagPhrase
@property(retain, nonatomic) NSString *displayIdentifier;	// G=0x19ad5d; S=0x19b92d; @synthesize=_displayIdentifier
@property(retain, nonatomic) NSString *bundleIdentifier;	// G=0x19ad4d; S=0x19b955; @synthesize=_bundleIdentifier
@property(retain, nonatomic) NSArray *requiredApps;	// G=0x19ad3d; S=0x19b97d; @synthesize=_requiredApps
@property(retain, nonatomic) NSArray *requiredCapabilities;	// G=0x19ad2d; S=0x19b9a5; @synthesize=_requiredCapabilities
@property(retain, nonatomic) NSString *sectionFilename;	// G=0x19ad1d; S=0x19b9cd; @synthesize=_sectionFilename
@property(readonly, retain, nonatomic) NSArray *sections;	// G=0x19b9f5; @synthesize=_sections
- (id)init;	// 0x19b849
- (void)dealloc;	// 0x19bff1
// declared property getter: - (id)sections;	// 0x19b9f5
// declared property getter: - (id)sectionFilename;	// 0x19ad1d
// declared property setter: - (void)setSectionFilename:(id)filename;	// 0x19b9cd
// declared property getter: - (id)requiredCapabilities;	// 0x19ad2d
// declared property setter: - (void)setRequiredCapabilities:(id)capabilities;	// 0x19b9a5
// declared property getter: - (id)requiredApps;	// 0x19ad3d
// declared property setter: - (void)setRequiredApps:(id)apps;	// 0x19b97d
// declared property getter: - (id)bundleIdentifier;	// 0x19ad4d
// declared property setter: - (void)setBundleIdentifier:(id)identifier;	// 0x19b955
// declared property getter: - (id)displayIdentifier;	// 0x19ad5d
// declared property setter: - (void)setDisplayIdentifier:(id)identifier;	// 0x19b92d
// declared property getter: - (id)tagPhrase;	// 0x19ad6d
// declared property setter: - (void)setTagPhrase:(id)phrase;	// 0x19b905
// declared property getter: - (id)name;	// 0x19ad7d
// declared property setter: - (void)setName:(id)name;	// 0x19b8dd
@end
