/**
 * This header is generated by class-dump-z 0.2b.
 *
 * Source: (null)
 */




@protocol SBAssistantViewDelegate <NSObject>
- (void)assistantViewSearchScrolledToView:(id)view;
- (void)assistantView:(id)view madeRequest:(id)request;
- (void)assistantViewAnimatedIn:(id)anIn;
- (void)assistantViewAnimatedOut:(id)anOut;
- (float)assistantViewAudioLevel:(id)level;
@end

