/**
 * This header is generated by class-dump-z 0.2b.
 *
 * Source: (null)
 */

#import "SBAssistantGuideDomainListDelegate.h"
#import "AFUIUtteranceViewDelegate.h"
#import "SBUnknownSuperclass.h"

@class SBAssistantGuideDomainListController, SBAssistantGuideSectionListController, SBAssistantTourGuideView, SBAssistantGuideModel;

@interface SBAssistantTourGuideController : SBUnknownSuperclass <AFUIUtteranceViewDelegate, SBAssistantGuideDomainListDelegate> {
	SBAssistantTourGuideView *_view;	// 12 = 0xc
	SBAssistantGuideDomainListController *_domainListController;	// 16 = 0x10
	SBAssistantGuideSectionListController *_sectionListController;	// 20 = 0x14
	SBAssistantGuideModel *_model;	// 24 = 0x18
}
@property(readonly, retain) SBAssistantTourGuideView *view;	// G=0x19ee7d; converted property
+ (float)peekAmount;	// 0x19f0d1
- (void)dealloc;	// 0x19f19d
- (id)_view;	// 0x19ecb1
// converted property getter: - (id)view;	// 0x19ee7d
- (BOOL)_wantsUnmodifiedHeight;	// 0x19ecad
- (BOOL)_affectsMagicPocket;	// 0x19ee8d
- (float)peekAmount;	// 0x19eebd
- (void)utteranceViewInfoButtonHit:(id)hit;	// 0x19ef19
- (void)revealGuide;	// 0x19ef61
- (void)setMode:(int)mode;	// 0x19f225
- (void)setUtteranceText:(id)text;	// 0x19ef81
- (id)_model;	// 0x19efad
- (void)_backButtonHit:(id)hit;	// 0x19eff9
- (void)assistantShowSectionsForDomainAtIndex:(unsigned)index;	// 0x19f019
@end
