/**
 * This header is generated by class-dump-z 0.2b.
 *
 * Source: (null)
 */




@protocol SBAssistantGuideDomainListDelegate <NSObject>
- (void)assistantShowSectionsForDomainAtIndex:(unsigned)index;
@end

