/**
 * This header is generated by class-dump-z 0.2b.
 *
 * Source: (null)
 */

#import "SBUnknownSuperclass.h"

@class SBAssistantBasicView, NSDictionary;

@interface SBAssistantBasicViewController : SBUnknownSuperclass {
	NSDictionary *_properties;	// 12 = 0xc
	SBAssistantBasicView *_view;	// 16 = 0x10
}
@property(readonly, retain) SBAssistantBasicView *view;	// G=0x13489d; converted property
- (id)initWithAceObject:(id)aceObject delegate:(id)delegate;	// 0x134835
- (void)dealloc;	// 0x134989
// converted property getter: - (id)view;	// 0x13489d
@end
