/**
 * This header is generated by class-dump-z 0.2b.
 *
 * Source: (null)
 */

#import "SBAssistantSpaceViewDelegate.h"
#import "SBUnknownSuperclass.h"

@class SBAssistantSpaceView;

@interface SBAssistantSpaceController : SBUnknownSuperclass <SBAssistantSpaceViewDelegate> {
	float _space;	// 12 = 0xc
	SBAssistantSpaceView *_view;	// 16 = 0x10
}
@property(assign, nonatomic) float space;	// G=0x14b2a1; S=0x14b2b1; @synthesize=_space
@property(readonly, retain) SBAssistantSpaceView *view;	// G=0x14b2f1; converted property
- (id)initWithAceObject:(id)aceObject delegate:(id)delegate;	// 0x14b375
- (void)dealloc;	// 0x14b3b5
// converted property getter: - (id)view;	// 0x14b2f1
- (float)assistantSpaceViewIdealHeight:(id)height;	// 0x14b289
- (BOOL)_wantsUnmodifiedHeight;	// 0x14b299
- (BOOL)_affectsMagicPocket;	// 0x14b29d
// declared property getter: - (float)space;	// 0x14b2a1
// declared property setter: - (void)setSpace:(float)space;	// 0x14b2b1
@end
