/**
 * This header is generated by class-dump-z 0.2b.
 *
 * Source: (null)
 */

#import "SBUnknownSuperclass.h"

@class NSTimer, SBAssistantEducationAlertItem;

@interface SBAssistantEducationAlertManager : SBUnknownSuperclass {
	int _notifyToken;	// 4 = 0x4
	id _unlockHandler;	// 8 = 0x8
	NSTimer *_unlockTimer;	// 12 = 0xc
	BOOL _waitingOnUserDataSync;	// 16 = 0x10
	SBAssistantEducationAlertItem *_item;	// 20 = 0x14
}
+ (BOOL)isUserEducated;	// 0x1a81f5
+ (void)setUserHasBeenEducated;	// 0x1a8155
+ (void)pleaseEducateTheUserWhenYouGetAChance;	// 0x1a810d
- (id)init;	// 0x1a8329
- (void)dealloc;	// 0x1a82e9
- (void)_invalidate;	// 0x1a8231
- (void)_showEducationAlertIfPossible;	// 0x1a7dc1
- (void)_startUnlockTimer;	// 0x1a8005
- (void)_clearUnlockTimer;	// 0x1a8089
- (void)_unlockTimerFired:(id)fired;	// 0x1a80c9
- (void)educationAlertWasDeactivated:(id)deactivated;	// 0x1a80d9
@end
