/**
 * This header is generated by class-dump-z 0.2b.
 *
 * Source: (null)
 */

#import "SBDismissOnlyAlertItem.h"

@protocol SBAssistantEducationAlertItemDelegate;

@interface SBAssistantEducationAlertItem : SBDismissOnlyAlertItem {
	id<SBAssistantEducationAlertItemDelegate> _delegate;	// 32 = 0x20
}
@property(assign, nonatomic) id<SBAssistantEducationAlertItemDelegate> delegate;	// G=0x1a7c05; S=0x1a7c15; @synthesize=_delegate
- (id)initWithDelegate:(id)delegate;	// 0x1a7c39
- (void)dealloc;	// 0x1a7fa9
- (void)didDeactivateForReason:(int)reason;	// 0x1a7f4d
- (void)_assistantActivationChanged:(id)changed;	// 0x1a7d41
// declared property getter: - (id)delegate;	// 0x1a7c05
// declared property setter: - (void)setDelegate:(id)delegate;	// 0x1a7c15
@end

