/**
 * This header is generated by class-dump-z 0.2b.
 *
 * Source: (null)
 */

#import "SpringBoard-Structs.h"
#import "UITableViewDelegate.h"
#import "UITableViewDataSource.h"
#import "SBAssistantGuideDomainListCellDelegate.h"
#import "SBUnknownSuperclass.h"

@class UIImageView, NSMutableArray, SBAssistantGuideModel, UITableView;
@protocol SBAssistantGuideDomainListDelegate;

@interface SBAssistantGuideDomainListController : SBUnknownSuperclass <UITableViewDelegate, UITableViewDataSource, SBAssistantGuideDomainListCellDelegate> {
	id<SBAssistantGuideDomainListDelegate> _delegate;	// 4 = 0x4
	UITableView *_tableView;	// 8 = 0x8
	UIImageView *_selectedOverlay;	// 12 = 0xc
	NSMutableArray *_filteredDomainIndices;	// 16 = 0x10
	SBAssistantGuideModel *_model;	// 20 = 0x14
}
@property(readonly, assign, nonatomic) UITableView *tableView;	// G=0x19c2bd; @synthesize=_tableView
@property(assign, nonatomic) id<SBAssistantGuideDomainListDelegate> delegate;	// G=0x19c29d; S=0x19c2ad; @synthesize=_delegate
- (id)initWithModel:(id)model view:(id)view;	// 0x19c2cd
- (void)dealloc;	// 0x19cbb9
- (void)updateDomainList;	// 0x19c8d9
- (int)tableView:(id)view numberOfRowsInSection:(int)section;	// 0x19c8b9
- (id)tableView:(id)view cellForRowAtIndexPath:(id)indexPath;	// 0x19c5dd
- (BOOL)tableView:(id)view canEditRowAtIndexPath:(id)indexPath;	// 0x19c299
- (float)tableView:(id)view heightForRowAtIndexPath:(id)indexPath;	// 0x19c5c1
- (void)tableView:(id)view didSelectRowAtIndexPath:(id)indexPath;	// 0x19c549
- (void)guideDomainCell:(id)cell didHighlight:(BOOL)highlight;	// 0x19c475
// declared property getter: - (id)delegate;	// 0x19c29d
// declared property setter: - (void)setDelegate:(id)delegate;	// 0x19c2ad
// declared property getter: - (id)tableView;	// 0x19c2bd
@end
