/**
 * This header is generated by class-dump-z 0.2b.
 *
 * Source: (null)
 */

#import "SpringBoard-Structs.h"
#import "SBUnknownSuperclass.h"

@protocol SBAssistantSpaceViewDelegate;

@interface SBAssistantSpaceView : SBUnknownSuperclass {
	id<SBAssistantSpaceViewDelegate> _delegate;	// 48 = 0x30
}
@property(assign, nonatomic) id<SBAssistantSpaceViewDelegate> delegate;	// G=0x14b269; S=0x14b279; @synthesize=_delegate
- (CGSize)sizeThatFits:(CGSize)fits;	// 0x14b2c1
// declared property getter: - (id)delegate;	// 0x14b269
// declared property setter: - (void)setDelegate:(id)delegate;	// 0x14b279
@end
