/**
 * This header is generated by class-dump-z 0.2b.
 *
 * Source: (null)
 */

#import "SBUnknownSuperclass.h"


@interface SBAssistantMicImages : SBUnknownSuperclass {
}
+ (void)initialize;	// 0x1a54f9
+ (unsigned)listeningImageCount;	// 0x1a5369
+ (unsigned)thinkingImageCount;	// 0x1a536d
+ (unsigned)fullImageCount;	// 0x1a5371
+ (id)listeningImageAtIndex:(unsigned)index;	// 0x1a5375
+ (id)thinkingImageAtIndex:(unsigned)index;	// 0x1a53e9
+ (id)fullImageAtIndex:(unsigned)index;	// 0x1a545d
+ (id)thinkingOnImage;	// 0x1a54d1
@end
