/**
 * This header is generated by class-dump-z 0.2b.
 *
 * Source: (null)
 */

#import "SBUnknownSuperclass.h"
#import "SpringBoard-Structs.h"

@class UILabel;

@interface SBAssistantBasicView : SBUnknownSuperclass {
	UILabel *_title;	// 48 = 0x30
	UILabel *_subtitle;	// 52 = 0x34
}
- (id)initWithFrame:(CGRect)frame;	// 0x1349e9
- (void)dealloc;	// 0x134d55
- (void)setTitleText:(id)text;	// 0x134d31
- (void)setSubtitleText:(id)text;	// 0x134d0d
- (void)layoutSubviews;	// 0x134bd1
@end
