/**
 * This header is generated by class-dump-z 0.2b.
 *
 * Source: (null)
 */

#import "SBUnknownSuperclass.h"


@interface SBAssistantNavigationController : SBUnknownSuperclass {
	int _currentStatusBarStyle;	// 232 = 0xe8
}
- (id)init;	// 0x1a77f1
- (void)viewWillDisappear:(BOOL)view;	// 0x1a78bd
- (void)viewWillAppear:(BOOL)view;	// 0x1a7851
@end
