/**
 * This header is generated by class-dump-z 0.2b.
 *
 * Source: (null)
 */

#import "SpringBoard-Structs.h"
#import "SBAlertDisplay.h"

@class UIView;

@interface SBAssistantAlertDisplay : SBAlertDisplay {
	UIView *_assistantView;	// 56 = 0x38
}
@property(retain, nonatomic) UIView *assistantView;	// G=0x134db5; S=0x134dfd; @synthesize=_assistantView
- (id)initWithFrame:(CGRect)frame;	// 0x134dc5
- (void)dealloc;	// 0x134f8d
- (void)layoutSubviews;	// 0x134f11
- (void)alertDisplayWillBecomeVisible;	// 0x134ecd
- (void)alertDisplayBecameVisible;	// 0x134e45
// declared property setter: - (void)setAssistantView:(id)view;	// 0x134dfd
// declared property getter: - (id)assistantView;	// 0x134db5
@end

