/**
 * This header is generated by class-dump-z 0.2b.
 *
 * Source: (null)
 */

#import "SBUnknownSuperclass.h"

@class NSString;

@interface SBAwayListUnlockActionContext : SBUnknownSuperclass {
	NSString *_lockLabel;	// 4 = 0x4
	NSString *_shortLockLabel;	// 8 = 0x8
	id _unlockAction;	// 12 = 0xc
	NSString *_bulletinID;	// 16 = 0x10
	float _fontsize;	// 20 = 0x14
	BOOL _launchActionCanBypassPinLock;	// 24 = 0x18
	BOOL _canBypassPinLock;	// 25 = 0x19
}
@property(assign, nonatomic) BOOL canBypassPinLock;	// G=0x1954a5; S=0x1954b5; @synthesize=_canBypassPinLock
@property(readonly, retain) NSString *lockLabel;	// G=0x195465; converted property
@property(readonly, retain) NSString *shortLockLabel;	// G=0x195475; converted property
@property(readonly, retain) id unlockAction;	// G=0x195455; converted property
@property(readonly, retain) NSString *bulletinID;	// G=0x195485; converted property
+ (id)unlockActionContextForBulletin:(id)bulletin;	// 0x1969d5
+ (id)unlockActionContextForAlertItem:(id)alertItem;	// 0x196905
- (id)_initWithLockLabel:(id)lockLabel shortLockLabel:(id)label unlockAction:(id)action bulletinID:(id)anId;	// 0x196711
- (id)_initWithLockLabel:(id)lockLabel shortLockLabel:(id)label unlockAction:(id)action bulletinID:(id)anId fontSize:(float)size;	// 0x196769
- (void)dealloc;	// 0x196c31
// converted property getter: - (id)unlockAction;	// 0x195455
// converted property getter: - (id)lockLabel;	// 0x195465
// converted property getter: - (id)shortLockLabel;	// 0x195475
// converted property getter: - (id)bulletinID;	// 0x195485
- (float)lockLabelFontSize;	// 0x195495
// declared property getter: - (BOOL)canBypassPinLock;	// 0x1954a5
// declared property setter: - (void)setCanBypassPinLock:(BOOL)lock;	// 0x1954b5
@end
