/**
 * This header is generated by class-dump-z 0.2b.
 *
 * Source: (null)
 */

#import "SBAlert.h"
#import "SpringBoard-Structs.h"

@class NSDate, PCPersistentTimer, SBUIController, SBAwayBulletinListController, SBApplication, NSTimeZone, SBAlertItem, PLCameraPageController, UIView, UIImageView, NSTimer, NSMutableDictionary, SBAwayView, NSDictionary, SBShowcaseController, NSString, NSMutableArray;
@protocol SBDeviceLockViewOwner;

@interface SBAwayController : SBAlert {
	SBUIController *_uiController;	// 60 = 0x3c
	SBShowcaseController *_showcaseController;	// 64 = 0x40
	SBAwayView *_awayView;	// 68 = 0x44
	NSTimer *_dimTimer;	// 72 = 0x48
	unsigned _isLocked : 1;	// 76 = 0x4c
	unsigned _isUnlocking : 1;	// 76 = 0x4c
	unsigned _isActivatingBacklightForUnlock : 1;	// 76 = 0x4c
	unsigned _isDeviceLocked : 1;	// 76 = 0x4c
	unsigned _isDeviceLockedInitialized : 1;	// 76 = 0x4c
	unsigned _isDimmed : 1;	// 76 = 0x4c
	unsigned _isDimming : 1;	// 76 = 0x4c
	unsigned _orderedOutDimmed : 1;	// 76 = 0x4c
	unsigned _frontDimmed : 1;	// 77 = 0x4d
	unsigned _isPermanentlyBlocked : 1;	// 77 = 0x4d
	unsigned _makingEmergencyCall : 1;	// 77 = 0x4d
	unsigned _appRequestedPasscodeEntry : 1;	// 77 = 0x4d
	unsigned _relockAfterUnlock : 1;	// 77 = 0x4d
	unsigned _showOverheatUI : 1;	// 77 = 0x4d
	unsigned _performingAutoUnlock : 1;	// 77 = 0x4d
	unsigned _springBoardIdleTimerScheduled : 1;	// 77 = 0x4d
	unsigned _validPhotoCountCheck : 1;	// 78 = 0x4e
	unsigned _showcaseAnimating : 1;	// 78 = 0x4e
	unsigned _hasBeenLockedOnce : 1;	// 78 = 0x4e
	int _unlockSource;	// 80 = 0x50
	NSDictionary *_nowPlayingInfo;	// 84 = 0x54
	SBApplication *_nowPlayingApp;	// 88 = 0x58
	id<SBDeviceLockViewOwner> _deviceUnlockDisplay;	// 92 = 0x5c
	double _deviceLockBlockTime;	// 96 = 0x60
	double _lastLockWallTime;	// 104 = 0x68
	NSTimeZone *_lastLockTimeZone;	// 112 = 0x70
	double _lastLockSecondsSinceBoot;	// 116 = 0x74
	PCPersistentTimer *_deviceLockTimer;	// 124 = 0x7c
	BOOL _devicePasscodeLoaded;	// 128 = 0x80
	NSString *_devicePasscode;	// 132 = 0x84
	BOOL _chargingViewHasFadedOut;	// 136 = 0x88
	NSMutableArray *_pendingAlertItems;	// 140 = 0x8c
	SBAlertItem *_currentAlertItem;	// 144 = 0x90
	SBAwayBulletinListController *_savedBulletinController;	// 148 = 0x94
	NSMutableDictionary *_awayViewPluginControllers;	// 152 = 0x98
	NSString *_alwaysFullscreenAwayPluginName;	// 156 = 0x9c
	NSMutableArray *_lockScreenBundlesToDisableAfterUnlock;	// 160 = 0xa0
	BOOL _cameraVisible;	// 164 = 0xa4
	BOOL _animatingCameraIn;	// 165 = 0xa5
	BOOL _cancelCameraAnimation;	// 166 = 0xa6
	PLCameraPageController *_cameraViewController;	// 168 = 0xa8
	UIImageView *_cameraDefaultImageView;	// 172 = 0xac
	UIView *_cameraBackgroundView;	// 176 = 0xb0
	UIView *_cameraContainerView;	// 180 = 0xb4
	BOOL _dimTimerDisabledForCamera;	// 184 = 0xb8
	BOOL _exitingCameraToPasscodeUI;	// 185 = 0xb9
	NSDate *_lastCameraSessionID;	// 188 = 0xbc
	BOOL _exitedCameraForAlert;	// 192 = 0xc0
	BOOL _restartCameraAfterCall;	// 193 = 0xc1
	int _gracePeriodWhenLocked;	// 196 = 0xc4
	NSString *_currentTestName;	// 200 = 0xc8
}
@property(assign, nonatomic) BOOL chargingViewHasFadedOut;	// G=0x42199; S=0x41f71; @synthesize=_chargingViewHasFadedOut
@property(retain, nonatomic) SBShowcaseController *showcaseController;	// G=0x42189; S=0x42e41; @synthesize=_showcaseController
@property(retain, nonatomic) NSString *currentTestName;	// G=0x42179; S=0x46725; @synthesize=_currentTestName
@property(readonly, assign) BOOL hasEverBeenLocked;	// G=0x41f5d; 
@property(readonly, assign) NSDate *lastLockDate;	// G=0x421a9; 
@property(assign) BOOL showOverheatUI;	// G=0x41fb1; S=0x4b071; converted property
@property(assign, getter=isDeviceLocked) BOOL deviceLocked;	// G=0x41fe9; S=0x4a241; converted property
@property(readonly, retain) SBAwayView *awayView;	// G=0x4bead; converted property
@property(readonly, retain) NSTimer *dimTimer;	// G=0x42111; converted property
@property(readonly, retain) NSMutableArray *pendingAlertItems;	// G=0x41fc5; converted property
@property(readonly, retain) SBAlertItem *currentAlertItem;	// G=0x42155; converted property
+ (id)sharedAwayController;	// 0x466b9
+ (id)sharedAwayControllerIfExists;	// 0x41f81
+ (void)registerForAlerts;	// 0x41f91
// declared property getter: - (id)lastLockDate;	// 0x421a9
// declared property getter: - (BOOL)hasEverBeenLocked;	// 0x41f5d
- (id)initWithUIController:(id)uicontroller;	// 0x4c00d
// declared property setter: - (void)setChargingViewHasFadedOut:(BOOL)anOut;	// 0x41f71
- (CGRect)alertWindowRect;	// 0x4bfb5
- (BOOL)showsSpringBoardStatusBar;	// 0x42205
- (float)finalAlpha;	// 0x41f95
- (BOOL)undimsDisplay;	// 0x41f9d
// converted property getter: - (id)awayView;	// 0x4bead
- (id)alertDisplayViewWithSize:(CGSize)size;	// 0x4be4d
- (void)alertDisplayWillBecomeVisible;	// 0x42299
- (void)_createCameraViewControllerWithNewSessionID:(BOOL)newSessionID;	// 0x422c1
- (void)_createCameraViewControllerWithNewSessionID;	// 0x4238d
- (void)_createCameraViewControllerWithOldSessionID;	// 0x423a1
- (void)activateCameraWithNewSessionID:(BOOL)newSessionID afterCall:(BOOL)call;	// 0x4bb9d
- (void)activateCamera;	// 0x42675
- (void)_activateCameraAfterCall;	// 0x426a5
- (void)dismissCameraAnimated:(BOOL)animated;	// 0x426d5
- (void)_setCameraAsWindowDelegate;	// 0x42cd9
- (void)_restoreWindowOrientationAndDelegate;	// 0x4bad1
- (void)tearDownCameraUIImmediately;	// 0x42d39
- (BOOL)cameraIsActive;	// 0x41fa1
- (BOOL)cameraIsInPreviewMode;	// 0x42dbd
- (void)takePicture;	// 0x42de1
- (id)cameraBackgroundViewIfOnscreen;	// 0x42e0d
// declared property setter: - (void)setShowcaseController:(id)controller;	// 0x42e41
- (void)activateAssistantWithOptions:(id)options withCompletion:(id)completion;	// 0x42ed1
- (BOOL)_activateAssistantWithOptions:(id)options;	// 0x4b74d
- (BOOL)expectsFaceContact;	// 0x43181
- (void)_deactivateAssistantShowcaseClearingOwner:(BOOL)owner;	// 0x431bd
- (void)_deactivateAssistantShowcase;	// 0x43319
- (void)_dismissAssistantImmediately;	// 0x4332d
- (void)_dismissAssistant;	// 0x43369
- (void)deactivateAssistant;	// 0x43671
- (void)simulateDeactivateAssistant;	// 0x4b625
- (void)_blockingViewHit:(id)hit;	// 0x43681
- (void)_releaseAwayView;	// 0x43691
- (void)reactivatePendingAlertItems;	// 0x4b365
- (void)playLockSound;	// 0x4b35d
- (void)_sendLockStateChangedNotification;	// 0x4b1e5
// converted property getter: - (BOOL)showOverheatUI;	// 0x41fb1
// converted property setter: - (void)setShowOverheatUI:(BOOL)ui;	// 0x4b071
- (void)_pendAlertItem:(id)item;	// 0x436e5
- (void)lock;	// 0x4372d
// converted property getter: - (id)pendingAlertItems;	// 0x41fc5
- (void)showTestBulletin;	// 0x43895
- (BOOL)performingAutoUnlock;	// 0x41fd5
- (void)_unlockWithSound:(BOOL)sound isAutoUnlock:(BOOL)unlock unlockSource:(int)source;	// 0x4aba9
- (void)_unlockWithSound:(BOOL)sound isAutoUnlock:(BOOL)unlock;	// 0x438d1
- (void)screensaverDidFadeToBlack:(id)screensaver finished:(id)finished context:(void *)context;	// 0x4ab51
- (void)unlockWithSound:(BOOL)sound lockOwner:(id)owner isAutoUnlock:(BOOL)unlock unlockSource:(int)source;	// 0x4a689
- (void)unlockWithSound:(BOOL)sound lockViewOwner:(id)owner;	// 0x438f5
- (void)unlockWithSound:(BOOL)sound isAutoUnlock:(BOOL)unlock unlockSource:(int)source;	// 0x4a62d
- (void)unlockFromSource:(int)source playSound:(BOOL)sound lockViewOwner:(id)owner;	// 0x4391d
- (void)unlockFromSource:(int)source playSound:(BOOL)sound isAutoUnlock:(BOOL)unlock;	// 0x43945
- (void)unlockFromSource:(int)source playSound:(BOOL)sound;	// 0x43969
- (void)unlockWithSound:(BOOL)sound;	// 0x4398d
- (BOOL)isPasswordProtected;	// 0x439ad
- (void)activationChanged:(id)changed;	// 0x4a3c1
// converted property getter: - (BOOL)isDeviceLocked;	// 0x41fe9
- (BOOL)isDeviceLockedOrBlocked;	// 0x439e1
// converted property setter: - (void)setDeviceLocked:(BOOL)locked;	// 0x4a241
- (int)_getGracePeriod;	// 0x43a19
- (void)_markLockTime;	// 0x4a111
- (BOOL)_shouldLockDeviceWithCurrentGracePeriod:(int)currentGracePeriod;	// 0x49fc5
- (void)_updateDeviceLockedState;	// 0x49cf5
- (void)clearDeviceLockedTimer;	// 0x49c8d
- (void)applicationRequestedDeviceUnlock;	// 0x49c29
- (void)cancelApplicationRequestedDeviceLockEntry;	// 0x43ac5
- (void)_syncingBegan:(id)began;	// 0x43b05
- (void)clearBlockedStateAndUpdateUI:(BOOL)ui;	// 0x43b39
- (BOOL)isBlocked;	// 0x49b79
- (BOOL)isPermanentlyBlocked:(double *)blocked;	// 0x43c35
- (double)idleDimDuration;	// 0x43cb1
- (void)noteSpringBoardIdleTimerScheduled:(BOOL)scheduled;	// 0x41ffd
- (void)noteResetRestoreStateChanged;	// 0x43cc1
- (BOOL)isLocked;	// 0x42019
- (BOOL)shouldShowLockStatusBarTime;	// 0x43dc1
- (BOOL)shouldShowLockStatusBarIcon;	// 0x43e9d
- (void)_photoLibraryChanged;	// 0x4202d
- (BOOL)deviceHasPhotos;	// 0x49b11
- (BOOL)hasPhotosDevicesAttached;	// 0x499f9
- (BOOL)shouldShowSlideshowButton;	// 0x49949
- (void)lockBarStartedTracking:(id)tracking;	// 0x43ed9
- (void)lockBarStoppedTracking:(id)tracking;	// 0x43f4d
- (void)frontLockedAnimationFinished;	// 0x44021
- (BOOL)shouldAnimateOtherDisplaysSuspension;	// 0x42069
- (BOOL)shouldAnimateOtherDisplaysResumption;	// 0x49871
- (void)printLockLog;	// 0x49851
- (void)frontLocked:(BOOL)locked withAnimation:(int)animation automatically:(BOOL)automatically disableLockSound:(BOOL)sound;	// 0x490b5
- (void)_lockFeaturesForRemoteLock:(BOOL)remoteLock;	// 0x44041
- (void)remoteLock:(BOOL)lock;	// 0x44139
- (void)frontLocked:(BOOL)locked animate:(BOOL)animate automatically:(BOOL)automatically;	// 0x441a5
- (void)attemptUnlockFromSource:(int)source;	// 0x441d5
- (void)attemptUnlock;	// 0x4433d
- (BOOL)_isAccessoryActive;	// 0x4206d
- (BOOL)isLockedAndUndimmed;	// 0x42099
- (BOOL)isLockedAndInactive;	// 0x44351
- (BOOL)isActivatingBacklightForUnlock;	// 0x420cd
- (void)_finishedUnlockAttemptWithStatus:(BOOL)status;	// 0x4438d
- (void)noteStartingPhoneCallWhileLocked;	// 0x443b5
- (void)cancelReturnToCameraAfterCall;	// 0x420e1
- (BOOL)shouldReturnToCameraAfterCall;	// 0x42101
- (void)prepareToReturnFromCall;	// 0x4440d
- (void)unlockFromPhoneCallIfNeeded;	// 0x44441
- (BOOL)awayBulletinControllerIsActive;	// 0x4448d
- (id)restoreFromSavedBulletinController;	// 0x444e9
- (double)_undimInterval;	// 0x4453d
- (BOOL)attemptDeviceUnlockWithPassword:(id)password lockViewOwner:(id)owner;	// 0x48bad
- (void)cancelDimTimer;	// 0x445e5
- (void)restartDimTimer;	// 0x44649
- (void)restartDimTimer:(float)timer;	// 0x44685
// converted property getter: - (id)dimTimer;	// 0x42111
- (BOOL)isDimmed;	// 0x42121
- (void)finishedDimmingScreen;	// 0x44809
- (void)notePasscodeGracePeriodMayHaveChanged;	// 0x448b5
- (void)dimTimerFired;	// 0x448c5
- (void)relockForButtonPress:(BOOL)buttonPress afterCall:(BOOL)call;	// 0x44965
- (void)relockForButtonPress:(BOOL)buttonPress afterCall:(BOOL)call dimmed:(BOOL)dimmed;	// 0x44be9
- (void)allowIdleSleep;	// 0x48b39
- (void)preventIdleSleep;	// 0x48ac5
- (void)preventIdleSleepForNumberOfSeconds:(float)seconds;	// 0x44c25
- (void)dimScreen:(BOOL)screen;	// 0x44cdd
- (int)interfaceOrientationForActivation;	// 0x44e3d
- (void)undimScreen;	// 0x48975
- (void)updateOrientationForUndim;	// 0x488c9
- (void)userEventOccurred;	// 0x44e5d
- (BOOL)handleKeyEvent:(GSEventRef)event;	// 0x48779
- (void)activate;	// 0x48605
- (void)deactivate;	// 0x48245
- (BOOL)allowsStackingOfAlert:(id)alert;	// 0x44f31
- (int)effectiveStatusBarStyle;	// 0x44f6d
- (int)statusBarStyle;	// 0x480c9
- (int)statusBarStyleOverridesToCancel;	// 0x42135
- (void)orderOut;	// 0x47d69
- (void)didFinishAnimatingOut;	// 0x47cc9
- (void)updateNowPlayingInfo:(id)info app:(id)app;	// 0x47b9d
- (void)updateAwayViewNowPlayingInfo;	// 0x45029
- (void)_nowPlayingAppChanged:(id)changed;	// 0x45075
- (void)_nowPlayingStateChanged:(id)changed;	// 0x45131
- (void)_iapExtendedModeChanged:(id)changed;	// 0x451a9
- (void)handleRequestedAlbumArt:(id)art;	// 0x42139
- (void)updateClockFormat;	// 0x45201
- (void)makeEmergencyCall;	// 0x45239
- (void)emergencyCallWasDisplayed;	// 0x47b45
- (void)emergencyCallWasRemoved;	// 0x452d1
- (BOOL)isMakingEmergencyCall;	// 0x4213d
- (void)didAnimateLockKeypadIn;	// 0x42151
- (void)didAnimateLockKeypadOut;	// 0x45341
// converted property getter: - (id)currentAlertItem;	// 0x42155
- (void)pendOrDeactivateCurrentAlertItem;	// 0x453e1
- (BOOL)activateAlertItem:(id)item;	// 0x47729
- (BOOL)wantsToHandleAlert:(id)handleAlert;	// 0x45481
- (void)deactivateAlertItem:(id)item;	// 0x4551d
- (void)updateInCallUI;	// 0x4575d
- (void)_batteryStatusChanged;	// 0x457c5
- (BOOL)isShowingMediaControls;	// 0x458b1
- (void)hideMediaControls;	// 0x458d5
- (BOOL)toggleMediaControls;	// 0x458f5
- (BOOL)toggleCameraButton;	// 0x45a5d
- (void)toggleShowsIMEIandICCID:(id)iccid;	// 0x45af1
- (BOOL)isAwayPluginViewVisible;	// 0x45bb9
- (id)highestPriorityAwayPluginController;	// 0x47635
- (id)activeAwayPluginController;	// 0x47535
- (id)interfaceControllingAwayPluginController;	// 0x45bed
- (id)nameOfPluginController:(id)pluginController;	// 0x45c4d
- (void)enableLockScreenBundleWithName:(id)name;	// 0x47341
- (void)disableLockScreenBundleWithName:(id)name;	// 0x45c8d
- (void)pluginVisiblityStateChanged:(id)changed;	// 0x45d09
- (void)_disablePluginControllersForLock;	// 0x4723d
- (void)_disablePluginControllersForUnlock;	// 0x4712d
- (void)_awayViewFinishedAnimatingOut:(id)anOut;	// 0x47071
- (void)_assistantVisibilityChanged:(id)changed;	// 0x45d35
- (void)disablePluginContainerNotification:(id)notification;	// 0x45d45
- (void)pluginFullscreenNotification:(id)notification;	// 0x45dc1
- (BOOL)awayPluginControllerShouldAnimateOthersResumption;	// 0x46fcd
- (BOOL)handleMenuButtonTap;	// 0x46dc9
- (BOOL)handleMenuButtonDoubleTap;	// 0x45e99
- (BOOL)handleMenuButtonHeld;	// 0x45f69
- (void)hardwareKeyboardAvailabilityChanged;	// 0x46d7d
- (BOOL)handleSlideshowHardwareButton;	// 0x46bb1
- (void)setAlwaysFullscreenAwayPluginName:(id)name;	// 0x45fc9
- (BOOL)isAlwaysFullscreenAwayPluginEnabled;	// 0x4607d
- (void)enableAlwaysFullscreenAwayPlugin;	// 0x46b35
- (void)unlockAlwaysFullscreenAwayView;	// 0x46109
- (void)updateInterfaceIfNecessary;	// 0x4611d
- (void)startLockSliderAnimations;	// 0x46afd
- (void)stopLockSliderAnimations;	// 0x46149
- (void)updateLockSlider;	// 0x46175
- (void)_sendToDeviceLockOwnerSetShowingDeviceLock:(BOOL)deviceLockOwnerSetShowingDeviceLock;	// 0x461a1
- (void)_sendToDeviceLockOwnerSetShowingDeviceLock:(BOOL)deviceLockOwnerSetShowingDeviceLock animated:(BOOL)animated;	// 0x461f5
- (void)_sendToDeviceLockOwnerDeviceUnlockSucceeded;	// 0x46251
- (void)_sendToDeviceLockOwnerDeviceUnlockFailed;	// 0x46295
- (BOOL)_sendToDeviceLockOwnerIsDisplayingErrorStatus;	// 0x462d9
- (BOOL)_sendToDeviceLockOwnerShouldUseTransparentStatusBar;	// 0x46321
- (void)_sendToDeviceLockOwnerAnimateToEmergencyCall;	// 0x46369
- (void)assistantWantsToBeFullyRevealed:(id)beFullyRevealed withBlock:(id)block;	// 0x4687d
- (void)_defferedFullyRevealed:(id)revealed;	// 0x46509
- (void)assistantWantsToBeDismissed:(id)beDismissed animated:(BOOL)animated;	// 0x4655d
- (double)assistantFullRevealDuration:(id)duration;	// 0x42165
- (void)_irisOpened;	// 0x46585
- (void)runUnlockTest:(id)test options:(id)options;	// 0x4674d
// declared property getter: - (id)currentTestName;	// 0x42179
// declared property setter: - (void)setCurrentTestName:(id)name;	// 0x46725
// declared property getter: - (id)showcaseController;	// 0x42189
// declared property getter: - (BOOL)chargingViewHasFadedOut;	// 0x42199
@end

