/**
 * This header is generated by class-dump-z 0.2b.
 *
 * Source: (null)
 */

#import "SpringBoard-Structs.h"
#import "SBBulletinCellContentViewBase.h"


@interface SBAwayBulletinFloatingContentView : SBBulletinCellContentViewBase {
	BOOL _hasButton;	// 120 = 0x78
}
@property(assign, nonatomic) BOOL hasButton;	// G=0x197a61; S=0x197a71; @synthesize=_hasButton
+ (float)heightForBulletinStyleWithSubtitle:(id)subtitle message:(id)message maxLines:(unsigned)lines contentWidth:(float)width;	// 0x19a161
+ (float)heightForBulletinStyleWithSubtitle:(id)subtitle message:(id)message maxLines:(unsigned)lines attachmentText:(id)text imageHeight:(float)height contentWidth:(float)width;	// 0x199fa9
+ (float)heightForSystemAlertStyleWithTitle:(id)title maxLines:(unsigned)lines message:(id)message maxLines:(unsigned)lines4 buttonHeight:(float)height contentWidth:(float)width;	// 0x199dcd
- (id)_titleFont;	// 0x199ca9
- (id)_subtitleFont;	// 0x199ccd
- (id)_messageFont;	// 0x199cf1
- (id)_attachmentFont;	// 0x199d11
- (id)_dateFont;	// 0x199d31
- (void)setTitle:(id)title;	// 0x199d51
- (void)setSubtitle:(id)subtitle;	// 0x19acbd
- (void)setMessage:(id)message;	// 0x19ac6d
- (void)setStartDate:(id)date endDate:(id)date2 timeZone:(id)zone allDay:(BOOL)day formatStyle:(int)style;	// 0x19abc9
- (void)setAttachmentImage:(id)image;	// 0x19ab79
- (void)setAttachmentImageSize:(CGSize)size;	// 0x19ab29
- (void)setAttachmentText:(id)text;	// 0x19aad9
- (void)layoutSubviews;	// 0x19a3d5
- (void)_configureLabel:(id)label withFont:(id)font alignment:(int)alignment;	// 0x19a2ed
// declared property getter: - (BOOL)hasButton;	// 0x197a61
// declared property setter: - (void)setHasButton:(BOOL)button;	// 0x197a71
@end

