/**
 * This header is generated by class-dump-z 0.2b.
 *
 * Source: (null)
 */

#import "SBUnknownSuperclass.h"

@class NSMutableDictionary, UIButton;

@interface SBAwayLockBar : SBUnknownSuperclass {
	UIButton *_slideshowButton;	// 104 = 0x68
	UIButton *_cameraButton;	// 108 = 0x6c
	NSMutableDictionary *_orientationToButtonImages;	// 112 = 0x70
}
- (void)dealloc;	// 0xefaf5
- (void)setShowsSlideshowButton:(BOOL)button;	// 0xef861
- (void)setSlideshowButtonSelected:(BOOL)selected;	// 0xef8b1
- (void)setShowsCameraButton:(BOOL)button;	// 0xef8d5
- (void)setOrientation:(int)orientation;	// 0xf00f1
- (id)_newButtonWithAction:(SEL)action tag:(int)tag hasComposedImage:(BOOL)image;	// 0xeff41
- (id)_unselectedImageForButtonTag:(int)buttonTag interfaceOrientation:(int)orientation;	// 0xef925
- (id)_selectedImageForButtonTag:(int)buttonTag interfaceOrientation:(int)orientation;	// 0xefded
- (void)_setImagesForButton:(id)button orientation:(int)orientation;	// 0xef96d
- (void)_setShowsButton:(BOOL)button button:(id *)button2 buttonTag:(int)tag hasComposedImage:(BOOL)image action:(SEL)action animated:(BOOL)animated;	// 0xefb7d
- (void)_slideshowButtonActivated:(id)activated;	// 0xefa09
- (void)_cameraButtonHit:(id)hit;	// 0xefaad
@end
