/**
 * This header is generated by class-dump-z 0.2b.
 *
 * Source: (null)
 */

#import "SBUnknownSuperclass.h"
#import "SpringBoard-Structs.h"

@class MPVolumeView, UIButton;

@interface SBAwayMediaControlsView : SBUnknownSuperclass {
	unsigned _beganSeeking : 1;	// 46 = 0x2e
	int _seekingDirection;	// 48 = 0x30
	UIButton *_prevButton;	// 52 = 0x34
	UIButton *_nextButton;	// 56 = 0x38
	UIButton *_playPauseButton;	// 60 = 0x3c
	MPVolumeView *_volumeView;	// 64 = 0x40
	MPVolumeView *_iPhoneRouteButtonVolumeView;	// 68 = 0x44
	int _orientation;	// 72 = 0x48
}
@property(assign, nonatomic) int orientation;	// G=0xa7f01; S=0xa9335; @synthesize=_orientation
- (id)initWithFrame:(CGRect)frame;	// 0xa7f11
- (void)dismissMediaControlsOverlaysAnimated:(BOOL)animated;	// 0xa9565
- (BOOL)isMediaControlsShowingOverlays;	// 0xa953d
- (void)dealloc;	// 0xa9375
// declared property setter: - (void)setOrientation:(int)orientation;	// 0xa9335
- (id)routeButtonVolumeView;	// 0xa92e1
- (void)layoutSubviews;	// 0xa8c81
- (void)setAlpha:(float)alpha;	// 0xa8c19
- (void)removeFromSuperview;	// 0xa8b95
- (void)_playPauseButtonAction:(id)action;	// 0xa8b2d
- (void)_changeTrackButtonDown:(id)down;	// 0xa8ad5
- (void)_changeTrackButtonUp:(id)up;	// 0xa89c9
- (void)_changeTrackButtonEndSeek:(id)seek;	// 0xa8965
- (void)_changeTrackButtonTouchPause:(id)pause;	// 0xa88c1
- (void)_volumeChange:(id)change;	// 0xa8885
- (void)_volumeViewVisibilityChanged;	// 0xa8875
- (void)_didPresentRoutePicker;	// 0xa8839
- (void)_registerForNowPlayingNotifications;	// 0xa87c9
- (void)_unregisterForNowPlayingNotifications;	// 0xa877d
- (void)_nowPlayingChanged:(id)changed;	// 0xa876d
- (id)_newButtonWithImage:(id)image action:(SEL)action tag:(int)tag;	// 0xa86b5
- (void)_updateInformation;	// 0xa84b1
// declared property getter: - (int)orientation;	// 0xa7f01
@end
