/**
 * This header is generated by class-dump-z 0.2b.
 *
 * Source: (null)
 */

#import "SBFloatingAlertGrabberDelegate.h"
#import "BBObserverDelegate.h"
#import "SpringBoard-Structs.h"
#import "SBUnknownSuperclass.h"
#import "UITableViewDelegate.h"
#import "UITableViewDataSource.h"

@class SBAwayListUnlockActionContext, UIView, SBAwayBulletinCell, SBAwayBulletinListView, NSArray, BBObserver, NSMutableArray;

@interface SBAwayBulletinListController : SBUnknownSuperclass <BBObserverDelegate, UITableViewDataSource, UITableViewDelegate, SBFloatingAlertGrabberDelegate> {
	BBObserver *_observer;	// 4 = 0x4
	NSMutableArray *_listItems;	// 8 = 0x8
	NSMutableArray *_realertTimers;	// 12 = 0xc
	SBAwayBulletinCell *_unlockingCell;	// 16 = 0x10
	BOOL _lockBarIsTracking;	// 20 = 0x14
	SBAwayBulletinCell *_trackingCell;	// 24 = 0x18
	SBAwayBulletinListView *_view;	// 28 = 0x1c
	CGRect _viewRect;	// 32 = 0x20
	float _contentHeight;	// 48 = 0x30
	BOOL _dimmed;	// 52 = 0x34
	BOOL _presentingNewBulletin;	// 53 = 0x35
	BOOL _dimmingForLockButtonPress;	// 54 = 0x36
	BOOL _hibernating;	// 55 = 0x37
	CGAffineTransform _pinnedViewTransform;	// 56 = 0x38
	SBAwayListUnlockActionContext *_unlockActionContext;	// 80 = 0x50
	NSMutableArray *_pendingSystemAlerts;	// 84 = 0x54
	id _itemToBlink;	// 88 = 0x58
	id _itemToFloat;	// 92 = 0x5c
}
@property(readonly, assign, nonatomic) UIView *view;	// G=0x185a49; @synthesize=_view
@property(assign, nonatomic) BOOL dimmed;	// G=0x185a39; S=0x188acd; @synthesize=_dimmed
@property(assign, nonatomic) CGRect viewRect;	// G=0x185a15; S=0x186569; @synthesize=_viewRect
@property(readonly, assign, nonatomic) BOOL lockBarIsTracking;	// G=0x185a05; @synthesize=_lockBarIsTracking
@property(readonly, assign, nonatomic) NSArray *listItems;	// G=0x1859f5; @synthesize=_listItems
@property(readonly, assign, nonatomic) BOOL presentingNewBulletin;	// G=0x1859e5; @synthesize=_presentingNewBulletin
@property(retain) SBAwayListUnlockActionContext *unlockActionContext;	// G=0x18918d; S=0x1896e5; converted property
@property(readonly, assign, getter=isHibernating) BOOL hibernating;	// G=0x1859cd; converted property
- (id)init;	// 0x185a59
- (void)dealloc;	// 0x189a09
- (void)clearViewsAndHibernate;	// 0x1898e9
- (void)rebuildViewsAndStopHibernating;	// 0x1897b9
// converted property getter: - (BOOL)isHibernating;	// 0x1859cd
// converted property setter: - (void)setUnlockActionContext:(id)context;	// 0x1896e5
- (void)showTestBulletin;	// 0x1894d5
- (id)_listItemForNewBulletin:(id)newBulletin;	// 0x1893d1
- (id)_listItemContainingBulletinID:(id)anId;	// 0x1892cd
- (id)_systemAlertItem;	// 0x18924d
- (void)_sortListItems;	// 0x1891c5
// converted property getter: - (id)unlockActionContext;	// 0x18918d
- (void)setTableItemToBlink:(id)blink;	// 0x188f7d
- (void)grabEnded;	// 0x188f51
- (void)setTableItemToFloat:(id)aFloat force:(BOOL)force;	// 0x188cb9
- (void)setTableItemToFloat:(id)aFloat;	// 0x188ca5
- (void)_awayControllerRelocked:(id)relocked;	// 0x188c1d
// declared property setter: - (void)setDimmed:(BOOL)dimmed;	// 0x188acd
- (void)setUnlockingTableViewCell:(id)cell;	// 0x188a85
- (void)lockBarStartedTrackingForCell:(id)cell;	// 0x1889e9
- (void)lockBarStoppedTracking;	// 0x188961
- (void)resetLockBarIfTracking;	// 0x188911
- (void)_alertForBulletin:(id)bulletin;	// 0x18882d
- (void)_realertTimerFired:(id)fired;	// 0x188655
- (void)_killRealerts:(id)realerts;	// 0x1885ad
- (void)_scheduleRealerts:(id)realerts;	// 0x188409
- (void)_hardwareButtonPressed:(id)pressed;	// 0x1883f5
- (int)_rowAnimationForInsert;	// 0x1883a1
- (int)_rowAnimationForDelete;	// 0x18834d
- (void)_updateModelAndTableViewForAddition:(id)addition;	// 0x1880fd
- (void)_updateModelAndTableViewForModification:(id)modification originalHeight:(float)height;	// 0x187df9
- (void)_updateModelAndTableViewForRemoval:(id)removal originalHeight:(float)height;	// 0x187c29
- (void)observer:(id)observer addBulletin:(id)bulletin forFeed:(unsigned)feed;	// 0x187985
- (void)observer:(id)observer modifyBulletin:(id)bulletin;	// 0x1878b9
- (void)observer:(id)observer removeBulletin:(id)bulletin;	// 0x187769
- (BOOL)observerShouldFetchAttachmentImageBeforeBulletinDelivery:(id)observer;	// 0x1859dd
- (id)observer:(id)observer multipleThumbnailSizeConstraintsForAttachmentType:(int)attachmentType;	// 0x187695
- (id)observer:(id)observer composedAttachmentImageForType:(int)type thumbnailData:(id)data key:(id)key;	// 0x1875fd
- (void)activateAlertItem:(id)item didUndimScreen:(BOOL)screen;	// 0x1872c9
- (void)deactivateAlertItem:(id)item;	// 0x187069
- (id)pendOrDeactivateAlertItemsForUnlock;	// 0x186e21
- (int)tableView:(id)view numberOfRowsInSection:(int)section;	// 0x186dbd
- (void)_setContentForTableCell:(id)tableCell withItem:(id)item floating:(BOOL)floating;	// 0x1869e1
- (id)tableView:(id)view cellForRowAtIndexPath:(id)indexPath;	// 0x1866b9
- (BOOL)tableView:(id)view canEditRowAtIndexPath:(id)indexPath;	// 0x1859e1
- (float)tableView:(id)view heightForRowAtIndexPath:(id)indexPath;	// 0x186601
- (void)scrollViewDidEndDragging:(id)scrollView willDecelerate:(BOOL)decelerate;	// 0x1865a1
// declared property setter: - (void)setViewRect:(CGRect)rect;	// 0x186569
- (double)animationDelayForShowPasscodeUI:(BOOL)showPasscodeUI duration:(double)duration;	// 0x186515
- (double)animationDurationForShowPasscodeUI:(BOOL)showPasscodeUI duration:(double)duration;	// 0x1864d5
- (void)setViewHiddenForUnlock:(BOOL)unlock;	// 0x1864c1
- (void)setViewHiddenForUnlock:(BOOL)unlock force:(BOOL)force;	// 0x186429
- (void)setPinnedViewTransform:(CGAffineTransform)transform;	// 0x1863e9
- (void)_configureAndPositionView;	// 0x186021
- (float)_rowHeightForItem:(id)item floating:(BOOL)floating;	// 0x185c89
// declared property getter: - (BOOL)presentingNewBulletin;	// 0x1859e5
// declared property getter: - (id)listItems;	// 0x1859f5
// declared property getter: - (BOOL)lockBarIsTracking;	// 0x185a05
// declared property getter: - (CGRect)viewRect;	// 0x185a15
// declared property getter: - (BOOL)dimmed;	// 0x185a39
// declared property getter: - (id)view;	// 0x185a49
@end
