/**
 * This header is generated by class-dump-z 0.2b.
 *
 * Source: (null)
 */

#import "SBUnknownSuperclass.h"
#import "SpringBoard-Structs.h"

@class UIImageView, SBBatteryChargingView;

@interface SBAwayChargingView : SBUnknownSuperclass {
	SBBatteryChargingView *_chargingView;	// 48 = 0x30
	SBBatteryChargingView *_headsetChargingView;	// 52 = 0x34
	UIImageView *_backgroundView;	// 56 = 0x38
	unsigned _animatingBatteries : 1;	// 60 = 0x3c
	unsigned _updateAfterAnimation : 1;	// 60 = 0x3c
	unsigned _showingDeviceBattery : 1;	// 60 = 0x3c
	unsigned _showingHeadsetBattery : 1;	// 60 = 0x3c
}
@property(readonly, retain) SBBatteryChargingView *chargingView;	// G=0xa486d; converted property
@property(readonly, retain) SBBatteryChargingView *headsetChargingView;	// G=0xa46bd; converted property
+ (id)backgroundImage;	// 0xa3a75
+ (CGSize)defaultSize;	// 0xa3c05
+ (BOOL)shouldShowDeviceBattery;	// 0xa3a9d
+ (BOOL)shouldShowHeadsetBattery;	// 0xa3b2d
- (id)initWithFrame:(CGRect)frame awayView:(id)view;	// 0xa3619
- (void)dealloc;	// 0xa3b61
- (void)updateInterface:(BOOL)interface;	// 0xa4985
// converted property getter: - (id)chargingView;	// 0xa486d
- (void)addChargingView;	// 0xa47dd
- (void)hideChargingView;	// 0xa3755
// converted property getter: - (id)headsetChargingView;	// 0xa46bd
- (void)addHeadsetChargingView;	// 0xa462d
- (void)hideHeadsetChargingView;	// 0xa3775
- (CGPoint)_dualBatteryPositionForBattery:(id)battery;	// 0xa4511
- (CGPoint)_singleBatteryPositionForBattery:(id)battery;	// 0xa43c9
- (void)_switchFromBattery:(id)battery toView:(id)view animate:(BOOL)animate;	// 0xa4205
- (void)_slideBattery:(id)battery toShowBattery:(id)showBattery animate:(BOOL)animate;	// 0xa3ffd
- (void)_slideBattery:(id)battery toHideBattery:(id)hideBattery animate:(BOOL)animate;	// 0xa3e45
- (void)_finishedFadeForSwitch:(id)aSwitch finished:(BOOL)finished context:(id)context;	// 0xa3795
- (void)_finishedSlideForSlideToReveal:(id)reveal finished:(BOOL)finished context:(id)context;	// 0xa3871
- (void)_finishedHideForHideToSlide:(id)slide finished:(BOOL)finished context:(id)context;	// 0xa3d19
- (void)_batteryAnimationFinished:(id)finished;	// 0xa394d
- (void)_test:(id)test;	// 0xa39a1
@end
