/**
 * This header is generated by class-dump-z 0.2b.
 *
 * Source: (null)
 */

#import "SpringBoard-Structs.h"
#import "SBAwayBulletinCell.h"


@interface SBAwayBulletinFloatingCell : SBAwayBulletinCell {
	BOOL _hideIcon;	// 273 = 0x111
}
+ (float)_contentWidthForRowWidth:(float)rowWidth leaveRoomForIcon:(BOOL)icon;	// 0x18b50d
+ (float)_rowHeightForContentHeight:(float)contentHeight;	// 0x18aeed
+ (float)rowHeightForSubtitle:(id)subtitle message:(id)message maxLines:(unsigned)lines rowWidth:(float)width;	// 0x18b4a9
+ (float)rowHeightForSubtitle:(id)subtitle message:(id)message maxLines:(unsigned)lines attachmentText:(id)text imageSize:(CGSize)size rowWidth:(float)width;	// 0x18b431
+ (float)_cellIconLeftPadding;	// 0x18aef1
+ (float)_cellContentLeftPadding;	// 0x18aef9
+ (float)_cellContentRightPadding;	// 0x18af01
+ (float)_cellContentTopPadding;	// 0x18af09
+ (float)_cellContentExtraPadding;	// 0x18af0d
- (void)_createContentView;	// 0x18b7ad
- (BOOL)_hasBackgroundColor;	// 0x18af11
- (void)setAttachmentImage:(id)image;	// 0x18b765
- (void)setUnlockActionContext:(id)context;	// 0x18b725
- (id)_lockBar;	// 0x18af15
- (BOOL)_drawsSeparator;	// 0x18af25
- (CGRect)_contentRect;	// 0x18b70d
- (CGRect)_cellContentViewFrame;	// 0x18b651
- (void)layoutSubviews;	// 0x18b56d
@end

