/**
 * This header is generated by class-dump-z 0.2b.
 *
 * Source: (null)
 */

#import "SBAwaySystemAlertCell.h"
#import "SpringBoard-Structs.h"


@interface SBAwaySystemAlertFloatingCell : SBAwaySystemAlertCell {
}
+ (float)_rowHeightForContentHeight:(float)contentHeight;	// 0x18af29
+ (float)rowHeightForTitle:(id)title message:(id)message rowWidth:(float)width buttonLabels:(id)labels;	// 0x18ba6d
+ (id)_alarmButtonBackgroundImage;	// 0x18b9dd
+ (id)_buttonBackgroundImage;	// 0x18b94d
+ (id)_cancelButtonBackgroundImage;	// 0x18b8bd
+ (id)_buttonFont;	// 0x18b891
+ (float)_buttonHorizontalInset;	// 0x18af2d
+ (float)_buttonVerticalInset;	// 0x18af35
+ (float)_cellContentLeftPadding;	// 0x18af3d
+ (float)_cellContentRightPadding;	// 0x18af45
+ (float)_cellContentTopPadding;	// 0x18af4d
+ (float)_cellContentExtraPadding;	// 0x18af51
- (void)_createContentView;	// 0x18c12d
- (BOOL)_hasBackgroundColor;	// 0x18af55
- (void)setIconImage:(id)image;	// 0x18c0fd
- (void)setButtonLabels:(id)labels handler:(id)handler isAlarm:(BOOL)alarm;	// 0x18bf11
- (BOOL)_drawsSeparator;	// 0x18af59
- (CGRect)_contentRect;	// 0x18bef9
- (CGRect)_cellContentViewFrame;	// 0x18bdc5
- (void)_getButtonWidth:(float *)width inset:(float *)inset;	// 0x18bc89
- (void)_clearButtonHandler;	// 0x18af5d
- (void)layoutSubviews;	// 0x18bb5d
@end

