/**
 * This header is generated by class-dump-z 0.2b.
 *
 * Source: (null)
 */

#import "SBUnknownSuperclass.h"

@class NSString, NSMutableArray, UIImage, BBBulletin, NSDate;

@interface SBAwayBulletinListItem : SBUnknownSuperclass {
	NSMutableArray *_bulletins;	// 4 = 0x4
	int _personID;	// 8 = 0x8
	NSString *_contactInfo;	// 12 = 0xc
	BBBulletin *_activeBulletin;	// 16 = 0x10
	NSDate *_sortDate;	// 20 = 0x14
	NSDate *_displayDate;	// 24 = 0x18
	NSString *_message;	// 28 = 0x1c
	UIImage *_listItemImage;	// 32 = 0x20
}
@property(readonly, retain) NSMutableArray *bulletins;	// G=0x195405; converted property
@property(readonly, retain) BBBulletin *activeBulletin;	// G=0x195415; converted property
@property(readonly, retain) NSDate *sortDate;	// G=0x1953f5; converted property
@property(readonly, retain) NSString *message;	// G=0x195425; converted property
- (id)initWithBulletin:(id)bulletin;	// 0x195525
- (void)dealloc;	// 0x196495
- (id)bulletinWithID:(id)anId;	// 0x1963b9
- (void)_update;	// 0x195bf9
- (void)addBulletin:(id)bulletin;	// 0x195bbd
- (void)removeBulletin:(id)bulletin;	// 0x195b55
- (void)modifyBulletin:(id)bulletin;	// 0x195ad5
- (BOOL)containsBulletinWithID:(id)anId;	// 0x195ab5
// converted property getter: - (id)sortDate;	// 0x1953f5
// converted property getter: - (id)bulletins;	// 0x195405
// converted property getter: - (id)activeBulletin;	// 0x195415
// converted property getter: - (id)message;	// 0x195425
- (id)title;	// 0x195a95
- (id)date;	// 0x195435
- (id)subtitle;	// 0x195a29
- (unsigned)maxMessageLines;	// 0x195a09
- (id)description;	// 0x195925
- (id)iconImage;	// 0x195445
- (id)attachmentImageForKey:(id)key;	// 0x1958d9
- (id)attachmentText;	// 0x195871
- (BOOL)hasSamePersonAsBulletin:(id)bulletin;	// 0x19570d
- (BOOL)canCoalesceWithBulletin:(id)bulletin;	// 0x195619
@end
