/**
 * This header is generated by class-dump-z 0.2b.
 *
 * Source: (null)
 */

#import "SBUnknownSuperclass.h"
#import "SpringBoard-Structs.h"

@class UIImage;

@interface SBBatteryReflectionView : SBUnknownSuperclass {
	UIImage *_image;	// 48 = 0x30
	UIImage *_maskImage;	// 52 = 0x34
	float _bottomMargin;	// 56 = 0x38
}
- (id)initWithImage:(id)image bottomMargin:(float)margin;	// 0xf01c1
- (void)dealloc;	// 0xf0315
- (void)setImage:(id)image;	// 0xf02bd
- (void)drawRect:(CGRect)rect;	// 0xf0375
@end
