/**
 * This header is generated by class-dump-z 0.2b.
 *
 * Source: (null)
 */

#import "SBUnknownSuperclass.h"
#import "SpringBoard-Structs.h"

@class SBBannerView, UIImageView, UIView;

@interface SBBannerAndShadowView : SBUnknownSuperclass {
	SBBannerView *_banner;	// 48 = 0x30
	UIImageView *_shadow[5];	// 52 = 0x34
	CGRect _shadowFrame[5];	// 72 = 0x48
	CGSize _bannerSize;	// 152 = 0x98
	float _sideWidth;	// 160 = 0xa0
	float _bottomHeight;	// 164 = 0xa4
	BOOL _shadowsInPortraitWindow;	// 168 = 0xa8
	UIView *_rollerContainer;	// 172 = 0xac
	UIImageView *_roller;	// 176 = 0xb0
}
@property(readonly, retain) SBBannerView *banner;	// G=0x162165; converted property
- (id)initWithBanner:(id)banner;	// 0x163d31
- (void)dealloc;	// 0x163285
// converted property getter: - (id)banner;	// 0x162165
- (void)replaceBannerWithBanner:(id)banner;	// 0x16288d
- (void)setBannerFrame:(CGRect)frame;	// 0x16294d
- (BOOL)_showsSideShadows;	// 0x162679
- (CGRect)_frameForBannerFrame:(CGRect)bannerFrame;	// 0x162175
- (CGSize)sizeThatFits:(CGSize)fits;	// 0x1629cd
- (void)_layoutSubviews;	// 0x16394d
- (void)moveShadowsToPortraitWindow:(id)portraitWindow fromOrientation:(int)orientation;	// 0x1637f5
- (void)pullShadowsBack;	// 0x1626b5
- (void)setShadowAlpha:(float)alpha;	// 0x16279d
- (void)prepareRoller;	// 0x163601
- (void)setRollerProgress:(float)progress;	// 0x163361
- (void)clearRoller;	// 0x1627e1
- (id)hitTest:(CGPoint)test withEvent:(id)event;	// 0x163325
@end
