/**
 * This header is generated by class-dump-z 0.2b.
 *
 * Source: (null)
 */

#import "SBUnknownSuperclass.h"
#import "SpringBoard-Structs.h"

@class UIImage, UIImageView, UILabel;

@interface SBBatteryChargingView : SBUnknownSuperclass {
	int _type;	// 48 = 0x30
	UIImageView *_topBatteryView;	// 52 = 0x34
	UIImageView *_bottomBatteryView;	// 56 = 0x38
	UIImage *_lastBatteryImage;	// 60 = 0x3c
	UILabel *_percentLabel;	// 64 = 0x40
	int _lastBatteryIndex;	// 68 = 0x44
	int _lastBatteryPercentage;	// 72 = 0x48
	unsigned _showReflection : 1;	// 76 = 0x4c
}
+ (CGSize)defaultSizeForType:(int)type;	// 0x83e45
+ (float)batteryHeightForType:(int)type;	// 0x83e7d
+ (int)redChargeIndexForType:(int)type;	// 0x83ea5
- (id)initWithFrame:(CGRect)frame type:(int)type;	// 0x83ee1
- (void)dealloc;	// 0x848f9
- (void)setShowsReflection:(BOOL)reflection;	// 0x848c9
- (int)_currentBatteryIndex;	// 0x846c9
- (id)_imageFormatString;	// 0x83eb1
- (void)_batteryStatusChanged:(id)changed;	// 0x83fe1
@end
