/**
 * This header is generated by class-dump-z 0.2b.
 *
 * Source: (null)
 */

#import "SBUnknownSuperclass.h"

@class SUDescriptor;

@interface SBBaseSoftwareUpdateAlertItem : SBUnknownSuperclass {
	SUDescriptor *_descriptor;	// 16 = 0x10
}
@property(readonly, assign, nonatomic) SUDescriptor *descriptor;	// G=0x16c585; @synthesize=_descriptor
- (id)initWithDescriptor:(id)descriptor;	// 0x16c595
- (void)dealloc;	// 0x16c6e5
- (id)updateName;	// 0x16c6c5
- (void)activateSoftwareUpdateSettingsDisplay;	// 0x16c67d
- (void)activateDisplayWithURL:(id)url;	// 0x16c669
- (BOOL)forcesModalAlertAppearance;	// 0x16c579
- (BOOL)shouldShowInLockScreen;	// 0x16c57d
- (BOOL)dismissOnLock;	// 0x16c581
// declared property getter: - (id)descriptor;	// 0x16c585
@end
