/**
 * This header is generated by class-dump-z 0.2b.
 *
 * Source: (null)
 */

#import "SpringBoard-Structs.h"
#import "SBHUDView.h"


@interface SBBrightnessHUDView : SBHUDView {
}
- (id)init;	// 0xf9b5d
- (BOOL)displaysLabel;	// 0xf9b35
@end

