/**
 * This header is generated by class-dump-z 0.2b.
 *
 * Source: (null)
 */

#import "SpringBoard-Structs.h"
#import "SBUnknownSuperclass.h"


@interface SBBrightnessController : SBUnknownSuperclass {
	BOOL _debounce;	// 4 = 0x4
}
+ (id)sharedBrightnessController;	// 0xf9f51
- (float)_calcButtonRepeatDelay;	// 0xf9b39
- (void)adjustBacklightLevel:(BOOL)level;	// 0xf9be5
- (void)_setBrightnessLevel:(float)level showHUD:(BOOL)hud;	// 0xf9c85
- (void)setBrightnessLevel:(float)level;	// 0xf9dad
- (void)increaseBrightnessAndRepeat;	// 0xf9dc1
- (void)decreaseBrightnessAndRepeat;	// 0xf9e51
- (void)handleBrightnessEvent:(GSEventRef)event;	// 0xf9f99
- (void)cancelBrightnessEvent;	// 0xf9ee1
@end
