/**
 * This header is generated by class-dump-z 0.2b.
 *
 * Source: (null)
 */

#import "SBBulletinHeaderViewDelegate.h"
#import "SBUnknownSuperclass.h"
#import "SpringBoard-Structs.h"

@class NSMutableSet, UIImageView, SBBulletinLinenSegmentView;

@interface SBBulletinTableView : SBUnknownSuperclass <SBBulletinHeaderViewDelegate> {
	NSMutableSet *_visibleSectionHeaders;	// 720 = 0x2d0
	SBBulletinLinenSegmentView *_fadeOverlay;	// 724 = 0x2d4
	UIImageView *_fadeOverlayMask;	// 728 = 0x2d8
}
@property(readonly, retain) NSMutableSet *visibleSectionHeaders;	// G=0x1531b5; converted property
- (id)initWithFrame:(CGRect)frame linenView:(id)view;	// 0x158efd
- (void)dealloc;	// 0x158999
// converted property getter: - (id)visibleSectionHeaders;	// 0x1531b5
- (void)setRasterizesFadeOverlay:(BOOL)overlay;	// 0x158ecd
- (void)setLinenGradientAlpha:(float)alpha;	// 0x158d1d
- (void)layoutSubviews;	// 0x158a55
- (void)headerViewWillAppear:(id)headerView;	// 0x158a31
- (void)headerViewWillDisappear:(id)headerView;	// 0x158a0d
@end
