/**
 * This header is generated by class-dump-z 0.2b.
 *
 * Source: (null)
 */

#import "SBBulletinLinenBackedCell.h"
#import "SpringBoard-Structs.h"

@class NSTimer, UIImageView, NSDate, SBBulletinCellContentView;

@interface SBBulletinListCell : SBBulletinLinenBackedCell {
	UIImageView *_bulletinAccessoryView;	// 244 = 0xf4
	UIImageView *_bottomCellSeparator;	// 248 = 0xf8
	SBBulletinCellContentView *_cellContentView;	// 252 = 0xfc
	NSDate *_futureDate;	// 256 = 0x100
	NSTimer *_futureDateTimer;	// 260 = 0x104
}
@property(retain) NSDate *futureDate;	// G=0x15768d; S=0x157669; @synthesize=_futureDate
+ (float)heightForRowWithSubtitle:(id)subtitle message:(id)message maxLines:(unsigned)lines width:(float)width italicize:(BOOL)italicize;	// 0x157619
+ (float)heightForRowWithSubtitle:(id)subtitle imageHeight:(float)height italicize:(BOOL)italicize;	// 0x1575e9
- (id)initWithLinenView:(id)linenView reuseIdentifier:(id)identifier;	// 0x15741d
- (void)dealloc;	// 0x158039
- (void)_clearFutureDateTimer;	// 0x157ff9
- (void)willMoveToSuperview:(id)superview;	// 0x157f9d
- (void)prepareForReuse;	// 0x157e61
- (void)setHighlighted:(BOOL)highlighted;	// 0x157e05
- (void)setMaxMessageLines:(unsigned)lines;	// 0x157de1
- (void)setTitle:(id)title;	// 0x157dbd
- (void)setSubtitle:(id)subtitle;	// 0x157d99
- (void)setMessage:(id)message;	// 0x157d75
- (void)setStartDate:(id)date endDate:(id)date2 timeZone:(id)zone allDay:(BOOL)day formatStyle:(int)style;	// 0x157d31
- (void)setAttachmentImage:(id)image;	// 0x157d0d
- (void)setAttachmentImageSize:(CGSize)size;	// 0x157ce1
- (void)setAttachmentText:(id)text;	// 0x157cbd
- (void)setBulletinAccessoryStyle:(int)style;	// 0x157b2d
- (void)setCellSeparatorStyle:(int)style;	// 0x157a2d
- (void)setContentItalicizedUntil:(id)until;	// 0x1578d9
- (void)_futureDateTimerFired:(id)fired;	// 0x157889
- (void)layoutSubviews;	// 0x1576a5
// declared property getter: - (id)futureDate;	// 0x15768d
// declared property setter: - (void)setFutureDate:(id)date;	// 0x157669
@end

