/**
 * This header is generated by class-dump-z 0.2b.
 *
 * Source: (null)
 */

#import "SpringBoard-Structs.h"
#import "SBUnknownSuperclass.h"


@interface SBBulletinLinenBackedCell : SBUnknownSuperclass {
}
- (id)initWithLinenView:(id)linenView reuseIdentifier:(id)identifier;	// 0x156bed
- (void)adjustLinenContents;	// 0x156d19
- (void)setLinenGradientAlpha:(float)alpha;	// 0x156ced
- (void)setFrame:(CGRect)frame;	// 0x156c99
@end
