/**
 * This header is generated by class-dump-z 0.2b.
 *
 * Source: (null)
 */

#import "SBUnknownSuperclass.h"

@class NSMutableDictionary, AVController, NSMutableArray, BBBulletin, BBObserver;

@interface SBBulletinSoundController : SBUnknownSuperclass {
	BBObserver *_observer;	// 4 = 0x4
	BOOL _deviceIsLocked;	// 8 = 0x8
	BOOL _assistantIsVisible;	// 9 = 0x9
	NSMutableArray *_blockQueue;	// 12 = 0xc
	BBBulletin *_ringtoneBulletin;	// 16 = 0x10
	AVController *_ringtoneController;	// 20 = 0x14
	id _ringtoneObserver;	// 24 = 0x18
	NSMutableDictionary *_clientsBySoundIDs;	// 28 = 0x1c
}
+ (id)_sharedInstanceCreateIfNecessary:(BOOL)necessary;	// 0x1a584d
+ (id)sharedInstance;	// 0x1a5839
+ (id)sharedInstanceIfExists;	// 0x1a5825
- (id)init;	// 0x1a5579
- (void)_cleanupSystemSound:(unsigned long)sound andKill:(BOOL)kill;	// 0x1a6989
- (void)_killSystemSound:(unsigned long)sound;	// 0x1a6975
- (void)_killRingtone;	// 0x1a6831
- (void)_hardwareButtonPressed:(id)pressed;	// 0x1a6751
- (BOOL)handleVolumeButtonDownEvent;	// 0x1a66b9
- (BOOL)playSoundForBulletin:(id)bulletin;	// 0x1a6079
- (void)killSoundForBulletin:(id)bulletin;	// 0x1a5ecd
- (BOOL)playSystemAlertSound:(unsigned long)sound forBundleID:(id)bundleID;	// 0x1a5d85
- (void)killSounds;	// 0x1a5be5
- (void)_enqueueBlock:(id)block;	// 0x1a5ac5
- (void)observer:(id)observer addBulletin:(id)bulletin forFeed:(unsigned)feed;	// 0x1a5991
- (void)observer:(id)observer removeBulletin:(id)bulletin;	// 0x1a5939
- (void)bulletinWindowStoppedBeingBusy;	// 0x1a5885
@end
