/**
 * This header is generated by class-dump-z 0.2b.
 *
 * Source: (null)
 */

#import "SBUnknownSuperclass.h"

@class NSMutableSet, UIWindow;

@interface SBBulletinWindowController : SBUnknownSuperclass {
	UIWindow *_bulletinWindow;	// 4 = 0x4
	int _bulletinWindowOrientation;	// 8 = 0x8
	NSMutableSet *_windowClients;	// 12 = 0xc
	NSMutableSet *_busyClients;	// 16 = 0x10
	NSMutableSet *_busyReasons;	// 20 = 0x14
}
@property(readonly, assign, nonatomic) UIWindow *window;	// G=0x167b81; @synthesize=_bulletinWindow
@property(readonly, assign, nonatomic) int windowOrientation;	// G=0x167b71; @synthesize=_bulletinWindowOrientation
+ (id)sharedInstance;	// 0x167c85
- (id)init;	// 0x167bcd
- (void)dealloc;	// 0x168835
- (void)setBusy:(BOOL)busy forReason:(id)reason;	// 0x1686f9
- (BOOL)isBusy;	// 0x1686c9
- (BOOL)allowsShowNotificationsGesture;	// 0x1684cd
- (BOOL)allowsHideNotificationsGesture;	// 0x168459
- (BOOL)allowsDismissBannerGesture;	// 0x168425
- (void)addWindowClient:(id)client;	// 0x168325
- (void)removeWindowClient:(id)client;	// 0x16825d
- (void)addBusyClient:(id)client;	// 0x168239
- (void)removeBusyClient:(id)client;	// 0x168215
- (void)updateBulletinWindowOrientation;	// 0x1681c5
- (void)setBulletinWindowOrientation:(int)orientation duration:(double)duration;	// 0x168071
- (void)prepareToRotateToOrientation:(int)orientation;	// 0x167f89
- (void)rotateToOrientation:(int)orientation;	// 0x167ea9
- (void)cleanUpAfterRotatingFromOrientation:(int)orientation;	// 0x167dc1
- (void)_setWindowOrientation:(int)orientation;	// 0x167ccd
// declared property getter: - (int)windowOrientation;	// 0x167b71
// declared property getter: - (id)window;	// 0x167b81
@end
