/**
 * This header is generated by class-dump-z 0.2b.
 *
 * Source: (null)
 */

#import "SpringBoard-Structs.h"
#import "SBBulletinWindowClient.h"
#import "UIGestureRecognizerDelegate.h"
#import "SBBulletinBusyClient.h"
#import "BBObserverDelegate.h"
#import "SBUnknownSuperclass.h"

@class NSMutableSet, SBBannerAndShadowView, BBObserver, UIView, NSMutableArray;

@interface SBBulletinBannerController : SBUnknownSuperclass <BBObserverDelegate, SBBulletinWindowClient, SBBulletinBusyClient, UIGestureRecognizerDelegate> {
	BBObserver *_observer;	// 4 = 0x4
	NSMutableArray *_incomingBulletinQueue;	// 8 = 0x8
	SBBannerAndShadowView *_bannerAndShadowView;	// 12 = 0xc
	UIView *_snapshotView;	// 16 = 0x10
	BOOL _dismissalOverdue;	// 20 = 0x14
	BOOL _replaceDelayIsActive;	// 21 = 0x15
	BOOL _soundIsPlaying;	// 22 = 0x16
	BOOL _assistantIsVisible;	// 23 = 0x17
	BOOL _inhospitableDisplayIsFrontmost;	// 24 = 0x18
	BOOL _deviceIsLocked;	// 25 = 0x19
	NSMutableSet *_sectionIDsToPend;	// 28 = 0x1c
	float _showcaseHeight;	// 32 = 0x20
}
+ (id)_sharedInstanceCreateIfNecessary:(BOOL)necessary;	// 0x15e85d
+ (id)sharedInstance;	// 0x15e849
+ (id)sharedInstanceIfExists;	// 0x15e835
- (id)init;	// 0x15e501
- (void)dealloc;	// 0x16195d
- (BOOL)isShowingBanner;	// 0x15e4a9
- (void)showTestBanner;	// 0x1617e1
- (void)dismissBanner;	// 0x1617cd
- (void)dismissBannerWithAnimation:(int)animation;	// 0x161765
- (void)setBannerAlpha:(float)alpha;	// 0x161741
- (id)newBannerSnapshotViewRotatedForOrientation:(int)orientation;	// 0x16147d
- (void)adjustLayoutForShowcaseHeight:(float)showcaseHeight;	// 0x1613c5
- (unsigned)_indexOfIncomingBulletinID:(id)incomingBulletinID;	// 0x161331
- (void)_removeEnqueuedBulletin:(id)bulletin;	// 0x1612d9
- (BOOL)_replaceEnqueuedBulletin:(id)bulletin;	// 0x161275
- (void)_enqueueBulletin:(id)bulletin;	// 0x161205
- (void)_dequeueBulletinIfPossible;	// 0x16104d
- (void)_presentBannerForItem:(id)item;	// 0x160dc1
- (void)_setBannerTranslation:(float)translation progress:(float)progress;	// 0x160d49
- (float)_progressForBannerTranslation:(float)bannerTranslation maxTranslation:(float)translation;	// 0x15e4c1
- (void)_adjustShadowAlphasForProgress:(float)progress;	// 0x160cb1
- (void)_handleBannerPanGesture:(id)gesture;	// 0x16082d
- (void)_handleBannerTapGesture:(id)gesture;	// 0x16079d
- (void)_tryToDismissBannerWithAnimation:(int)animation;	// 0x160725
- (void)_dismissIntervalElapsed;	// 0x1606e9
- (void)_replaceIntervalElapsed;	// 0x1606c9
- (void)_bulletinSoundCompleted:(id)completed;	// 0x1605f1
- (void)_stopCurrentSound;	// 0x160595
- (BOOL)gestureRecognizerShouldBegin:(id)gestureRecognizer;	// 0x1604e5
- (void)bulletinWindowWillRotateToOrientation:(int)bulletinWindow;	// 0x1604c5
- (void)bulletinWindowIsAnimatingRotationToOrientation:(int)orientation;	// 0x160469
- (void)bulletinWindowDidRotateFromOrientation:(int)bulletinWindow;	// 0x15e4f9
- (void)bulletinWindowStoppedBeingBusy;	// 0x160429
- (void)observer:(id)observer addBulletin:(id)bulletin forFeed:(unsigned)feed;	// 0x1603dd
- (void)observer:(id)observer modifyBulletin:(id)bulletin;	// 0x1603c9
- (void)observer:(id)observer removeBulletin:(id)bulletin;	// 0x160319
- (void)observer:(id)observer updateSectionInfo:(id)info;	// 0x1602b5
- (BOOL)observerShouldFetchAttachmentImageBeforeBulletinDelivery:(id)observer;	// 0x15e4fd
- (id)observer:(id)observer thumbnailSizeConstraintsForAttachmentType:(int)attachmentType;	// 0x160295
- (id)observer:(id)observer composedAttachmentImageForType:(int)type thumbnailData:(id)data key:(id)key;	// 0x160271
- (id)_dequeueNextBulletinItem;	// 0x16012d
- (CGRect)_normalBannerFrameForOrientation:(int)orientation;	// 0x160051
- (CGRect)_currentBannerFrameForOrientation:(int)orientation;	// 0x15ff49
- (CGRect)_calculateFlipRectAndCreateSnapshotViewForBannerFrame:(CGRect)bannerFrame orientation:(int)orientation;	// 0x15fc95
- (void)_setUpPerspectiveForNormalFlipRect:(CGRect)normalFlipRect;	// 0x15fac5
- (void)_removePerspective;	// 0x15f97d
- (void)_tearDownView;	// 0x15f8b9
- (void)_flipToBanner:(id)banner animation:(int)animation;	// 0x15f1e9
- (void)animationDidStop:(id)animation finished:(BOOL)finished;	// 0x15efb9
- (id)_meshTransformForDegreesOfRotation:(float)rotation flipInsets:(UIEdgeInsets)insets orientation:(int)orientation topIsLive:(BOOL)live;	// 0x15e895
@end
