/**
 * This header is generated by class-dump-z 0.2b.
 *
 * Source: (null)
 */




@protocol SBBulletinDateLabel <NSObject>
@property(assign, nonatomic, getter=isAllDay) BOOL allDay;
- (void)setStartDate:(id)date withTimeZone:(id)timeZone;
- (void)setEndDate:(id)date withTimeZone:(id)timeZone;
// declared property getter: - (BOOL)isAllDay;
// declared property setter: - (void)setAllDay:(BOOL)day;
@end

