/**
 * This header is generated by class-dump-z 0.2b.
 *
 * Source: (null)
 */

#import "SBBulletinAlertHandlerRegistry.h"
#import "SBUnknownSuperclass.h"

@class NSMutableDictionary;

@protocol SBBulletinAlertHandlerRegistry
- (void)addAlertHandler:(id)handler forSection:(id)section;
@end

@interface SBBulletinAlertHandlerRegistry : SBUnknownSuperclass <SBBulletinAlertHandlerRegistry> {
	NSMutableDictionary *_handlersBySectionID;	// 4 = 0x4
}
- (id)init;	// 0x1a4cc5
- (void)dealloc;	// 0x1a4dd5
- (id)alertHandlersForSection:(id)section;	// 0x1a4db1
- (void)addAlertHandler:(id)handler forSection:(id)section;	// 0x1a4d29
@end
