/**
 * This header is generated by class-dump-z 0.2b.
 *
 * Source: (null)
 */

#import "SpringBoard-Structs.h"
#import "SBUnknownSuperclass.h"


@interface SBBulletinLockBar : SBUnknownSuperclass {
}
- (id)initWithFrame:(CGRect)frame knobImage:(id)image;	// 0x19ebf5
- (void)dealloc;	// 0x19ebb5
- (float)defaultWellWidth;	// 0x19e5f9
- (id)wellImageName;	// 0x19e601
- (BOOL)allowsTouchTrackingBeyondVerticalThreshold;	// 0x19e60d
- (BOOL)usesBackgroundImage;	// 0x19e611
- (BOOL)_shouldStopLabelAnimationForGrab;	// 0x19e615
- (float)knobTrackInsetLeft;	// 0x19e619
- (float)knobTrackInsetRight;	// 0x19eb3d
- (void)_adjustLabelOrigin;	// 0x19ea71
- (float)_calcKnobYOffset;	// 0x19e9d9
- (void)knobDragged:(float)dragged;	// 0x19e939
- (CGSize)sizeThatFits:(CGSize)fits;	// 0x19e8f9
- (void)showKnob;	// 0x19e80d
- (void)hideKnob;	// 0x19e7e1
- (void)setAlpha:(float)alpha;	// 0x19e70d
- (void)setWellWidth:(float)width;	// 0x19e655
@end
