/**
 * This header is generated by class-dump-z 0.2b.
 *
 * Source: (null)
 */

#import "SpringBoard-Structs.h"
#import "SBBulletinLinenSegmentView.h"

@class SBBulletinClearButton, SBBulletinBlurredShadowLabel, NSString, UIView;
@protocol SBBulletinHeaderViewDelegate;

@interface SBBulletinHeaderView : SBBulletinLinenSegmentView {
	UIView *_translucentOverlay;	// 64 = 0x40
	UIView *_iconView;	// 68 = 0x44
	SBBulletinBlurredShadowLabel *_sectionLabel;	// 72 = 0x48
	SBBulletinClearButton *_clearButton;	// 76 = 0x4c
	id<SBBulletinHeaderViewDelegate> _delegate;	// 80 = 0x50
	NSString *_sectionID;	// 84 = 0x54
}
@property(assign, nonatomic) id<SBBulletinHeaderViewDelegate> delegate;	// G=0x15313d; S=0x15314d; @synthesize=_delegate
@property(retain, nonatomic) NSString *sectionID;	// G=0x15312d; S=0x156289; @synthesize=_sectionID
@property(readonly, assign, nonatomic) SBBulletinClearButton *clearButton;	// G=0x15311d; @synthesize=_clearButton
+ (float)headerHeight;	// 0x153115
- (id)initWithFrame:(CGRect)frame linenView:(id)view;	// 0x155bed
// declared property setter: - (void)setSectionID:(id)anId;	// 0x156289
- (void)dealloc;	// 0x1561ed
- (void)setShowsClearButton:(BOOL)button animated:(BOOL)animated;	// 0x1560f1
- (void)layoutSubviews;	// 0x155eed
- (void)willMoveToWindow:(id)window;	// 0x155eb5
- (id)_sectionNameForSectionID:(id)sectionID;	// 0x155e69
- (id)_newIconViewForSectionID:(id)sectionID;	// 0x155de5
// declared property getter: - (id)clearButton;	// 0x15311d
// declared property getter: - (id)sectionID;	// 0x15312d
// declared property getter: - (id)delegate;	// 0x15313d
// declared property setter: - (void)setDelegate:(id)delegate;	// 0x15314d
@end

