/**
 * This header is generated by class-dump-z 0.2b.
 *
 * Source: (null)
 */

#import "SBUnknownSuperclass.h"


@interface SBBulletinListTabView : SBUnknownSuperclass {
}
- (id)init;	// 0x15938d
@end
