/**
 * This header is generated by class-dump-z 0.2b.
 *
 * Source: (null)
 */

#import "BBObserverDelegate.h"
#import "SBBulletinWindowClient.h"
#import "SBBulletinListViewDelegate.h"
#import "SpringBoard-Structs.h"
#import "SBUnknownSuperclass.h"

@class SBApplication, SBBulletinClearButton, NSTimer, NSMutableDictionary, NSArray, BBObserver, SBBulletinListTabView, SBBulletinListView, NSMutableArray;

@interface SBBulletinListController : SBUnknownSuperclass <BBObserverDelegate, SBBulletinListViewDelegate, SBBulletinWindowClient> {
	BBObserver *_observer;	// 4 = 0x4
	NSMutableDictionary *_enabledSectionsByID;	// 8 = 0x8
	NSMutableArray *_visibleSectionIDs;	// 12 = 0xc
	NSArray *_possibleSectionIDs;	// 16 = 0x10
	unsigned _sectionOrderRule;	// 20 = 0x14
	NSMutableArray *_weeApps;	// 24 = 0x18
	NSMutableDictionary *_headerViewsBySectionID;	// 28 = 0x1c
	SBBulletinListTabView *_tabView;	// 32 = 0x20
	SBBulletinListView *_listView;	// 36 = 0x24
	BOOL _listViewTableViewHasLoaded;	// 40 = 0x28
	BOOL _listViewIsActive;	// 41 = 0x29
	BOOL _weeAppFullViewsHaveBeenLoaded;	// 42 = 0x2a
	SBApplication *_coveredApplication;	// 44 = 0x2c
	SBBulletinClearButton *_clearButtonCurrentlyInClearState;	// 48 = 0x30
	NSMutableArray *_enqueuedUpdates;	// 52 = 0x34
	BOOL _grabbed;	// 56 = 0x38
	float _grabbedY;	// 60 = 0x3c
	BOOL _pullingDownOutsideList;	// 64 = 0x40
	float _showcaseOffset;	// 68 = 0x44
	NSTimer *_weeAppSnapshotTimer;	// 72 = 0x48
}
@property(readonly, retain) SBBulletinListView *listView;	// G=0x14b401; converted property
@property(readonly, assign) BOOL listViewIsActive;	// G=0x14b429; converted property
+ (id)_sharedInstanceCreateIfNecessary:(BOOL)necessary;	// 0x14b7a9
+ (id)sharedInstance;	// 0x14b795
+ (id)sharedInstanceIfExists;	// 0x14b781
- (id)init;	// 0x14b4e5
- (void)dealloc;	// 0x150df1
// converted property getter: - (id)listView;	// 0x14b401
- (float)listViewHeight;	// 0x150dd1
- (void)showTabViewAnimated:(BOOL)animated;	// 0x150bad
- (void)hideTabViewAnimated:(BOOL)animated;	// 0x150ae5
- (BOOL)isShowingTabView;	// 0x14b411
- (void)prepareToShowListViewAnimated:(BOOL)showListViewAnimated aboveBanner:(BOOL)banner;	// 0x1505c5
- (void)prepareToHideListViewAnimated:(BOOL)hideListViewAnimated;	// 0x15049d
- (void)_positionTabViewAtY:(float)y;	// 0x150405
- (void)positionListViewAtY:(float)y;	// 0x1503b5
- (void)setListViewBottomShadowAlpha:(float)alpha;	// 0x150391
- (void)_cleanupAfterShowListView;	// 0x150231
- (void)_cleanupAfterHideListView;	// 0x150195
- (void)_finishShowingListViewAnimated:(BOOL)animated;	// 0x150089
- (void)finishShowingListView;	// 0x150075
- (void)showListViewAnimated:(BOOL)animated;	// 0x15000d
- (void)hideListViewAnimated:(BOOL)animated;	// 0x14ff19
- (id)_dynamicAnimationForShow:(BOOL)show targetValue:(double)value withInitialVelocity:(double)initialVelocity extraPull:(BOOL)pull;	// 0x14fda5
- (void)showListViewWithInitialVelocity:(float)initialVelocity additionalValueApplier:(id)applier completion:(id)completion;	// 0x14fc6d
- (void)hideListViewWithInitialVelocity:(float)initialVelocity hiddenY:(float)y extraPull:(BOOL)pull additionalValueApplier:(id)applier completion:(id)completion;	// 0x14fb71
- (void)hideListViewWithInitialVelocity:(float)initialVelocity completion:(id)completion;	// 0x14fb19
- (void)showListViewWithInitialVelocity:(float)initialVelocity completion:(id)completion;	// 0x14faf9
- (void)_setListViewActive:(BOOL)active;	// 0x14fa89
- (void)adjustViewForShowcaseOffset:(float)showcaseOffset;	// 0x14f8c9
- (void)_clearSnapshotTimer;	// 0x14f889
- (void)_clearWeeAppSnapshots;	// 0x14f7e1
- (void)_snapshotTimerFired;	// 0x14f7b5
- (void)_tearDownListView;	// 0x14f4c5
- (void)_tearDownTabView;	// 0x14f421
// converted property getter: - (BOOL)listViewIsActive;	// 0x14b429
- (void)_sortVisibleSectionIDsForManualSortOrder;	// 0x14f3bd
- (void)_sortVisibleSectionIDsForAutomaticSortOrder;	// 0x14f359
- (void)_sortVisibleSectionIDs;	// 0x14f325
- (unsigned)_insertVisibleSectionIDForManualSortOrder:(id)manualSortOrder;	// 0x14f1fd
- (unsigned)_insertVisibleSectionIDForAutomaticSortOrder:(id)automaticSortOrder;	// 0x14efc9
- (unsigned)_insertVisibleSectionID:(id)anId;	// 0x14ef55
- (id)_weeAppForSectionID:(id)sectionID;	// 0x14ee79
- (void)_removeWeeAppForSectionID:(id)sectionID;	// 0x14ee39
- (id)_weeAppForSectionID:(id)sectionID bundlePath:(id)path;	// 0x14ec7d
- (BOOL)_canPerformUpdate;	// 0x14b439
- (void)_performOrEnqueueUpdate:(id)update;	// 0x14ebad
- (void)_performEnqueuedUpdates;	// 0x14eae1
- (void)_loadSections;	// 0x14ea3d
- (void)_reloadTableView;	// 0x14e9d5
- (void)_configureForChangedContentAnimated:(BOOL)changedContentAnimated;	// 0x14e885
- (id)_sectionAtIndex:(unsigned)index;	// 0x14e811
- (id)_bulletinAtIndexPath:(id)indexPath;	// 0x14e7b1
- (id)_indexPathForBulletin:(id)bulletin;	// 0x14e6e1
- (float)_rowHeightForBulletin:(id)bulletin;	// 0x14e54d
- (float)_headerHeightForSection:(id)section;	// 0x14e501
- (void)_clearSection:(id)section;	// 0x14e1ad
- (void)_handleUngrabWithVelocity:(CGPoint)velocity completion:(id)completion;	// 0x14e175
- (void)_updateForTouchBeganOrMovedWithLocation:(CGPoint)location velocity:(CGPoint)velocity;	// 0x14df95
- (void)_updateForTouchEndedWithVelocity:(CGPoint)velocity completion:(id)completion;	// 0x14df45
- (void)_updateForTouchCanceled;	// 0x14df11
- (void)handleShowNotificationsGestureBeganWithTouchLocation:(CGPoint)touchLocation;	// 0x14dced
- (void)handleShowNotificationsGestureChangedWithTouchLocation:(CGPoint)touchLocation velocity:(CGPoint)velocity;	// 0x14dcdd
- (void)handleShowNotificationsGestureEndedWithVelocity:(CGPoint)velocity completion:(id)completion;	// 0x14dccd
- (void)handleShowNotificationsGestureCanceled;	// 0x14dcbd
- (void)handleTap:(id)tap;	// 0x14dca9
- (void)handlePan:(id)pan;	// 0x14dbb9
- (void)handleEatenTouch:(id)touch;	// 0x14db61
- (BOOL)gestureRecognizerShouldBegin:(id)gestureRecognizer;	// 0x14dab9
- (BOOL)gestureRecognizer:(id)recognizer shouldReceiveTouch:(id)touch;	// 0x14da01
- (void)_setClearButtonCurrentlyInClearState:(id)clearState;	// 0x14d985
- (void)bulletinWindowWillRotateToOrientation:(int)bulletinWindow;	// 0x14d8b9
- (void)bulletinWindowIsAnimatingRotationToOrientation:(int)orientation;	// 0x14d699
- (void)bulletinWindowDidRotateFromOrientation:(int)bulletinWindow;	// 0x14d5cd
- (void)_updateModelAndTableViewForNewSectionOrderRule:(unsigned)newSectionOrderRule;	// 0x14d579
- (void)_updateModelAndTableViewForNewSectionOrder:(id)newSectionOrder;	// 0x14d501
- (void)_updateModelAndTableViewForNewSectionInfo:(id)newSectionInfo;	// 0x14d295
- (void)_fixCellSeparatorAboveRow:(unsigned)row inSection:(id)section sectionIndex:(unsigned)index;	// 0x14d1ed
- (void)_fixLastRowSeparatorsAndWeeAppTopPaddingInAllSections;	// 0x14d035
- (void)_updateModelAndTableViewForAddition:(id)addition;	// 0x14cd61
- (void)_updateModelAndTableViewForModification:(id)modification originalIndex:(unsigned)index;	// 0x14c92d
- (void)_updateModelAndTableViewForRemoval:(id)removal originalIndex:(unsigned)index;	// 0x14c661
- (void)observer:(id)observer addBulletin:(id)bulletin forFeed:(unsigned)feed;	// 0x14c609
- (void)observer:(id)observer modifyBulletin:(id)bulletin;	// 0x14c5b1
- (void)observer:(id)observer removeBulletin:(id)bulletin;	// 0x14c559
- (void)observer:(id)observer updateSectionOrderRule:(unsigned)rule;	// 0x14c501
- (void)observer:(id)observer updateSectionOrder:(id)order;	// 0x14c4a9
- (void)observer:(id)observer updateSectionInfo:(id)info;	// 0x14c451
- (BOOL)observerShouldFetchAttachmentImageBeforeBulletinDelivery:(id)observer;	// 0x14b465
- (BOOL)observerShouldFetchAttachmentSizeBeforeBulletinDelivery:(id)observer;	// 0x14b475
- (id)observer:(id)observer thumbnailSizeConstraintsForAttachmentType:(int)attachmentType;	// 0x14c431
- (id)observer:(id)observer composedAttachmentImageForType:(int)type thumbnailData:(id)data key:(id)key;	// 0x14c40d
- (CGSize)observer:(id)observer composedAttachmentSizeForType:(int)type thumbnailWidth:(float)width height:(float)height key:(id)key;	// 0x14c3d9
- (int)numberOfSectionsInTableView:(id)tableView;	// 0x14c3b9
- (float)tableView:(id)view heightForHeaderInSection:(int)section;	// 0x14c385
- (id)tableView:(id)view viewForHeaderInSection:(int)section;	// 0x14c139
- (int)tableView:(id)view numberOfRowsInSection:(int)section;	// 0x14c0f1
- (float)tableView:(id)view heightForRowAtIndexPath:(id)indexPath;	// 0x14bffd
- (int)_separatorStyleForRow:(unsigned)row inSection:(id)section sectionIndex:(unsigned)index;	// 0x14bfa5
- (id)_bulletinCellForSection:(id)section sectionIndex:(unsigned)index row:(unsigned)row tableView:(id)view;	// 0x14bbe9
- (BOOL)_useTopPaddingForWeeAppAtSectionIndex:(unsigned)sectionIndex;	// 0x14bbb9
- (id)_weeAppCellForSection:(id)section sectionIndex:(unsigned)index tableView:(id)view;	// 0x14bac1
- (id)tableView:(id)view cellForRowAtIndexPath:(id)indexPath;	// 0x14b9f1
- (void)tableView:(id)view didSelectRowAtIndexPath:(id)indexPath;	// 0x14b929
- (void)tableViewDidFinishReload:(id)tableView;	// 0x14b8e9
- (void)scrollViewWillBeginDragging:(id)scrollView;	// 0x14b479
- (void)scrollViewDidEndDragging:(id)scrollView willDecelerate:(BOOL)decelerate;	// 0x14b47d
- (void)scrollViewDidEndDecelerating:(id)scrollView;	// 0x14b481
- (void)scrollViewDidScroll:(id)scrollView;	// 0x14b8c9
- (void)runScrollTest:(id)test iterations:(int)iterations delta:(int)delta;	// 0x14b7f5
- (void)finishedScrollTest;	// 0x14b7e1
@end
