/**
 * This header is generated by class-dump-z 0.2b.
 *
 * Source: (null)
 */

#import "SpringBoard-Structs.h"
#import "SBUnknownSuperclass.h"


@interface SBBulletinBlurredShadowLabel : SBUnknownSuperclass {
}
- (CGSize)sizeThatFits:(CGSize)fits;	// 0x155ac5
- (void)drawTextInRect:(CGRect)rect;	// 0x155a31
@end
