/**
 * This header is generated by class-dump-z 0.2b.
 *
 * Source: (null)
 */




@protocol SBBulletinWindowClient <NSObject>
- (void)bulletinWindowWillRotateToOrientation:(int)bulletinWindow;
- (void)bulletinWindowIsAnimatingRotationToOrientation:(int)orientation;
- (void)bulletinWindowDidRotateFromOrientation:(int)bulletinWindow;
@end

