/**
 * This header is generated by class-dump-z 0.2b.
 *
 * Source: (null)
 */

#import "SBBulletinModalController.h"
#import "SpringBoard-Structs.h"
#import "SBBulletinBusyClient.h"
#import "BBObserverDelegate.h"
#import "SBBulletinAlertHandler.h"
#import "SBUnknownSuperclass.h"

@class BBObserver, NSMutableArray, NSMapTable, NSMutableDictionary;

@interface SBBulletinModalController : SBUnknownSuperclass <BBObserverDelegate, SBBulletinAlertHandler, SBBulletinBusyClient> {
	BBObserver *_observer;	// 4 = 0x4
	BOOL _deviceIsLocked;	// 8 = 0x8
	NSMutableArray *_incomingBulletinEventQueue;	// 12 = 0xc
	NSMutableDictionary *_handlersBySectionID;	// 16 = 0x10
	NSMapTable *_handlersByBulletinID;	// 20 = 0x14
	NSMapTable *_alertsByBulletinID;	// 24 = 0x18
}
+ (id)_sharedInstanceCreateIfNecessary:(BOOL)necessary;	// 0x15dac9
+ (id)sharedInstance;	// 0x15dab5
+ (id)sharedInstanceIfExists;	// 0x15daa1
- (id)init;	// 0x15d7e5
- (void)_dequeuePendedEventsIfPossible;	// 0x15de4d
- (BOOL)_enqueueEventBlock:(id)block;	// 0x15ddb1
- (void)observer:(id)observer addBulletin:(id)bulletin forFeed:(unsigned)feed;	// 0x15dd4d
- (void)observer:(id)observer modifyBulletin:(id)bulletin;	// 0x15dce9
- (void)observer:(id)observer removeBulletin:(id)bulletin;	// 0x15dc85
- (void)observer:(id)observer purgeReferencesToBulletinID:(id)bulletinID;	// 0x15dc61
- (void)bulletinWindowStoppedBeingBusy;	// 0x15dc51
- (BOOL)bindBulletin:(id)bulletin forRegistry:(id)registry;	// 0x15d7e1
- (void)handleEvent:(int)event withBulletin:(id)bulletin forRegistry:(id)registry;	// 0x15db01
@end

@interface SBBulletinModalController (SBBulletinModalAlertLifeCycle)
- (void)destroyingAlert:(id)alert withBulletinID:(id)bulletinID;	// 0x15e441
@end
