/**
 * This header is generated by class-dump-z 0.2b.
 *
 * Source: (null)
 */

#import "SBUnknownSuperclass.h"

@class NSArray, NSMutableArray, SBWeeApp, NSDate;

@interface SBBulletinListSection : SBUnknownSuperclass {
	unsigned _sectionType;	// 4 = 0x4
	SBWeeApp *_weeApp;	// 8 = 0x8
	NSMutableArray *_bulletins;	// 12 = 0xc
	NSArray *_sortDescriptors;	// 16 = 0x10
	NSDate *_lastSortDate;	// 20 = 0x14
}
@property(retain, nonatomic) SBWeeApp *weeApp;	// G=0x14b4d5; S=0x1519dd; @synthesize=_weeApp
@property(retain, nonatomic) NSArray *sortDescriptors;	// G=0x14b4c5; S=0x151e05; @synthesize=_sortDescriptors
@property(readonly, retain) NSDate *lastSortDate;	// G=0x14b4b5; converted property
- (BOOL)isWeeAppSection;	// 0x14b485
- (BOOL)isBulletinSection;	// 0x14b49d
- (unsigned)bulletinCount;	// 0x15208d
- (BOOL)hasClearableBulletins;	// 0x151fc9
// converted property getter: - (id)lastSortDate;	// 0x14b4b5
- (id)initWithSectionType:(unsigned)sectionType;	// 0x151f01
- (void)dealloc;	// 0x151e79
// declared property setter: - (void)setSortDescriptors:(id)descriptors;	// 0x151e05
- (unsigned)_indexForNewBulletin:(id)newBulletin;	// 0x151c81
- (unsigned)indexOfBulletinID:(id)bulletinID;	// 0x151bf1
- (unsigned)addBulletin:(id)bulletin;	// 0x151b19
- (unsigned)removeBulletin:(id)bulletin;	// 0x151a4d
- (id)bulletinAtIndex:(unsigned)index;	// 0x151a05
// declared property getter: - (id)sortDescriptors;	// 0x14b4c5
// declared property getter: - (id)weeApp;	// 0x14b4d5
// declared property setter: - (void)setWeeApp:(id)app;	// 0x1519dd
@end
