/**
 * This header is generated by class-dump-z 0.2b.
 *
 * Source: (null)
 */




@protocol SBBulletinAlertHandler <NSObject>
- (BOOL)bindBulletin:(id)bulletin forRegistry:(id)registry;
- (void)handleEvent:(int)event withBulletin:(id)bulletin forRegistry:(id)registry;
@end

