/**
 * This header is generated by class-dump-z 0.2b.
 *
 * Source: (null)
 */

#import "UIGestureRecognizerDelegate.h"
#import "SBUnknownSuperclass.h"


@interface SBBulletinListTouchEater : SBUnknownSuperclass <UIGestureRecognizerDelegate> {
}
- (void)touchesBegan:(id)began withEvent:(id)event;	// 0x159271
- (void)touchesEnded:(id)ended withEvent:(id)event;	// 0x159285
- (void)touchesCancelled:(id)cancelled withEvent:(id)event;	// 0x159299
- (BOOL)canBePreventedByGestureRecognizer:(id)recognizer;	// 0x1531c5
@end
