/**
 * This header is generated by class-dump-z 0.2b.
 *
 * Source: (null)
 */




@protocol SBBulletinHeaderViewDelegate <NSObject>
- (void)headerViewWillAppear:(id)headerView;
- (void)headerViewWillDisappear:(id)headerView;
@end

