/**
 * This header is generated by class-dump-z 0.2b.
 *
 * Source: (null)
 */

#import "SBUnknownSuperclass.h"

@class NSArray, BBBulletin;

@interface SBBulletinModalAlert : SBUnknownSuperclass {
	BBBulletin *_bulletin;	// 16 = 0x10
	NSArray *_buttons;	// 20 = 0x14
	BOOL _playedSound;	// 24 = 0x18
	SBBulletinModalAlert *_superseded;	// 28 = 0x1c
}
@property(retain, nonatomic) NSArray *buttons;	// G=0x16742d; S=0x167585; @synthesize=_buttons
- (id)initWithBulletin:(id)bulletin;	// 0x16743d
- (id)initWithBulletin:(id)bulletin supersededAlert:(id)alert;	// 0x167505
- (void)dealloc;	// 0x167aa9
- (void)alertView:(id)view clickedButtonAtIndex:(int)index;	// 0x1679dd
- (void)dismiss:(int)dismiss;	// 0x167989
- (void)configure:(BOOL)configure requirePasscodeForActions:(BOOL)actions;	// 0x1675ad
- (void)willPresentAlertView:(id)view;	// 0x167451
- (void)didPresentAlertView:(id)view;	// 0x16748d
- (void)willDeactivateForReason:(int)reason;	// 0x1674d9
- (BOOL)shouldShowInLockScreen;	// 0x167421
- (BOOL)dismissOnLock;	// 0x167425
- (BOOL)allowMenuButtonDismissal;	// 0x167429
// declared property getter: - (id)buttons;	// 0x16742d
// declared property setter: - (void)setButtons:(id)buttons;	// 0x167585
@end
