/**
 * This header is generated by class-dump-z 0.2b.
 *
 * Source: (null)
 */

#import "SBUnknownSuperclass.h"


@interface SBBulletinDateLabelFactory : SBUnknownSuperclass {
}
+ (id)newLabelWithStartDate:(id)startDate endDate:(id)date timeZone:(id)zone allDay:(BOOL)day forStyle:(int)style;	// 0x190915
@end
