/**
 * This header is generated by class-dump-z 0.2b.
 *
 * Source: (null)
 */

#import "SBUnknownSuperclass.h"
#import "SpringBoard-Structs.h"

@class UIImageView;

@interface SBBulletinCellSelectionView : SBUnknownSuperclass {
	UIImageView *_gradientView;	// 48 = 0x30
	float _cellSeparatorHeight;	// 52 = 0x34
}
- (id)initWithFrame:(CGRect)frame;	// 0x157205
- (void)dealloc;	// 0x1573d1
- (void)setCellSeparatorHeight:(float)height;	// 0x157395
- (void)layoutSubviews;	// 0x1572ed
@end
