/**
 * This header is generated by class-dump-z 0.2b.
 *
 * Source: (null)
 */

#import "SBDismissOnlyAlertItem.h"


@interface SBBuddyLockScreenDismissOnlyAlertItem : SBDismissOnlyAlertItem {
}
- (BOOL)allowInSetup;	// 0x1a767d
- (BOOL)forcesModalAlertAppearance;	// 0x1a7681
@end

