/**
 * This header is generated by class-dump-z 0.2b.
 *
 * Source: (null)
 */

#import "SBUnknownSuperclass.h"
#import "SpringBoard-Structs.h"

@class SBBulletinBlurredShadowLabel, SBBulletinListTouchEater, SBBulletinTableView, UIView, UIStatusBar;

@interface SBBulletinListView : SBUnknownSuperclass {
	int _orientation;	// 48 = 0x30
	float _currentY;	// 52 = 0x34
	UIView *_slidingView;	// 56 = 0x38
	UIView *_linenView;	// 60 = 0x3c
	CGSize _linenSize;	// 64 = 0x40
	SBBulletinTableView *_tableView;	// 72 = 0x48
	UIStatusBar *_statusBar;	// 76 = 0x4c
	UIView *_statusBarPocket;	// 80 = 0x50
	UIView *_grabber;	// 84 = 0x54
	SBBulletinBlurredShadowLabel *_noNotificationsLabel;	// 88 = 0x58
	SBBulletinListTouchEater *_clearButtonTouchEater;	// 92 = 0x5c
	UIView *_cornerView[4];	// 96 = 0x60
	UIView *_bottomShadowView;	// 112 = 0x70
	UIView *_linenMask;	// 116 = 0x74
	UIView *_linenGradient;	// 120 = 0x78
	UIView *_linenRim;	// 124 = 0x7c
	UIView *_wholeShadowView;	// 128 = 0x80
	UIView *_sideShadowView[2];	// 132 = 0x84
	float _tableViewContentHeight;	// 140 = 0x8c
}
@property(readonly, assign) float currentY;	// G=0x1530a5; converted property
@property(readonly, retain) UIView *slidingView;	// G=0x1530b5; converted property
@property(readonly, retain) UIView *linenView;	// G=0x153095; converted property
@property(readonly, retain) SBBulletinTableView *tableView;	// G=0x153085; converted property
@property(readonly, retain) SBBulletinListTouchEater *clearButtonTouchEater;	// G=0x1530c5; converted property
+ (id)linen;	// 0x1534a1
+ (id)_pathToLinenCache;	// 0x153461
+ (void)removeCachedLinen;	// 0x15340d
+ (void)loadLinen;	// 0x153355
- (id)initWithFrame:(CGRect)frame delegate:(id)delegate;	// 0x154a55
- (void)dealloc;	// 0x1531c9
// converted property getter: - (id)tableView;	// 0x153085
// converted property getter: - (id)linenView;	// 0x153095
- (float)linenGradientAlpha;	// 0x154a11
- (void)positionSlidingViewAtY:(float)y;	// 0x15496d
- (float)onscreenY;	// 0x154931
- (float)offscreenY;	// 0x1548bd
// converted property getter: - (float)currentY;	// 0x1530a5
- (void)setBottomCornersOffscreen:(BOOL)offscreen animated:(BOOL)animated;	// 0x154779
- (void)setCornerAlpha:(float)alpha;	// 0x154705
- (void)setBottomShadowAlpha:(float)alpha;	// 0x154651
- (void)_positionNoNotificationsLabel;	// 0x154545
- (void)setShowsNoNotificationsLabel:(BOOL)label animated:(BOOL)animated;	// 0x154275
- (CGRect)slidingViewFrame;	// 0x15424d
// converted property getter: - (id)slidingView;	// 0x1530b5
// converted property getter: - (id)clearButtonTouchEater;	// 0x1530c5
- (void)handleStatusBarTap:(id)tap;	// 0x1541f1
- (void)handleTableViewOffsetChange;	// 0x1540e5
- (void)layoutForOrientation:(int)orientation;	// 0x15393d
- (void)_ensureContentHeightHasBeenComputed;	// 0x1538d5
- (float)_iPadSlidingViewHeightInOrientation:(int)orientation;	// 0x153841
- (float)_linenGradientAlphaForHeight:(float)height;	// 0x1530d5
- (void)adjustLayoutForAnimatedTableViewContentHeightChange:(float)animatedTableViewContentHeightChange;	// 0x1536a1
- (void)adjustLayoutForTableViewReload;	// 0x1535c9
- (void)willRotateToOrientation:(int)orientation;	// 0x153549
- (void)didRotateFromOrientation:(int)orientation;	// 0x1534c9
@end
