/**
 * This header is generated by class-dump-z 0.2b.
 *
 * Source: (null)
 */

#import "SpringBoard-Structs.h"
#import "SBBulletinCellContentViewBase.h"


@interface SBBulletinCellContentView : SBBulletinCellContentViewBase {
	BOOL _italicizeContent;	// 120 = 0x78
	float _shadowBlur;	// 124 = 0x7c
	BOOL _buttonsBelowContent;	// 128 = 0x80
}
+ (id)_titleFont:(BOOL)font;	// 0x198e61
+ (id)_dateFont:(BOOL)font;	// 0x198e25
+ (id)_subtitleFont:(BOOL)font;	// 0x198de9
+ (id)_messageFont:(BOOL)font;	// 0x198dad
+ (id)_attachmentFont:(BOOL)font;	// 0x198d71
+ (float)heightForBulletinStyleWithSubtitle:(id)subtitle message:(id)message maxLines:(unsigned)lines contentWidth:(float)width italicize:(BOOL)italicize;	// 0x198c0d
+ (float)heightForBulletinStyleWithSubtitle:(id)subtitle imageHeight:(float)height italicize:(BOOL)italicize;	// 0x198b81
+ (float)heightForSystemAlertStyleWithTitle:(id)title maxLines:(unsigned)lines message:(id)message maxLines:(unsigned)lines4 contentWidth:(float)width;	// 0x198a25
- (void)setItalicizesContent:(BOOL)content;	// 0x198919
- (void)setShadowBlur:(float)blur;	// 0x198971
- (void)setHasButtonBelow:(BOOL)below;	// 0x1989ad
- (id)_initForLayoutStyle:(int)layoutStyle;	// 0x1989dd
- (void)_configureLabel:(id)label withFont:(id)font alignment:(int)alignment;	// 0x199bdd
- (id)_dateFont;	// 0x199ba5
- (id)_titleFont;	// 0x199b6d
- (id)_subtitleFont;	// 0x199b35
- (id)_messageFont;	// 0x199afd
- (id)_attachmentFont;	// 0x199ac5
- (BOOL)_shouldVerticallyCenterBulletinStyleTitleAndDate;	// 0x199a19
- (float)_layoutTitleAtX:(float)x y:(float)y;	// 0x199801
- (float)_layoutSubtitleAtX:(float)x y:(float)y;	// 0x199751
- (float)_layoutAttachmentImageAtX:(float)x y:(float)y;	// 0x1996ed
- (float)_layoutMessageAtX:(float)x y:(float)y;	// 0x199475
- (void)_layoutAttachmentTextAtX:(float)x;	// 0x1993a1
- (void)layoutSubviews;	// 0x199151
- (void)_drawLabel:(id)label inContext:(CGContextRef)context;	// 0x1990e1
- (void)drawRect:(CGRect)rect;	// 0x198e9d
@end

