/**
 * This header is generated by class-dump-z 0.2b.
 *
 * Source: (null)
 */

#import "SpringBoard-Structs.h"
#import "SBSlidingAlertDisplay.h"


@interface SBCallFailureAlertDisplay : SBSlidingAlertDisplay {
}
+ (id)newTopBarForInstance:(id)instance;	// 0x8e7c5
+ (id)newBottomBarForInstance:(id)instance;	// 0x8e4d1
- (void)ignore:(id)ignore;	// 0x8ebad
- (void)callBack:(id)back;	// 0x8eac1
- (void)setAlert:(id)alert;	// 0x8e9b9
@end

