/**
 * This header is generated by class-dump-z 0.2b.
 *
 * Source: (null)
 */

#import "SBUnknownSuperclass.h"

@class NSURL, SBApplication;

@interface SBCallPermissionAlertItem : SBUnknownSuperclass {
	NSURL *_url;	// 16 = 0x10
	SBApplication *_sender;	// 20 = 0x14
}
- (id)initWithURL:(id)url;	// 0xee131
- (id)initWithURL:(id)url sender:(id)sender;	// 0xee3a5
- (void)dealloc;	// 0xee345
- (void)alertView:(id)view clickedButtonAtIndex:(int)index;	// 0xee2d9
- (void)configure:(BOOL)configure requirePasscodeForActions:(BOOL)actions;	// 0xee189
- (BOOL)shouldShowInLockScreen;	// 0xee125
- (BOOL)dismissOnLock;	// 0xee129
- (BOOL)allowMenuButtonDismissal;	// 0xee12d
@end
