/**
 * This header is generated by class-dump-z 0.2b.
 *
 * Source: (null)
 */

#import "SBUnknownSuperclass.h"


@interface SBCalendarController : SBUnknownSuperclass {
}
+ (id)sharedInstance;	// 0xd2419
- (id)init;	// 0xd234d
- (void)dealloc;	// 0xd25fd
- (void)_finishInitialization;	// 0xd259d
- (void)_checkForTimeZoneIfNecessary;	// 0xd248d
- (void)_significantTimeChange;	// 0xd2461
@end
