/**
 * This header is generated by class-dump-z 0.2b.
 *
 * Source: (null)
 */

#import "SBUnknownSuperclass.h"

@class CNFConferenceController;

@interface SBConferenceManager : SBUnknownSuperclass {
	CNFConferenceController *_conferenceController;	// 4 = 0x4
	unsigned _chatState;	// 8 = 0x8
}
@property(readonly, assign) unsigned chatState;	// G=0x110535; @synthesize=_chatState
@property(readonly, assign) CNFConferenceController *conferenceController;	// G=0x110d79; 
+ (id)sharedInstance;	// 0x1106d9
+ (void)initialize;	// 0x1106c9
- (id)init;	// 0x110545
// declared property getter: - (id)conferenceController;	// 0x110d79
- (BOOL)videoConferenceInvitationExists;	// 0x1104d9
- (BOOL)activeFaceTimeCallExists;	// 0x1104f1
- (BOOL)inConference;	// 0x11050d
- (BOOL)canStartConference;	// 0x110d55
- (void)dealloc;	// 0x110ca9
- (void)_handleInvitation:(id)invitation;	// 0x110c45
- (void)_conferenceStateChanged:(id)changed;	// 0x110b19
- (void)endConference;	// 0x110af1
- (id)currentCallRemoteUserId;	// 0x110ac9
- (id)currentCallStatusDisplayString;	// 0x1109d9
- (void)_conferenceAvailabilityChanged:(id)changed;	// 0x110941
- (void)_conferenceCapabilityChanged:(id)changed;	// 0x110931
- (void)updateStatusBar;	// 0x1108ed
- (void)_updateStatusBar;	// 0x110721
// declared property getter: - (unsigned)chatState;	// 0x110535
@end
