/**
 * This header is generated by class-dump-z 0.2b.
 *
 * Source: (null)
 */

#import "SpringBoard-Structs.h"
#import "SBUnknownSuperclass.h"


@interface SBCornerViewFactory : SBUnknownSuperclass {
}
+ (id)newCornerViewForCorner:(int)corner cornersFrame:(CGRect)frame;	// 0xf0a2d
+ (id)createCornerWindowForCorner:(int)corner windowLevel:(float)level cornersFrame:(CGRect)frame;	// 0xf0a69
@end
