/**
 * This header is generated by class-dump-z 0.2b.
 *
 * Source: (null)
 */

#import "SpringBoard-Structs.h"
#import "SBUnknownSuperclass.h"

@class NSMutableArray;

@interface SBCompassRecalibrationController : SBUnknownSuperclass {
	NSMutableArray *_assertionPorts;	// 4 = 0x4
}
+ (id)sharedInstance;	// 0xef38d
- (void)dealloc;	// 0xef599
- (BOOL)isCompassCalibrationHUDVisible;	// 0xef201
- (void)showHUD;	// 0xef269
- (void)removeHUD;	// 0xef2f5
- (void)clientRequestedCompassHUD:(unsigned)hud;	// 0xef475
- (void)_clientInvalidated:(CFMachPortRef)invalidated;	// 0xef3d5
@end
