/**
 * This header is generated by class-dump-z 0.2b.
 *
 * Source: (null)
 */

#import "SBPhraseInterpretation.h"

@class NSString;

@interface SBConstantInterpretation : SBPhraseInterpretation {
	NSString *_string;	// 8 = 0x8
}
- (id)initWithString:(id)string;	// 0x1929f5
- (void)dealloc;	// 0x1929a9
- (id)text;	// 0x191da5
@end

