/**
 * This header is generated by class-dump-z 0.2b.
 *
 * Source: (null)
 */

#import "SpringBoard-Structs.h"
#import "SBHUDView.h"


@interface SBCompassRecalibrationView : SBHUDView {
}
- (id)init;	// 0xeeb7d
@end

