/**
 * This header is generated by class-dump-z 0.2b.
 *
 * Source: (null)
 */

#import "SBDataPlanAccountAlertItem.h"

@class NSNumber;

@interface SBDataPlanUsageAlertItem : SBDataPlanAccountAlertItem {
	NSNumber *_remainingPortion;	// 20 = 0x14
}
@property(retain, nonatomic) NSNumber *remainingPortion;	// G=0xfadad; S=0xfae09; @synthesize=_remainingPortion
- (id)initWithAccountURL:(id)accountURL usage:(id)usage;	// 0xfadbd
- (void)dealloc;	// 0xfafc5
- (void)configure:(BOOL)configure requirePasscodeForActions:(BOOL)actions;	// 0xfae31
// declared property getter: - (id)remainingPortion;	// 0xfadad
// declared property setter: - (void)setRemainingPortion:(id)portion;	// 0xfae09
@end

