/**
 * This header is generated by class-dump-z 0.2b.
 *
 * Source: (null)
 */

#import "SBDataPlanAlertItem.h"


@interface SBDataPlanDisableAlertItem : SBDataPlanAlertItem {
}
- (void)configure:(BOOL)configure requirePasscodeForActions:(BOOL)actions;	// 0xfb031
- (void)alertView:(id)view clickedButtonAtIndex:(int)index;	// 0xfb19d
@end

