/**
 * This header is generated by class-dump-z 0.2b.
 *
 * Source: (null)
 */

#import "SBDataPlanAccountAlertItem.h"

@class NSString;

@interface SBDataPlanFailureAlertItem : SBDataPlanAccountAlertItem {
	NSString *_carrierName;	// 20 = 0x14
	BOOL _newAccount;	// 24 = 0x18
}
@property(copy, nonatomic) NSString *carrierName;	// G=0xfb701; S=0xfb821; @synthesize=_carrierName
@property(assign, nonatomic, getter=isNewAccount) BOOL newAccount;	// G=0xfb6e1; S=0xfb6f1; @synthesize=_newAccount
+ (id)laterButtonTitle;	// 0xfb7c9
+ (id)nowButtonTitle;	// 0xfb771
- (id)initWithAccountURL:(id)accountURL carrierName:(id)name newAccount:(BOOL)account;	// 0xfb711
- (void)dealloc;	// 0xfb985
- (void)configure:(BOOL)configure requirePasscodeForActions:(BOOL)actions;	// 0xfb845
// declared property getter: - (BOOL)isNewAccount;	// 0xfb6e1
// declared property setter: - (void)setNewAccount:(BOOL)account;	// 0xfb6f1
// declared property getter: - (id)carrierName;	// 0xfb701
// declared property setter: - (void)setCarrierName:(id)name;	// 0xfb821
@end

