/**
 * This header is generated by class-dump-z 0.2b.
 *
 * Source: (null)
 */

#import "SBDataPlanAlertItem.h"

@class NSURL;

@interface SBDataPlanAccountAlertItem : SBDataPlanAlertItem {
	NSURL *_accountURL;	// 16 = 0x10
}
@property(copy, nonatomic) NSURL *accountURL;	// G=0xfaafd; S=0xfac09; @synthesize=_accountURL
+ (id)laterButtonTitle;	// 0xfabb1
+ (id)nowButtonTitle;	// 0xfab59
- (id)initWithAccountURL:(id)accountURL;	// 0xfab0d
- (void)dealloc;	// 0xfad61
- (void)configure:(BOOL)configure requirePasscodeForActions:(BOOL)actions;	// 0xfacad
- (void)alertView:(id)view clickedButtonAtIndex:(int)index;	// 0xfac2d
// declared property getter: - (id)accountURL;	// 0xfaafd
// declared property setter: - (void)setAccountURL:(id)url;	// 0xfac09
@end

