/**
 * This header is generated by class-dump-z 0.2b.
 *
 * Source: (null)
 */

#import "SBUnknownSuperclass.h"
#import "SpringBoard-Structs.h"

@class SBDeviceLockViewWithKeyboard;

@interface SBDeviceLockKeyboard : SBUnknownSuperclass {
	SBDeviceLockViewWithKeyboard *_deviceLockView;	// 64 = 0x40
}
@property(assign, getter=isMinimized) BOOL minimized;	// G=0xf1f4d; S=0xf1ee9; converted property
- (id)initWithFrame:(CGRect)frame deviceLockView:(id)view;	// 0xf1f05
- (BOOL)canDismiss;	// 0xf2001
- (void)minimize;	// 0xf1fe1
- (void)maximize;	// 0xf1fc1
// converted property setter: - (void)setMinimized:(BOOL)minimized;	// 0xf1ee9
// converted property getter: - (BOOL)isMinimized;	// 0xf1f4d
@end
