/**
 * This header is generated by class-dump-z 0.2b.
 *
 * Source: (null)
 */

#import "SBUnknownSuperclass.h"

@class NSString, SBDeviceLockTitle, SBDeviceLockEntryField, UIView;

@interface SBDeviceLockView : SBUnknownSuperclass {
	int _style;	// 48 = 0x30
	int _interfaceOrientation;	// 52 = 0x34
	SBDeviceLockTitle *_statusView;	// 56 = 0x38
	SBDeviceLockEntryField *_entryView;	// 60 = 0x3c
	id _delegate;	// 64 = 0x40
}
@property(readonly, assign, nonatomic) int style;	// G=0xf6239; @synthesize=_style
@property(assign, nonatomic) int interfaceOrientation;	// G=0xf6229; S=0xf656d; @synthesize=_interfaceOrientation
@property(assign, nonatomic) id delegate;	// G=0xf6209; S=0xf6219; @synthesize=_delegate
@property(readonly, assign, nonatomic, getter=isKeypadMinimized) BOOL keypadMinimized;	// G=0xf61f9; 
@property(assign, nonatomic) BOOL showsEmergencyCallButton;	// G=0xf61f1; S=0xf61f5; 
@property(assign, nonatomic) BOOL playsKeyboardClicks;	// G=0xf61e9; S=0xf61ed; 
@property(assign, nonatomic, getter=isShowingEntryStatusWarning) BOOL showingEntryStatusWarning;	// G=0xf6735; S=0xf6711; 
@property(retain, nonatomic) NSString *passcode;	// G=0xf677d; S=0xf6759; 
@property(assign, nonatomic, getter=isShowingStatusWarning) BOOL showingStatusWarning;	// G=0xf67e1; S=0xf67bd; 
@property(retain, nonatomic) NSString *statusSubtitle;	// G=0xf6829; S=0xf6805; 
@property(retain, nonatomic) NSString *statusTitle;	// G=0xf686d; S=0xf6849; 
@property(readonly, assign, nonatomic) UIView *keypadView;	// G=0xf61e5; 
@property(readonly, assign, nonatomic) UIView *entryView;	// G=0xf61d5; 
@property(readonly, assign, nonatomic) UIView *statusView;	// G=0xf61c5; 
+ (int)defaultStyle;	// 0xf64f5
+ (id)newWithStyle:(int)style interfaceOrientation:(int)orientation showsEmergencyCall:(BOOL)call;	// 0xf6375
- (id)_initWithStyle:(int)style interfaceOrientation:(int)orientation showsEmergencyCall:(BOOL)call;	// 0xf6249
- (BOOL)canBecomeFirstResponder;	// 0xf69a9
- (BOOL)becomeFirstResponder;	// 0xf6985
- (BOOL)isFirstResponder;	// 0xf6961
- (BOOL)resignFirstResponder;	// 0xf693d
- (void)dealloc;	// 0xf68dd
- (void)setUserInteractionEnabled:(BOOL)enabled;	// 0xf688d
// declared property getter: - (id)statusView;	// 0xf61c5
// declared property getter: - (id)entryView;	// 0xf61d5
// declared property getter: - (id)keypadView;	// 0xf61e5
// declared property getter: - (id)statusTitle;	// 0xf686d
// declared property setter: - (void)setStatusTitle:(id)title;	// 0xf6849
// declared property getter: - (id)statusSubtitle;	// 0xf6829
// declared property setter: - (void)setStatusSubtitle:(id)subtitle;	// 0xf6805
// declared property getter: - (BOOL)isShowingStatusWarning;	// 0xf67e1
// declared property setter: - (void)setShowingStatusWarning:(BOOL)warning;	// 0xf67bd
- (void)blinkStatusView;	// 0xf679d
// declared property getter: - (id)passcode;	// 0xf677d
// declared property setter: - (void)setPasscode:(id)passcode;	// 0xf6759
// declared property getter: - (BOOL)isShowingEntryStatusWarning;	// 0xf6735
// declared property setter: - (void)setShowingEntryStatusWarning:(BOOL)warning;	// 0xf6711
// declared property getter: - (BOOL)playsKeyboardClicks;	// 0xf61e9
// declared property setter: - (void)setPlaysKeyboardClicks:(BOOL)clicks;	// 0xf61ed
// declared property getter: - (BOOL)showsEmergencyCallButton;	// 0xf61f1
// declared property setter: - (void)setShowsEmergencyCallButton:(BOOL)button;	// 0xf61f5
// declared property getter: - (BOOL)isKeypadMinimized;	// 0xf61f9
- (void)deviceLockEntryFieldDidAcceptEntry:(id)deviceLockEntryField;	// 0xf6701
- (void)deviceLockEntryFieldDidCancelEntry:(id)deviceLockEntryField;	// 0xf66f1
- (BOOL)deviceLockEntryField:(id)field shouldInsertText:(id)text;	// 0xf61fd
- (void)deviceLockEntryFieldTextDidChange:(id)deviceLockEntryFieldText;	// 0xf66e1
- (void)notifyDelegateThatPasscodeDidChange;	// 0xf6699
- (void)notifyDelegateThatPasscodeWasEntered;	// 0xf6651
- (void)notifyDelegateThatCancelButtonWasPressed;	// 0xf6609
- (void)notifyDelegateThatEmergencyCallButtonWasPressed;	// 0xf65c1
// declared property setter: - (void)setInterfaceOrientation:(int)orientation;	// 0xf656d
- (void)willAnimateToInterfaceOrientation:(int)interfaceOrientation;	// 0xf6201
- (void)animateToInterfaceInterfaceOrientation:(int)interfaceInterfaceOrientation;	// 0xf655d
- (void)didAnimateToInterfaceOrientation:(int)interfaceOrientation;	// 0xf6205
// declared property getter: - (id)delegate;	// 0xf6209
// declared property setter: - (void)setDelegate:(id)delegate;	// 0xf6219
// declared property getter: - (int)interfaceOrientation;	// 0xf6229
// declared property getter: - (int)style;	// 0xf6239
@end
