/**
 * This header is generated by class-dump-z 0.2b.
 *
 * Source: (null)
 */

#import "SBDeviceLockViewWithKeypad.h"

@class UIView;

@interface SBDeviceLockViewWithKeypadWildcat : SBDeviceLockViewWithKeypad {
	UIView *_bottomContainer;	// 72 = 0x48
}
- (id)_initWithStyle:(int)style interfaceOrientation:(int)orientation showsEmergencyCall:(BOOL)call;	// 0xf3779
- (void)dealloc;	// 0xf372d
- (id)keypadView;	// 0xf3205
@end

