/**
 * This header is generated by class-dump-z 0.2b.
 *
 * Source: (null)
 */




@protocol SBDeviceLockViewOwner <NSObject>
@optional
- (void)setShowingDeviceLock:(BOOL)lock;
- (void)setShowingDeviceLock:(BOOL)lock animated:(BOOL)animated;
- (void)deviceUnlockSucceeded;
- (void)deviceUnlockFailed;
- (BOOL)isDisplayingErrorStatus;
- (BOOL)shouldUseTransparentStatusBar;
- (void)animateToEmergencyCall;
@end

