/**
 * This header is generated by class-dump-z 0.2b.
 *
 * Source: (null)
 */

#import "SBUnknownSuperclass.h"

@class NSDateFormatter;

@interface SBDefaultDateLabelDateFormatCache : SBUnknownSuperclass {
	NSDateFormatter *_dayOfWeekFormatter;	// 4 = 0x4
	NSDateFormatter *_dayMonthYearFormatter;	// 8 = 0x8
	NSDateFormatter *_dayMonthFormatter;	// 12 = 0xc
	NSDateFormatter *_timeFormatter;	// 16 = 0x10
}
- (id)init;	// 0x1909f5
- (void)dealloc;	// 0x190e3d
- (void)resetFormattersIfNecessary;	// 0x190dc9
- (void)resetFormatters:(id)formatters;	// 0x190b4d
- (id)formatDateAsDayOfWeek:(id)week;	// 0x190b11
- (id)formatDateAsDayMonthYearStyle:(id)style;	// 0x190ad5
- (id)formatDateAsDayMonthStyle:(id)style;	// 0x190a99
- (id)formatDateAsTimeStyle:(id)style;	// 0x190a5d
@end
