/**
 * This header is generated by class-dump-z 0.2b.
 *
 * Source: (null)
 */

#import "SBIcon.h"


@interface SBDestinationHole : SBIcon {
}
+ (id)destinationHole;	// 0x13b5ed
- (id)automationID;	// 0x13b5c9
- (id)generateIconImage:(int)image;	// 0x13ab19
- (BOOL)shouldCacheImageForFormat:(int)format;	// 0x13ab1d
@end

