/**
 * This header is generated by class-dump-z 0.2b.
 *
 * Source: (null)
 */

#import "UIAlertViewDelegate.h"
#import "SBUnknownSuperclass.h"

@class SBIcon;

@interface SBDeleteIconAlertItem : SBUnknownSuperclass <UIAlertViewDelegate> {
	SBIcon *_icon;	// 16 = 0x10
	BOOL _checkedDocumentsInCloudState;	// 20 = 0x14
	BOOL _appHasDocumentsInCloud;	// 21 = 0x15
	BOOL _appHasDocumentsWithPendingUpdates;	// 22 = 0x16
	BOOL _askedUserAboutDocumentsDocumentsInCloud;	// 23 = 0x17
	BOOL _askedUserAboutDocumentsWithPendingUpdates;	// 24 = 0x18
}
@property(readonly, retain) SBIcon *icon;	// G=0xc34fd; converted property
- (id)initWithIcon:(id)icon;	// 0xc3515
- (void)dealloc;	// 0xc3aa1
// converted property getter: - (id)icon;	// 0xc34fd
- (void)alertView:(id)view clickedButtonAtIndex:(int)index;	// 0xc3891
- (void)_checkDocumentsInCloudStateIfNeeded;	// 0xc3739
- (void)configure:(BOOL)configure requirePasscodeForActions:(BOOL)actions;	// 0xc356d
- (BOOL)shouldShowInLockScreen;	// 0xc350d
- (BOOL)dismissOnLock;	// 0xc3511
@end
