/**
 * This header is generated by class-dump-z 0.2b.
 *
 * Source: (null)
 */

#import "SBBulletinDateLabel.h"
#import "SBUnknownSuperclass.h"

@class NSDate;

@interface SBDefaultDateLabel : SBUnknownSuperclass <SBBulletinDateLabel> {
	NSDate *_timeZoneRelativeStartDate;	// 108 = 0x6c
	NSDate *_timeZoneRelativeEndDate;	// 112 = 0x70
	BOOL _allDay;	// 116 = 0x74
	NSDate *_effectiveAllDayStartDate;	// 120 = 0x78
	NSDate *_effectiveAllDayLastValidDate;	// 124 = 0x7c
	NSDate *_effectiveAllDayEndDate;	// 128 = 0x80
	BOOL _effectiveAllDay;	// 132 = 0x84
}
@property(assign, nonatomic, getter=isAllDay) BOOL allDay;	// G=0x1909e5; S=0x191c4d; @synthesize=_allDay
@property(readonly, assign, getter=isEffectiveAllDay) BOOL effectiveAllDay;	// G=0x1909d5; converted property
+ (void)initialize;	// 0x190fa9
- (id)init;	// 0x190ec5
- (void)dealloc;	// 0x191c7d
// declared property setter: - (void)setAllDay:(BOOL)day;	// 0x191c4d
- (void)setTimeZoneRelativeStartDate:(id)date absoluteStartDate:(id)date2;	// 0x191be1
- (void)setTimeZoneRelativeEndDate:(id)date;	// 0x191b75
- (void)setStartDate:(id)date withTimeZone:(id)timeZone;	// 0x191b39
- (void)setEndDate:(id)date withTimeZone:(id)timeZone;	// 0x191b05
- (void)_resetEffectiveAllDayState:(BOOL)state;	// 0x191a89
- (void)_updateEffectiveAllDayTimes;	// 0x1918c9
- (id)_localDateForDate:(id)date inTimeZone:(id)timeZone;	// 0x19182d
- (BOOL)isDateWithinEffectiveAllDayRange:(id)range;	// 0x1916a5
// converted property getter: - (BOOL)isEffectiveAllDay;	// 0x1909d5
- (id)constructLabelString;	// 0x1910e9
- (void)updateTextIfNecessary;	// 0x19103d
- (void)update;	// 0x191011
// declared property getter: - (BOOL)isAllDay;	// 0x1909e5
@end
