/**
 * This header is generated by class-dump-z 0.2b.
 *
 * Source: (null)
 */

#import "SBDeviceLockViewWithKeyboard.h"


@interface SBDeviceLockViewWithKeyboardWildcat : SBDeviceLockViewWithKeyboard {
}
- (void)_centerStatusView;	// 0xf3075
- (void)_layoutForCurrentOrientation;	// 0xf2f15
- (id)_initWithStyle:(int)style interfaceOrientation:(int)orientation showsEmergencyCall:(BOOL)call;	// 0xf2f41
- (void)setMinimized:(BOOL)minimized;	// 0xf3035
- (void)setInterfaceOrientation:(int)orientation;	// 0xf2fe1
- (void)returnKeyPressed:(id)pressed;	// 0xf2fa1
- (void)hardwareReturnKeyPressed:(id)pressed;	// 0xf2f91
@end

