/**
 * This header is generated by class-dump-z 0.2b.
 *
 * Source: (null)
 */

#import "SBUnknownSuperclass.h"
#import "SpringBoard-Structs.h"

@class NSString, UIPasscodeField, UITextInputTraits;

@interface SBDeviceLockEntryField : SBUnknownSuperclass {
	int _style;	// 48 = 0x30
	int _interfaceOrientation;	// 52 = 0x34
	UIPasscodeField *_passcodeField;	// 56 = 0x38
	UITextInputTraits *_textInputTraits;	// 60 = 0x3c
	CFCharacterSetRef _numericTrimmingSet;	// 64 = 0x40
	BOOL _highlighted;	// 68 = 0x44
	id _delegate;	// 72 = 0x48
}
@property(assign, nonatomic) int interfaceOrientation;	// G=0xf3c69; S=0xf5071; @synthesize=_interfaceOrientation
@property(assign, nonatomic) id delegate;	// G=0xf3c49; S=0xf3c59; @synthesize=_delegate
@property(assign, nonatomic, getter=isHighlighted) BOOL highlighted;	// G=0xf3c39; S=0xf4c7d; 
@property(assign, nonatomic, getter=isOkayButtonEnabled) BOOL okayButtonEnabled;	// G=0xf4ff5; S=0xf4fc9; 
@property(copy, nonatomic) NSString *stringValue;	// G=0xf501d; S=0xf5045; 
@property(readonly, retain) UIPasscodeField *passcodeField;	// G=0xf3c29; converted property
@property(readonly, retain) UITextInputTraits *textInputTraits;	// G=0xf4f0d; converted property
- (id)initWithStyle:(int)style interfaceOrientation:(int)orientation;	// 0xf571d
- (void)dealloc;	// 0xf56a5
- (BOOL)canBecomeFirstResponder;	// 0xf48fd
- (BOOL)becomeFirstResponder;	// 0xf495d
- (BOOL)isFirstResponder;	// 0xf5645
- (BOOL)resignFirstResponder;	// 0xf55e5
// converted property getter: - (id)passcodeField;	// 0xf3c29
- (CGSize)_fieldSizeForCurrentDevice;	// 0xf54c5
- (id)_backgroundImage;	// 0xf53a9
- (void)_layoutForCurrentDevice;	// 0xf50e5
// declared property setter: - (void)setInterfaceOrientation:(int)orientation;	// 0xf5071
// declared property setter: - (void)setStringValue:(id)value;	// 0xf5045
// declared property getter: - (id)stringValue;	// 0xf501d
// declared property getter: - (BOOL)isOkayButtonEnabled;	// 0xf4ff5
// declared property setter: - (void)setOkayButtonEnabled:(BOOL)enabled;	// 0xf4fc9
- (void)appendString:(id)string;	// 0xf4f7d
- (void)deleteLastCharacter;	// 0xf4f55
// converted property getter: - (id)textInputTraits;	// 0xf4f0d
- (void)passcodeFieldTextDidChange:(id)passcodeFieldText;	// 0xf4ec5
- (BOOL)passcodeField:(id)field shouldInsertText:(id)text;	// 0xf4e69
- (void)passcodeFieldDidAcceptEntry:(id)passcodeField;	// 0xf4d7d
// declared property getter: - (BOOL)isHighlighted;	// 0xf3c39
// declared property setter: - (void)setHighlighted:(BOOL)highlighted;	// 0xf4c7d
- (void)_handleKeyEvent:(GSEventRef)event;	// 0xf4a69
- (BOOL)respondsToSelector:(SEL)selector;	// 0xf4a09
- (id)methodSignatureForSelector:(SEL)selector;	// 0xf49bd
// declared property getter: - (id)delegate;	// 0xf3c49
// declared property setter: - (void)setDelegate:(id)delegate;	// 0xf3c59
// declared property getter: - (int)interfaceOrientation;	// 0xf3c69
@end
