/**
 * This header is generated by class-dump-z 0.2b.
 *
 * Source: (null)
 */

#import "SBDeviceLockViewWithKeyboard.h"


@interface SBDeviceLockViewWithKeyboardPhone : SBDeviceLockViewWithKeyboard {
}
@property(assign) BOOL showsEmergencyCallButton;	// G=0xf2ed5; S=0xf2e41; converted property
- (id)_initWithStyle:(int)style interfaceOrientation:(int)orientation showsEmergencyCall:(BOOL)call;	// 0xf2cb1
// converted property getter: - (BOOL)showsEmergencyCallButton;	// 0xf2ed5
// converted property setter: - (void)setShowsEmergencyCallButton:(BOOL)button;	// 0xf2e41
- (void)returnKeyPressed:(id)pressed;	// 0xf2dcd
- (void)hardwareReturnKeyPressed:(id)pressed;	// 0xf2dbd
- (void)_layoutForCurrentOrientation;	// 0xf2d01
@end

