/**
 * This header is generated by class-dump-z 0.2b.
 *
 * Source: (null)
 */

#import "SpringBoard-Structs.h"
#import "SBSlidingAlertDisplay.h"


@interface SBDeviceLockPasscodeEntryAlertDisplay : SBSlidingAlertDisplay {
}
- (void)useEmergencyCallButton;	// 0xa3469
- (void)deviceUnlockSucceeded;	// 0xa3475
- (void)deviceUnlockCanceled;	// 0xa34b9
- (void)alertDisplayWillBecomeVisible;	// 0xa34fd
- (void)dismiss;	// 0xa35c5
- (float)delayForOthersActivation;	// 0xa346d
- (float)durationForOthersActivation;	// 0xa3471
@end

