/**
 * This header is generated by class-dump-z 0.2b.
 *
 * Source: (null)
 */

#import "SBDeviceLockTitle.h"

@class TPLCDView;

@interface SBDeviceLockTitlePhone : SBDeviceLockTitle {
	BOOL _highlighted;	// 56 = 0x38
	TPLCDView *_lcdView;	// 60 = 0x3c
}
@property(assign, getter=isHighlighted) BOOL highlighted;	// G=0xf0ac5; S=0xf0d89; converted property
@property(retain) id title;	// G=0xf0d69; S=0xf0d45; converted property
@property(retain) id subtitle;	// G=0xf0d25; S=0xf0cc9; converted property
- (id)_initWithStyle:(int)style interfaceOrientation:(int)orientation;	// 0xf0e95
- (void)dealloc;	// 0xf0c5d
// converted property getter: - (BOOL)isHighlighted;	// 0xf0ac5
// converted property setter: - (void)setHighlighted:(BOOL)highlighted;	// 0xf0d89
// converted property getter: - (id)title;	// 0xf0d69
// converted property setter: - (void)setTitle:(id)title;	// 0xf0d45
// converted property getter: - (id)subtitle;	// 0xf0d25
// converted property setter: - (void)setSubtitle:(id)subtitle;	// 0xf0cc9
- (void)blinkSubtitle;	// 0xf0ca9
@end

