/**
 * This header is generated by class-dump-z 0.2b.
 *
 * Source: (null)
 */

#import "SBDeviceLockView.h"

@class SBDeviceLockKeypad;

@interface SBDeviceLockViewWithKeypad : SBDeviceLockView {
	SBDeviceLockKeypad *_keypad;	// 68 = 0x44
}
@property(assign) BOOL playsKeyboardClicks;	// G=0xf3631; S=0xf360d; converted property
@property(assign) BOOL showsEmergencyCallButton;	// G=0xf35e9; S=0xf35c5; converted property
- (id)_initWithStyle:(int)style interfaceOrientation:(int)orientation showsEmergencyCall:(BOOL)call;	// 0xf3215
- (void)dealloc;	// 0xf36e1
- (id)keypadView;	// 0xf31f5
- (void)setPasscode:(id)passcode;	// 0xf3655
// converted property getter: - (BOOL)playsKeyboardClicks;	// 0xf3631
// converted property setter: - (void)setPlaysKeyboardClicks:(BOOL)clicks;	// 0xf360d
// converted property getter: - (BOOL)showsEmergencyCallButton;	// 0xf35e9
// converted property setter: - (void)setShowsEmergencyCallButton:(BOOL)button;	// 0xf35c5
- (void)deviceLockEntryFieldTextDidChange:(id)deviceLockEntryFieldText;	// 0xf3539
- (void)phonePad:(id)pad keyDown:(BOOL)down;	// 0xf34f9
- (void)phonePad:(id)pad keyUp:(BOOL)up;	// 0xf32d5
@end

