/**
 * This header is generated by class-dump-z 0.2b.
 *
 * Source: (null)
 */

#import "SBIconListModel.h"


@interface SBDockIconListModel : SBIconListModel {
}
+ (Class)viewClass;	// 0x102f45
@end

