/**
 * This header is generated by class-dump-z 0.2b.
 *
 * Source: (null)
 */

#import "SpringBoard-Structs.h"
#import "SBIconListView.h"


@interface SBDockIconListView : SBIconListView {
}
+ (unsigned)iconColumnsForInterfaceOrientation:(int)interfaceOrientation;	// 0x3143c
+ (unsigned)iconRowsForInterfaceOrientation:(int)interfaceOrientation;	// 0x311c4
+ (id)backgroundImageForOrientation:(int)orientation;	// 0x31480
- (id)initForOrientation:(int)orientation;	// 0x311d4
- (id)initWithFrame:(CGRect)frame;	// 0x31514
- (void)_updateForOrientationAnimationStopped;	// 0x31260
- (void)_updateForOrientation:(int)orientation duration:(double)duration;	// 0x319ac
- (BOOL)_shouldAnimatePropertyWithKey:(id)key;	// 0x3192c
- (void)setOrientation:(int)orientation;	// 0x31274
- (void)setOrientation:(int)orientation duration:(double)duration;	// 0x3188c
- (int)visibleIconsInDock;	// 0x312ac
- (unsigned)iconsInRowForSpacingCalculation;	// 0x3133c
- (float)topIconInset;	// 0x313e8
- (unsigned)rowAtPoint:(CGPoint)point;	// 0x311cc
- (float)sideIconInset;	// 0x31744
- (float)_additionalSideInsetToCenterIcons;	// 0x31688
- (CGPoint)originForIconAtX:(unsigned)x Y:(unsigned)y;	// 0x315f8
- (unsigned)columnAtPoint:(CGPoint)point;	// 0x31588
@end

