/**
 * This header is generated by class-dump-z 0.2b.
 *
 * Source: (null)
 */

#import "SpringBoard-Structs.h"
#import "SBIconView.h"

@class SBDownloadingProgressBar, SBDownloadingIcon;

@interface SBDownloadingIconView : SBIconView {
	SBDownloadingProgressBar *_progressView;	// 180 = 0xb4
}
@property(readonly, retain) SBDownloadingIcon *downloadingIcon;	// G=0x13e8d9; 
- (id)initWithDefaultSize;	// 0x13e935
- (void)dealloc;	// 0x13e8e9
// declared property getter: - (id)downloadingIcon;	// 0x13e8d9
- (void)setDownloadingIcon:(id)icon;	// 0x13e65d
- (void)setIcon:(id)icon;	// 0x13e831
- (void)setDisplayedIconImage:(id)image;	// 0x13e78d
- (void)_updateProgressBar;	// 0x13e73d
- (void)setGhostly:(BOOL)ghostly requester:(int)requester;	// 0x13e6e1
- (void)iconAccessoriesDidUpdate:(id)iconAccessories;	// 0x13e689
@end

