/**
 * This header is generated by class-dump-z 0.2b.
 *
 * Source: (null)
 */

#import "SpringBoard-Structs.h"
#import "SBLeafIcon.h"

@class NSString, NSMutableArray, SSDownload, SSDownloadStatus, NSOperation;

@interface SBDownloadingIcon : SBLeafIcon {
	NSString *_leafIdentifier;	// 68 = 0x44
	NSString *_applicationBundleID;	// 72 = 0x48
	SSDownload *_download;	// 76 = 0x4c
	float _progress;	// 80 = 0x50
	BOOL _installing;	// 84 = 0x54
	BOOL _wasUninstalledByUser;	// 85 = 0x55
	BOOL _isNewsstandDownload;	// 86 = 0x56
	SSDownloadStatus *_lastStatus;	// 88 = 0x58
	SSDownload *_downloadForImageDataBeingLoaded;	// 92 = 0x5c
	NSOperation *_iconImageGenerationOperation;	// 96 = 0x60
	NSMutableArray *_imageCacheFilePaths;	// 100 = 0x64
	BOOL _imageCacheBeingRead;	// 104 = 0x68
}
@property(retain) NSString *leafIdentifier;	// G=0xc7c19; S=0xc9139; converted property
@property(retain) NSString *applicationBundleID;	// G=0xc7c61; S=0xc8491; converted property
@property(retain) SSDownload *download;	// G=0xc7c71; S=0xc8325; converted property
@property(assign, getter=isNewsstandDownload) BOOL newsstandDownload;	// G=0xc7c81; S=0xc7c91; converted property
@property(assign) BOOL uninstalledByUser;	// G=0xc7ca1; S=0xc7cb1; converted property
@property(readonly, assign) float progress;	// G=0xc7c29; converted property
+ (dispatch_queue_s *)backgroundQueue;	// 0xc7ff1
+ (id)__imageCacheDirectoryPath;	// 0xc7fc5
+ (void)setupDownloadingIconImageCache;	// 0xc7f6d
+ (id)leafIdentifierForDownloadUniqueID:(id)downloadUniqueID;	// 0xc7f51
+ (id)leafIdentifierForDownload:(id)download;	// 0xc7f1d
+ (id)__darkenedIconImageForImage:(id)image;	// 0xc7de9
+ (id)__iconImageFromData:(id)data format:(int)format scale:(float)scale options:(int)options darken:(BOOL)darken;	// 0xc7d09
- (id)initWithLeafIdentifier:(id)leafIdentifier;	// 0xc9421
- (id)initWithDownload:(id)download;	// 0xc93c1
- (void)dealloc;	// 0xc9281
- (BOOL)matchesRepresentation:(id)representation;	// 0xc91ed
- (id)representation;	// 0xc7be9
- (id)description;	// 0xc9181
// converted property setter: - (void)setLeafIdentifier:(id)identifier;	// 0xc9139
- (id)identifierForCorrespondingApplicationIcon;	// 0xc9129
- (id)undarkenedHomeScreenIconImage;	// 0xc90b1
- (int)_iconImageOptions;	// 0xc8f95
- (id)getGenericIconImage:(int)image;	// 0xc8ec1
- (int)iconFormatForLocation:(int)location;	// 0xc8e75
- (BOOL)shouldCacheImageForFormat:(int)format;	// 0xc7cc5
- (void)loadAndDarkenHomeScreenIconImageInBackground;	// 0xc8db1
- (void)_reloadThumbnailImage;	// 0xc8ce5
- (void)_removeImageCacheFileAtPath:(id)path;	// 0xc8c6d
- (id)generateIconImage:(int)image;	// 0xc8b41
- (BOOL)canEllipsizeLabel;	// 0xc8b1d
- (id)displayName;	// 0xc883d
- (id)realDisplayName;	// 0xc881d
// converted property getter: - (id)leafIdentifier;	// 0xc7c19
- (void)launch;	// 0xc8709
- (BOOL)allowsUninstall;	// 0xc86bd
- (void)completeUninstall;	// 0xc85ed
- (void)reloadForStatusChange;	// 0xc84d9
// converted property getter: - (float)progress;	// 0xc7c29
- (BOOL)isDone;	// 0xc7c39
// converted property getter: - (id)applicationBundleID;	// 0xc7c61
// converted property setter: - (void)setApplicationBundleID:(id)anId;	// 0xc8491
// converted property setter: - (void)setDownload:(id)download;	// 0xc8325
// converted property getter: - (id)download;	// 0xc7c71
// converted property getter: - (BOOL)isNewsstandDownload;	// 0xc7c81
// converted property setter: - (void)setNewsstandDownload:(BOOL)download;	// 0xc7c91
- (void)retry;	// 0xc8305
- (void)remove;	// 0xc82cd
// converted property getter: - (BOOL)uninstalledByUser;	// 0xc7ca1
// converted property setter: - (void)setUninstalledByUser:(BOOL)user;	// 0xc7cb1
- (id)uninstallAlertTitle;	// 0xc8231
- (id)uninstallAlertBody;	// 0xc8195
- (id)uninstallAlertConfirmTitle;	// 0xc813d
- (id)uninstallAlertCancelTitle;	// 0xc80e5
- (void)_showAlertForError:(id)error;	// 0xc8035
- (BOOL)iconAppearsInNewsstand;	// 0xc801d
@end

