/**
 * This header is generated by class-dump-z 0.2b.
 *
 * Source: (null)
 */

#import "SBUnknownSuperclass.h"
#import "SpringBoard-Structs.h"

@class UIView;

@interface SBEmergencyCallView : SBUnknownSuperclass {
	UIView *_topBar;	// 48 = 0x30
}
@property(retain) UIView *topBar;	// G=0x95b99; S=0x95ed1; converted property
- (id)initWithFrame:(CGRect)frame topBarFrame:(CGRect)frame2 bottomBarFrame:(CGRect)frame3;	// 0x95ba9
// converted property getter: - (id)topBar;	// 0x95b99
// converted property setter: - (void)setTopBar:(id)bar;	// 0x95ed1
- (void)dealloc;	// 0x95e85
@end
