/**
 * This header is generated by class-dump-z 0.2b.
 *
 * Source: (null)
 */

#import "SpringBoard-Structs.h"
#import "SBUnknownSuperclass.h"

@class SBSlidingViewHighlight, UIImageView, SBWallpaperView, SBFolderNotchHighlightView, SBFolderNotchView, UIView, SBFolderView;

@interface SBFolderSlidingView : SBUnknownSuperclass {
	int _position;	// 48 = 0x30
	SBFolderView *_folderView;	// 52 = 0x34
	int _orientation;	// 56 = 0x38
	XXStruct_9ihRqB _notchInfo;	// 60 = 0x3c
	CGRect _wallpaperRect;	// 80 = 0x50
	UIView *_rasterizationView;	// 96 = 0x60
	UIView *_wallpaperContainerView;	// 100 = 0x64
	SBWallpaperView *_wallpaperView;	// 104 = 0x68
	SBFolderNotchView *_linenNotchView;	// 108 = 0x6c
	SBSlidingViewHighlight *_highlightView;	// 112 = 0x70
	SBFolderNotchHighlightView *_notchHighlightView;	// 116 = 0x74
	UIImageView *_dockView;	// 120 = 0x78
	UIImageView *_outgoingDockView;	// 124 = 0x7c
}
@property(readonly, retain) SBFolderView *folderView;	// G=0x11a495; converted property
- (id)initWithPosition:(int)position folderView:(id)view;	// 0x11ccd1
- (void)prepareToSetDockOrientation:(int)setDockOrientation;	// 0x11c15d
- (void)cleanUpAfterDockOrientationChange;	// 0x11c1d1
- (void)setOrientation:(int)orientation wallpaperRect:(CGRect)rect notchInfo:(XXStruct_9ihRqB)info;	// 0x11ca85
// converted property getter: - (id)folderView;	// 0x11a495
- (void)dealloc;	// 0x11c245
- (CGRect)_rectByAddingOverlapToRect:(CGRect)rect;	// 0x11a4a5
- (void)_placeNotchAndHighlights;	// 0x11c531
- (id)_newDockViewForOrientation:(int)orientation;	// 0x11c40d
- (void)setShowsHighlight:(BOOL)highlight;	// 0x11c3ad
- (void)setShouldRasterize:(BOOL)rasterize;	// 0x11c37d
- (void)handleTapGestureInWallpaperContainer:(id)wallpaperContainer;	// 0x11c331
@end
