/**
 * This header is generated by class-dump-z 0.2b.
 *
 * Source: (null)
 */

#import "SBUnknownSuperclass.h"
#import "SpringBoard-Structs.h"

@class UITextInteractionAssistant;

@interface SBFolderTextField : SBUnknownSuperclass {
}
@property(readonly, assign, nonatomic) UITextInteractionAssistant *interactionAssistant;	// @dynamic
- (id)initWithFrame:(CGRect)frame;	// 0x11c0b5
- (CGRect)textRectForBounds:(CGRect)bounds;	// 0x11a455
- (CGRect)editingRectForBounds:(CGRect)bounds;	// 0x11c12d
@end
