/**
 * This header is generated by class-dump-z 0.2b.
 *
 * Source: (null)
 */

#import "SpringBoard-Structs.h"
#import "SBUnknownSuperclass.h"


@interface SBFolderScrollOffset : SBUnknownSuperclass {
	CGPoint _scrollOffset;	// 4 = 0x4
	unsigned _identifier;	// 12 = 0xc
	int _orientation;	// 16 = 0x10
}
@property(assign) CGPoint scrollOffset;	// G=0x11cff9; S=0x11d01d; @synthesize=_scrollOffset
@property(assign) int orientation;	// G=0x11a519; S=0x11a529; @synthesize=_orientation
@property(assign) unsigned identifier;	// G=0x11a4f9; S=0x11a509; @synthesize=_identifier
// declared property getter: - (unsigned)identifier;	// 0x11a4f9
// declared property setter: - (void)setIdentifier:(unsigned)identifier;	// 0x11a509
// declared property getter: - (int)orientation;	// 0x11a519
// declared property setter: - (void)setOrientation:(int)orientation;	// 0x11a529
// declared property getter: - (CGPoint)scrollOffset;	// 0x11cff9
// declared property setter: - (void)setScrollOffset:(CGPoint)offset;	// 0x11d01d
@end
