/**
 * This header is generated by class-dump-z 0.2b.
 *
 * Source: (null)
 */

#import "SpringBoard-Structs.h"
#import "SBUnknownSuperclass.h"

@class NSSet;

@interface SBFolderRotationAnimationContext : SBUnknownSuperclass {
	NSSet *_icons;	// 4 = 0x4
	XXStruct_9ihRqB _notchInfo;	// 8 = 0x8
	double _duration;	// 28 = 0x1c
}
@property(retain, nonatomic) NSSet *icons;	// G=0x1097a9; S=0x10d5b1; @synthesize=_icons
@property(assign, nonatomic) XXStruct_9ihRqB notchInfo;	// G=0x109755; S=0x109781; @synthesize=_notchInfo
@property(assign, nonatomic) double duration;	// G=0x109729; S=0x109741; @synthesize=_duration
- (void)dealloc;	// 0x10d5d9
// declared property getter: - (double)duration;	// 0x109729
// declared property setter: - (void)setDuration:(double)duration;	// 0x109741
// declared property getter: - (XXStruct_9ihRqB)notchInfo;	// 0x109755
// declared property setter: - (void)setNotchInfo:(XXStruct_9ihRqB)info;	// 0x109781
// declared property getter: - (id)icons;	// 0x1097a9
// declared property setter: - (void)setIcons:(id)icons;	// 0x10d5b1
@end
