/**
 * This header is generated by class-dump-z 0.2b.
 *
 * Source: (null)
 */

#import "SpringBoard-Structs.h"
#import "SBUnknownSuperclass.h"


@interface SBFolderNotchView : SBUnknownSuperclass {
	XXStruct_9ihRqB _notchInfo;	// 52 = 0x34
	int _orientation;	// 72 = 0x48
}
+ (id)_keyComponentForNotchInfoRect:(CGRect)notchInfoRect;	// 0x14a7b5
+ (id)_keyForNotchInfo:(XXStruct_9ihRqB)notchInfo orientation:(int)orientation;	// 0x14a729
+ (id)_squareImageForNotchInfo:(XXStruct_9ihRqB)notchInfo orientation:(int)orientation;	// 0x14a4b5
+ (id)_imageForNotchInfo:(XXStruct_9ihRqB)notchInfo orientation:(int)orientation;	// 0x14a605
+ (id)notchForNotchInfo:(XXStruct_9ihRqB)notchInfo orientation:(int)orientation;	// 0x14a525
- (id)initWithFrame:(CGRect)frame notchInfo:(XXStruct_9ihRqB)info orientation:(int)orientation;	// 0x14a4b9
- (void)setNotchInfo:(XXStruct_9ihRqB)info orientation:(int)orientation;	// 0x14a839
@end
