/**
 * This header is generated by class-dump-z 0.2b.
 *
 * Source: (null)
 */

#import "SpringBoard-Structs.h"
#import "SBIconListView.h"


@interface SBFolderIconListView : SBIconListView {
}
+ (unsigned)iconColumnsForInterfaceOrientation:(int)interfaceOrientation;	// 0xfba9d
+ (unsigned)iconRowsForInterfaceOrientation:(int)interfaceOrientation;	// 0xfbae5
- (float)topIconInset;	// 0xfb9d1
- (float)bottomIconInset;	// 0xfb9d9
- (CGRect)nineIconRectForScrollPosition:(int)scrollPosition;	// 0xfb9e1
@end

