/**
 * This header is generated by class-dump-z 0.2b.
 *
 * Source: (null)
 */

#import "SBIconListModel.h"


@interface SBFolderIconListModel : SBIconListModel {
}
+ (Class)viewClass;	// 0x102f61
@end

