/**
 * This header is generated by class-dump-z 0.2b.
 *
 * Source: (null)
 */

#import "SBIconObserver.h"


@protocol SBFolderIconObserver <SBIconObserver>
- (void)containedIconImageDidUpdate:(id)containedIconImage;
@end

