/**
 * This header is generated by class-dump-z 0.2b.
 *
 * Source: (null)
 */

#import "SBUnknownSuperclass.h"

@class UIView, NSString;

@interface SBGestureViewCacheNode : SBUnknownSuperclass {
	UIView *m_view;	// 4 = 0x4
	int m_viewType;	// 8 = 0x8
	NSString *m_contextHostViewRequester;	// 12 = 0xc
	int m_orientation;	// 16 = 0x10
}
@property(retain, nonatomic) UIView *view;	// G=0x1833fd; S=0x183451; @synthesize=m_view
@property(assign, nonatomic) int viewType;	// G=0x1833dd; S=0x1833ed; @synthesize=m_viewType
@property(copy, nonatomic) NSString *contextHostViewRequester;	// G=0x1833cd; S=0x183479; @synthesize=m_contextHostViewRequester
@property(assign, nonatomic) int orientation;	// G=0x1833ad; S=0x1833bd; @synthesize=m_orientation
+ (id)node;	// 0x18340d
- (void)dealloc;	// 0x18349d
// declared property getter: - (int)orientation;	// 0x1833ad
// declared property setter: - (void)setOrientation:(int)orientation;	// 0x1833bd
// declared property getter: - (id)contextHostViewRequester;	// 0x1833cd
// declared property setter: - (void)setContextHostViewRequester:(id)requester;	// 0x183479
// declared property getter: - (int)viewType;	// 0x1833dd
// declared property setter: - (void)setViewType:(int)type;	// 0x1833ed
// declared property getter: - (id)view;	// 0x1833fd
// declared property setter: - (void)setView:(id)view;	// 0x183451
@end
