/**
 * This header is generated by class-dump-z 0.2b.
 *
 * Source: (null)
 */

#import "SBUnknownSuperclass.h"


@interface SBHarmonicOscillator : SBUnknownSuperclass {
	float A;	// 4 = 0x4
	float Z;	// 8 = 0x8
	float k;	// 12 = 0xc
	float dk;	// 16 = 0x10
	float mink;	// 20 = 0x14
	float m;	// 24 = 0x18
	float dm;	// 28 = 0x1c
	float minm;	// 32 = 0x20
	float psi_n;	// 36 = 0x24
	float psi_d;	// 40 = 0x28
	float zeta;	// 44 = 0x2c
}
@property(assign, nonatomic) float startingAmplitude;	// G=0x131b01; S=0x131b11; @synthesize=A
@property(assign, nonatomic) float endingAmplitude;	// G=0x131ae1; S=0x131af1; @synthesize=Z
@property(assign, nonatomic) float springStrength;	// G=0x131ac1; S=0x131ad1; @synthesize=k
@property(assign, nonatomic) float springDecay;	// G=0x131aa1; S=0x131ab1; @synthesize=dk
@property(assign, nonatomic) float minimumSpringStrength;	// G=0x131a81; S=0x131a91; @synthesize=mink
@property(assign, nonatomic) float mass;	// G=0x131a71; S=0x131e49; @synthesize=m
@property(assign, nonatomic) float massDecay;	// G=0x131a51; S=0x131a61; @synthesize=dm
@property(assign, nonatomic) float minimumMass;	// G=0x131a31; S=0x131a41; @synthesize=minm
- (id)init;	// 0x131b21
- (void)setSpringConstant:(float)constant;	// 0x131e69
// declared property setter: - (void)setMass:(float)mass;	// 0x131e49
- (void)updateParameters;	// 0x131dc5
- (float)amplitudeForElapsedTime:(double)elapsedTime;	// 0x131c1d
// declared property getter: - (float)minimumMass;	// 0x131a31
// declared property setter: - (void)setMinimumMass:(float)mass;	// 0x131a41
// declared property getter: - (float)massDecay;	// 0x131a51
// declared property setter: - (void)setMassDecay:(float)decay;	// 0x131a61
// declared property getter: - (float)mass;	// 0x131a71
// declared property getter: - (float)minimumSpringStrength;	// 0x131a81
// declared property setter: - (void)setMinimumSpringStrength:(float)strength;	// 0x131a91
// declared property getter: - (float)springDecay;	// 0x131aa1
// declared property setter: - (void)setSpringDecay:(float)decay;	// 0x131ab1
// declared property getter: - (float)springStrength;	// 0x131ac1
// declared property setter: - (void)setSpringStrength:(float)strength;	// 0x131ad1
// declared property getter: - (float)endingAmplitude;	// 0x131ae1
// declared property setter: - (void)setEndingAmplitude:(float)amplitude;	// 0x131af1
// declared property getter: - (float)startingAmplitude;	// 0x131b01
// declared property setter: - (void)setStartingAmplitude:(float)amplitude;	// 0x131b11
@end
