/**
 * This header is generated by class-dump-z 0.2b.
 *
 * Source: (null)
 */

#import "SBUnknownSuperclass.h"

@class NSDictionary, UIView, NSMutableSet;

@interface SBHostRequesterInfo : SBUnknownSuperclass {
	UIView *_wrapperView;	// 4 = 0x4
	NSMutableSet *_hiddenContexts;	// 8 = 0x8
	NSDictionary *_realContextHostViewChangedProperties;	// 12 = 0xc
	NSDictionary *_realContextHostViewOriginalProperties;	// 16 = 0x10
}
@property(readonly, assign, nonatomic) UIView *wrapperView;	// G=0xdc0d8; @synthesize=_wrapperView
@property(readonly, assign, nonatomic) NSMutableSet *hiddenContexts;	// G=0xdc0c4; @synthesize=_hiddenContexts
@property(retain, nonatomic) NSDictionary *realContextHostViewChangedProperties;	// G=0xdc0b0; S=0xde42c; @synthesize=_realContextHostViewChangedProperties
@property(retain, nonatomic) NSDictionary *realContextHostViewOriginalProperties;	// G=0xdc09c; S=0xde460; @synthesize=_realContextHostViewOriginalProperties
- (id)init;	// 0xde558
- (void)dealloc;	// 0xde494
// declared property getter: - (id)realContextHostViewOriginalProperties;	// 0xdc09c
// declared property setter: - (void)setRealContextHostViewOriginalProperties:(id)properties;	// 0xde460
// declared property getter: - (id)realContextHostViewChangedProperties;	// 0xdc0b0
// declared property setter: - (void)setRealContextHostViewChangedProperties:(id)properties;	// 0xde42c
// declared property getter: - (id)hiddenContexts;	// 0xdc0c4
// declared property getter: - (id)wrapperView;	// 0xdc0d8
@end
