/**
 * This header is generated by class-dump-z 0.2b.
 *
 * Source: (null)
 */

#import "SBUnknownSuperclass.h"


@interface SBHUDWindow : SBUnknownSuperclass {
}
- (BOOL)_ignoresHitTest;	// 0xfa0ed
@end
