/**
 * This header is generated by class-dump-z 0.2b.
 *
 * Source: (null)
 */

#import "SBUnknownSuperclass.h"


@interface SBiBooksUpdateAlertItem : SBUnknownSuperclass {
}
- (BOOL)dismissOnLock;	// 0x129ded
- (void)configure:(BOOL)configure requirePasscodeForActions:(BOOL)actions;	// 0x129df1
- (void)alertView:(id)view clickedButtonAtIndex:(int)index;	// 0x129fa5
@end
