/**
 * This header is generated by class-dump-z 0.2b.
 *
 * Source: (null)
 */

#import "SpringBoard-Structs.h"
#import "SBUnknownSuperclass.h"


@interface SBIconImageContainerView : SBUnknownSuperclass {
}
- (BOOL)pointInside:(CGPoint)inside withEvent:(id)event;	// 0x135141
- (id)hitTest:(CGPoint)test withEvent:(id)event;	// 0x13a855
@end
