/**
 * This header is generated by class-dump-z 0.2b.
 *
 * Source: (null)
 */

#import "SpringBoard-Structs.h"
#import "SBUnknownSuperclass.h"


@interface SBIconScrollView : SBUnknownSuperclass {
}
- (BOOL)cancelTouchTracking;	// 0xa9ac8
- (BOOL)_scrollsToMakeFirstResponderVisible;	// 0xa95e8
- (void)setContentOffset:(CGPoint)offset;	// 0xa9b60
@end
