/**
 * This header is generated by class-dump-z 0.2b.
 *
 * Source: (null)
 */

#import "SBUnknownSuperclass.h"
#import "SpringBoard-Structs.h"

@protocol SBIconListPageControlDelegate;

@interface SBIconListPageControl : SBUnknownSuperclass {
	id _delegate;	// 88 = 0x58
}
@property(assign, nonatomic) id<SBIconListPageControlDelegate> delegate;	// G=0xed515; S=0xed525; @synthesize=_delegate
- (void)touchesBegan:(id)began withEvent:(id)event;	// 0xed50d
- (void)touchesMoved:(id)moved withEvent:(id)event;	// 0xed511
- (void)touchesEnded:(id)ended withEvent:(id)event;	// 0xed535
- (id)_pageIndicatorImageForPage:(int)page;	// 0xed609
- (id)_pageIndicatorCurrentImageForPage:(int)page;	// 0xed709
- (void)setFrame:(CGRect)frame;	// 0xed671
// declared property getter: - (id)delegate;	// 0xed515
// declared property setter: - (void)setDelegate:(id)delegate;	// 0xed525
@end
