/**
 * This header is generated by class-dump-z 0.2b.
 *
 * Source: (null)
 */

#import "SBIcon.h"
#import "SBUnknownSuperclass.h"

@class UIImage, NSHashTable;
@protocol SBIconDelegate;

@interface SBIcon : SBUnknownSuperclass {
	NSHashTable *_observers;	// 4 = 0x4
	id _badgeNumberOrString;	// 8 = 0x8
	unsigned _isRevealable : 1;	// 12 = 0xc
	unsigned _uninstalled : 1;	// 12 = 0xc
	UIImage *_cachedIconImages[13];	// 16 = 0x10
	id<SBIconDelegate> _delegate;	// 68 = 0x44
}
@property(assign, nonatomic) id<SBIconDelegate> delegate;	// G=0x13aaf9; S=0x13ab09; @synthesize=_delegate
@property(readonly, assign, nonatomic) BOOL shouldWarmUp;	// G=0x13aa4d; 
@property(assign) BOOL isRevealable;	// G=0x13aa7d; S=0x13aa61; converted property
@property(readonly, retain) id badgeNumberOrString;	// G=0x13aaa5; converted property
- (void)addObserver:(id)observer;	// 0x13ab29
- (void)removeObserver:(id)observer;	// 0x13abc1
- (BOOL)hasObserver:(id)observer;	// 0x13abf1
// declared property getter: - (BOOL)shouldWarmUp;	// 0x13aa4d
- (int)iconFormatForLocation:(int)location;	// 0x13ac19
- (id)iconOverlayImageForLocation:(int)location;	// 0x13b4e9
- (id)init;	// 0x13b479
- (void)dealloc;	// 0x13b41d
- (id)representation;	// 0x13aa51
- (BOOL)matchesRepresentation:(id)representation;	// 0x13aa5d
- (void)localeChanged;	// 0x13ac45
// converted property setter: - (void)setIsRevealable:(BOOL)revealable;	// 0x13aa61
// converted property getter: - (BOOL)isRevealable;	// 0x13aa7d
- (id)displayName;	// 0x13aa91
- (BOOL)canEllipsizeLabel;	// 0x13aa95
- (int)localizedCompareDisplayNames:(id)names;	// 0x13ac55
- (BOOL)matchesEntity:(id)entity;	// 0x13aca5
- (id)tags;	// 0x13aa99
- (BOOL)launchEnabled;	// 0x13aa9d
- (id)generateIconImage:(int)image;	// 0x13aaa1
- (BOOL)shouldCacheImageForFormat:(int)format;	// 0x13b3f9
- (id)getStandardIconImageForLocation:(int)location;	// 0x13b3c9
- (id)getIconImage:(int)image;	// 0x13b33d
- (id)getGenericIconImage:(int)image;	// 0x13b2ad
- (void)purgeCachedImages;	// 0x13b261
- (void)reloadIconImage;	// 0x13b24d
- (void)reloadIconImagePurgingImageCache:(BOOL)cache;	// 0x13b1e5
- (int)badgeValue;	// 0x13b1c5
// converted property getter: - (id)badgeNumberOrString;	// 0x13aaa5
- (void)noteBadgeDidChange;	// 0x13b175
- (void)setBadge:(id)badge;	// 0x13b11d
- (id)automationID;	// 0x13b0e5
- (void)launch;	// 0x13aab5
- (void)launchFromViewSwitcher;	// 0x13aab9
- (BOOL)allowsUninstall;	// 0x13aabd
- (void)completeUninstall;	// 0x13aac1
- (void)setUninstalled;	// 0x13aac5
- (BOOL)isUninstalled;	// 0x13aadd
- (id)uninstallAlertTitle;	// 0x13b08d
- (id)uninstallAlertTitleForAppWithDocumentsInCloud;	// 0x13b035
- (id)uninstallAlertTitleForAppWithDocumentUpdatesPending;	// 0x13afdd
- (id)uninstallAlertBody;	// 0x13af41
- (id)uninstallAlertBodyForAppWithDocumentsInCloud;	// 0x13aea5
- (id)uninstallAlertBodyForAppWithDocumentUpdatesPending;	// 0x13ae09
- (id)uninstallAlertConfirmTitle;	// 0x13adb1
- (id)uninstallAlertCancelTitle;	// 0x13ad59
- (id)folderTitleOptions;	// 0x13aaf1
- (id)folderFallbackTitle;	// 0x13aaf5
// declared property getter: - (id)delegate;	// 0x13aaf9
// declared property setter: - (void)setDelegate:(id)delegate;	// 0x13ab09
@end

@interface SBIcon (SBApplicationIcon)
- (BOOL)isApplicationIcon;	// 0x257b9
- (id)application;	// 0x250c5
@end

@interface SBIcon (SBBookmarkIcon)
- (BOOL)isBookmarkIcon;	// 0xc28c5
@end

@interface SBIcon (SBDownloadingIcon)
- (BOOL)isDownloadingIcon;	// 0xc9545
- (id)download;	// 0xc7cc1
@end

@interface SBIcon (SBUserInstalledApplicationIcon)
- (BOOL)isUserInstalledApplicationIcon;	// 0xca8b9
@end

@interface SBIcon (SBWebApplicationIcon)
- (BOOL)isWebApplicationIcon;	// 0xd4609
@end

@interface SBIcon (SBFolderIcon)
- (BOOL)isFolderIcon;	// 0xfd2b5
- (id)folder;	// 0xfbb5d
- (id)enclosingFolder;	// 0xfd2f1
@end

@interface SBIcon (SBLeafIcon)
- (BOOL)isLeafIcon;	// 0x10059d
- (id)leafIdentifier;	// 0x1003cd
- (id)webClip;	// 0x1003d1
- (id)applicationBundleID;	// 0x1003d5
@end

@interface SBIcon (SBPrintStatusIcon)
- (BOOL)isPrintStatusIcon;	// 0x126019
@end

@interface SBIcon (SBDestinationHole)
- (BOOL)isDestinationHole;	// 0x13b6b9
@end

@interface SBIcon (SBNullIcon)
- (BOOL)isNullIcon;	// 0x13b67d
@end

@interface SBIcon (Internal)
- (void)_notifyImageDidUpdate;	// 0x13b6f5
- (void)_notifyAccessoriesDidUpdate;	// 0x13b7d9
- (void)_notifyLaunchEnabledDidChange;	// 0x13b8bd
@end

@interface SBIcon (SBNewsstandApplicationIcon)
- (BOOL)isNewsstandApplicationIcon;	// 0x13f759
- (BOOL)iconAppearsInNewsstand;	// 0x13f10d
@end

@interface SBIcon (SBNewsstandIcon)
- (BOOL)isNewsstandIcon;	// 0x13fa11
@end
