/**
 * This header is generated by class-dump-z 0.2b.
 *
 * Source: (null)
 */

#import "SpringBoard-Structs.h"
#import "SBUnknownSuperclass.h"

@class UIView, SBIcon;

@interface SBIconRotationContainer : SBUnknownSuperclass {
	UIView *_startSnapshot;	// 48 = 0x30
	UIView *_endSnapshot;	// 52 = 0x34
	SBIcon *_icon;	// 56 = 0x38
	BOOL _shouldCrossfade;	// 60 = 0x3c
	int _toOrientation;	// 64 = 0x40
	int _fromOrientation;	// 68 = 0x44
	unsigned _startIndex;	// 72 = 0x48
	unsigned _endIndex;	// 76 = 0x4c
}
@property(retain, nonatomic) SBIcon *icon;	// G=0x7e369; S=0x7ee85; @synthesize=_icon
- (void)dealloc;	// 0x7fd85
- (void)setStartIcon:(id)icon endIcon:(id)icon2 inIconList:(id)iconList fromOrientation:(int)orientation toOrientation:(int)orientation5;	// 0x7f83d
- (void)setOrigin:(CGPoint)origin;	// 0x7f7e9
- (void)prepareToCrossfade;	// 0x7f7ad
- (void)crossfadeWithDuration:(double)duration inIconList:(id)iconList;	// 0x7f1a1
- (id)newSnapshot:(id)snapshot includingShadows:(BOOL)shadows;	// 0x7eead
// declared property getter: - (id)icon;	// 0x7e369
// declared property setter: - (void)setIcon:(id)icon;	// 0x7ee85
@end
