/**
 * This header is generated by class-dump-z 0.2b.
 *
 * Source: (null)
 */

#import "SBUnknownSuperclass.h"

@class NSIndexPath;

@interface SBIconIndexPath : SBUnknownSuperclass {
	NSIndexPath *_listIndexes;	// 4 = 0x4
	NSIndexPath *_iconIndexes;	// 8 = 0x8
}
@property(retain, nonatomic) NSIndexPath *listIndexes;	// G=0x100d3d; S=0x1010fd; @synthesize=_listIndexes
@property(retain, nonatomic) NSIndexPath *iconIndexes;	// G=0x100d2d; S=0x101125; @synthesize=_iconIndexes
+ (id)indexPathWithIconIndex:(unsigned)iconIndex;	// 0x1010a1
+ (id)indexPathWithIconIndex:(unsigned)iconIndex listIndex:(unsigned)index;	// 0x101031
- (void)dealloc;	// 0x10135d
- (void)pushListIndex:(unsigned)index;	// 0x100d4d
- (void)pushIconIndex:(unsigned)index;	// 0x100de1
- (unsigned)popListIndex;	// 0x100e75
- (unsigned)popIconIndex;	// 0x100ed9
- (unsigned)outermostListIndex;	// 0x100f3d
- (unsigned)outermostIconIndex;	// 0x100f5d
- (id)indexPathByPoppingOutermostListAndIconIndexes;	// 0x100f7d
- (id)indexPathByPushingOutermostListIndex:(unsigned)index iconIndex:(unsigned)index2;	// 0x1012a1
- (BOOL)isEmpty;	// 0x101255
- (id)description;	// 0x1011e5
- (id)_listIndexes;	// 0x100d0d
- (id)_iconIndexes;	// 0x100d1d
- (BOOL)isEqualToIndexPath:(id)indexPath;	// 0x10114d
// declared property getter: - (id)iconIndexes;	// 0x100d2d
// declared property setter: - (void)setIconIndexes:(id)indexes;	// 0x101125
// declared property getter: - (id)listIndexes;	// 0x100d3d
// declared property setter: - (void)setListIndexes:(id)indexes;	// 0x1010fd
@end
