/**
 * This header is generated by class-dump-z 0.2b.
 *
 * Source: (null)
 */

#import "SpringBoard-Structs.h"
#import "BBObserverDelegate.h"
#import "SBIconListPageControlDelegate.h"
#import "SBIconViewDelegate.h"
#import "UIScrollViewDelegate.h"
#import "SBIconController.h"
#import "SBUnknownSuperclass.h"

@class NSMutableArray, SBFolderScrollOffset, SBFolderSlidingView, SBIconListView, BBObserver, SBSearchView, SBFolderView, SBWallpaperNotchView, SBSearchController, TPLCDTextView, NSMutableSet, SBIconListPageControl, SBFolder, UIView, SBIconScrollView, SBLeafIcon, SBRootFolder, SBIcon, SBDockIconListView, SBIconIndexPath, SBIconModel, UITouch, NSTimer;

@interface SBIconController : SBUnknownSuperclass <UIScrollViewDelegate, SBIconListPageControlDelegate, SBIconViewDelegate, BBObserverDelegate> {
	SBIconModel *_iconModel;	// 4 = 0x4
	SBRootFolder *_rootFolder;	// 8 = 0x8
	UIView *_contentView;	// 12 = 0xc
	SBIconScrollView *_scrollView;	// 16 = 0x10
	SBIconListPageControl *_pageControl;	// 20 = 0x14
	NSMutableArray *_rootIconLists;	// 24 = 0x18
	SBDockIconListView *_dock;	// 28 = 0x1c
	UIView *_dockContainerView;	// 32 = 0x20
	BBObserver *_bbObserver;	// 36 = 0x24
	NSMutableSet *_displayIDsWithBadgingDisabled;	// 40 = 0x28
	SBFolderView *_folderView;	// 44 = 0x2c
	NSMutableArray *_folderIconLists;	// 48 = 0x30
	SBFolder *_openFolder;	// 52 = 0x34
	SBFolder *_closingFolder;	// 56 = 0x38
	SBFolder *_folderToReopenWhenSwitcherCloses;	// 60 = 0x3c
	SBFolder *_folderToOpenWhenScrollingEnds;	// 64 = 0x40
	int _wantsToScrollListIndex;	// 68 = 0x44
	BOOL _wantsToScrollAnimated;	// 72 = 0x48
	SBFolderScrollOffset *_openFolderScrollOffset;	// 76 = 0x4c
	SBIconIndexPath *_openFolderIndexPath;	// 80 = 0x50
	id _currentListRepresentation;	// 84 = 0x54
	id _dockRepresentation;	// 88 = 0x58
	UIView *_slidingViewsContainer;	// 92 = 0x5c
	SBFolderSlidingView *_upperSlidingView;	// 96 = 0x60
	SBFolderSlidingView *_lowerSlidingView;	// 100 = 0x64
	UIView *_upperIconsSlidingView;	// 104 = 0x68
	SBWallpaperNotchView *_slidingNotchView;	// 108 = 0x6c
	SBIconListView *_ghostedIconListForFolder;	// 112 = 0x70
	SBIconListView *_ghostedIconListForSwitcher;	// 116 = 0x74
	int _currentIconListIndex;	// 120 = 0x78
	unsigned _currentFolderIconListIndex;	// 124 = 0x7c
	TPLCDTextView *_idleText;	// 128 = 0x80
	float _currentIdleTextOffset;	// 132 = 0x84
	SBSearchView *_searchView;	// 136 = 0x88
	SBSearchController *_searchController;	// 140 = 0x8c
	int _orientation;	// 144 = 0x90
	SBIcon *_lastTappedIcon;	// 148 = 0x94
	double _lastTapTime;	// 152 = 0x98
	SBLeafIcon *_iconToReveal;	// 160 = 0xa0
	SBIcon *_grabbedIcon;	// 164 = 0xa4
	SBIcon *_recipientIcon;	// 168 = 0xa8
	NSMutableArray *_iconsDroppedInToOrOutOfFolder;	// 172 = 0xac
	NSMutableArray *_insertionIndexPathsForDroppedIcons;	// 176 = 0xb0
	unsigned _numberOfDroppedIconsStillAnimatingIntoPlace;	// 180 = 0xb4
	NSTimer *_closeFolderTimer;	// 184 = 0xb8
	SBIconListView *_destinationIconList;	// 188 = 0xbc
	unsigned _destinationIndex;	// 192 = 0xc0
	SBIcon *_lastTouchedIcon;	// 196 = 0xc4
	NSTimer *_scrollPageTimer;	// 200 = 0xc8
	unsigned _didScroll : 1;	// 204 = 0xcc
	unsigned _isEditing : 1;	// 204 = 0xcc
	unsigned _animatedScrolling : 1;	// 204 = 0xcc
	unsigned _scrollingToSearch : 1;	// 204 = 0xcc
	unsigned _movedFromOrigin : 1;	// 204 = 0xcc
	unsigned _disableUpdatingCurrentIconList : 1;	// 204 = 0xcc
	unsigned _onWallpaper : 1;	// 204 = 0xcc
	unsigned _animatingFolder : 1;	// 204 = 0xcc
	unsigned _folderClosedWhileAnimatingOpen : 1;	// 205 = 0xcd
	unsigned _grabbedIconHasEverEnteredFolderView : 1;	// 205 = 0xcd
	unsigned _grabbedIconIsDraggedOutOfFolderView : 1;	// 205 = 0xcd
	BOOL _allowsUninstall;	// 206 = 0xce
	float _iconAlpha;	// 208 = 0xd0
	float _searchViewAlpha;	// 212 = 0xd4
	float _oldScrollOffset;	// 216 = 0xd8
	UITouch *_lastTouch;	// 220 = 0xdc
	CGPoint _dragPausePoint;	// 224 = 0xe0
	NSTimer *_dragPauseTimer;	// 232 = 0xe8
	NSTimer *_folderSpringloadTimer;	// 236 = 0xec
	BOOL _folderKeyboardIsAnimatingRotation;	// 240 = 0xf0
	BOOL _isAnimatingDockForIconScatter;	// 241 = 0xf1
	BOOL _isAnimatingDockFade;	// 242 = 0xf2
}
@property(readonly, assign, nonatomic) SBSearchController *searchController;	// G=0xa9740; @synthesize=_searchController
@property(retain) SBIconListView *destinationIconList;	// G=0xa9724; S=0xb4c14; converted property
@property(assign) BOOL iconsDisplayOnWallpaper;	// G=0xa9674; S=0xb2ecc; converted property
@property(retain) SBLeafIcon *iconToReveal;	// G=0xb2e90; S=0xb2e2c; converted property
@property(assign) BOOL allowsUninstall;	// G=0xa96a0; S=0xa968c; converted property
@property(assign) BOOL isEditing;	// G=0xa96d0; S=0xae634; converted property
@property(retain) SBIcon *grabbedIcon;	// G=0xa96e8; S=0xacf4c; converted property
@property(retain) SBIcon *lastTouchedIcon;	// G=0xa96fc; S=0xacbd8; converted property
@property(readonly, retain) UIView *contentView;	// G=0xb6a4c; converted property
@property(readonly, retain) SBIconScrollView *scrollView;	// G=0xa95f0; converted property
@property(readonly, retain) SBDockIconListView *dock;	// G=0xa9618; converted property
@property(readonly, retain) UIView *dockContainerView;	// G=0xa9604; converted property
@property(readonly, assign) int currentIconListIndex;	// G=0xa964c; converted property
@property(readonly, assign) int orientation;	// G=0xa9660; converted property
@property(readonly, retain) SBIcon *recipientIcon;	// G=0xa9710; converted property
@property(readonly, assign) BOOL isAnimatingDockForIconScatter;	// G=0xa96b8; converted property
+ (id)sharedInstance;	// 0xa9c44
- (id)init;	// 0xb7894
- (void)configureBBObserver;	// 0xb777c
- (void)dealloc;	// 0xb7348
// converted property getter: - (id)contentView;	// 0xb6a4c
- (CGRect)_dockContainerViewFrameForCurrentOrientation;	// 0xb68f8
// converted property getter: - (id)scrollView;	// 0xa95f0
// converted property getter: - (id)dockContainerView;	// 0xa9604
- (void)setShouldRasterizeFirstIconList:(BOOL)rasterizeFirstIconList;	// 0xb68a8
- (id)rootIconListAtIndex:(int)index;	// 0xb6804
- (id)folderIconListAtIndex:(unsigned)index;	// 0xb677c
- (void)prepareToResetRootIconLists;	// 0xb64b0
- (void)resetRootIconLists;	// 0xb5dfc
- (void)_iconVisibilityChanged:(id)changed;	// 0xb593c
- (void)setPageControlVisible:(BOOL)visible;	// 0xb5910
- (void)setPageControlAlpha:(float)alpha;	// 0xb58f0
- (void)showInfoAlertIfNeeded;	// 0xb5744
- (void)showCarrierDebuggingAlertIfNeeded;	// 0xb54b4
- (BOOL)isScrolling;	// 0xb542c
- (BOOL)isFolderScrolling;	// 0xb5384
- (void)pageControl:(id)control didRecieveTouchInDirection:(int)direction;	// 0xb52d4
- (int)lowestVisibleIconListIndexAndColumn:(int *)column totalLists:(unsigned)lists columnsPerList:(unsigned)list;	// 0xb5160
- (void)updateCurrentIconListIndexAndVisibility;	// 0xb4f20
- (void)resetCurrentVisibleIconListImageVisibilityAndJitterState;	// 0xb4cb8
- (id)currentRootIconList;	// 0xb4c98
// converted property getter: - (id)dock;	// 0xa9618
- (id)currentFolderIconList;	// 0xb4c78
// converted property setter: - (void)setDestinationIconList:(id)list;	// 0xb4c14
- (BOOL)isShowingSearch;	// 0xa962c
// converted property getter: - (int)currentIconListIndex;	// 0xa964c
- (BOOL)_iconCanBeGrabbed:(id)grabbed;	// 0xb4bc0
- (BOOL)_shouldLockItemsInStoreDemoMode;	// 0xb4b7c
- (BOOL)iconAppearsOnCurrentPage:(id)page;	// 0xb4b00
- (void)scrollToIconListContainingIcon:(id)iconListContainingIcon animate:(BOOL)animate;	// 0xb4a24
- (void)scrollToIconListAtIndex:(int)index animate:(BOOL)animate;	// 0xb4738
// converted property getter: - (int)orientation;	// 0xa9660
- (void)willRotateToInterfaceOrientation:(int)interfaceOrientation duration:(double)duration;	// 0xb4364
- (void)willAnimateRotationToInterfaceOrientation:(int)interfaceOrientation duration:(double)duration;	// 0xb3f48
- (void)didRotateFromInterfaceOrientation:(int)interfaceOrientation;	// 0xb3c1c
- (void)updateContentSize;	// 0xb3b7c
- (void)updateRootIconListFrames;	// 0xb38f0
- (void)updateIconListWallpaperState;	// 0xb36c0
- (void)updateNumberOfRootIconLists;	// 0xb3600
- (void)removeEmptyIconList:(id)list animate:(BOOL)animate;	// 0xb34ec
- (void)addNewIconsToDesignatedLocations:(id)designatedLocations saveIconState:(BOOL)state;	// 0xb334c
- (void)addNewIconToDesignatedLocation:(id)designatedLocation animate:(BOOL)animate scrollToList:(BOOL)list saveIconState:(BOOL)state;	// 0xb3098
- (void)replaceIconAtPath:(id)path withIcon:(id)icon saveState:(BOOL)state;	// 0xb2f18
// converted property getter: - (BOOL)iconsDisplayOnWallpaper;	// 0xa9674
// converted property setter: - (void)setIconsDisplayOnWallpaper:(BOOL)wallpaper;	// 0xb2ecc
// converted property getter: - (id)iconToReveal;	// 0xb2e90
// converted property setter: - (void)setIconToReveal:(id)reveal;	// 0xb2e2c
- (void)finishInstallingIcon;	// 0xb2d38
- (void)scrollToIconDestination;	// 0xb2b3c
- (id)addEmptyListViewForFolder:(id)folder;	// 0xb2a1c
- (id)placeIcon:(id)icon atIndexPath:(id)indexPath moveNow:(BOOL)now layoutNow:(BOOL)now4 pop:(BOOL)pop;	// 0xb2890
- (id)insertIcon:(id)icon atIndexPath:(id)indexPath moveNow:(BOOL)now pop:(BOOL)pop;	// 0xb272c
- (id)insertIcon:(id)icon atIndexPath:(id)indexPath moveNow:(BOOL)now;	// 0xb26fc
- (id)insertIcon:(id)icon intoListView:(id)view iconIndex:(int)index moveNow:(BOOL)now pop:(BOOL)pop;	// 0xb2320
- (id)insertIcon:(id)icon intoListView:(id)view iconIndex:(int)index moveNow:(BOOL)now;	// 0xb22e8
- (void)updateGhostlyRequestersForIcon:(id)icon inListView:(id)listView;	// 0xb2144
- (void)_iconAddedToList:(id)list;	// 0xb2084
- (void)removeIcon:(id)icon andCompactFolder:(BOOL)folder folderRef:(id *)ref;	// 0xb1edc
- (void)removeIcon:(id)icon compactFolder:(BOOL)folder;	// 0xb1eb0
- (void)uninstallIconDidAnimate:(id)uninstallIcon finished:(id)finished icon:(id)icon;	// 0xb1c6c
// converted property setter: - (void)setAllowsUninstall:(BOOL)uninstall;	// 0xa968c
// converted property getter: - (BOOL)allowsUninstall;	// 0xa96a0
- (BOOL)canUninstallIcon:(id)icon;	// 0xb1c18
- (void)uninstallIcon:(id)icon;	// 0xb1c04
- (void)uninstallIcon:(id)icon animate:(BOOL)animate;	// 0xb1958
- (void)lcdTextViewCompletedScroll:(id)scroll;	// 0xb191c
- (void)idleTextDidAnimate:(id)idleText finished:(id)finished toText:(id)text;	// 0xb1884
- (void)updateNumberOfRowsWithDuration:(float)duration;	// 0xb1614
- (BOOL)hasIdleModeText;	// 0xb15cc
- (void)setIdleModeText:(id)text;	// 0xb0f3c
- (void)scatterWithDuration:(double)duration startTime:(double)time;	// 0xb0f08
- (void)scatterWithDuration:(double)duration startTime:(double)time fade:(BOOL)fade;	// 0xb0c7c
- (void)unscatterWithDuration:(double)duration startTime:(double)time;	// 0xb0c48
- (void)unscatterWithDuration:(double)duration startTime:(double)time fade:(BOOL)fade;	// 0xb090c
- (void)_finishedUnscattering;	// 0xb0874
- (void)finishedUnscatteringIconList:(id)list;	// 0xb0808
- (void)finishedUnscatteringSearchView;	// 0xb07cc
// converted property getter: - (BOOL)isAnimatingDockForIconScatter;	// 0xa96b8
- (void)_showDockAnimationStopped:(id)stopped finished:(id)finished context:(void *)context;	// 0xb06e0
- (void)showDock:(BOOL)dock startTime:(double)time duration:(double)duration;	// 0xb0358
- (void)adjustViewsForTransition;	// 0xaff7c
- (void)_lockStateChanged:(id)changed;	// 0xafef0
- (void)_showSearchKeyboardIfNecessary:(BOOL)necessary;	// 0xafe84
- (void)scrollViewWillBeginDragging:(id)scrollView;	// 0xafe38
- (void)scrollViewDidScroll:(id)scrollView;	// 0xafab0
- (void)_scrollingDidFinish;	// 0xaf7f4
- (void)scrollViewDidEndDragging:(id)scrollView willDecelerate:(BOOL)decelerate;	// 0xaf738
- (void)scrollViewWillBeginDecelerating:(id)scrollView;	// 0xaf6a8
- (void)scrollViewDidEndDecelerating:(id)scrollView;	// 0xaf5dc
- (void)scrollViewDidEndScrollingAnimation:(id)scrollView;	// 0xaf360
- (void)_launchIcon:(id)icon;	// 0xaf264
- (void)iconWasDoubleTapped:(id)tapped;	// 0xaf1e8
- (void)iconWasTapped:(id)tapped;	// 0xaedfc
- (void)_addEmptyListIfNecessary;	// 0xaec8c
// converted property setter: - (void)setIsEditing:(BOOL)editing;	// 0xae634
// converted property getter: - (BOOL)isEditing;	// 0xa96d0
- (id)_keyboard;	// 0xae618
- (void)_keyboardWillShow:(id)_keyboard;	// 0xae430
- (void)_keyboardWillHide:(id)_keyboard;	// 0xae2a4
- (void)moveIconToWindow:(id)window;	// 0xae164
- (void)moveIconFromWindow:(id)window toIconList:(id)iconList;	// 0xae07c
- (void)restoreScrollingAndRotationAfterUngrab;	// 0xae010
- (void)ungrabAnimation:(id)animation didFinish:(id)finish grabbedIcon:(id)icon;	// 0xadf00
- (void)noteDownloadStateChanged;	// 0xadeec
- (void)noteDownloadingIconStateChanged:(id)changed;	// 0xadc9c
- (void)noteViewCovered;	// 0xadc88
- (void)setLastTouch:(id)touch;	// 0xadc24
- (void)fixupBouncedIconsInFolder:(id)folder startingWithIndex:(int)index;	// 0xada78
- (void)_dropIconInDestinationHole:(id)destinationHole;	// 0xad870
// converted property setter: - (void)setGrabbedIcon:(id)icon;	// 0xacf4c
// converted property getter: - (id)grabbedIcon;	// 0xa96e8
- (void)setRecipientIcon:(id)icon duration:(double)duration;	// 0xacc3c
// converted property getter: - (id)lastTouchedIcon;	// 0xa96fc
// converted property setter: - (void)setLastTouchedIcon:(id)icon;	// 0xacbd8
- (void)overlapAnimationStopped:(id)stopped finished:(id)finished oldRecipientIcon:(id)icon;	// 0xacb5c
// converted property getter: - (id)recipientIcon;	// 0xa9710
// converted property getter: - (id)destinationIconList;	// 0xa9724
- (void)cancelScrollTimer;	// 0xacaf8
- (void)scrollLeft;	// 0xaca08
- (void)scrollRight;	// 0xac8e4
- (void)cancelCloseFolderTimer;	// 0xac880
- (void)closeFolderTimerFired;	// 0xac848
- (void)setCloseFolderTimerIfNecessary;	// 0xac7c8
- (void)cancelDragPauseTimer;	// 0xac764
- (void)resetDragPauseTimer;	// 0xac6d8
- (void)cancelFolderSpringloadTimer;	// 0xac674
- (void)resetFolderSpringloadTimer;	// 0xac5e8
- (void)noteGrabbedIconLocationChangedWithTouch:(id)touch;	// 0xabe3c
- (void)dragPauseTimerFired;	// 0xab850
- (void)folderSpringloadTimerFired;	// 0xab624
- (void)animationDidStop:(id)animation finished:(BOOL)finished;	// 0xab470
- (void)noteGrabbedIconLocationChangedWithEvent:(id)event;	// 0xab420
- (void)compactFolders:(id)folders;	// 0xab2c4
- (void)compactRootIconLists;	// 0xab11c
- (void)compactIconsInIconListsInFolder:(id)folder moveNow:(BOOL)now limitToIconList:(id)iconList;	// 0xaaf4c
- (void)layoutIconLists:(float)lists domino:(BOOL)domino forceRelayout:(BOOL)relayout;	// 0xaaca4
- (void)moveAnimation:(id)animation didFinish:(id)finish movePlan:(id)plan;	// 0xaab14
- (void)moveIcon:(id)icon fromIconList:(id)iconList toIndex:(int)index toIconList:(id)iconList4 animate:(BOOL)animate;	// 0xaa864
- (void)moveIcon:(id)icon fromIconList:(id)iconList toIndex:(int)index toIconList:(id)iconList4;	// 0xaa82c
- (BOOL)iconAllowJitter:(id)jitter;	// 0xaa788
- (BOOL)iconPositionIsEditable:(id)editable;	// 0xaa76c
- (void)iconHandleLongPress:(id)press;	// 0xaa5c4
- (void)icon:(id)icon touchEnded:(BOOL)ended;	// 0xaa5b0
- (void)iconTouchBegan:(id)began;	// 0xaa538
- (void)icon:(id)icon touchMovedWithEvent:(id)event;	// 0xaa4bc
- (BOOL)iconShouldAllowTap:(id)icon;	// 0xaa494
- (void)iconTapped:(id)tapped;	// 0xaa454
- (BOOL)icon:(id)icon canReceiveGrabbedIcon:(id)icon2;	// 0xaa42c
- (int)closeBoxTypeForIcon:(id)icon;	// 0xa9738
- (void)iconCloseBoxTapped:(id)tapped;	// 0xaa374
- (BOOL)iconShouldPrepareGhostlyImage:(id)icon;	// 0xaa2ec
- (BOOL)iconAllowsBadging:(id)badging;	// 0xaa294
- (BOOL)iconViewDisplaysBadges:(id)badges;	// 0xaa254
- (BOOL)_badgesAreDisabledForSectionInfo:(id)sectionInfo;	// 0xaa224
- (void)_updateDisabledBadgesSetWithSections:(id)sections replacePrevious:(BOOL)previous;	// 0xa9cfc
- (void)observer:(id)observer updateSectionInfo:(id)info;	// 0xa9cac
// declared property getter: - (id)searchController;	// 0xa9740
@end

@interface SBIconController (Folders)
@property(retain) id openFolder;	// G=0x109669; S=0x1099e1; converted property
@property(retain) id folderToReopenWhenSwitcherCloses;	// G=0x109655; S=0x109cb1; converted property
- (void)getListView:(id *)view folder:(id *)folder relativePath:(id *)path forIcon:(id)icon;	// 0x1097b9
- (void)getListView:(id *)view folder:(id *)folder relativePath:(id *)path forIndexPath:(id)indexPath createIfNecessary:(BOOL)necessary;	// 0x109861
- (id)iconListViewAtIndex:(unsigned)index inFolder:(id)folder createIfNecessary:(BOOL)necessary;	// 0x109909
// converted property setter: - (void)setOpenFolder:(id)folder;	// 0x1099e1
- (BOOL)hasOpenFolder;	// 0x109605
- (void)_setHasAnimatingFolder:(BOOL)folder;	// 0x109a55
- (void)_setFolderToOpenAfterScrolling:(id)openAfterScrolling;	// 0x109bf1
- (BOOL)hasAnimatingFolder;	// 0x109621
// converted property setter: - (void)setFolderToReopenWhenSwitcherCloses:(id)reopenWhenSwitcherCloses;	// 0x109cb1
- (void)saveFolderToReopenWhenSwitcherCloses;	// 0x109cf9
- (void)clearFolderToReopenWhenSwitcherCloses;	// 0x109d19
// converted property getter: - (id)folderToReopenWhenSwitcherCloses;	// 0x109655
// converted property getter: - (id)openFolder;	// 0x109669
- (BOOL)isNewsstandOpen;	// 0x109d2d
- (void)openFolder:(id)folder animated:(BOOL)animated;	// 0x109d7d
- (void)openFolder:(id)folder animated:(BOOL)animated fromSwitcher:(BOOL)switcher;	// 0x10afd9
- (void)closeFolderAnimated:(BOOL)animated;	// 0x109da1
- (void)closeFolderAnimated:(BOOL)animated toSwitcher:(BOOL)switcher;	// 0x10b7b1
- (id)createNewFolderFromRecipientIcon:(id)recipientIcon grabbedIcon:(id)icon;	// 0x109db5
- (void)dropIconIntoOpenFolder:(id)folder;	// 0x10e1f1
- (void)_moveDroppedIconsIntoFolderIconListView;	// 0x10bbdd
- (void)dropIconOutOfClosingFolder:(id)closingFolder insertionPosition:(int)position;	// 0x10cb59
- (void)_moveDroppedIconsIntoRootIconListView;	// 0x10bd99
- (void)dropIconOutOfClosingFolderAnimationDidStop:(id)dropIconOutOfClosingFolderAnimation finished:(id)finished context:(void *)context;	// 0x10a0c9
- (BOOL)isDroppingIconsInOrOutOfFolder;	// 0x10967d
- (void)animateIcon:(id)icon intoFolderIcon:(id)icon2;	// 0x10a115
- (void)animateIcons:(id)icons intoFolderIcon:(id)icon openFolderOnFinish:(BOOL)finish;	// 0x10e959
- (void)replaceFolderIcon:(id)icon byContainedIcon:(id)icon2 animated:(BOOL)animated;	// 0x10f1b5
- (void)_slideFolderOpen:(BOOL)open animated:(BOOL)animated;	// 0x10a15d
- (void)_openCloseFolderAnimationEnded:(id)ended finished:(id)finished context:(void *)context;	// 0x10a59d
- (void)_cleanupForClosingFolderAnimated:(BOOL)closingFolderAnimated;	// 0x10bff9
- (void)_compactRootListsAfterFolderCloseWithAnimation:(BOOL)animation;	// 0x10a84d
- (void)_addToFolderAnimation:(id)folderAnimation didFinish:(id)finish context:(id)context;	// 0x10c441
- (void)_outOfFolderAnimation:(id)folderAnimation didFinish:(id)finish context:(id)context;	// 0x10a8f9
- (void)_snapshotFadeDidStop:(id)_snapshotFade finished:(id)finished snapshot:(id)snapshot;	// 0x10aa0d
- (id)_proposedFolderNameForGrabbedIcon:(id)grabbedIcon recipientIcon:(id)icon;	// 0x10aa3d
- (void)prepareToRotateFolderAndSlidingViewsToOrientation:(int)orientation;	// 0x10ab99
- (void)rotateFolderAndSlidingViewsWithDuration:(double)duration;	// 0x10d0c5
- (void)_folderRotationIconFadeAnimationDidStop:(id)_folderRotationIconFadeAnimation finished:(id)finished context:(id)context;	// 0x10d625
- (void)cleanUpFolderAndSlidingViewsAfterRotation;	// 0x10ac01
- (void)_insertFolderViewAndSlidingViewsForFolder:(id)folder;	// 0x10d871
- (void)_positionFolderViewAndSlidingViewsForFolder:(id)folder notchInfo:(XXStruct_9ihRqB)info;	// 0x10f6dd
- (void)shiftFolderViewsForKeyboardAppearing:(BOOL)keyboardAppearing keyboardHeight:(float)height;	// 0x10fad1
- (void)dismissFolderKeyboard;	// 0x10ac65
- (void)_clearFolderViewAndSlidingViews;	// 0x10ac9d
- (void)prepareToGhostCurrentPageIconsForRequester:(int)requester skipIcon:(id)icon;	// 0x10c671
- (void)setCurrentPageIconsGhostly:(BOOL)ghostly forRequester:(int)requester skipIcon:(id)icon;	// 0x10c7fd
- (void)setCurrentPageIconsPartialGhostly:(float)ghostly forRequester:(int)requester skipIcon:(id)icon;	// 0x10c8f5
- (void)cleanUpGhostlyIconsForRequester:(int)requester;	// 0x10ca11
- (id)_iconsOnGhostedListForRequester:(int)requester;	// 0x10add9
- (id)_iconsOnGhostedListForRequester:(int)requester skippingIcon:(id)icon;	// 0x10aded
- (id)_ghostedIconListForRequester:(int)requester;	// 0x109699
- (CGRect)_contentViewRelativeFrameForIcon:(id)icon;	// 0x10deb9
- (XXStruct_9ihRqB)_notchInfoForFolderIcon:(id)folderIcon;	// 0x10fc2d
- (unsigned)_folderRowsForFolder:(id)folder inOrientation:(int)orientation;	// 0x10aed5
- (unsigned)_folderRowsForFolder:(id)folder;	// 0x10af81
- (void)_computeUpperTransform:(CGAffineTransform *)transform lowerTransform:(CGAffineTransform *)transform2 notchTransform:(CGAffineTransform *)transform3 forFolderIcon:(id)folderIcon;	// 0x10fee9
- (void)_placeIcon:(id)icon inSlidingViewsWithNotchInfo:(XXStruct_9ihRqB)notchInfo;	// 0x10f929
- (void)updateSlidingViewWithIcon:(id)icon fromListView:(id)listView;	// 0x10dfb1
- (void)_runFolderOpenCloseTest;	// 0x110289
@end
