/**
 * This header is generated by class-dump-z 0.2b.
 *
 * Source: (null)
 */

#import "SpringBoard-Structs.h"
#import "SBUnknownSuperclass.h"

@class SBIconLabelProperties;

@interface SBIconLabelImage : SBUnknownSuperclass {
	SBIconLabelProperties *_properties;	// 16 = 0x10
	int _referenceCount;	// 20 = 0x14
}
@property(readonly, retain, nonatomic) SBIconLabelProperties *properties;	// G=0x1a323d; @synthesize=_properties
@property(assign, nonatomic) int referenceCount;	// G=0x1a321d; S=0x1a322d; @synthesize=_referenceCount
- (id)initWithCGImage:(CGImageRef)cgimage scale:(float)scale orientation:(int)orientation properties:(id)properties;	// 0x1a3a21
- (void)dealloc;	// 0x1a3a95
// declared property getter: - (int)referenceCount;	// 0x1a321d
// declared property setter: - (void)setReferenceCount:(int)count;	// 0x1a322d
// declared property getter: - (id)properties;	// 0x1a323d
@end
