/**
 * This header is generated by class-dump-z 0.2b.
 *
 * Source: (null)
 */

#import "SpringBoard-Structs.h"
#import "SBUnknownSuperclass.h"

@class NSString;

@interface SBIconBadgeImage : SBUnknownSuperclass {
	NSString *_text;	// 16 = 0x10
	int _checkoutCount;	// 20 = 0x14
}
@property(readonly, copy) NSString *text;	// G=0xc2981; @synthesize=_text
@property(assign) int checkoutCount;	// G=0xc2901; S=0xc2911; @synthesize=_checkoutCount
- (id)initWithCGImage:(CGImageRef)cgimage scale:(float)scale orientation:(int)orientation text:(id)text;	// 0xc2921
- (void)dealloc;	// 0xc2999
// declared property getter: - (int)checkoutCount;	// 0xc2901
// declared property setter: - (void)setCheckoutCount:(int)count;	// 0xc2911
// declared property getter: - (id)text;	// 0xc2981
@end
