/**
 * This header is generated by class-dump-z 0.2b.
 *
 * Source: (null)
 */

#import "SpringBoard-Structs.h"
#import "SBUnknownSuperclass.h"

@class NSMutableSet, SBIcon, NSMutableArray, UIView, SBIconListModel;

@interface SBIconListView : SBUnknownSuperclass {
	SBIconListModel *_model;	// 48 = 0x30
	int _orientation;	// 52 = 0x34
	SBIcon *_bouncedIcon;	// 56 = 0x38
	NSMutableArray *_removedIcons;	// 60 = 0x3c
	NSMutableArray *_iconContainerMatrix;	// 64 = 0x40
	unsigned _scattered : 1;	// 68 = 0x44
	unsigned _needsLayout : 1;	// 68 = 0x44
	unsigned _rotating : 1;	// 68 = 0x44
	unsigned _onWallpaper : 1;	// 68 = 0x44
	UIView *_fadeView;	// 72 = 0x48
	BOOL _iconsAreElsewhere;	// 76 = 0x4c
	BOOL _recyclesIconViewsWhenNotShowing;	// 77 = 0x4d
	NSMutableSet *_notShownIconViews;	// 80 = 0x50
	NSMutableArray *_rasterizedIcons;	// 84 = 0x54
	BOOL _showingCloseBoxes;	// 88 = 0x58
}
@property(retain) SBIconListModel *model;	// G=0x7e279; S=0x8346d; converted property
@property(assign) BOOL iconsAreElsewhere;	// G=0x7e2c1; S=0x7e2b1; converted property
@property(assign) BOOL recyclesIconViewsWhenNotShowing;	// G=0x7e2d1; S=0x82179; converted property
@property(retain) SBIcon *bouncedIcon;	// G=0x7e34d; S=0x80fcd; converted property
@property(readonly, retain) NSMutableArray *removedIcons;	// G=0x7e911; converted property
+ (unsigned)iconRowsForInterfaceOrientation:(int)interfaceOrientation;	// 0x7fdd1
+ (unsigned)maxVisibleIconRowsInterfaceOrientation:(int)orientation;	// 0x7fe19
+ (unsigned)iconColumnsForInterfaceOrientation:(int)interfaceOrientation;	// 0x7fe29
+ (unsigned)maxIcons;	// 0x7fe71
- (Class)modelClass;	// 0x7e379
- (id)initWithFrame:(CGRect)frame;	// 0x7ff4d
- (void)dealloc;	// 0x835b9
// converted property setter: - (void)setModel:(id)model;	// 0x8346d
// converted property getter: - (id)model;	// 0x7e279
- (unsigned)iconRowsForCurrentOrientation;	// 0x7e395
- (unsigned)iconColumnsForCurrentOrientation;	// 0x7e3cd
- (unsigned)iconsInRowForSpacingCalculation;	// 0x7e405
- (void)setOrientation:(int)orientation;	// 0x7e289
- (void)setDisplaysOnWallpaper:(BOOL)wallpaper;	// 0x7e415
- (unsigned)indexForX:(unsigned)x Y:(unsigned)y forOrientation:(int)orientation;	// 0x7e455
- (void)getX:(unsigned *)x Y:(unsigned *)y forIndex:(unsigned)index forOrientation:(int)orientation;	// 0x7e4c1
- (unsigned)rowForIcon:(id)icon;	// 0x7e535
- (BOOL)compactIcons:(BOOL)icons;	// 0x832e5
- (id)icons;	// 0x7e589
- (id)visibleIcons;	// 0x7e609
- (BOOL)isEmpty;	// 0x7e619
- (BOOL)isFull;	// 0x7e63d
- (unsigned)firstFreeSlotIndex;	// 0x7e661
- (unsigned)firstFreeSlotIndexForType:(int)type;	// 0x7e675
- (unsigned)firstFreeSlotOrLastSlotIndex;	// 0x7e699
- (unsigned)firstFreeSlotOrLastSlotIndexForType:(int)type;	// 0x7e6ad
- (void)showIconAnimationDidStop:(id)showIconAnimation didFinish:(id)finish iconView:(id)view;	// 0x83231
- (void)_popIconView:(id)view;	// 0x83105
- (void)_noteNewIconInModel:(id)model;	// 0x7e299
- (id)placeIcon:(id)icon atIndex:(unsigned)index moveNow:(BOOL)now pop:(BOOL)pop;	// 0x82e91
- (id)insertIcon:(id)icon atIndex:(unsigned)index moveNow:(BOOL)now pop:(BOOL)pop;	// 0x7e701
- (id)insertIcon:(id)icon atIndex:(unsigned)index moveNow:(BOOL)now;	// 0x7e8ed
// converted property getter: - (id)removedIcons;	// 0x7e911
- (void)removeIconAtIndex:(unsigned)index;	// 0x7e95d
- (void)removeIcon:(id)icon;	// 0x7e9f5
- (BOOL)isScattered;	// 0x7e29d
- (void)setAlphaForAllIcons:(float)allIcons;	// 0x82d79
- (void)scatterAnimationDidStop;	// 0x7ea35
- (void)scatterWithDuration:(double)duration startTime:(double)time;	// 0x82a89
- (void)unscatterAnimationDidStop;	// 0x7ea89
- (void)unscatterWithDuration:(double)duration startTime:(double)time;	// 0x827b1
- (void)setShouldRasterizeAllIcons:(BOOL)rasterizeAllIcons;	// 0x82619
- (void)removeAllIconAnimations;	// 0x82521
- (CGSize)defaultIconSize;	// 0x824fd
- (CGPoint)originForIconAtIndex:(int)index;	// 0x824ad
- (CGPoint)originForIcon:(id)icon;	// 0x82441
- (void)setFrame:(CGRect)frame;	// 0x823a1
// converted property setter: - (void)setIconsAreElsewhere:(BOOL)elsewhere;	// 0x7e2b1
// converted property getter: - (BOOL)iconsAreElsewhere;	// 0x7e2c1
// converted property setter: - (void)setRecyclesIconViewsWhenNotShowing:(BOOL)showing;	// 0x82179
// converted property getter: - (BOOL)recyclesIconViewsWhenNotShowing;	// 0x7e2d1
- (void)setIconsNeedLayout;	// 0x7e2e1
- (void)layoutIconsNow;	// 0x7eac1
- (CATransform3D)_transformForIconAtIndex:(unsigned)index inOrientation:(int)orientation;	// 0x7e2f9
- (float)layoutIconsIfNeeded:(float)needed domino:(BOOL)domino;	// 0x81b19
- (id)iconAtPoint:(CGPoint)point index:(unsigned *)index;	// 0x7eaf1
- (id)iconAtPoint:(CGPoint)point index:(unsigned *)index proposedOrder:(int *)order grabbedIcon:(id)icon;	// 0x81955
- (void)showIconImagesFromColumn:(int)column toColumn:(int)column2 totalColumns:(int)columns visibleIconsJitter:(BOOL)jitter;	// 0x8165d
- (void)stopJittering;	// 0x81571
- (void)startJittering;	// 0x81485
- (void)showCloseBoxes;	// 0x81349
- (void)hideCloseBoxes;	// 0x8124d
- (void)makeIconsPerformSelector:(SEL)selector;	// 0x7ebb9
- (void)makeIconViewsPerformSelector:(SEL)selector;	// 0x7ec25
- (void)makeIconsPerformBlock:(id)block;	// 0x81155
- (void)makeIconViewsPerformBlock:(id)block;	// 0x8102d
- (BOOL)isDock;	// 0x7e349
// converted property setter: - (void)setBouncedIcon:(id)icon;	// 0x80fcd
// converted property getter: - (id)bouncedIcon;	// 0x7e34d
- (float)topIconInset;	// 0x7ec95
- (float)bottomIconInset;	// 0x7ed49
- (float)sideIconInset;	// 0x7edfd
- (float)horizontalBumpForColumn:(unsigned)column;	// 0x80e35
- (float)horizontalIconPadding;	// 0x80d99
- (float)verticalIconPadding;	// 0x80ce5
- (CGPoint)originForIconAtX:(unsigned)x Y:(unsigned)y;	// 0x80be9
- (unsigned)columnAtPoint:(CGPoint)point;	// 0x80b19
- (unsigned)rowAtPoint:(CGPoint)point;	// 0x80a75
- (unsigned)_preRotationFirstVisibleRow;	// 0x7e35d
- (unsigned)_postRotationFirstVisibleRow;	// 0x7e361
- (unsigned)_rotationReferenceRow;	// 0x7e365
- (id)rotationIconContainers;	// 0x80859
- (Class)iconRotationContainerClass;	// 0x7ee69
- (void)prepareToRotateToInterfaceOrientation:(int)interfaceOrientation;	// 0x8047d
- (void)performRotationWithDuration:(double)duration;	// 0x8028d
- (void)cleanupAfterRotation;	// 0x80029
@end
