/**
 * This header is generated by class-dump-z 0.2b.
 *
 * Source: (null)
 */

#import "SBUnknownSuperclass.h"

@class NSMutableSet, NSMutableDictionary, SBRootFolder, SBNewsstandIcon, NSSet, NSDictionary;

@interface SBIconModel : SBUnknownSuperclass {
	NSDictionary *_lastKnownUserGeneratedIconState;	// 4 = 0x4
	NSSet *_lastKnownUserGeneratedIconStateFlattened;	// 8 = 0x8
	NSMutableDictionary *_leafIconsByIdentifier;	// 12 = 0xc
	NSSet *_hiddenIconTags;	// 16 = 0x10
	NSSet *_visibleIconTags;	// 20 = 0x14
	BOOL _tagsHaveBeenSet;	// 24 = 0x18
	NSMutableSet *_downloadedIconIDs;	// 28 = 0x1c
	SBRootFolder *_rootFolder;	// 32 = 0x20
	SBNewsstandIcon *_newsstandIcon;	// 36 = 0x24
	BOOL _needsRelayout;	// 40 = 0x28
	BOOL _allowReadingCachedStateFromDisk;	// 41 = 0x29
}
@property(readonly, retain) NSMutableSet *downloadedIconIDs;	// G=0xb7d99; converted property
@property(readonly, retain) SBRootFolder *rootFolder;	// G=0xb7d61; converted property
@property(readonly, retain) SBNewsstandIcon *newsstandIcon;	// G=0xb7d71; converted property
+ (id)sharedInstance;	// 0xb856d
+ (id)_migrateLeafIdentifierIfNecessary:(id)necessary;	// 0xb8425
+ (id)_modernIconCellForCell:(id)cell;	// 0xb82b5
+ (id)_modernIconListForList:(id)list;	// 0xb805d
+ (id)_modernIconListsForLists:(id)lists;	// 0xb7f39
+ (id)modernIconStateForState:(id)state;	// 0xb7e7d
- (id)init;	// 0xb7da9
- (void)dealloc;	// 0xbdbf1
// converted property getter: - (id)rootFolder;	// 0xb7d61
// converted property getter: - (id)newsstandIcon;	// 0xb7d71
- (id)newsstandFolder;	// 0xbdbd1
- (void)localeChanged;	// 0xbdb19
- (void)setVisibilityOfIconsWithVisibleTags:(id)visibleTags hiddenTags:(id)tags;	// 0xbd5e5
- (BOOL)isIconVisible:(id)visible;	// 0xbd3c1
- (id)addDownloadingIconForDownload:(id)download;	// 0xbd321
- (id)addDownloadingIconForIdentifier:(id)identifier;	// 0xbd28d
- (void)removeApplicationIconForDownloadingIcon:(id)downloadingIcon;	// 0xbd259
- (id)downloadingIconForIdentifier:(id)identifier;	// 0xbd169
- (id)addBookmarkIconForWebClip:(id)webClip;	// 0xbd0ed
- (void)addIconForApplication:(id)application;	// 0xbd05d
- (void)addNewsstandIcon;	// 0xbcfd5
- (void)loadAllIcons;	// 0xbcbd9
- (id)visibleIconIdentifiers;	// 0xbcac1
- (id)leafIcons;	// 0xbca75
- (id)_applicationIcons;	// 0xbc981
- (id)leafIconForIdentifier:(id)identifier;	// 0xbc951
- (id)applicationIconForDisplayIdentifier:(id)displayIdentifier;	// 0xbc91d
- (id)iconState;	// 0xbc8bd
- (id)iconStatePath;	// 0xbc8a1
- (id)_cachedIconStatePath;	// 0xbc885
- (id)_iconState:(BOOL)state;	// 0xbc609
- (void)noteIconStateChangedExternally;	// 0xbc57d
- (id)firstPageLeafIdentifiers;	// 0xbc4c5
- (void)_createIconLists;	// 0xbbfe5
- (void)uninstallBookmarkIcon:(id)icon;	// 0xbbf91
- (void)addIcon:(id)icon;	// 0xbbf35
- (void)removeIcon:(id)icon;	// 0xbbee9
- (void)removeIconForIdentifier:(id)identifier;	// 0xbbe19
- (id)indexPathForIconInPlatformState:(id)platformState;	// 0xbbd19
- (id)_indexPathForIdentifier:(id)identifier inListRepresentation:(id)listRepresentation;	// 0xbbbc5
- (id)_indexPathForIdentifier:(id)identifier inListsRepresentation:(id)listsRepresentation;	// 0xbbb45
- (BOOL)hasCachedUserGeneratedIconState;	// 0xb7d81
- (void)clearCachedUserGeneratedIconState;	// 0xbba41
- (void)clearCachedUserGeneratedIconStateIfPossible;	// 0xbb8fd
- (id)_indexPathForFirstFreeNewsstandSlot;	// 0xbb801
- (id)indexPathForNewIcon:(id)newIcon isDesignatedLocation:(BOOL *)location replaceExistingIconAtIndexPath:(id *)indexPath;	// 0xbb531
- (void)_addNewIconToDesignatedLocation:(id)designatedLocation;	// 0xbb4b9
- (void)deleteIconState;	// 0xbb455
- (BOOL)_writeIconState:(id)state toPath:(id)path;	// 0xbb431
- (BOOL)_writeIconState:(id)state toPath:(id)path withFormat:(unsigned)format;	// 0xbb361
- (void)_writeCurrentIconStateWithNotification:(BOOL)notification;	// 0xbb1c5
- (void)_writeCachedIconState;	// 0xbb141
- (void)saveIconState;	// 0xbb0fd
- (void)_replaceAppIconsWithDownloadingIcons;	// 0xbaf75
- (void)_replaceAppIconsWithDownloadingIcons:(id)downloadingIcons;	// 0xbac6d
- (void)_flattenIconListState:(id)state intoArray:(id)array;	// 0xbaac9
- (id)newsstandFolderFromIconState:(id)iconState;	// 0xba831
- (id)_newsstandIconIdentifiersFromIconState:(id)iconState;	// 0xba77d
- (id)_flattenIconState:(id)state;	// 0xba6e5
- (void)noteFolderStoppedAnimating;	// 0xba6a9
- (void)noteDownloadsEnded;	// 0xba67d
- (void)noteDownloadCompletedForIconID:(id)iconID;	// 0xba5a1
- (void)removeDownloadedIconID:(id)anId;	// 0xba571
// converted property getter: - (id)downloadedIconIDs;	// 0xb7d99
- (void)relayout;	// 0xba341
- (void)uninstallApplicationIcon:(id)icon;	// 0xba2cd
- (id)forecastedLayoutForIconState:(id)iconState;	// 0xb9965
- (void)_addNodeToRootLists:(id)rootLists node:(id)node createListIfNecessary:(BOOL)necessary;	// 0xb9829
- (id)_trimList:(id)list toMaxSize:(int)maxSize;	// 0xb97b9
- (id)_deepCopyIconState:(id)state;	// 0xb94a5
- (id)_deepCopyListForIconState:(id)iconState;	// 0xb9299
- (id)exportState:(BOOL)state;	// 0xb9175
- (id)exportPendingState:(BOOL)state;	// 0xb9041
- (id)exportFlattenedState:(BOOL)state;	// 0xb8f95
- (id)_iTunesIconListsForLists:(id)lists preApex:(BOOL)apex forPending:(BOOL)pending;	// 0xb8eb9
- (id)_iTunesIconListForList:(id)list preApex:(BOOL)apex forPending:(BOOL)pending;	// 0xb8c51
- (id)_iTunesIconCellForCell:(id)cell preApex:(BOOL)apex forPending:(BOOL)pending;	// 0xb8abd
- (id)_iTunesDictionaryForLeafIdentifier:(id)leafIdentifier;	// 0xb8a55
- (id)_iTunesDictionaryForLeafIcon:(id)leafIcon;	// 0xb87f9
- (id)_iTunesDictionaryForDownloadingIcon:(id)downloadingIcon;	// 0xb8765
- (BOOL)importState:(id)state;	// 0xb85c5
@end
