/**
 * This header is generated by class-dump-z 0.2b.
 *
 * Source: (null)
 */

#import "SBUnknownSuperclass.h"
#import "SpringBoard-Structs.h"

@class NSString, SBIconLabelImage;

@interface SBIconLabel : SBUnknownSuperclass {
	SBIconLabelImage *_labelImage;	// 72 = 0x48
	NSString *_label;	// 76 = 0x4c
	unsigned _drawMoreLegibly : 1;	// 80 = 0x50
	unsigned _inDock : 1;	// 80 = 0x50
	unsigned _ellipsizesText : 1;	// 80 = 0x50
	unsigned _onWallpaper : 1;	// 80 = 0x50
}
- (id)initWithSize:(CGSize)size text:(id)text inDock:(BOOL)dock onWallpaper:(BOOL)wallpaper ellipsizes:(BOOL)ellipsizes;	// 0x124a71
- (void)dealloc;	// 0x125a15
- (id)description;	// 0x1259a9
- (void)setText:(id)text;	// 0x1257a9
- (void)setInDock:(BOOL)dock;	// 0x125769
- (void)setDisplaysOnWallpaper:(BOOL)wallpaper;	// 0x125729
- (void)setEllipsizesText:(BOOL)text;	// 0x1256e9
- (void)setBounds:(CGRect)bounds;	// 0x125641
- (void)setFrame:(CGRect)frame;	// 0x125599
- (id)_textFont;	// 0x1254f9
- (float)heightOfCurrentString;	// 0x12547d
- (id)_textColor;	// 0x1253d1
- (id)_textShadowColor;	// 0x125339
- (CGSize)_textShadowOffset;	// 0x1252dd
- (void)_updateImage;	// 0x124f39
- (CGImageRef)buildLabelImage;	// 0x124b55
@end
