/**
 * This header is generated by class-dump-z 0.2b.
 *
 * Source: (null)
 */

#import "SBUnknownSuperclass.h"

@class NSMutableArray, SBFolder;

@interface SBIconListModel : SBUnknownSuperclass {
	NSMutableArray *_icons;	// 4 = 0x4
	BOOL _iconStateIsDirty;	// 8 = 0x8
	SBFolder *_folder;	// 12 = 0xc
}
@property(readonly, retain) NSMutableArray *icons;	// G=0x101499; converted property
@property(readonly, retain) SBFolder *folder;	// G=0x101489; converted property
+ (Class)viewClass;	// 0x1015ad
+ (unsigned)maxIcons;	// 0x101585
- (id)initWithFolder:(id)folder;	// 0x101511
- (void)dealloc;	// 0x102ef9
// converted property getter: - (id)folder;	// 0x101489
// converted property getter: - (id)icons;	// 0x101499
- (id)iconAtIndex:(unsigned)index;	// 0x102e89
- (unsigned)indexForIcon:(id)icon;	// 0x102dcd
- (unsigned)indexForLeafIconWithIdentifier:(id)identifier;	// 0x102ccd
- (BOOL)containsIcon:(id)icon;	// 0x102ca9
- (BOOL)containsLeafIconWithIdentifier:(id)identifier;	// 0x102c85
- (BOOL)allowsAddingIcon:(id)icon;	// 0x102c61
- (void)notifyAdded:(id)added;	// 0x102bd9
- (BOOL)addIcon:(id)icon;	// 0x102bc1
- (BOOL)addIcon:(id)icon asDirty:(BOOL)dirty;	// 0x102ab1
- (id)placeIcon:(id)icon atIndex:(unsigned *)index;	// 0x102a8d
- (id)placeIcon:(id)icon atIndex:(unsigned *)index notify:(BOOL)notify;	// 0x102921
- (id)insertIcon:(id)icon atIndex:(unsigned *)index;	// 0x1027a5
- (void)removeIconAtIndex:(unsigned)index;	// 0x1026cd
- (void)removeIcon:(id)icon;	// 0x10269d
- (unsigned)firstFreeSlotIndex;	// 0x102689
- (unsigned)firstFreeSlotIndexForType:(int)type;	// 0x10256d
- (BOOL)isEmpty;	// 0x1024b9
- (BOOL)isFull;	// 0x102495
- (BOOL)needsCompacting;	// 0x1023bd
- (void)compactIcons;	// 0x102305
- (id)iconsOfClass:(Class)aClass;	// 0x102175
- (id)indexPathForEntity:(id)entity;	// 0x102085
- (id)indexPathForFirstFreeSlot;	// 0x102041
- (BOOL)isIconStateDirty;	// 0x101f3d
- (void)markIconStateClean;	// 0x101e55
- (BOOL)resetWithRepresentation:(id)representation leafIdentifiersAdded:(id)added;	// 0x1018dd
- (id)representation;	// 0x1017bd
- (BOOL)matchesRepresentation:(id)representation;	// 0x101651
- (id)description;	// 0x1015c9
@end
