/**
 * This header is generated by class-dump-z 0.2b.
 *
 * Source: (null)
 */

#import "SBUnknownSuperclass.h"

@class SBDisplay, NSString;

@interface SBLaunchAlertItem : SBUnknownSuperclass {
	SBDisplay *_associatedDisplay;	// 16 = 0x10
	int _type;	// 20 = 0x14
	NSString *_bundleID;	// 24 = 0x18
	BOOL _isDataAlert;	// 28 = 0x1c
	BOOL _usesCellNetwork;	// 29 = 0x1d
}
- (id)initWithLaunchAlertType:(int)launchAlertType dataAlert:(BOOL)alert usesCellNetwork:(BOOL)network bundleID:(id)anId;	// 0x9c4a9
- (void)dealloc;	// 0x9cb8d
- (void)setAssociatedWithDisplay:(id)display;	// 0x9ca91
- (void)_displayDeactivated:(id)deactivated;	// 0x9ca61
- (BOOL)dismissOnLock;	// 0x9c4a5
- (id)_customAirplaneModeAlertPrompt;	// 0x9c9bd
- (id)alertSheet;	// 0x9c5e9
- (void)alertView:(id)view clickedButtonAtIndex:(int)index;	// 0x9c531
@end
