/**
 * This header is generated by class-dump-z 0.2b.
 *
 * Source: (null)
 */

#import "SBIcon.h"


@interface SBLeafIcon : SBIcon {
}
- (id)representation;	// 0x1003d9
- (BOOL)matchesRepresentation:(id)representation;	// 0x100401
- (id)description;	// 0x100525
- (BOOL)isEqual:(id)equal;	// 0x10046d
- (unsigned)hash;	// 0x1004fd
@end

