/**
 * This header is generated by class-dump-z 0.2b.
 *
 * Source: (null)
 */

#import "SBUnknownSuperclass.h"
#import "SpringBoard-Structs.h"

@class NSMutableArray;

@interface SBLinenView : SBUnknownSuperclass {
	int _type;	// 48 = 0x30
	NSMutableArray *_strips;	// 52 = 0x34
}
@property(assign, nonatomic) int type;	// G=0x12abbd; S=0x12b5d1; @synthesize=_type
+ (void)setupCache;	// 0x12b589
+ (void)removeCacheFiles;	// 0x12b4b5
+ (id)_folderSwitcherLinenPath;	// 0x12b475
+ (id)_allFolderSwitcherLinenPaths:(BOOL)paths;	// 0x12b3a1
+ (CGRect)_scaledRectForIndex:(unsigned)index ofImage:(id)image;	// 0x12b231
+ (void)_generateLinenStripsIfNeeded;	// 0x12b021
+ (float)naturalWidth;	// 0x12afd9
+ (id)squareImageForBounds:(CGRect)bounds;	// 0x12adc5
+ (id)_imageForIndex:(unsigned)index;	// 0x12ad5d
+ (id)_imageViewForIndex:(unsigned)index;	// 0x12aced
+ (float)_vOffsetOfTopForType:(int)type;	// 0x12ac21
- (id)initWithFrame:(CGRect)frame;	// 0x12abcd
- (void)dealloc;	// 0x12b9b9
- (void)setFrame:(CGRect)frame;	// 0x12b8d1
- (void)_layoutForBounds:(CGRect)bounds;	// 0x12b63d
- (void)layoutSubviews;	// 0x12b5f1
// declared property setter: - (void)setType:(int)type;	// 0x12b5d1
- (float)_vOffsetOfTop;	// 0x12b599
// declared property getter: - (int)type;	// 0x12abbd
@end
