/**
 * This header is generated by class-dump-z 0.2b.
 *
 * Source: (null)
 */

#import "SBUnknownSuperclass.h"


@interface SBLockScreenAudioRoutesAlertItem : SBUnknownSuperclass {
}
- (Class)alertSheetClass;	// 0xed781
- (id)alertSheet;	// 0xed79d
- (BOOL)allowMenuButtonDismissal;	// 0xed771
- (void)willRelockForButtonPress:(BOOL)buttonPress;	// 0xed825
- (BOOL)shouldShowInLockScreen;	// 0xed775
- (BOOL)togglesMediaControls;	// 0xed779
- (BOOL)allowAutoUnlock;	// 0xed77d
- (void)performUnlockAction;	// 0xed845
- (void)audioRoutingPicker:(id)picker didSelectRouteAtIndex:(int)index;	// 0xed855
@end
