/**
 * This header is generated by class-dump-z 0.2b.
 *
 * Source: (null)
 */

#import "SBUnknownSuperclass.h"


@interface SBLowPowerAlertItem : SBUnknownSuperclass {
	unsigned _talkLevel;	// 16 = 0x10
}
+ (id)systemVersionDescription;	// 0x9b9c9
+ (void)saveLowBatteryLogWithCapacity:(int)capacity voltage:(int)voltage;	// 0x9b339
+ (void)initialize;	// 0x9b2cd
+ (unsigned)_thresholdForLevel:(unsigned)level;	// 0x9af65
+ (BOOL)_shouldIgnoreChangeToBatteryLevel:(unsigned)batteryLevel;	// 0x9b229
+ (void)setBatteryLevel:(unsigned)level;	// 0x9afe5
- (id)init;	// 0x9af9d
- (id)initWithLevel:(unsigned)level;	// 0x9bdfd
- (void)willPresentAlertView:(id)view;	// 0x9bded
- (void)configure:(BOOL)configure requirePasscodeForActions:(BOOL)actions;	// 0x9bab9
- (void)alertView:(id)view clickedButtonAtIndex:(int)index;	// 0x9ba9d
- (BOOL)shouldShowInLockScreen;	// 0x9af91
- (BOOL)shouldShowInEmergencyCall;	// 0x9af95
- (BOOL)undimsScreen;	// 0x9af99
@end
