/**
 * This header is generated by class-dump-z 0.2b.
 *
 * Source: (null)
 */

#import "SpringBoard-Structs.h"
#import "SBUnknownSuperclass.h"

@class NSTimer, NSDictionary;

@interface SBMediaController : SBUnknownSuperclass {
	int _manualVolumeChangeCount;	// 4 = 0x4
	NSDictionary *_nowPlayingInfo;	// 8 = 0x8
	float _pendingVolumeChange;	// 12 = 0xc
	NSTimer *_volumeCommitTimer;	// 16 = 0x10
	BOOL _debounceVolumeRepeat;	// 20 = 0x14
	int _numberOfVolumeDecreasesSinceDownButtonDown;	// 24 = 0x18
	int _lastNowPlayingAppPID;	// 28 = 0x1c
	BOOL _lastNowPlayingAppIsPlaying;	// 32 = 0x20
	BOOL _suppressHUD;	// 33 = 0x21
	BOOL _ringerMuted;	// 34 = 0x22
}
@property(assign) BOOL suppressHUD;	// G=0xc0681; S=0xc15d5; 
@property(assign, nonatomic, getter=isRingerMuted) BOOL ringerMuted;	// G=0xc0691; S=0xc1225; 
@property(assign) float volume;	// G=0xc1441; S=0xc13bd; converted property
+ (id)sharedInstance;	// 0xc076d
+ (BOOL)applicationCanBeConsideredNowPlaying:(id)playing;	// 0xc071d
- (id)init;	// 0xc06c5
- (void)dealloc;	// 0xc1a91
- (id)_nowPlayingInfo;	// 0xc1a31
- (void)setNowPlayingInfo:(id)info;	// 0xc18fd
- (BOOL)hasTrack;	// 0xc18dd
- (BOOL)isFirstTrack;	// 0xc1879
- (BOOL)isLastTrack;	// 0xc1815
- (BOOL)isPlaying;	// 0xc066d
- (BOOL)isMovie;	// 0xc17d5
- (BOOL)isTVOut;	// 0xc067d
- (id)nowPlayingArtist;	// 0xc17a1
- (id)nowPlayingTitle;	// 0xc176d
- (id)nowPlayingAlbum;	// 0xc1739
- (id)nowPlayingApplication;	// 0xc1671
- (id)mediaControlsDestinationApp;	// 0xc1651
// declared property getter: - (BOOL)suppressHUD;	// 0xc0681
// declared property setter: - (void)setSuppressHUD:(BOOL)hud;	// 0xc15d5
- (BOOL)changeTrack:(int)track;	// 0xc157d
- (BOOL)beginSeek:(int)seek;	// 0xc152d
- (BOOL)endSeek:(int)seek;	// 0xc14dd
- (BOOL)togglePlayPause;	// 0xc14b5
// converted property getter: - (float)volume;	// 0xc1441
// converted property setter: - (void)setVolume:(float)volume;	// 0xc13bd
- (BOOL)muted;	// 0xc136d
// declared property setter: - (void)setRingerMuted:(BOOL)muted;	// 0xc1225
// declared property getter: - (BOOL)isRingerMuted;	// 0xc0691
- (BOOL)lastSavedRingerMutedState;	// 0xc11e9
- (void)_changeVolumeBy:(float)by;	// 0xc1199
- (float)_calcButtonRepeatDelay;	// 0xc06a1
- (void)increaseVolume;	// 0xc10d9
- (void)decreaseVolume;	// 0xc0fad
- (void)cancelVolumeEvent;	// 0xc0f4d
- (void)handleVolumeEvent:(GSEventRef)event;	// 0xc0e15
- (void)_registerForNotifications;	// 0xc0c9d
- (void)_unregisterForNotifications;	// 0xc0c55
- (void)_serverConnectionDied:(id)died;	// 0xc0c29
- (void)_systemVolumeChanged:(id)changed;	// 0xc0ad1
- (void)_softMuteChanged:(id)changed;	// 0xc0a29
- (void)_systemMuteChanged:(id)changed;	// 0xc0985
- (void)_nowPlayingInfoChanged;	// 0xc0969
- (void)_nowPlayingPIDChanged;	// 0xc0911
- (void)_nowPlayingAppIsPlayingDidChange;	// 0xc08b9
- (void)_cancelPendingVolumeChange;	// 0xc0869
- (void)_commitVolumeChange:(id)change;	// 0xc07f1
- (void)_delayedExtendSleepTimer;	// 0xc07b5
@end
