/**
 * This header is generated by class-dump-z 0.2b.
 *
 * Source: (null)
 */

#import "SBUnknownSuperclass.h"


@interface SBModelessSyncStubs : SBUnknownSuperclass {
}
+ (id)iconState;	// 0x15d7b9
@end
