/**
 * This header is generated by class-dump-z 0.2b.
 *
 * Source: (null)
 */

#import "SpringBoard-Structs.h"
#import "SBAlert.h"


@interface SBMobilityManagementAlert : SBAlert {
}
+ (void)registerForAlerts;	// 0x8df75
+ (void)test;	// 0x8e2b9
@end

