/**
 * This header is generated by class-dump-z 0.2b.
 *
 * Source: (null)
 */

#import "SBUnknownSuperclass.h"

@class ATConnection;

@interface SBModelessSyncController : SBUnknownSuperclass {
	BOOL _isAppSyncing;	// 4 = 0x4
	BOOL _isSyncing;	// 5 = 0x5
	int _syncRegistrationToken;	// 8 = 0x8
	int _iCloudRestoreToken;	// 12 = 0xc
	BOOL _restoringFromICloud;	// 16 = 0x10
	BOOL _isAutoSyncing;	// 17 = 0x11
	BOOL _isWirelessSyncing;	// 18 = 0x12
	ATConnection *_airTrafficConnection;	// 20 = 0x14
}
@property(readonly, assign, nonatomic) BOOL isAppSyncing;	// G=0x15d059; @synthesize=_isAppSyncing
@property(readonly, assign, nonatomic) BOOL isSyncing;	// G=0x15d049; @synthesize=_isSyncing
@property(readonly, assign, nonatomic) BOOL isAutoSyncing;	// G=0x15cff1; @synthesize=_isAutoSyncing
@property(readonly, assign, nonatomic) BOOL isWirelessSyncing;	// G=0x15d015; @synthesize=_isWirelessSyncing
@property(readonly, assign, nonatomic) BOOL isRestoringFromICloud;	// G=0x15d039; 
+ (id)sharedInstance;	// 0x15d0b1
- (id)init;	// 0x15d069
- (void)dealloc;	// 0x15d6e9
- (void)setIsSyncing:(BOOL)syncing;	// 0x15d671
// declared property getter: - (BOOL)isAutoSyncing;	// 0x15cff1
// declared property getter: - (BOOL)isWirelessSyncing;	// 0x15d015
- (void)connection:(id)connection updatedProgress:(id)progress;	// 0x15d5c5
- (void)connectionWasInterrupted:(id)interrupted;	// 0x15d5b1
- (void)beginMonitoring;	// 0x15d4b5
- (void)endMonitoring;	// 0x15d449
- (void)gotLowBatteryWarning;	// 0x15d429
- (void)_appSyncStateChanged;	// 0x15d3d5
- (void)_setAppSyncState:(BOOL)state;	// 0x15d349
- (void)_updateIconsForStateChange;	// 0x15d259
// declared property getter: - (BOOL)isRestoringFromICloud;	// 0x15d039
- (void)_iCloudStatusChanged;	// 0x15d195
- (void)_beginObservingICloudRestoreStatus;	// 0x15d101
- (void)_endObservingICloudRestoreStatus;	// 0x15d0dd
// declared property getter: - (BOOL)isSyncing;	// 0x15d049
// declared property getter: - (BOOL)isAppSyncing;	// 0x15d059
@end
