/**
 * This header is generated by class-dump-z 0.2b.
 *
 * Source: (null)
 */

#import "SBIconLabelProperties.h"
#import "SpringBoard-Structs.h"

@class NSString;

@interface SBMutableIconLabelProperties : SBIconLabelProperties {
}
@property(retain, nonatomic) NSString *text;	// @dynamic
@property(assign, nonatomic) Class labelClass;	// @dynamic
@property(assign, nonatomic) BOOL ellipsize;	// @dynamic
@property(assign, nonatomic) BOOL appearsInDock;	// @dynamic
@property(assign, nonatomic) BOOL appearsOnWallpaper;	// @dynamic
@property(assign, nonatomic) CGSize size;	// @dynamic
@end

