/**
 * This header is generated by class-dump-z 0.2b.
 *
 * Source: (null)
 */

#import "SpringBoard-Structs.h"
#import "SBUnknownSuperclass.h"

@class NSTimer, UIImageView;

@interface SBNewsstandCardView : SBUnknownSuperclass {
	BOOL _skewed;	// 46 = 0x2e
	BOOL _highlighted;	// 47 = 0x2f
	BOOL _touchOnCard;	// 48 = 0x30
	UIImageView *_cardView;	// 52 = 0x34
	UIImageView *_textView;	// 56 = 0x38
	UIImageView *_overlayView;	// 60 = 0x3c
	NSTimer *_delayedUnhighlightTimer;	// 64 = 0x40
}
+ (id)_cachedImagePathForName:(id)name scale:(float)scale;	// 0x1829c1
+ (id)_cachedCardImagePath;	// 0x182991
+ (id)_cachedTextImagePath;	// 0x182961
+ (id)_cachedImageAtPath:(id)path;	// 0x182911
+ (id)_cachedCardImage;	// 0x1828e1
+ (id)_cachedTextImage;	// 0x1828b1
+ (void)_generatedCachedImages;	// 0x182139
+ (void)setupCache;	// 0x18210d
- (id)init;	// 0x1831cd
- (void)dealloc;	// 0x182085
- (CATransform3D)skewTransform;	// 0x181ff9
- (void)setSkewed:(BOOL)skewed;	// 0x183071
- (float)shadowPadding;	// 0x18303d
- (id)overlayImage;	// 0x182f49
- (void)_delayedUnhighlight;	// 0x182f35
- (void)setHighlighted:(BOOL)highlighted delayUnhighlight:(BOOL)unhighlight;	// 0x182bc9
- (void)touchesBegan:(id)began withEvent:(id)event;	// 0x182b75
- (void)touchesMoved:(id)moved withEvent:(id)event;	// 0x182af5
- (void)touchesEnded:(id)ended withEvent:(id)event;	// 0x182a61
- (void)touchesCancelled:(id)cancelled withEvent:(id)event;	// 0x182a4d
@end
