/**
 * This header is generated by class-dump-z 0.2b.
 *
 * Source: (null)
 */

#import "SBUnknownSuperclass.h"

@class UIImage;

@interface SBNewsstandTilingImageView : SBUnknownSuperclass {
	UIImage *_tileImage;	// 48 = 0x30
}
@property(retain, nonatomic) UIImage *_tileImage;	// G=0x145e95; S=0x147799; @synthesize
@property(retain, nonatomic) UIImage *image;	// G=0x145f4d; S=0x145f5d; 
- (id)initWithImage:(id)image;	// 0x145ec1
- (void)dealloc;	// 0x147759
// declared property getter: - (id)image;	// 0x145f4d
// declared property setter: - (void)setImage:(id)image;	// 0x145f5d
// declared property getter: - (id)_tileImage;	// 0x145e95
// declared property setter: - (void)set_tileImage:(id)image;	// 0x147799
@end
