/**
 * This header is generated by class-dump-z 0.2b.
 *
 * Source: (null)
 */

#import "SBIconLabel.h"
#import "SpringBoard-Structs.h"


@interface SBNewsstandIconLabel : SBIconLabel {
}
- (id)_textColor;	// 0x125aa5
- (id)_textShadowColor;	// 0x125aed
- (CGSize)_textShadowOffset;	// 0x124a65
- (id)_textFont;	// 0x125b21
@end

