/**
 * This header is generated by class-dump-z 0.2b.
 *
 * Source: (null)
 */

#import "SBUnknownSuperclass.h"


@interface SBNewsstand : SBUnknownSuperclass {
}
+ (void)initialize;	// 0x166c5d
+ (void)_buildCacheDirectory;	// 0x166d71
+ (id)cachePath;	// 0x1670ed
+ (void)setupCache;	// 0x166dcd
+ (void)removeCacheFiles;	// 0x166e15
+ (void)removeLocalizedCacheFiles;	// 0x16714d
+ (void)openNewsstandAppStore;	// 0x16728d
+ (void)_loadDefaults;	// 0x166e69
+ (void)_updateStoreAvailability;	// 0x166f21
+ (void)_checkStoreSupport;	// 0x166fdd
+ (void)noteCapabilitiesDidChange;	// 0x1670b9
+ (void)reloadDefaults;	// 0x167345
+ (void)_availableStoreItemKindsDidChange:(id)_availableStoreItemKinds;	// 0x1672ed
+ (void)_iconVisibilityDidChange:(id)_iconVisibility;	// 0x1670dd
+ (BOOL)newsstandEnabled;	// 0x166b71
+ (BOOL)newsstandStoreIsAvailable;	// 0x166b75
+ (BOOL)_newsstandStoreIsRestricted;	// 0x166b85
+ (BOOL)_newsstandStoreIsSupported;	// 0x166b95
+ (BOOL)disableIconSkew;	// 0x166ba5
+ (BOOL)alwaysShowIconLabels;	// 0x166bb5
+ (BOOL)addManyIcons;	// 0x166bc5
+ (id)bundleIDToReplicate;	// 0x166bf1
+ (BOOL)debugRotation;	// 0x166c01
+ (BOOL)addFakeApps;	// 0x166c11
@end
