/**
 * This header is generated by class-dump-z 0.2b.
 *
 * Source: (null)
 */

#import "SBUnknownSuperclass.h"

@class UIImageView, UILabel;

@interface SBNewsstandShelfView : SBUnknownSuperclass {
	UIImageView *_body;	// 244 = 0xf4
	UIImageView *_leftEdge;	// 248 = 0xf8
	UIImageView *_rightEdge;	// 252 = 0xfc
	UIImageView *_shadowLeft;	// 256 = 0x100
	UIImageView *_shadowMiddle;	// 260 = 0x104
	UIImageView *_shadowRight;	// 264 = 0x108
	int _orientation;	// 268 = 0x10c
	unsigned _shelfIndex;	// 272 = 0x110
	UILabel *_label;	// 276 = 0x114
}
@property(readonly, assign) unsigned shelfIndex;	// G=0x145eb1; converted property
+ (float)shelfHeight;	// 0x146a4d
+ (float)shelfEdgeHeight;	// 0x146a95
+ (float)shelfItemBaselineOffset;	// 0x146add
+ (id)reuseIdentifier;	// 0x145ea5
+ (id)shelf;	// 0x146b05
- (id)initWithStyle:(int)style reuseIdentifier:(id)identifier;	// 0x1474c9
- (void)dealloc;	// 0x1473cd
// converted property getter: - (unsigned)shelfIndex;	// 0x145eb1
- (void)configureForOrientation:(int)orientation shelfIndex:(unsigned)index;	// 0x146b69
@end
