/**
 * This header is generated by class-dump-z 0.2b.
 *
 * Source: (null)
 */

#import "SBUnknownSuperclass.h"
#import "SpringBoard-Structs.h"

@class SBNewsstandShelfHeaderView, SBNewsstandTilingImageView;

@interface SBNewsstandShelfFrameView : SBUnknownSuperclass {
	CGSize _borderSize;	// 48 = 0x30
	SBNewsstandShelfHeaderView *_headerView;	// 56 = 0x38
	SBNewsstandTilingImageView *_leftBorder;	// 60 = 0x3c
	SBNewsstandTilingImageView *_rightBorder;	// 64 = 0x40
	int _orientation;	// 68 = 0x44
}
+ (void)setupCache;	// 0x1463b1
- (id)initWithFrame:(CGRect)frame;	// 0x1477c1
- (void)dealloc;	// 0x147bf9
- (void)showHeaderView;	// 0x147b11
- (void)setFrame:(CGRect)frame;	// 0x147a81
- (void)configureForOrientation:(int)orientation;	// 0x146289
- (void)layoutSubviews;	// 0x14794d
@end
