/**
 * This header is generated by class-dump-z 0.2b.
 *
 * Source: (null)
 */

#import "SpringBoard-Structs.h"
#import "SBFolderIconView.h"


@interface SBNewsstandIconView : SBFolderIconView {
}
- (id)_folderBackgroundImage;	// 0x145ad9
- (id)_folderForegroundImage;	// 0x145ba1
- (void)setIconScrollPosition:(int)position animated:(BOOL)animated;	// 0x145ad1
- (void)_positionMiniGrid;	// 0x145ad5
- (void)positionIconImageView;	// 0x145cc5
- (void)placeIconOverlayView;	// 0x145ded
@end

