/**
 * This header is generated by class-dump-z 0.2b.
 *
 * Source: (null)
 */

#import "SpringBoard-Structs.h"
#import "SBIconView.h"


@interface SBNewsstandItemIconViewBase : SBIconView {
}
+ (BOOL)allowsRecycling;	// 0x147c8d
+ (id)createBadgeLabelImageAndGetTextCenterPoint:(CGPoint *)point;	// 0x149819
+ (float)_badgeLabelFontSize;	// 0x147c91
+ (CGPoint)badgeLabelCenterPoint;	// 0x147c95
+ (BOOL)_hasBadgeLabel;	// 0x147cb1
- (void)iconImageDidUpdate:(id)iconImage;	// 0x1497bd
- (CGRect)_adjustProspectiveBadgeFrame:(CGRect)frame fromView:(id)view toView:(id)view3;	// 0x149c85
- (void)_updateBadgePosition;	// 0x149ac9
- (id)_superviewForBadge;	// 0x147cad
- (float)_badgeHorizontalPadding;	// 0x149a81
- (float)_badgeVerticalPadding;	// 0x149a39
@end

