/**
 * This header is generated by class-dump-z 0.2b.
 *
 * Source: (null)
 */

#import "SpringBoard-Structs.h"
#import "SBApplication.h"


@interface SBNewsstandApplication : SBApplication {
	BOOL _isMagazineApp;	// 300 = 0x12c
	BOOL _iconIsBoundOnRight;	// 301 = 0x12d
	unsigned char _newsstandWakes;	// 302 = 0x12e
	unsigned _lastPostedState;	// 304 = 0x130
}
@property(readonly, assign, nonatomic) BOOL isMagazineApp;	// G=0x13ea1d; @synthesize=_isMagazineApp
@property(readonly, assign, nonatomic) BOOL iconIsBoundOnRight;	// G=0x13ea0d; @synthesize=_iconIsBoundOnRight
- (id)initWithBundleIdentifier:(id)bundleIdentifier webClip:(id)clip path:(id)path bundle:(id)bundle infoDictionary:(id)dictionary isSystemApplication:(BOOL)application signerIdentity:(id)identity provisioningProfileValidated:(BOOL)validated;	// 0x13ea31
- (BOOL)isNewsstandApplication;	// 0x13ea05
- (Class)iconClass;	// 0x13efd5
- (void)activate;	// 0x13ef41
- (void)_sendApplicationStateChangedNotification:(unsigned)notification;	// 0x13edf5
- (void)process:(id)process didAddAssertion:(id)assertion;	// 0x13ecd1
- (void)resumeForContentAvailable;	// 0x13ec55
- (BOOL)isFakeApp;	// 0x13ea09
- (BOOL)hasReachedWakeQuota;	// 0x13ec1d
// declared property getter: - (BOOL)iconIsBoundOnRight;	// 0x13ea0d
// declared property getter: - (BOOL)isMagazineApp;	// 0x13ea1d
@end

