/**
 * This header is generated by class-dump-z 0.2b.
 *
 * Source: (null)
 */

#import "SBFolderScrollOffset.h"
#import "SpringBoard-Structs.h"


@interface SBNewsstandFolderScrollOffset : SBFolderScrollOffset {
	unsigned _firstVisibleRow;	// 20 = 0x14
}
@property(assign) unsigned firstVisibleRow;	// G=0x141439; S=0x141449; @synthesize=_firstVisibleRow
// declared property getter: - (unsigned)firstVisibleRow;	// 0x141439
// declared property setter: - (void)setFirstVisibleRow:(unsigned)row;	// 0x141449
@end

