/**
 * This header is generated by class-dump-z 0.2b.
 *
 * Source: (null)
 */

#import "SpringBoard-Structs.h"
#import "SBFolderIconListView.h"

@class NSMutableArray;

@interface SBNewsstandIconListView : SBFolderIconListView {
	unsigned _firstVisibleRow;	// 92 = 0x5c
	unsigned _lastVisibleRow;	// 96 = 0x60
	unsigned _preRotationFirstVisibleRow;	// 100 = 0x64
	unsigned _postRotationFirstVisibleRow;	// 104 = 0x68
	unsigned _rotationPlacementRow;	// 108 = 0x6c
	NSMutableArray *_visibleIcons;	// 112 = 0x70
	BOOL _compactingIcons;	// 116 = 0x74
}
@property(readonly, retain) NSMutableArray *visibleIcons;	// G=0x13fd95; converted property
+ (unsigned)maxIcons;	// 0x13fd51
+ (unsigned)iconRowsForInterfaceOrientation:(int)interfaceOrientation;	// 0x13fd59
+ (unsigned)iconColumnsForInterfaceOrientation:(int)interfaceOrientation;	// 0x14048d
+ (unsigned)maxVisibleIconRowsInterfaceOrientation:(int)orientation;	// 0x1404d5
- (Class)iconRotationContainerClass;	// 0x13fe05
- (id)initWithFrame:(CGRect)frame;	// 0x141041
- (void)dealloc;	// 0x140519
- (unsigned)iconRowsForCurrentOrientation;	// 0x140fcd
- (float)topIconInset;	// 0x13fd61
- (float)bottomIconInset;	// 0x13fd71
- (float)sideIconInset;	// 0x13fd75
- (float)verticalIconPadding;	// 0x13fd85
- (CGSize)defaultIconSize;	// 0x140fa9
- (CATransform3D)_transformForIconAtIndex:(unsigned)index inOrientation:(int)orientation;	// 0x140a0d
- (void)cleanupAfterRotation;	// 0x1409cd
// converted property getter: - (id)visibleIcons;	// 0x13fd95
- (unsigned)_preRotationFirstVisibleRow;	// 0x13fda5
- (unsigned)_postRotationFirstVisibleRow;	// 0x13fdb5
- (unsigned)_rotationReferenceRow;	// 0x13fdc5
- (void)setFirstRowToStartRotation:(unsigned)startRotation endRotation:(unsigned)rotation moveIconsRelativeToRow:(unsigned)row;	// 0x13fdd5
- (void)_updateVisibleIconsFromRow:(unsigned)row toRow:(unsigned)row2 includeIcon:(id)icon layoutIfNeeded:(BOOL)needed;	// 0x1405f9
- (BOOL)compactIcons:(BOOL)icons;	// 0x14056d
- (void)_noteNewIconInModel:(id)model;	// 0x1403e1
- (void)showIconImagesFromRow:(unsigned)row toRow:(unsigned)row2;	// 0x140469
@end

