/**
 * This header is generated by class-dump-z 0.2b.
 *
 * Source: (null)
 */

#import "SBUnknownSuperclass.h"

@class UIView;

@interface SBNewsstandShelfTableView : SBUnknownSuperclass {
	UIView *_backView;	// 720 = 0x2d0
}
@property(assign, nonatomic) UIView *shelfFrameView;	// G=0x1413d5; S=0x1413e5; @synthesize=_backView
- (void)didAddSubview:(id)subview;	// 0x141459
- (void)willRemoveSubview:(id)subview;	// 0x14148d
- (void)reloadData;	// 0x14280d
// declared property getter: - (id)shelfFrameView;	// 0x1413d5
// declared property setter: - (void)setShelfFrameView:(id)view;	// 0x1413e5
@end
