/**
 * This header is generated by class-dump-z 0.2b.
 *
 * Source: (null)
 */

#import "SBSwitcherPopoverWindowControllerDelegate.h"
#import "UIPopoverControllerDelegate.h"
#import "SBIconViewDelegate.h"
#import "SBUnknownSuperclass.h"

@class SBSwitcherVolumeSlider, MPAudioVideoRoutingActionSheet, UIViewController, MPAudioVideoRoutingPopoverController, SBAirPlayBarView, UIButton, SBApplication, SBNowPlayingBarView, MPAudioDeviceController;

@interface SBNowPlayingBar : SBUnknownSuperclass <SBIconViewDelegate, UIPopoverControllerDelegate, SBSwitcherPopoverWindowControllerDelegate> {
	SBNowPlayingBarView *_barView;	// 4 = 0x4
	SBAirPlayBarView *_airPlayView;	// 8 = 0x8
	MPAudioVideoRoutingActionSheet *_airPlayActionSheet;	// 12 = 0xc
	UIViewController *_airPlayController;	// 16 = 0x10
	SBSwitcherVolumeSlider *_volumeSlider;	// 20 = 0x14
	UIButton *_airPlayButton;	// 24 = 0x18
	SBApplication *_nowPlayingApp;	// 28 = 0x1c
	int _scanDirection;	// 32 = 0x20
	MPAudioDeviceController *_audioDeviceController;	// 36 = 0x24
	MPAudioVideoRoutingPopoverController *_audioRoutingPopoverController;	// 40 = 0x28
	BOOL _audioRoutingPopoverVisible;	// 44 = 0x2c
	BOOL _showPopoverWhenRotationComplete;	// 45 = 0x2d
}
@property(readonly, assign) int scanDirection;	// G=0x122049; converted property
- (id)init;	// 0x1231a1
- (void)dealloc;	// 0x123e5d
- (id)views;	// 0x1238f5
// converted property getter: - (int)scanDirection;	// 0x122049
- (void)viewAtIndexDidAppear:(int)viewAtIndex;	// 0x122081
- (void)viewAtIndexDidDisappear:(int)viewAtIndex;	// 0x122139
- (void)viewDidAppear;	// 0x12220d
- (void)prepareToDisappear;	// 0x12225d
- (BOOL)shouldScrollCancelInContentForView:(id)view;	// 0x122329
- (void)_updateDisplay;	// 0x12382d
- (void)_toggleButtonHit:(id)hit;	// 0x12239d
- (void)_playButtonHit:(id)hit;	// 0x122495
- (void)_trackButtonUp:(id)up;	// 0x1224c9
- (void)_trackButtonCancel:(id)cancel;	// 0x122599
- (void)_trackButtonDown:(id)down;	// 0x122615
- (void)_trackButtonDownSeek:(id)seek;	// 0x12264d
- (void)_updateNowPlayingApp;	// 0x1226e1
- (void)_updateNowPlayingInfo;	// 0x1228e1
- (void)_nowPlayingInfoChanged;	// 0x12299d
- (void)_updateNowPlayingButtonImages;	// 0x1229c9
- (void)_updateAudioRouteDisplay:(BOOL)display;	// 0x122a55
- (void)_iapExtendedModeChanged:(id)changed;	// 0x122ca5
- (void)_brightnessSliderChanged:(id)changed;	// 0x122cb5
- (void)_airPlayButtonHit:(id)hit;	// 0x12353d
- (void)_dismissAirPlayDetail;	// 0x122d31
- (BOOL)_shouldShowAirPlayButton;	// 0x122f05
- (void)_showAudioRoutingPopover;	// 0x123355
- (BOOL)_isAirPlayOn;	// 0x122f29
- (void)iconTapped:(id)tapped;	// 0x12328d
- (BOOL)iconShouldAllowTap:(id)icon;	// 0x122065
- (void)iconTouchBegan:(id)began;	// 0x122f59
- (void)backlightLevelChanged;	// 0x122f6d
- (void)audioDeviceControllerAudioRoutesChanged:(id)changed;	// 0x122fc9
- (void)audioDeviceControllerMediaServerDied:(id)died;	// 0x122069
- (void)popoverControllerDidDismissPopover:(id)popoverController;	// 0x122fdd
- (void)switcherPopoverController:(id)controller willRotateToOrientation:(int)orientation duration:(double)duration;	// 0x123121
- (void)switcherPopoverController:(id)controller didRotateFromInterfaceOrientation:(int)interfaceOrientation;	// 0x123161
- (void)viewControllerRequestsDismissal:(id)dismissal;	// 0x123191
@end
