/**
 * This header is generated by class-dump-z 0.2b.
 *
 * Source: (null)
 */

#import "SBUnknownSuperclass.h"
#import "SpringBoard-Structs.h"

@class UILabel;

@interface SBNoResultsView : SBUnknownSuperclass {
	UILabel *_noResultsLabel;	// 48 = 0x30
}
- (id)initWithFrame:(CGRect)frame;	// 0xe82f1
- (void)dealloc;	// 0xe867d
- (void)layoutSubviews;	// 0xe8575
- (void)setShowsText:(BOOL)text;	// 0xe6615
@end
