/**
 * This header is generated by class-dump-z 0.2b.
 *
 * Source: (null)
 */

#import "SBUnknownSuperclass.h"
#import "SpringBoard-Structs.h"

@class SBNowPlayingBarMediaControlsView, UIButton, UIImageView, UISlider, SBIconView, UIView;

@interface SBNowPlayingBarView : SBUnknownSuperclass {
	int _toggleType;	// 48 = 0x30
	UIView *_toggleButtonContainer;	// 52 = 0x34
	UIButton *_toggleButton;	// 56 = 0x38
	UISlider *_brightnessSlider;	// 60 = 0x3c
	UISlider *_volumeSlider;	// 64 = 0x40
	UIImageView *_brightnessImage;	// 68 = 0x44
	UIImageView *_volumeImage;	// 72 = 0x48
	SBNowPlayingBarMediaControlsView *_mediaView;	// 76 = 0x4c
	SBIconView *_nowPlayingIconView;	// 80 = 0x50
}
@property(readonly, assign, nonatomic) UIButton *toggleButton;	// G=0x1272d1; @synthesize=_toggleButton
@property(readonly, assign, nonatomic) UISlider *brightnessSlider;	// G=0x1272c1; @synthesize=_brightnessSlider
@property(readonly, assign, nonatomic) UISlider *volumeSlider;	// G=0x1272b1; @synthesize=_volumeSlider
@property(readonly, assign, nonatomic) SBNowPlayingBarMediaControlsView *mediaView;	// G=0x1272a1; @synthesize=_mediaView
@property(retain, nonatomic) SBIconView *nowPlayingIconView;	// G=0x127291; S=0x128d31; @synthesize=_nowPlayingIconView
@property(assign, nonatomic) BOOL marqueeRunning;	// G=0x128e49; S=0x128e6d; 
@property(readonly, assign, nonatomic) UIButton *airPlayButton;	// G=0x128e91; 
@property(assign, nonatomic) int toggleType;	// G=0x12727d; S=0x128aa5; 
// declared property getter: - (int)toggleType;	// 0x12727d
// declared property setter: - (void)setToggleType:(int)type;	// 0x128aa5
- (id)initWithFrame:(CGRect)frame;	// 0x129805
- (void)dealloc;	// 0x128af5
- (void)layoutSubviews;	// 0x1297ad
- (void)_layoutForiPhone;	// 0x129511
- (void)_layoutForiPad;	// 0x128fa5
- (void)_updateToggleButton;	// 0x128eb1
// declared property getter: - (id)airPlayButton;	// 0x128e91
// declared property setter: - (void)setMarqueeRunning:(BOOL)running;	// 0x128e6d
// declared property getter: - (BOOL)marqueeRunning;	// 0x128e49
// declared property setter: - (void)setNowPlayingIconView:(id)view;	// 0x128d31
- (void)showAudioRoutesPickerButton:(BOOL)button;	// 0x128c41
- (void)showVolume:(BOOL)volume;	// 0x128bfd
// declared property getter: - (id)nowPlayingIconView;	// 0x127291
// declared property getter: - (id)mediaView;	// 0x1272a1
// declared property getter: - (id)volumeSlider;	// 0x1272b1
// declared property getter: - (id)brightnessSlider;	// 0x1272c1
// declared property getter: - (id)toggleButton;	// 0x1272d1
@end
