/**
 * This header is generated by class-dump-z 0.2b.
 *
 * Source: (null)
 */

#import "SBUnknownSuperclass.h"
#import "SpringBoard-Structs.h"

@class UIButton, UILabel, SBIconLabel;

@interface SBNowPlayingBarMediaControlsView : SBUnknownSuperclass {
	UIButton *_prevButton;	// 48 = 0x30
	UIButton *_playButton;	// 52 = 0x34
	UIButton *_nextButton;	// 56 = 0x38
	UIButton *_airPlayButton;	// 60 = 0x3c
	UILabel *_trackLabel;	// 64 = 0x40
	int _toggleType;	// 68 = 0x44
	SBIconLabel *_toggleLabel;	// 72 = 0x48
	BOOL _isAirPlayVisible;	// 76 = 0x4c
	BOOL _isPlaying;	// 77 = 0x4d
	BOOL _isEnabled;	// 78 = 0x4e
	BOOL _showingToggleLabel;	// 79 = 0x4f
}
@property(readonly, assign, nonatomic) UIButton *prevButton;	// G=0x12726d; @synthesize=_prevButton
@property(readonly, assign, nonatomic) UIButton *playButton;	// G=0x12725d; @synthesize=_playButton
@property(readonly, assign, nonatomic) UIButton *nextButton;	// G=0x12724d; @synthesize=_nextButton
@property(readonly, assign, nonatomic) UIButton *airPlayButton;	// G=0x12723d; @synthesize=_airPlayButton
@property(assign, nonatomic) BOOL airPlayButtonVisible;	// G=0x12722d; S=0x127a65; @synthesize=_isAirPlayVisible
@property(assign, nonatomic) BOOL marqueeRunning;	// G=0x127a1d; S=0x127a41; 
- (id)initWithFrame:(CGRect)frame;	// 0x1283b9
- (void)dealloc;	// 0x1272e1
- (void)updateImages:(BOOL)images enabled:(BOOL)enabled;	// 0x1280d5
- (void)layoutSubviews;	// 0x12807d
- (void)_layoutForiPhone;	// 0x127dfd
- (void)_layoutForiPad;	// 0x127afd
- (void)setTrackString:(id)string;	// 0x127ad9
// declared property setter: - (void)setAirPlayButtonVisible:(BOOL)visible;	// 0x127a65
// declared property setter: - (void)setMarqueeRunning:(BOOL)running;	// 0x127a41
// declared property getter: - (BOOL)marqueeRunning;	// 0x127a1d
- (void)setLabelWidth:(float)width;	// 0x127955
- (id)_descriptionLabel;	// 0x1278e9
- (void)_toggleStatus:(id)status;	// 0x1276fd
- (void)_setToggleType:(int)type;	// 0x1276a9
- (id)_toggleLabelText;	// 0x127461
- (void)_orientationLockChanged:(id)changed;	// 0x127411
- (void)_muteChanged:(id)changed;	// 0x1273c1
// declared property getter: - (BOOL)airPlayButtonVisible;	// 0x12722d
// declared property getter: - (id)airPlayButton;	// 0x12723d
// declared property getter: - (id)nextButton;	// 0x12724d
// declared property getter: - (id)playButton;	// 0x12725d
// declared property getter: - (id)prevButton;	// 0x12726d
@end
