/**
 * This header is generated by class-dump-z 0.2b.
 *
 * Source: (null)
 */

#import "SBIcon.h"


@interface SBNullIcon : SBIcon {
}
+ (id)nullIcon;	// 0x13b635
- (id)generateIconImage:(int)image;	// 0x13ab21
- (BOOL)shouldCacheImageForFormat:(int)format;	// 0x13ab25
@end

