/**
 * This header is generated by class-dump-z 0.2b.
 *
 * Source: (null)
 */

#import "SBUnknownSuperclass.h"

@class NSString;

@interface SBPasscodeComplianceAlertItem : SBUnknownSuperclass {
	NSString *_title;	// 16 = 0x10
	NSString *_message;	// 20 = 0x14
	NSString *_continueButtonTitle;	// 24 = 0x18
	NSString *_cancelButtonTitle;	// 28 = 0x1c
}
- (id)initWithTitle:(id)title message:(id)message continueButtonTitle:(id)title3 cancelButtonTitle:(id)title4;	// 0xd1021
- (void)dealloc;	// 0xd1215
- (BOOL)shouldShowInLockScreen;	// 0xd07dd
- (void)alertView:(id)view clickedButtonAtIndex:(int)index;	// 0xd11b1
- (void)configure:(BOOL)configure requirePasscodeForActions:(BOOL)actions;	// 0xd10d5
@end
