/**
 * This header is generated by class-dump-z 0.2b.
 *
 * Source: (null)
 */

#import "SBWaveView.h"
#import "SpringBoard-Structs.h"


@interface SBPathWaveView : SBWaveView {
}
+ (Class)layerClass;	// 0xe9479
- (id)_shapeLayer;	// 0xe9415
- (id)initWithFrame:(CGRect)frame;	// 0xe9495
- (BOOL)_shouldAnimatePropertyWithKey:(id)key;	// 0xe970d
- (CGPathRef)_copyCurrentPath;	// 0xe9559
- (void)_updateCurrentPath;	// 0xe9511
- (void)setColor:(id)color;	// 0xe9425
- (void)layoutSubviews;	// 0xe9469
@end

