/**
 * This header is generated by class-dump-z 0.2b.
 *
 * Source: (null)
 */

#import "SBUnknownSuperclass.h"

@class NSString;

@interface SBPhoneAlertItem : SBUnknownSuperclass {
	NSString *_bodyText;	// 16 = 0x10
	NSString *_title;	// 20 = 0x14
}
- (id)initWithTitle:(id)title bodyText:(id)text;	// 0x9beb9
- (void)dealloc;	// 0x9c015
- (void)configure:(BOOL)configure requirePasscodeForActions:(BOOL)actions;	// 0x9bf39
@end
