/**
 * This header is generated by class-dump-z 0.2b.
 *
 * Source: (null)
 */

#import "SBUnknownSuperclass.h"

@class NSString;

@interface SBPhraseInterpretation : SBUnknownSuperclass {
	int _weight;	// 4 = 0x4
}
@property(assign, nonatomic) int weight;	// G=0x191d85; S=0x191d95; @synthesize=_weight
@property(readonly, retain, nonatomic) NSString *text;	// G=0x191d79; 
- (id)init;	// 0x192a49
// declared property getter: - (id)text;	// 0x191d79
- (BOOL)removeSpaceBefore;	// 0x191d7d
- (BOOL)removeSpaceAfter;	// 0x191d81
- (id)description;	// 0x192a95
// declared property getter: - (int)weight;	// 0x191d85
// declared property setter: - (void)setWeight:(int)weight;	// 0x191d95
@end
