/**
 * This header is generated by class-dump-z 0.2b.
 *
 * Source: (null)
 */

#import "SBUnknownSuperclass.h"
#import "SpringBoard-Structs.h"

@class NSMutableDictionary, NSString, NSDictionary;

@interface SBPlatformController : SBUnknownSuperclass {
	NSString *_currentConfigurationName;	// 4 = 0x4
	NSMutableDictionary *_currentConfiguration;	// 8 = 0x8
	NSMutableDictionary *_currentCapabilities;	// 12 = 0xc
	NSMutableDictionary *_regionalOverrideSoftwareBehaviors;	// 16 = 0x10
	NSDictionary *_discoveredCapabilities;	// 20 = 0x14
	int _currentLockdownState;	// 24 = 0x18
	BOOL _saveLocalePostActivation;	// 28 = 0x1c
}
@property(readonly, retain) NSString *currentConfigurationName;	// G=0xa6f91; converted property
+ (id)sharedInstance;	// 0xa539d
- (id)init;	// 0xa5231
- (void)dealloc;	// 0xa7c25
- (id)systemBuildVersion;	// 0xa7bcd
- (id)infoForCapability:(id)capability;	// 0xa7ba9
- (id)defaultInfoForCapability:(id)capability;	// 0xa7b85
- (id)hardwareInfoForCapability:(id)capability;	// 0xa7b49
- (void)setValue:(id)value forCapability:(id)capability;	// 0xa7ad9
- (void)addCapabilities:(id)capabilities resetCapabilites:(id)capabilites;	// 0xa7939
- (BOOL)hasCapability:(id)capability;	// 0xa78c9
- (id)enabledCapabilities;	// 0xa778d
- (BOOL)hasRestriction:(id)restriction;	// 0xa774d
- (BOOL)canDisplayHomescreenWallpaper;	// 0xa76e5
- (id)platformName;	// 0xa5201
- (id)iconState;	// 0xa76bd
- (void)_addIconListIdentifiers:(id)identifiers toSet:(id)set;	// 0xa761d
- (id)defaultDisplayIdentifiers;	// 0xa7431
- (BOOL)matchesPlatforms:(id)platforms;	// 0xa7365
- (id)localizedPlatformName;	// 0xa7345
- (BOOL)isInternalInstall;	// 0xa7321
- (BOOL)isCarrierInstall;	// 0xa7301
- (void)noteITunesStoreCapabilityChanged;	// 0xa7265
- (BOOL)capabililtyOverrideEnabledByPreference:(id)preference;	// 0xa7225
- (void)noteCapabilityOverrideMightHaveChanged:(id)changed setByPreference:(id)preference;	// 0xa7185
- (void)noteCapabilityOverridesMightHaveChanged;	// 0xa7159
- (void)noteDeveloperDeviceStateMightHaveChanged;	// 0xa5211
// converted property getter: - (id)currentConfigurationName;	// 0xa6f91
- (void)postCurrentConfiguration;	// 0xa6e05
- (id)_copyConfigInfoWithName:(id)name;	// 0xa6d71
- (id)_copyDefaultConfigInfo;	// 0xa6c1d
- (BOOL)allowSensitiveUI:(BOOL)ui hasInternalBundle:(BOOL)bundle;	// 0xa6b01
- (BOOL)isCarrierInstall:(BOOL)install hasInternalBundle:(BOOL)bundle;	// 0xa5215
- (BOOL)allowYouTube;	// 0xa6aad
- (BOOL)allowYouTubePlugin;	// 0xa6a7d
- (void)discoverCurrentConfiguration;	// 0xa5ed1
- (void)addTelephonyCapabilitiesAndPost:(BOOL)post;	// 0xa5ca1
- (CFBooleanRef)currentITunesStoreCapability;	// 0xa5bd9
- (void)noteConfigurationChangedWithKeys:(id)keys;	// 0xa5b11
- (void)resetDefaultSoftwareBehaviorsAndPost:(BOOL)post;	// 0xa5791
- (void)setSoftwareBehavior:(id)behavior forKey:(id)key;	// 0xa5729
- (id)regionalOverrideSoftwareBehaviorForKey:(id)key;	// 0xa55c5
- (void)lockdownStateChanged;	// 0xa54fd
- (void)_iCloudRestoreDidEnd;	// 0xa54ed
- (void)localeChanged;	// 0xa54b9
- (void)setOriginalRegionFormatCountryCodeAndResetSoftwareBehaviorsIfNecessary;	// 0xa53e5
@end
