/**
 * This header is generated by class-dump-z 0.2b.
 *
 * Source: (null)
 */

#import "SpringBoard-Structs.h"
#import "SBAlert.h"

@class SBPowerDownView;

@interface SBPowerDownController : SBAlert {
	int _count;	// 60 = 0x3c
	id _delegate;	// 64 = 0x40
	SBPowerDownView *_powerDownView;	// 68 = 0x44
	BOOL _isFront;	// 72 = 0x48
}
+ (id)sharedInstance;	// 0x742f5
- (void)dealloc;	// 0x7453d
- (double)autoLockTime;	// 0x74255
- (BOOL)isOrderedFront;	// 0x74261
- (void)orderFront;	// 0x74539
- (void)orderOut;	// 0x74285
- (id)powerDownViewWithSize:(CGSize)size;	// 0x74451
- (void)activate;	// 0x743d1
- (void)_restoreIconListIfNecessary;	// 0x7437d
- (void)deactivate;	// 0x7433d
- (id)alertDisplayViewWithSize:(CGSize)size;	// 0x742a5
- (void)alertDisplayWillBecomeVisible;	// 0x74271
- (void)setDelegate:(id)delegate;	// 0x74275
- (void)powerDown;	// 0x742b5
- (void)cancel;	// 0x742d5
@end

