/**
 * This header is generated by class-dump-z 0.2b.
 *
 * Source: (null)
 */

#import "SpringBoard-Structs.h"
#import "SBUnknownSuperclass.h"


@interface SBPolygon : SBUnknownSuperclass {
	int m_pointCount;	// 4 = 0x4
	CGPoint m_points[5];	// 8 = 0x8
	unsigned m_pathIDs[5];	// 48 = 0x30
	float m_weights[5];	// 68 = 0x44
	CGPoint m_centroid;	// 88 = 0x58
	CGPoint m_weightedCentroid;	// 96 = 0x60
	unsigned m_baseLeftVertex;	// 104 = 0x68
	unsigned m_bottomRightVertex;	// 108 = 0x6c
}
@property(readonly, assign, nonatomic) int pointCount;	// G=0x1303dd; @synthesize=m_pointCount
@property(assign, nonatomic) CGPoint centroid;	// G=0x1303c5; S=0x12ffa9; @synthesize=m_centroid
@property(assign, nonatomic) CGPoint weightedCentroid;	// G=0x1303ad; S=0x130071; @synthesize=m_weightedCentroid
@property(readonly, assign, nonatomic) BOOL isLeftHanded;	// G=0x13106d; 
+ (BOOL)candidate:(id)candidate matchesTemplate:(id)aTemplate transforms:(int)transforms acceptFactor:(float)factor;	// 0x130481
- (void)commonInit;	// 0x131261
- (void)makeLike:(id)like;	// 0x131179
- (void)clear;	// 0x1310e9
- (void)beginPointUpdate;	// 0x1303ed
- (void)addPoint:(CGPoint)point;	// 0x12fee1
- (void)addPoint:(CGPoint)point pathIndex:(unsigned)index;	// 0x12ff3d
- (void)endPointUpdate;	// 0x1303fd
- (float)weightAtIndex:(int)index;	// 0x12ff95
// declared property setter: - (void)setCentroid:(CGPoint)centroid;	// 0x12ffa9
// declared property setter: - (void)setWeightedCentroid:(CGPoint)centroid;	// 0x130071
- (float)width;	// 0x13013d
- (float)height;	// 0x1301d9
// declared property getter: - (BOOL)isLeftHanded;	// 0x13106d
- (unsigned)thumbIndex;	// 0x13040d
- (void)rotate:(float)rotate;	// 0x130f45
- (void)scale:(float)scale;	// 0x130e1d
- (void)flipHorizontally;	// 0x130d09
- (void)sortAlongOutsideEdge;	// 0x130ac5
- (float)findLongestOutsideEdge;	// 0x13093d
- (CGPoint)calculateCentroid;	// 0x1302a1
- (CGPoint)calculateWeightedCentroid;	// 0x130311
- (float)baseOrientation;	// 0x1308cd
- (float)meanFingertipRowAngle;	// 0x13080d
- (float)meanRadius;	// 0x130765
// declared property getter: - (CGPoint)weightedCentroid;	// 0x1303ad
// declared property getter: - (CGPoint)centroid;	// 0x1303c5
// declared property getter: - (int)pointCount;	// 0x1303dd
@end
