/**
 * This header is generated by class-dump-z 0.2b.
 *
 * Source: (null)
 */

#import "SpringBoard-Structs.h"
#import "SBAlertDisplay.h"

@class SBPowerDownController, NSTimer, TPBottomSingleButtonBar, UIView, TPTopLockBar;

@interface SBPowerDownView : SBAlertDisplay {
	UIView *_dimView;	// 56 = 0x38
	TPTopLockBar *_lockView;	// 60 = 0x3c
	TPBottomSingleButtonBar *_cancelView;	// 64 = 0x40
	SBPowerDownController *_powerDownController;	// 68 = 0x44
	NSTimer *_autoDismissTimer;	// 72 = 0x48
}
- (id)initWithFrame:(CGRect)frame;	// 0x74599
- (void)dealloc;	// 0x75429
- (void)cancelAutoDismissTimer;	// 0x753e9
- (void)resetAutoDismissTimer;	// 0x7536d
- (void)cancel:(id)cancel;	// 0x75335
- (void)lockBarUnlocked:(id)unlocked;	// 0x75309
- (void)lockBarStartedTracking:(id)tracking;	// 0x752f9
- (void)lockBarStoppedTracking:(id)tracking;	// 0x752e9
- (void)powerDown:(id)down;	// 0x752c9
- (void)setPowerDownController:(id)controller;	// 0x74589
- (void)finishedAnimatingIn;	// 0x7528d
- (void)finishedAnimatingOut;	// 0x7527d
- (void)notifyDelegateOfPowerDown;	// 0x7525d
- (void)animateIn;	// 0x74fc1
- (void)animateOut;	// 0x74e1d
- (void)animateDark;	// 0x74bf9
- (BOOL)isSupportedInterfaceOrientation:(int)orientation;	// 0x74ba9
- (void)layoutForInterfaceOrientation:(int)interfaceOrientation;	// 0x749b9
@end

