/**
 * This header is generated by class-dump-z 0.2b.
 *
 * Source: (null)
 */

#import "SBLeafIcon.h"


@interface SBPrintStatusIcon : SBLeafIcon {
}
- (id)generateIconImage:(int)image;	// 0x125f99
- (id)displayName;	// 0x125fc1
- (id)leafIdentifier;	// 0x125f79
- (BOOL)shouldEllipsizeLabel;	// 0x125f85
- (id)applicationBundleID;	// 0x125f89
- (BOOL)delaysUnhighlightWhenTapped;	// 0x125f95
@end

