/**
 * This header is generated by class-dump-z 0.2b.
 *
 * Source: (null)
 */

#import "SBSwitcherPopoverWindowControllerDelegate.h"
#import "UIPrintStatusDelegate.h"
#import "UIStatusBarStyleDelegate.h"
#import "UINavigationControllerDelegate.h"
#import "SBUnknownSuperclass.h"

@class UITransitionView, SBAppSwitcherController, UIPrintStatusViewController, UIView, UIStatusBar;

@interface SBPrintStatusController : SBUnknownSuperclass <UIPrintStatusDelegate, UINavigationControllerDelegate, UIStatusBarStyleDelegate, SBSwitcherPopoverWindowControllerDelegate> {
	SBAppSwitcherController *_switcherController;	// 4 = 0x4
	UIPrintStatusViewController *_printStatusController;	// 8 = 0x8
	int _numPrintJobs;	// 12 = 0xc
	BOOL _dismissingImmediately;	// 16 = 0x10
	BOOL _printViewVisible;	// 17 = 0x11
	UIView *_rootView;	// 20 = 0x14
	UITransitionView *_transitionView;	// 24 = 0x18
	UIStatusBar *_fakeStatusBar;	// 28 = 0x1c
	BOOL _savePopoverWindowForRotation;	// 32 = 0x20
	BOOL _showPopoverWhenRotationComplete;	// 33 = 0x21
}
@property(readonly, assign, nonatomic) int numPrintJobs;	// G=0x12606d; @synthesize=_numPrintJobs
- (id)initWithSwitcherController:(id)switcherController;	// 0x12607d
- (void)dealloc;	// 0x126fa5
- (BOOL)printStatusViewIsShowing;	// 0x126055
- (void)activatePrintStatusView;	// 0x126be5
- (void)activatePrintStatusPopoverForView:(id)view;	// 0x126a7d
- (void)dismissPrintStatusView;	// 0x126a21
- (void)_updateStateForNumberOfJobs:(int)jobs;	// 0x1268ed
- (void)_printStateChanged:(id)changed;	// 0x1268b5
- (void)_cleanupPrintController;	// 0x126841
- (void)_cleanupPopoverViews:(BOOL)views;	// 0x1267d9
- (void)_dismissPrintStatus;	// 0x1264ed
- (void)transitionViewDidComplete:(id)transitionView fromView:(id)view toView:(id)view3;	// 0x1263b5
- (double)durationForTransition:(int)transition;	// 0x126369
- (void)printStatusViewController:(id)controller didDismissWithCancel:(BOOL)cancel;	// 0x1262b5
- (void)printStatusViewControllerJobDidCancel:(id)printStatusViewControllerJob;	// 0x126289
- (void)navigationController:(id)controller willShowViewController:(id)controller2 animated:(BOOL)animated;	// 0x1261e9
- (int)statusBar:(id)bar styleForRequestedStyle:(int)requestedStyle overrides:(int)overrides;	// 0x1261c9
- (void)statusBar:(id)bar willAnimateFromHeight:(float)height toHeight:(float)height3 duration:(double)duration animation:(int)animation;	// 0x126065
- (void)statusBar:(id)bar didAnimateFromHeight:(float)height toHeight:(float)height3 animation:(int)animation;	// 0x126069
- (void)switcherPopoverController:(id)controller willRotateToOrientation:(int)orientation duration:(double)duration;	// 0x12617d
- (void)switcherPopoverController:(id)controller didRotateFromInterfaceOrientation:(int)interfaceOrientation;	// 0x126129
// declared property getter: - (int)numPrintJobs;	// 0x12606d
@end
