/**
 * This header is generated by class-dump-z 0.2b.
 *
 * Source: (null)
 */

#import "SBUnknownSuperclass.h"

@class SBApplication;

@interface SBRemoteNotificationNeedIdentityAlert : SBUnknownSuperclass {
	SBApplication *_app;	// 16 = 0x10
}
- (id)initWithApplication:(id)application;	// 0xef5ed
- (void)dealloc;	// 0xef815
- (void)configure:(BOOL)configure requirePasscodeForActions:(BOOL)actions;	// 0xef645
- (BOOL)dismissOnLock;	// 0xef5e5
- (BOOL)dismissOnModalDisplayActivation;	// 0xef5e9
@end
