/**
 * This header is generated by class-dump-z 0.2b.
 *
 * Source: (null)
 */

#import "SBUnknownSuperclass.h"
#import "APSConnectionDelegate.h"

@class NSMutableDictionary, NSString;

@interface SBRemoteNotificationServer : SBUnknownSuperclass <APSConnectionDelegate> {
	NSMutableDictionary *_bundleIdentifiersToClients;	// 4 = 0x4
	NSMutableDictionary *_environmentsToConnections;	// 8 = 0x8
	NSString *_lastNotificationReceivedBundleIdentifier;	// 12 = 0xc
}
@property(assign, getter=isSystemwideEnabled) BOOL systemwideEnabled;	// G=0xe19f5; S=0xe19f9; converted property
@property(readonly, retain) NSString *lastNotificationReceivedBundleIdentifier;	// G=0xe19e5; converted property
+ (id)sharedInstance;	// 0xe203d
- (id)init;	// 0xe3ed5
- (void)dealloc;	// 0xe1f99
- (void)run;	// 0xe3e21
- (void)connection:(id)connection didReceivePublicToken:(id)token;	// 0xe3c51
- (void)noteApplicationFinishedLaunching:(id)launching;	// 0xe3b25
- (void)connection:(id)connection didReceiveMessageForTopic:(id)topic userInfo:(id)info;	// 0xe3325
// converted property getter: - (id)lastNotificationReceivedBundleIdentifier;	// 0xe19e5
- (id)allAppEnabledTypeValues;	// 0xe3191
- (id)allSettingsEnabledTypeValues;	// 0xe2ffd
- (void)calculateTopics;	// 0xe2a75
- (void)registerApplication:(id)application forEnvironment:(id)environment withTypes:(int)types;	// 0xe25c1
- (void)unregisterApplication:(id)application;	// 0xe25a1
- (int)getEffectiveEnabledTypesForApplication:(id)application;	// 0xe2545
// converted property getter: - (BOOL)isSystemwideEnabled;	// 0xe19f5
// converted property setter: - (void)setSystemwideEnabled:(BOOL)enabled;	// 0xe19f9
- (BOOL)hasRegisteredBundleIdentifiers;	// 0xe2515
- (void)notePermissionAlertAcceptedTypes:(int)types forBundleIdentifier:(id)bundleIdentifier;	// 0xe24a5
- (int)appEnabledTypesForBundleIdentifier:(id)bundleIdentifier;	// 0xe2465
- (int)settingsEnabledTypesForBundleIdentifier:(id)bundleIdentifier;	// 0xe2425
- (void)setSettingsTypes:(int)types forBundleIdentifier:(id)bundleIdentifier;	// 0xe22ed
- (void)postSettingsChangedNotificationForBundleIdentifier:(id)bundleIdentifier;	// 0xe22a5
- (void)setMessageUserInfo:(id)info forBundleIdentifier:(id)bundleIdentifier;	// 0xe2265
- (id)getMessageUserInfoForBundleIdentifier:(id)bundleIdentifier;	// 0xe21f1
- (id)_allPushRegisteredThirdPartyBundleIDs;	// 0xe2085
@end
