/**
 * This header is generated by class-dump-z 0.2b.
 *
 * Source: (null)
 */

#import "SBUnknownSuperclass.h"

@class NSCalendar, NSTimer, NSDate;
@protocol SBRelativeDateTimerDelegate;

@interface SBRelativeDateTimer : SBUnknownSuperclass {
	NSCalendar *_gregorian;	// 4 = 0x4
	NSTimer *_timer;	// 8 = 0x8
	NSDate *_date;	// 12 = 0xc
	id<SBRelativeDateTimerDelegate> _delegate;	// 16 = 0x10
	int _currResolution;	// 20 = 0x14
	int _currValue;	// 24 = 0x18
}
@property(retain) NSDate *date;	// G=0x18a595; S=0x18a5cd; converted property
- (id)init;	// 0x189dbd
- (void)dealloc;	// 0x18a725
- (void)_fireForEvent:(id)event;	// 0x18a6f9
- (void)_fireForLocaleEvent:(id)localeEvent;	// 0x18a68d
- (void)setDelegate:(id)delegate;	// 0x189da5
// converted property setter: - (void)setDate:(id)date;	// 0x18a5cd
// converted property getter: - (id)date;	// 0x18a595
- (double)nextFireInterval;	// 0x18a559
- (void)fireAndSchedule;	// 0x18a519
- (void)invalidate;	// 0x18a4d1
- (id)_timeDifferenceFromDate:(id)date;	// 0x18a489
- (void)_fireAndUpdateTimerIfNecessary;	// 0x18a095
- (double)_nextFireInterval:(id)interval resolution:(int)resolution comparedToNow:(int)now;	// 0x189f19
@end
