/**
 * This header is generated by class-dump-z 0.2b.
 *
 * Source: (null)
 */

#import "SBUnknownSuperclass.h"

@class SBApplication;

@interface SBRemoteNotificationPermissionAlert : SBUnknownSuperclass {
	SBApplication *_app;	// 16 = 0x10
	int _types;	// 20 = 0x14
}
- (id)initWithApplication:(id)application notificationTypes:(int)types;	// 0xee3e9
- (void)dealloc;	// 0xee859
- (void)alertView:(id)view clickedButtonAtIndex:(int)index;	// 0xee7c5
- (void)configure:(BOOL)configure requirePasscodeForActions:(BOOL)actions;	// 0xee451
- (BOOL)shouldShowInLockScreen;	// 0xee3e5
@end
