/**
 * This header is generated by class-dump-z 0.2b.
 *
 * Source: (null)
 */

#import "SBUnknownSuperclass.h"
#import "SpringBoard-Structs.h"

@class NSTimer, SBResetProgressView;

@interface SBResetView : SBUnknownSuperclass {
	SBResetProgressView *_progressView;	// 48 = 0x30
	NSTimer *_progressTimer;	// 52 = 0x34
}
- (id)initWithFrame:(CGRect)frame;	// 0xcf595
- (void)dealloc;	// 0xcf275
- (void)_resetStarted:(id)started;	// 0xcf4f9
- (void)_resetFinished:(id)finished;	// 0xcf375
- (void)_updateProgress;	// 0xcf319
@end
