/**
 * This header is generated by class-dump-z 0.2b.
 *
 * Source: (null)
 */

#import "SBUnknownSuperclass.h"


@interface SBRingerHUDController : SBUnknownSuperclass {
}
+ (void)activate:(int)activate;	// 0x76a11
@end
