/**
 * This header is generated by class-dump-z 0.2b.
 *
 * Source: (null)
 */

#import "SpringBoard-Structs.h"
#import "SBHUDView.h"


@interface SBRingerHUDView : SBHUDView {
	BOOL _silent;	// 72 = 0x48
}
@property(assign, nonatomic, getter=isSilent) BOOL silent;	// G=0x76921; S=0x76999; @synthesize=_silent
- (void)_updateSilentImage;	// 0x76931
- (id)init;	// 0x769c9
// declared property setter: - (void)setSilent:(BOOL)silent;	// 0x76999
// declared property getter: - (BOOL)isSilent;	// 0x76921
@end

