/**
 * This header is generated by class-dump-z 0.2b.
 *
 * Source: (null)
 */

#import "SpringBoard-Structs.h"
#import "SBHUDView.h"


@interface SBRotationLockHUDView : SBHUDView {
	BOOL _locked;	// 72 = 0x48
	BOOL locked;	// 73 = 0x49
}
@property(assign, nonatomic, getter=isLocked) BOOL locked;	// G=0x11a1c9; S=0x11a241; @synthesize
- (void)_updateLockedImage;	// 0x11a1d9
- (id)init;	// 0x11a3ad
// declared property setter: - (void)setLocked:(BOOL)locked;	// 0x11a241
// declared property getter: - (BOOL)isLocked;	// 0x11a1c9
@end

