/**
 * This header is generated by class-dump-z 0.2b.
 *
 * Source: (null)
 */

#import "SBUnknownSuperclass.h"


@interface SBRotationLockHUDController : SBUnknownSuperclass {
}
+ (void)activateWithLocked:(BOOL)locked;	// 0x11a271
@end
