/**
 * This header is generated by class-dump-z 0.2b.
 *
 * Source: (null)
 */

#import "SpringBoard-Structs.h"
#import "SBUnknownSuperclass.h"


@interface SBRoundedMaskCornerView : SBUnknownSuperclass {
	float _cornerRadius;	// 48 = 0x30
	unsigned _corner;	// 52 = 0x34
}
- (id)initWithCorner:(unsigned)corner radius:(float)radius;	// 0xe60e5
- (void)drawRect:(CGRect)rect;	// 0xe653d
@end
