/**
 * This header is generated by class-dump-z 0.2b.
 *
 * Source: (null)
 */

#import "SBUnknownSuperclass.h"

@class UIView, UIWindow;

@interface SBScreenFlash : SBUnknownSuperclass {
	UIWindow *_flashWindow;	// 4 = 0x4
	UIView *_flashView;	// 8 = 0x8
	BOOL _windowVisible;	// 12 = 0xc
}
+ (id)sharedInstance;	// 0xa27c9
- (void)dealloc;	// 0xa2975
- (void)_createUIWithColor:(id)color;	// 0xa2811
- (void)_tearDown;	// 0xa242d
- (void)_orderWindowOut:(id)anOut;	// 0xa2481
- (void)_orderWindowFront:(id)front withColor:(id)color;	// 0xa2549
- (void)stopFlash;	// 0xa263d
- (void)flash;	// 0xa2685
- (void)flashColor:(id)color;	// 0xa26c1
- (void)animationDidStop:(id)animation finished:(id)finished context:(void *)context;	// 0xa2745
@end
