/**
 * This header is generated by class-dump-z 0.2b.
 *
 * Source: (null)
 */

#import "SpringBoard-Structs.h"
#import "SBFluidSlideGestureRecognizer.h"


@interface SBScaleGestureRecognizer : SBFluidSlideGestureRecognizer {
}
- (float)computeIncrementalGestureMotion:(SBGestureContextRef)motion;	// 0x16ceed
@end

