/**
 * This header is generated by class-dump-z 0.2b.
 *
 * Source: (null)
 */

#import "SBUnknownSuperclass.h"


@interface SBSDaemonHandler : SBUnknownSuperclass {
}
+ (void)initialize;	// 0x16da99
+ (BOOL)addRequest:(id)request forKey:(id)key forDaemonPid:(int)daemonPid;	// 0x16db31
+ (void)removeRequestForKey:(id)key forDaemonPid:(int)daemonPid;	// 0x16dac5
+ (id)stateDescription;	// 0x16dc15
+ (void)noteDaemonCanceled:(id)canceled;	// 0x16d725
@end
