/**
 * This header is generated by class-dump-z 0.2b.
 *
 * Source: (null)
 */

#import "SpringBoard-Structs.h"
#import "SBUnknownSuperclass.h"


@interface SBSDaemonRequest : SBUnknownSuperclass {
	id _enabler;	// 4 = 0x4
	id _disabler;	// 8 = 0x8
}
@property(copy, nonatomic) id enabler;	// G=0x16cf9d; S=0x16d8d1; @synthesize=_enabler
@property(copy, nonatomic) id disabler;	// G=0x16cf8d; S=0x16d8f5; @synthesize=_disabler
+ (id)requestWithEnabler:(id)enabler disabler:(id)disabler;	// 0x16d85d
- (void)dealloc;	// 0x16d9d1
- (void)dispatchEnablerOnQueue:(dispatch_queue_s *)queue;	// 0x16d975
- (void)dispatchDisablerOnQueue:(dispatch_queue_s *)queue;	// 0x16d919
// declared property getter: - (id)disabler;	// 0x16cf8d
// declared property setter: - (void)setDisabler:(id)disabler;	// 0x16d8f5
// declared property getter: - (id)enabler;	// 0x16cf9d
// declared property setter: - (void)setEnabler:(id)enabler;	// 0x16d8d1
@end
