/**
 * This header is generated by class-dump-z 0.2b.
 *
 * Source: (null)
 */

#import "SBUnknownSuperclass.h"
#import "SpringBoard-Structs.h"

@class UILabel, UISearchBar, SBNoResultsView, UITableView, UIView, SBRoundedCornersView;

@interface SBSearchView : SBUnknownSuperclass {
	SBRoundedCornersView *_roundedCornersView;	// 48 = 0x30
	UISearchBar *_searchBar;	// 52 = 0x34
	UITableView *_tableView;	// 56 = 0x38
	UILabel *_noResultsLabel;	// 60 = 0x3c
	SBNoResultsView *_noResultsView;	// 64 = 0x40
	UIView *_rootView;	// 68 = 0x44
	UIView *_contentView;	// 72 = 0x48
	BOOL _isKeyboardAnimatingRotation;	// 76 = 0x4c
	BOOL _hidesEmptyTableFooter;	// 77 = 0x4d
}
@property(readonly, assign, nonatomic) UISearchBar *searchBar;	// G=0xe5aa5; @synthesize=_searchBar
@property(readonly, assign, nonatomic) UITableView *tableView;	// G=0xe5a95; @synthesize=_tableView
@property(retain, nonatomic) UIView *contentView;	// G=0xe5a85; S=0xe6709; @synthesize=_contentView
@property(retain, nonatomic) UIView *rootView;	// G=0xe5a75; S=0xe6731; @synthesize=_rootView
@property(readonly, assign, nonatomic) UIView *roundedCornersView;	// G=0xe5a65; @synthesize=_roundedCornersView
- (id)initWithFrame:(CGRect)frame;	// 0xe5ab5
- (id)initWithFrame:(CGRect)frame withContent:(id)content onWallpaper:(id)wallpaper;	// 0xe7a65
- (void)dealloc;	// 0xe6645
- (void)didMoveToWindow;	// 0xe79ed
- (void)setFrame:(CGRect)frame;	// 0xe7975
- (void)scrollViewIsScrollingHorizontally;	// 0xe5b3d
- (void)setShowsNoResultsView:(BOOL)view;	// 0xe7715
- (void)layoutCornerView;	// 0xe74dd
- (void)setHidesEmptyTableFooter:(BOOL)footer;	// 0xe5a45
- (float)_footerHeight;	// 0xe7375
- (void)layoutFooterView;	// 0xe7141
- (void)_layoutNoResultsView;	// 0xe70c1
- (Class)tableViewClass;	// 0xe5b5d
- (Class)searchBarClass;	// 0xe5b79
- (id)_keyboard;	// 0xe5b95
- (BOOL)isKeyboardMinimized;	// 0xe5bb1
- (BOOL)isKeyboardVisible;	// 0xe7075
- (void)setShowsKeyboard:(BOOL)keyboard animated:(BOOL)animated;	// 0xe6ead
- (void)keyboardDidShow:(id)keyboard;	// 0xe5bd9
- (void)setShowingNoResultsText:(BOOL)text;	// 0xe6c19
- (void)_setDistantContentViewTransform;	// 0xe6b75
- (void)_resetContentViewTransform;	// 0xe6abd
- (void)scatter:(BOOL)scatter startTime:(double)time;	// 0xe684d
- (void)unscatter:(BOOL)unscatter startTime:(double)time;	// 0xe5dc5
- (void)unscatterAnimationDidStop;	// 0xe5fa9
- (void)willRotateToInterfaceOrientation:(int)interfaceOrientation duration:(double)duration;	// 0xe67e1
- (void)willAnimateRotationToInterfaceOrientation:(int)interfaceOrientation duration:(double)duration;	// 0xe67ad
- (void)didRotateFromInterfaceOrientation:(int)interfaceOrientation;	// 0xe6759
// declared property getter: - (id)roundedCornersView;	// 0xe5a65
// declared property getter: - (id)rootView;	// 0xe5a75
// declared property setter: - (void)setRootView:(id)view;	// 0xe6731
// declared property getter: - (id)contentView;	// 0xe5a85
// declared property setter: - (void)setContentView:(id)view;	// 0xe6709
// declared property getter: - (id)tableView;	// 0xe5a95
// declared property getter: - (id)searchBar;	// 0xe5aa5
@end
