/**
 * This header is generated by class-dump-z 0.2b.
 *
 * Source: (null)
 */

#import "SBUnknownSuperclass.h"
#import "SpringBoard-Structs.h"

@class NSString, UIFont;

@interface SBSearchTableViewCell : SBUnknownSuperclass {
	UIFont *_titleFont;	// 244 = 0xf4
	UIFont *_subtitleFont;	// 248 = 0xf8
	UIFont *_topHitFont;	// 252 = 0xfc
	NSString *_title;	// 256 = 0x100
	NSString *_subtitle;	// 260 = 0x104
	NSString *_summary;	// 264 = 0x108
	NSString *_auxiliaryTitle;	// 268 = 0x10c
	NSString *_auxiliarySubtitle;	// 272 = 0x110
	BOOL _badged;	// 276 = 0x114
	BOOL _usesAlternateBackgroundColor;	// 277 = 0x115
	BOOL _isTopHit;	// 278 = 0x116
	BOOL _isBelowTopHit;	// 279 = 0x117
	BOOL _isFirstInTableView;	// 280 = 0x118
	BOOL _isFirstInSection;	// 281 = 0x119
	float _sectionHeaderWidth;	// 284 = 0x11c
	float _edgeInset;	// 288 = 0x120
}
@property(retain, nonatomic) NSString *title;	// G=0xeba01; S=0xeccf5; @synthesize=_title
@property(retain, nonatomic) NSString *subtitle;	// G=0xeb9f1; S=0xebca5; @synthesize=_subtitle
@property(retain, nonatomic) NSString *summary;	// G=0xeb9e1; S=0xebccd; @synthesize=_summary
@property(retain, nonatomic) NSString *auxiliaryTitle;	// G=0xeb9d1; S=0xebcf5; @synthesize=_auxiliaryTitle
@property(retain, nonatomic) NSString *auxiliarySubtitle;	// G=0xeb9c1; S=0xebd1d; @synthesize=_auxiliarySubtitle
@property(assign, nonatomic, getter=isBadged) BOOL badged;	// G=0xeb9a1; S=0xeb9b1; @synthesize=_badged
@property(assign, nonatomic) BOOL usesAlternateBackgroundColor;	// G=0xeb981; S=0xeb991; @synthesize=_usesAlternateBackgroundColor
@property(assign, nonatomic, getter=isTopHit) BOOL topHit;	// G=0xeb961; S=0xeb971; @synthesize=_isTopHit
@property(assign, nonatomic, getter=isBelowTopHit) BOOL belowTopHit;	// G=0xeb941; S=0xeb951; @synthesize=_isBelowTopHit
@property(assign, nonatomic, getter=isFirstInTableView) BOOL firstInTableView;	// G=0xeb921; S=0xeb931; @synthesize=_isFirstInTableView
@property(assign, nonatomic, getter=isFirstInSection) BOOL firstInSection;	// G=0xeb901; S=0xeb911; @synthesize=_isFirstInSection
@property(assign, nonatomic) float sectionHeaderWidth;	// G=0xeb8e1; S=0xeb8f1; @synthesize=_sectionHeaderWidth
@property(assign, nonatomic) float edgeInset;	// G=0xeb8c1; S=0xeb8d1; @synthesize=_edgeInset
+ (id)backgroundColor;	// 0xebc35
+ (id)alternateBackgroundColor;	// 0xebbc5
+ (id)lineColor;	// 0xebba9
+ (id)alternateLineColor;	// 0xebb55
+ (id)topLineShadowColor;	// 0xebae5
- (id)initWithStyle:(int)style reuseIdentifier:(id)identifier;	// 0xeba11
- (void)dealloc;	// 0xece21
- (void)clearContents;	// 0xecd8d
// declared property setter: - (void)setTitle:(id)title;	// 0xeccf5
- (BOOL)_drawsContent;	// 0xeb8bd
- (void)_drawContentInRect:(CGRect)rect selected:(BOOL)selected;	// 0xebe1d
- (void)drawRect:(CGRect)rect;	// 0xebdd1
- (id)_scriptingInfo;	// 0xebd45
// declared property getter: - (float)edgeInset;	// 0xeb8c1
// declared property setter: - (void)setEdgeInset:(float)inset;	// 0xeb8d1
// declared property getter: - (float)sectionHeaderWidth;	// 0xeb8e1
// declared property setter: - (void)setSectionHeaderWidth:(float)width;	// 0xeb8f1
// declared property getter: - (BOOL)isFirstInSection;	// 0xeb901
// declared property setter: - (void)setFirstInSection:(BOOL)section;	// 0xeb911
// declared property getter: - (BOOL)isFirstInTableView;	// 0xeb921
// declared property setter: - (void)setFirstInTableView:(BOOL)tableView;	// 0xeb931
// declared property getter: - (BOOL)isBelowTopHit;	// 0xeb941
// declared property setter: - (void)setBelowTopHit:(BOOL)hit;	// 0xeb951
// declared property getter: - (BOOL)isTopHit;	// 0xeb961
// declared property setter: - (void)setTopHit:(BOOL)hit;	// 0xeb971
// declared property getter: - (BOOL)usesAlternateBackgroundColor;	// 0xeb981
// declared property setter: - (void)setUsesAlternateBackgroundColor:(BOOL)color;	// 0xeb991
// declared property getter: - (BOOL)isBadged;	// 0xeb9a1
// declared property setter: - (void)setBadged:(BOOL)badged;	// 0xeb9b1
// declared property getter: - (id)auxiliarySubtitle;	// 0xeb9c1
// declared property setter: - (void)setAuxiliarySubtitle:(id)subtitle;	// 0xebd1d
// declared property getter: - (id)auxiliaryTitle;	// 0xeb9d1
// declared property setter: - (void)setAuxiliaryTitle:(id)title;	// 0xebcf5
// declared property getter: - (id)summary;	// 0xeb9e1
// declared property setter: - (void)setSummary:(id)summary;	// 0xebccd
// declared property getter: - (id)subtitle;	// 0xeb9f1
// declared property setter: - (void)setSubtitle:(id)subtitle;	// 0xebca5
// declared property getter: - (id)title;	// 0xeba01
@end
