/**
 * This header is generated by class-dump-z 0.2b.
 *
 * Source: (null)
 */

#import "SpringBoard-Structs.h"
#import "SBUnknownSuperclass.h"


@interface SBShowcaseContext : SBUnknownSuperclass {
	int _appOrientation;	// 4 = 0x4
	int _showcaseOrientation;	// 8 = 0x8
	CGAffineTransform _portraitRelativeViewTransform;	// 12 = 0xc
	CGAffineTransform _currentReleativeViewTransform;	// 36 = 0x24
	BOOL _onSpringBoard;	// 60 = 0x3c
	BOOL _onApp;	// 61 = 0x3d
	float _offset;	// 64 = 0x40
}
@property(assign, nonatomic) int appOrientation;	// G=0x134b9; S=0x134c9; @synthesize=_appOrientation
@property(assign, nonatomic) int showcaseOrientation;	// G=0x13499; S=0x134a9; @synthesize=_showcaseOrientation
@property(assign, nonatomic) CGAffineTransform portraitRelativeViewTransform;	// G=0x1343d; S=0x1346d; @synthesize=_portraitRelativeViewTransform
@property(assign, nonatomic) CGAffineTransform currentReleativeViewTransform;	// G=0x133e1; S=0x13411; @synthesize=_currentReleativeViewTransform
@property(assign, nonatomic) BOOL onSpringBoard;	// G=0x133c1; S=0x133d1; @synthesize=_onSpringBoard
@property(assign, nonatomic) BOOL onApp;	// G=0x133a1; S=0x133b1; @synthesize=_onApp
@property(assign, nonatomic) float offset;	// G=0x13381; S=0x13391; @synthesize=_offset
// declared property getter: - (float)offset;	// 0x13381
// declared property setter: - (void)setOffset:(float)offset;	// 0x13391
// declared property getter: - (BOOL)onApp;	// 0x133a1
// declared property setter: - (void)setOnApp:(BOOL)app;	// 0x133b1
// declared property getter: - (BOOL)onSpringBoard;	// 0x133c1
// declared property setter: - (void)setOnSpringBoard:(BOOL)board;	// 0x133d1
// declared property getter: - (CGAffineTransform)currentReleativeViewTransform;	// 0x133e1
// declared property setter: - (void)setCurrentReleativeViewTransform:(CGAffineTransform)transform;	// 0x13411
// declared property getter: - (CGAffineTransform)portraitRelativeViewTransform;	// 0x1343d
// declared property setter: - (void)setPortraitRelativeViewTransform:(CGAffineTransform)transform;	// 0x1346d
// declared property getter: - (int)showcaseOrientation;	// 0x13499
// declared property setter: - (void)setShowcaseOrientation:(int)orientation;	// 0x134a9
// declared property getter: - (int)appOrientation;	// 0x134b9
// declared property setter: - (void)setAppOrientation:(int)orientation;	// 0x134c9
@end
