/**
 * This header is generated by class-dump-z 0.2b.
 *
 * Source: (null)
 */

#import "SBUnknownSuperclass.h"

@class SBProxyRemoteView, SBApplication;

@interface SBSheetView : SBUnknownSuperclass {
	SBProxyRemoteView *_remoteProxyView;	// 48 = 0x30
	SBApplication *_app;	// 52 = 0x34
	BOOL _wasPresentedAnimated;	// 56 = 0x38
}
@property(readonly, assign) BOOL wasPresentedAnimated;	// G=0xe16e5; converted property
- (id)initWithRemoteViewIdentifier:(id)remoteViewIdentifier application:(id)application wasPresentedAnimated:(BOOL)animated;	// 0xe1759
- (id)remoteViewIdentifier;	// 0xe16f5
- (id)application;	// 0xe16d5
// converted property getter: - (BOOL)wasPresentedAnimated;	// 0xe16e5
- (void)noteSheetDidEnd;	// 0xe1715
- (void)dealloc;	// 0xe1899
@end
