/**
 * This header is generated by class-dump-z 0.2b.
 *
 * Source: (null)
 */

#import "SBUnknownSuperclass.h"


@interface SBSIMLockAlertItem : SBUnknownSuperclass {
	int _status;	// 16 = 0x10
	int _okButtonIndex;	// 20 = 0x14
	int _unlockButtonIndex;	// 24 = 0x18
}
@property(readonly, assign) int status;	// G=0x99169; converted property
+ (id)alertTitleForStatus:(int)status languageCode:(id)code;	// 0x991e9
+ (id)alertTitleForStatus:(int)status;	// 0x991d5
- (id)initWithStatus:(int)status;	// 0x9917d
- (void)_resetButtonIndexes;	// 0x99145
- (void)dealloc;	// 0x999b1
- (BOOL)canUnlock;	// 0x9995d
- (id)alertTitleForLanguageCode:(id)languageCode;	// 0x99921
- (id)alertTextForLanguageCode:(id)languageCode;	// 0x997e9
// converted property getter: - (int)status;	// 0x99169
- (void)didDeactivateForReason:(int)reason;	// 0x99785
- (void)unlock;	// 0x99741
- (void)alertView:(id)view clickedButtonAtIndex:(int)index;	// 0x996d1
- (void)performUnlockAction;	// 0x99675
- (void)configure:(BOOL)configure requirePasscodeForActions:(BOOL)actions;	// 0x99455
- (id)lockLabel;	// 0x993fd
- (BOOL)forcesModalAlertAppearance;	// 0x993a9
- (BOOL)allowInSetup;	// 0x99369
- (BOOL)pendInSetupIfNotAllowed;	// 0x99179
- (BOOL)reappearsAfterUnlock;	// 0x992f5
- (BOOL)reappearsAfterLock;	// 0x99281
@end
