/**
 * This header is generated by class-dump-z 0.2b.
 *
 * Source: (null)
 */

#import "SpringBoard-Structs.h"
#import "SBSIMLockEntryAlertDisplay.h"

@class NSString;

@interface SBSIMLockPUKEntryAlertDisplay : SBSIMLockEntryAlertDisplay {
	int _state;	// 112 = 0x70
	NSString *_enteredPUKCode;	// 116 = 0x74
	NSString *_newPIN;	// 120 = 0x78
}
- (void)dealloc;	// 0x9aee5
- (id)_pukAttemptsRemainingLabel;	// 0x9a91d
- (void)setupSuccess;	// 0x9aa0d
- (id)titleText;	// 0x9aaa9
- (void)setupFailureState;	// 0x9ab19
- (id)label;	// 0x9ac19
- (void)_attemptPUKUnlock;	// 0x9af45
- (void)unlock;	// 0x9ac81
@end

