/**
 * This header is generated by class-dump-z 0.2b.
 *
 * Source: (null)
 */

#import "SpringBoard-Structs.h"
#import "SBAlert.h"


@interface SBSIMLockEntryAlert : SBAlert {
	int _status;	// 60 = 0x3c
}
@property(readonly, assign) int status;	// G=0x99b01; converted property
- (id)init;	// 0x99d09
- (id)alertDisplayViewWithSize:(CGSize)size;	// 0x99b4d
// converted property getter: - (int)status;	// 0x99b01
- (void)activate;	// 0x99a5d
- (void)deactivate;	// 0x99a89
@end

