/**
 * This header is generated by class-dump-z 0.2b.
 *
 * Source: (null)
 */

#import "SBUnknownSuperclass.h"
#import "SpringBoard-Structs.h"

@class UIImageView;

@interface SBSlidingViewHighlight : SBUnknownSuperclass {
	UIImageView *_leftHighlight;	// 48 = 0x30
	UIImageView *_rightHighlight;	// 52 = 0x34
	CGRect _notchRect;	// 56 = 0x38
}
+ (float)defaultHeight;	// 0x11d4dd
+ (id)highlightImage;	// 0x11d645
- (id)initWithFrame:(CGRect)frame;	// 0x11d4e5
- (id)initWithFrame:(CGRect)frame notchRect:(CGRect)rect;	// 0x11d565
- (void)layoutSubviews;	// 0x11d789
- (void)setNotchRect:(CGRect)rect;	// 0x11d52d
- (void)dealloc;	// 0x11d729
@end
