/**
 * This header is generated by class-dump-z 0.2b.
 *
 * Source: (null)
 */

#import "SpringBoard-Structs.h"
#import "SBApplication.h"


@interface SBSMSApplication : SBApplication {
}
- (id)activationValue:(unsigned)value;	// 0xc3431
@end

