/**
 * This header is generated by class-dump-z 0.2b.
 *
 * Source: (null)
 */

#import "SBUSSDAlert.h"


@interface SBSMSClass0Alert : SBUSSDAlert {
}
+ (void)registerForAlerts;	// 0x8a779
+ (BOOL)shouldPlayMessageReceived;	// 0x8a5cd
+ (void)playMessageReceived;	// 0x8a729
+ (void)defaultAlertTonePrefChanged;	// 0x8a631
- (void)_unregisterForNotifications;	// 0x8a5c5
- (void)_registerForNotifications;	// 0x8a5c9
- (id)initWithString:(id)string;	// 0x8a5e5
- (void)deactivate;	// 0x8a7fd
@end

