/**
 * This header is generated by class-dump-z 0.2b.
 *
 * Source: (null)
 */

#import "SBBaseSoftwareUpdateAlertItem.h"


@interface SBSoftwareUpdateAvailableAlertItem : SBBaseSoftwareUpdateAlertItem {
}
- (void)alertView:(id)view clickedButtonAtIndex:(int)index;	// 0x16b389
- (void)configure:(BOOL)configure requirePasscodeForActions:(BOOL)actions;	// 0x16b3bd
- (BOOL)reappearsAfterUnlock;	// 0x16b381
- (BOOL)dismissOnLock;	// 0x16b385
@end

