/**
 * This header is generated by class-dump-z 0.2b.
 *
 * Source: (null)
 */

#import "SBBaseSoftwareUpdateAlertItem.h"

@class NSError;

@interface SBSoftwareUpdateDownloadFailedAlertItem : SBBaseSoftwareUpdateAlertItem {
	NSError *_error;	// 20 = 0x14
}
@property(retain, nonatomic) NSError *error;	// G=0x16c731; S=0x16cb85; @synthesize=_error
- (void)dealloc;	// 0x16cb39
- (void)alertView:(id)view clickedButtonAtIndex:(int)index;	// 0x16c741
- (void)configure:(BOOL)configure requirePasscodeForActions:(BOOL)actions;	// 0x16c7d5
// declared property getter: - (id)error;	// 0x16c731
// declared property setter: - (void)setError:(id)error;	// 0x16cb85
@end

