/**
 * This header is generated by class-dump-z 0.2b.
 *
 * Source: (null)
 */

#import "SBBaseSoftwareUpdateAlertItem.h"


@interface SBSoftwareUpdateVerificationFailedAlertItem : SBBaseSoftwareUpdateAlertItem {
}
- (void)alertView:(id)view clickedButtonAtIndex:(int)index;	// 0x1a3af5
- (void)configure:(BOOL)configure requirePasscodeForActions:(BOOL)actions;	// 0x1a3b41
- (BOOL)reappearsAfterLock;	// 0x1a3ae1
- (BOOL)undimsScreen;	// 0x1a3ae5
- (BOOL)shouldShowInLockScreen;	// 0x1a3ae9
- (BOOL)allowMenuButtonDismissal;	// 0x1a3aed
- (BOOL)dismissOnLock;	// 0x1a3af1
@end

