/**
 * This header is generated by class-dump-z 0.2b.
 *
 * Source: (null)
 */

#import "SBSoundPreferences.h"
#import "SBUnknownSuperclass.h"


@interface SBSoundPreferences : SBUnknownSuperclass {
}
+ (void)userDefaultsDidChanged:(id)userDefaults;	// 0x838b1
+ (id)calendarAlarmPath;	// 0x8396d
+ (id)ringtoneIdentifier;	// 0x839b9
+ (id)ringtonePath;	// 0x839f9
+ (BOOL)playLockSound;	// 0x83c69
+ (id)vibratePattern;	// 0x83b5d
+ (BOOL)vibrateWhenRinging;	// 0x83b09
+ (BOOL)vibrateWhenSilent;	// 0x83ab5
+ (BOOL)shouldVibrateForCurrentRingerState;	// 0x83a5d
@end

@interface SBSoundPreferences (Private)
+ (void)_loadDefaultsIfNeeded;	// 0x83cbd
@end
