/**
 * This header is generated by class-dump-z 0.2b.
 *
 * Source: (null)
 */

#import "SpringBoard-Structs.h"
#import "SBUnknownSuperclass.h"


@interface SBSpringBoardMetaHostingWindow : SBUnknownSuperclass {
}
- (BOOL)_isWindowServerHostingManaged;	// 0x5025
- (id)hitTest:(CGPoint)test withEvent:(id)event;	// 0x12691
@end
