/**
 * This header is generated by class-dump-z 0.2b.
 *
 * Source: (null)
 */

#import "SBPhraseInterpretation.h"

@class NSArray;

@interface SBSpeechTokenInterpretation : SBPhraseInterpretation {
	NSArray *_speechTokens;	// 8 = 0x8
}
- (id)initWithSpeechTokens:(id)speechTokens;	// 0x192da5
- (BOOL)removeSpaceBefore;	// 0x192b41
- (BOOL)removeSpaceAfter;	// 0x192b95
- (void)dealloc;	// 0x192be9
- (id)text;	// 0x192c35
@end

