/**
 * This header is generated by class-dump-z 0.2b.
 *
 * Source: (null)
 */

#import "SBUnknownSuperclass.h"
#import "RadiosPreferencesDelegate.h"

@class RadiosPreferences, NSString, NSDateFormatter, NSTimer;

@interface SBStatusBarDataManager : SBUnknownSuperclass <RadiosPreferencesDelegate> {
	struct {
		BOOL itemIsEnabled[23];
		BOOL timeString[64];
		int gsmSignalStrengthRaw;
		int gsmSignalStrengthBars;
		BOOL serviceString[100];
		BOOL serviceCrossfadeString[100];
		BOOL serviceImages[3][100];
		BOOL operatorDirectory[1024];
		unsigned serviceContentType;
		int wifiSignalStrengthRaw;
		int wifiSignalStrengthBars;
		unsigned dataNetworkType;
		int batteryCapacity;
		unsigned batteryState;
		BOOL notChargingString[150];
		int bluetoothBatteryCapacity;
		int thermalColor;
		unsigned thermalSunlightMode : 1;
		unsigned slowActivity : 1;
		unsigned syncActivity : 1;
		BOOL activityDisplayId[256];
		unsigned bluetoothConnected : 1;
		unsigned displayRawGSMSignal : 1;
		unsigned displayRawWifiSignal : 1;
	} _data;	// 4 = 0x4
	int _actions;	// 2068 = 0x814
	BOOL _itemIsEnabled[23];	// 2072 = 0x818
	BOOL _itemIsCloaked[23];	// 2095 = 0x82f
	BOOL _telephonyAndBluetoothCloaked;	// 2118 = 0x846
	BOOL _allButBatteryCloaked;	// 2119 = 0x847
	BOOL _timeCloaked;	// 2120 = 0x848
	int _updateBlockDepth;	// 2124 = 0x84c
	BOOL _dataChangedSinceLastPost;	// 2128 = 0x850
	NSDateFormatter *_timeItemDateFormatter;	// 2132 = 0x854
	NSTimer *_timeItemTimer;	// 2136 = 0x858
	NSString *_timeItemTimeString;	// 2140 = 0x85c
	RadiosPreferences *_radiosPrefs;	// 2144 = 0x860
	BOOL _simulateInCallStatusBar;	// 2148 = 0x864
	NSString *_serviceString;	// 2152 = 0x868
	NSString *_serviceCrossfadeString;	// 2156 = 0x86c
	NSString *_serviceImages[3];	// 2160 = 0x870
	NSString *_operatorDirectory;	// 2172 = 0x87c
	BOOL _showsActivityIndicatorOnHomeScreen;	// 2176 = 0x880
	int _syncActivityIndicatorCount;	// 2180 = 0x884
	int _activityIndicatorEverywhereCount;	// 2184 = 0x888
	int _thermalColor;	// 2188 = 0x88c
	BOOL _thermalSunlightMode;	// 2192 = 0x890
	NSString *_recordingAppString;	// 2196 = 0x894
	BOOL _showingNotChargingItem;	// 2200 = 0x898
	NSString *_notChargingString;	// 2204 = 0x89c
}
+ (id)sharedDataManager;	// 0xf6ad9
- (id)init;	// 0xf69e1
- (void)dealloc;	// 0xf99f1
- (void)beginUpdateBlock;	// 0xf69cd
- (void)endUpdateBlock;	// 0xf9929
- (void)setStatusBarItem:(int)item enabled:(BOOL)enabled;	// 0xf98ed
- (void)updateStatusBarItem:(int)item;	// 0xf9895
- (void)sendStatusBarActions:(int)actions;	// 0xf9871
- (void)enableLock:(BOOL)lock time:(BOOL)time;	// 0xf9811
- (void)setShowsActivityIndicatorOnHomeScreen:(BOOL)screen;	// 0xf97f1
- (void)setShowsActivityIndicatorEverywhere:(BOOL)everywhere;	// 0xf97bd
- (void)setShowsSyncActivityIndicator:(BOOL)indicator;	// 0xf9789
- (void)_updateCloakedItems;	// 0xf96a9
- (void)setTelephonyAndBluetoothItemsCloaked:(BOOL)cloaked;	// 0xf9689
- (void)setAllItemsExceptBatteryCloaked:(BOOL)cloaked;	// 0xf9669
- (void)setTimeCloaked:(BOOL)cloaked;	// 0xf9649
- (void)setThermalColor:(int)color sunlightMode:(BOOL)mode;	// 0xf9619
- (void)_initializeData;	// 0xf95a9
- (void)_dataChanged;	// 0xf956d
- (void)_postData;	// 0xf94c5
- (void)_updateTimeString;	// 0xf939d
- (void)_updateTimeItem;	// 0xf9371
- (void)_updateAirplaneMode;	// 0xf9321
- (void)_updateSignalStrengthItem;	// 0xf9149
- (void)_updateServiceItem;	// 0xf8bd1
- (void)_updateDataNetworkItem;	// 0xf89c1
- (void)_updateBatteryItem;	// 0xf88a1
- (void)_updateBatteryPercentItem;	// 0xf870d
- (void)_updateNotChargingItem;	// 0xf85d1
- (void)_updateBluetoothItem;	// 0xf8491
- (void)_updateBluetoothBatteryItem;	// 0xf83b9
- (void)_updateTTYItem;	// 0xf8379
- (void)_updateVPNItem;	// 0xf8305
- (void)_updateCallForwardingItem;	// 0xf82a9
- (void)_updateActivityItem;	// 0xf8029
- (void)_updatePlayItem;	// 0xf7ec9
- (void)_updateLocationItem;	// 0xf7e7d
- (void)_updateRotationLockItem;	// 0xf7e31
- (void)_updateThermalColorItem;	// 0xf7d91
- (void)_registerForNotifications;	// 0xf78c9
- (void)_significantTimeOrLocaleChange;	// 0xf78b5
- (void)_didWakeFromSleep;	// 0xf7875
- (void)_batteryStatusChange;	// 0xf7829
- (void)_notChargingStatusChange;	// 0xf7791
- (void)_operatorChange;	// 0xf7745
- (void)_signalStrengthChange;	// 0xf7731
- (void)_ttyChange;	// 0xf771d
- (void)_callForwardingChange;	// 0xf7709
- (void)_vpnChange;	// 0xf76f5
- (void)_dataNetworkChange;	// 0xf76a9
- (void)_dataConnectionTypeChange;	// 0xf7659
- (void)airplaneModeChanged;	// 0xf7569
- (void)_bluetoothChange;	// 0xf7555
- (void)_bluetoothBatteryChange;	// 0xf7541
- (void)_locationStatusChange;	// 0xf752d
- (void)_rotationLockChange;	// 0xf7519
- (void)_configureTimeItemDateFormatter;	// 0xf740d
- (void)_stopTimeItemTimer;	// 0xf73cd
- (void)_restartTimeItemTimer;	// 0xf72dd
- (BOOL)_shouldShowNotChargingItem;	// 0xf7269
- (void)_updateNotChargingItemAfterDelay;	// 0xf7255
- (void)_updateTelephonyState;	// 0xf71ed
- (void)toggleSimulatesInCallStatusBar;	// 0xf7195
- (BOOL)_simStatusMeansLocked:(id)locked;	// 0xf7149
- (id)_displayStringForSIMStatus:(id)simstatus;	// 0xf6ff9
- (id)_displayStringForRegistrationStatus:(int)registrationStatus;	// 0xf6f4d
- (BOOL)_getServiceImageNames:(id [3])names directory:(id *)directory forOperator:(id)anOperator statusBarCarrierName:(id *)name;	// 0xf6c3d
- (BOOL)_shouldShowEmergencyOnlyStatus;	// 0xf6bad
@end
