/**
 * This header is generated by class-dump-z 0.2b.
 *
 * Source: (null)
 */

#import "SBUnknownSuperclass.h"
#import "SpringBoard-Structs.h"


@interface SBSwitcherSlider : SBUnknownSuperclass {
}
- (id)initWithFrame:(CGRect)frame;	// 0x12ba35
- (BOOL)pointInside:(CGPoint)inside withEvent:(id)event;	// 0x12bcc5
- (CGRect)trackRectForBounds:(CGRect)bounds;	// 0x12bc59
- (CGRect)thumbRectForBounds:(CGRect)bounds trackRect:(CGRect)rect value:(float)value;	// 0x12bb35
- (UIEdgeInsets)_thumbHitEdgeInsets;	// 0x12ba05
@end
