/**
 * This header is generated by class-dump-z 0.2b.
 *
 * Source: (null)
 */

#import "SBUnknownSuperclass.h"

@class UIView, SBStretchTransformer, SBApplication;

@interface SBSwitchAppGestureView : SBUnknownSuperclass {
	int m_orientation;	// 48 = 0x30
	SBApplication *m_startingApp;	// 52 = 0x34
	SBApplication *m_endingApp;	// 56 = 0x38
	SBApplication *m_leftwardApp;	// 60 = 0x3c
	SBApplication *m_rightwardApp;	// 64 = 0x40
	int m_startingViewOrientation;	// 68 = 0x44
	int m_leftwardViewOrientation;	// 72 = 0x48
	int m_rightwardViewOrientation;	// 76 = 0x4c
	UIView *m_startingView;	// 80 = 0x50
	UIView *m_leftwardView;	// 84 = 0x54
	UIView *m_rightwardView;	// 88 = 0x58
	float m_pageWidth;	// 92 = 0x5c
	float m_percentage;	// 96 = 0x60
	float m_contentOffset;	// 100 = 0x64
	SBStretchTransformer *m_stretchTransformer;	// 104 = 0x68
	BOOL m_finishingPaging;	// 108 = 0x6c
	BOOL m_underflowing;	// 109 = 0x6d
	BOOL m_overflowing;	// 110 = 0x6e
	id m_completion;	// 112 = 0x70
}
@property(assign, nonatomic) int orientation;	// G=0x16f351; S=0x16f361; @synthesize=m_orientation
@property(retain, nonatomic) SBApplication *startingApp;	// G=0x16f341; S=0x16fff5; @synthesize=m_startingApp
@property(retain, nonatomic) SBApplication *endingApp;	// G=0x16f331; S=0x17001d; @synthesize=m_endingApp
@property(retain, nonatomic) SBApplication *leftwardApp;	// G=0x16f321; S=0x170045; @synthesize=m_leftwardApp
@property(retain, nonatomic) SBApplication *rightwardApp;	// G=0x16f311; S=0x17006d; @synthesize=m_rightwardApp
@property(retain, nonatomic) UIView *startingView;	// G=0x16f301; S=0x170095; @synthesize=m_startingView
@property(retain, nonatomic) UIView *leftwardView;	// G=0x16f2f1; S=0x1700bd; @synthesize=m_leftwardView
@property(retain, nonatomic) UIView *rightwardView;	// G=0x16f2e1; S=0x1700e5; @synthesize=m_rightwardView
@property(assign, nonatomic) int startingViewOrientation;	// G=0x16f2c1; S=0x16f2d1; @synthesize=m_startingViewOrientation
@property(assign, nonatomic) int leftwardViewOrientation;	// G=0x16f2a1; S=0x16f2b1; @synthesize=m_leftwardViewOrientation
@property(assign, nonatomic) int rightwardViewOrientation;	// G=0x16f281; S=0x16f291; @synthesize=m_rightwardViewOrientation
@property(assign, nonatomic) float pageWidth;	// G=0x16f261; S=0x16f271; @synthesize=m_pageWidth
@property(assign, nonatomic) float percentage;	// G=0x16f241; S=0x16f251; @synthesize=m_percentage
@property(assign, nonatomic) float contentOffset;	// G=0x16f221; S=0x16f231; @synthesize=m_contentOffset
@property(retain, nonatomic) SBStretchTransformer *stretchTransformer;	// G=0x16f211; S=0x17010d; @synthesize=m_stretchTransformer
@property(assign, nonatomic) BOOL underflowing;	// G=0x16f1f1; S=0x16f201; @synthesize=m_underflowing
@property(assign, nonatomic) BOOL overflowing;	// G=0x16f1d1; S=0x16f1e1; @synthesize=m_overflowing
@property(copy, nonatomic) id completion;	// G=0x16f1c1; S=0x170135; @synthesize=m_completion
@property(readonly, assign, nonatomic) BOOL pagingRightward;	// G=0x16fced; 
@property(readonly, assign, nonatomic) BOOL pagingLeftward;	// G=0x16fcc5; 
- (id)initWithInterfaceOrientation:(int)interfaceOrientation startingApp:(id)app leftwardApp:(id)app3 rightwardApp:(id)app4;	// 0x16fe1d
- (void)dealloc;	// 0x17110d
- (void)transformGestureViewContainer:(id)container;	// 0x170f85
- (id)viewForApp:(id)app;	// 0x16fd15
- (void)beginPaging;	// 0x170d15
- (void)updatePaging:(float)paging;	// 0x16f371
- (void)finishForwardToEndWithPercentage:(float)percentage completion:(id)completion;	// 0x16f6f1
- (void)finishBackwardToStartWithCompletion:(id)completion;	// 0x16f901
- (float)contentOffsetForApp:(id)app;	// 0x16fad9
- (float)percentageForApp:(id)app;	// 0x16fb79
- (float)scaleForPercentage:(float)percentage;	// 0x16f081
- (float)opacityForPercentage:(float)percentage;	// 0x16f121
- (void)moveToApp:(id)app;	// 0x16fbdd
- (void)moveToApp:(id)app animated:(BOOL)animated;	// 0x16fbf1
- (void)moveToContentOffset:(float)contentOffset percentage:(float)percentage animated:(BOOL)animated;	// 0x170319
- (void)animationDidStop:(id)animation finished:(BOOL)finished;	// 0x170249
- (void)stretchTransformerAnimationDidStop:(BOOL)stretchTransformerAnimation;	// 0x170159
- (BOOL)isPagingUnderflowPercentage:(float)percentage;	// 0x16fc5d
- (BOOL)isPagingOverflowPercentage:(float)percentage;	// 0x16fc91
// declared property getter: - (BOOL)pagingLeftward;	// 0x16fcc5
// declared property getter: - (BOOL)pagingRightward;	// 0x16fced
// declared property getter: - (id)completion;	// 0x16f1c1
// declared property setter: - (void)setCompletion:(id)completion;	// 0x170135
// declared property getter: - (BOOL)overflowing;	// 0x16f1d1
// declared property setter: - (void)setOverflowing:(BOOL)overflowing;	// 0x16f1e1
// declared property getter: - (BOOL)underflowing;	// 0x16f1f1
// declared property setter: - (void)setUnderflowing:(BOOL)underflowing;	// 0x16f201
// declared property getter: - (id)stretchTransformer;	// 0x16f211
// declared property setter: - (void)setStretchTransformer:(id)transformer;	// 0x17010d
// declared property getter: - (float)contentOffset;	// 0x16f221
// declared property setter: - (void)setContentOffset:(float)offset;	// 0x16f231
// declared property getter: - (float)percentage;	// 0x16f241
// declared property setter: - (void)setPercentage:(float)percentage;	// 0x16f251
// declared property getter: - (float)pageWidth;	// 0x16f261
// declared property setter: - (void)setPageWidth:(float)width;	// 0x16f271
// declared property getter: - (int)rightwardViewOrientation;	// 0x16f281
// declared property setter: - (void)setRightwardViewOrientation:(int)orientation;	// 0x16f291
// declared property getter: - (int)leftwardViewOrientation;	// 0x16f2a1
// declared property setter: - (void)setLeftwardViewOrientation:(int)orientation;	// 0x16f2b1
// declared property getter: - (int)startingViewOrientation;	// 0x16f2c1
// declared property setter: - (void)setStartingViewOrientation:(int)orientation;	// 0x16f2d1
// declared property getter: - (id)rightwardView;	// 0x16f2e1
// declared property setter: - (void)setRightwardView:(id)view;	// 0x1700e5
// declared property getter: - (id)leftwardView;	// 0x16f2f1
// declared property setter: - (void)setLeftwardView:(id)view;	// 0x1700bd
// declared property getter: - (id)startingView;	// 0x16f301
// declared property setter: - (void)setStartingView:(id)view;	// 0x170095
// declared property getter: - (id)rightwardApp;	// 0x16f311
// declared property setter: - (void)setRightwardApp:(id)app;	// 0x17006d
// declared property getter: - (id)leftwardApp;	// 0x16f321
// declared property setter: - (void)setLeftwardApp:(id)app;	// 0x170045
// declared property getter: - (id)endingApp;	// 0x16f331
// declared property setter: - (void)setEndingApp:(id)app;	// 0x17001d
// declared property getter: - (id)startingApp;	// 0x16f341
// declared property setter: - (void)setStartingApp:(id)app;	// 0x16fff5
// declared property getter: - (int)orientation;	// 0x16f351
// declared property setter: - (void)setOrientation:(int)orientation;	// 0x16f361
@end
