/**
 * This header is generated by class-dump-z 0.2b.
 *
 * Source: (null)
 */

#import "SBUnknownSuperclass.h"
#import "SpringBoard-Structs.h"
#import "UIWindowDelegate.h"

@class UIWindow, UIView;
@protocol SBSwitcherPopoverWindowControllerDelegate;

@interface SBSwitcherPopoverWindowController : SBUnknownSuperclass <UIWindowDelegate> {
	UIWindow *_popoverWindow;	// 4 = 0x4
	UIView *_popoverRootView;	// 8 = 0x8
	BOOL _popoverVisible;	// 12 = 0xc
	id _delegate;	// 16 = 0x10
}
@property(readonly, assign, nonatomic) UIView *rootView;	// G=0x12c059; @synthesize=_popoverRootView
@property(assign, nonatomic) id<SBSwitcherPopoverWindowControllerDelegate> delegate;	// G=0x12c039; S=0x12c049; @synthesize=_delegate
@property(readonly, assign, nonatomic) BOOL popoverVisible;	// G=0x12c029; @synthesize=_popoverVisible
@property(readonly, assign, nonatomic) UIWindow *window;	// G=0x12c621; 
+ (id)sharedInstance;	// 0x12c18d
- (void)dealloc;	// 0x12c801
// declared property getter: - (id)rootView;	// 0x12c059
// declared property getter: - (id)window;	// 0x12c621
- (void)prepareAndPresentPopoverForFrame:(CGRect)frame inView:(id)view delegate:(id)delegate withPresentationBlock:(id)presentationBlock;	// 0x12c3b9
- (void)rotatePopoverWindowToOrientation:(int)orientation;	// 0x12c235
- (void)cleanupPopover;	// 0x12c1d5
- (void)willRotateToOrientation:(int)orientation;	// 0x12c0fd
- (void)didRotateFromOrientation:(int)orientation;	// 0x12c159
// declared property getter: - (BOOL)popoverVisible;	// 0x12c029
// declared property getter: - (id)delegate;	// 0x12c039
// declared property setter: - (void)setDelegate:(id)delegate;	// 0x12c049
@end
