/**
 * This header is generated by class-dump-z 0.2b.
 *
 * Source: (null)
 */

#import "SBUnknownSuperclass.h"

@class NSString, NSTimer, SBApplication;
@protocol SBSystemLocalNotificationAlertDelegate;

@interface SBSystemLocalNotificationAlert : SBUnknownSuperclass {
	id<SBSystemLocalNotificationAlertDelegate> _delegate;	// 16 = 0x10
	SBApplication *_app;	// 20 = 0x14
	NSString *_body;	// 24 = 0x18
	NSString *_actionLabel;	// 28 = 0x1c
	NSString *_customLockLabel;	// 32 = 0x20
	NSString *_alertLaunchImage;	// 36 = 0x24
	BOOL _showActionButton;	// 40 = 0x28
	BOOL _hideTitle;	// 41 = 0x29
	BOOL _allowSnooze;	// 42 = 0x2a
	NSTimer *_ringtoneAutoMuteTimer;	// 44 = 0x2c
	unsigned _launchButtonIndex;	// 48 = 0x30
	unsigned _snoozeButtonIndex;	// 52 = 0x34
	id _context;	// 56 = 0x38
}
@property(assign, nonatomic) id<SBSystemLocalNotificationAlertDelegate> delegate;	// G=0x183ed1; S=0x183ee1; @synthesize=_delegate
@property(assign, nonatomic) BOOL hideTitle;	// G=0x183eb1; S=0x183ec1; @synthesize=_hideTitle
@property(assign, nonatomic) BOOL allowSnooze;	// G=0x183e91; S=0x183ea1; @synthesize=_allowSnooze
@property(retain, nonatomic) NSString *customLockLabel;	// G=0x183e81; S=0x184ca5; @synthesize=_customLockLabel
@property(retain, nonatomic) NSString *alertLaunchImage;	// G=0x183e71; S=0x184ccd; @synthesize=_alertLaunchImage
@property(retain, nonatomic) id context;	// G=0x183e61; S=0x184cf5; @synthesize=_context
@property(readonly, assign, nonatomic) SBApplication *application;	// G=0x183e51; @synthesize=_app
+ (id)presentWithLocalNotification:(id)localNotification application:(id)application;	// 0x1848bd
+ (id)localizedStringFromKey:(id)key defaultValue:(id)value inBundle:(id)bundle arguments:(id)arguments;	// 0x18478d
+ (id)alertMatchingContext:(id)context;	// 0x184665
+ (void)playAlertSound:(BOOL)sound soundName:(id)name inBundle:(id)bundle isRingtone:(BOOL)ringtone sandboxPath:(id)path;	// 0x184045
+ (BOOL)isPlayingRingtone;	// 0x183e35
+ (void)stopPlayingAlertSoundOrRingtone;	// 0x183f4d
- (id)initWithApplication:(id)application body:(id)body showActionButton:(BOOL)button actionLabel:(id)label;	// 0x1858a1
- (void)dealloc;	// 0x1857a9
- (Class)alertSheetClass;	// 0x18578d
- (void)configure:(BOOL)configure requirePasscodeForActions:(BOOL)actions;	// 0x18541d
- (id)lockLabel;	// 0x1852ad
- (float)lockLabelFontSize;	// 0x183f01
- (BOOL)shouldShowInEmergencyCall;	// 0x183e31
- (void)alertView:(id)view clickedButtonAtIndex:(int)index;	// 0x1851f9
- (void)performUnlockAction;	// 0x1851ad
- (void)willDeactivateForReason:(int)reason;	// 0x185121
- (void)snoozeIfPossible;	// 0x1850f5
- (void)snoozeOrDismiss;	// 0x185075
- (void)dismiss:(int)dismiss;	// 0x184fad
- (void)startRingtoneAutoMuteTimer;	// 0x184e7d
- (void)_ringtoneAutoMuteTimerFired;	// 0x184e31
- (void)stopRingtoneAutoMuteTimer;	// 0x184db1
- (int)alertItemNotificationType;	// 0x183e4d
- (id)alertItemNotificationSender;	// 0x184d91
- (int)alertPriority;	// 0x184d1d
// declared property getter: - (id)application;	// 0x183e51
// declared property getter: - (id)context;	// 0x183e61
// declared property setter: - (void)setContext:(id)context;	// 0x184cf5
// declared property getter: - (id)alertLaunchImage;	// 0x183e71
// declared property setter: - (void)setAlertLaunchImage:(id)image;	// 0x184ccd
// declared property getter: - (id)customLockLabel;	// 0x183e81
// declared property setter: - (void)setCustomLockLabel:(id)label;	// 0x184ca5
// declared property getter: - (BOOL)allowSnooze;	// 0x183e91
// declared property setter: - (void)setAllowSnooze:(BOOL)snooze;	// 0x183ea1
// declared property getter: - (BOOL)hideTitle;	// 0x183eb1
// declared property setter: - (void)setHideTitle:(BOOL)title;	// 0x183ec1
// declared property getter: - (id)delegate;	// 0x183ed1
// declared property setter: - (void)setDelegate:(id)delegate;	// 0x183ee1
@end
