/**
 * This header is generated by class-dump-z 0.2b.
 *
 * Source: (null)
 */

#import "SpringBoard-Structs.h"
#import "SBUnknownSuperclass.h"


@interface SBTetherController : SBUnknownSuperclass {
	int _tetherState;	// 4 = 0x4
	unsigned _demoCardConnection;	// 8 = 0x8
	int _lastOrientationCode;	// 12 = 0xc
	BOOL _orientationNotificationsDisabled;	// 16 = 0x10
}
@property(assign, nonatomic, getter=isOrientationNotificationDisabled) BOOL orientationNotificationDisabled;	// G=0xd31d9; S=0xd31e9; @synthesize=_orientationNotificationsDisabled
+ (id)sharedInstance;	// 0xd3261
- (id)init;	// 0xd4049
- (unsigned)_demoCardConnection;	// 0xd3f31
- (void)_postDisplayPortNotificationCode:(int)code;	// 0xd3ea5
- (void)_setTetherState:(int)state;	// 0xd3db5
- (BOOL)isTethered;	// 0xd3c29
- (BOOL)usesDisplayPortTethering;	// 0xd3221
- (void)_handleDemoModeChanged;	// 0xd3aa1
- (void)noteInterfaceOrientationChanged;	// 0xd3879
- (void)setDitheringEnabled:(int)enabled;	// 0xd37b5
- (BOOL)_serviceExists:(CFStringRef)exists;	// 0xd367d
- (BOOL)_reverseTetheringActive;	// 0xd3521
- (void)updatePreferencesIfNeeded;	// 0xd32e1
- (void)dealloc;	// 0xd32a9
// declared property getter: - (BOOL)isOrientationNotificationDisabled;	// 0xd31d9
// declared property setter: - (void)setOrientationNotificationDisabled:(BOOL)disabled;	// 0xd31e9
@end
