/**
 * This header is generated by class-dump-z 0.2b.
 *
 * Source: (null)
 */

#import "SpringBoard-Structs.h"
#import "SBUnknownSuperclass.h"

@class SBPolygon;

@interface SBTouchTemplate : SBUnknownSuperclass {
	SBPolygon *m_template;	// 4 = 0x4
	SBPolygon *m_candidate;	// 8 = 0x8
	unsigned m_transformType;	// 12 = 0xc
	float m_acceptFactor;	// 16 = 0x10
}
@property(assign, nonatomic) unsigned transformType;	// G=0x131729; S=0x131739; @synthesize=m_transformType
@property(assign, nonatomic) float acceptFactor;	// G=0x131709; S=0x131719; @synthesize=m_acceptFactor
@property(readonly, assign, nonatomic) unsigned pointCount;	// G=0x1319b1; 
- (id)initWithPoints:(CGPoint *)points count:(unsigned)count;	// 0x131749
- (void)dealloc;	// 0x1319d1
// declared property getter: - (unsigned)pointCount;	// 0x1319b1
- (BOOL)acceptPoints:(CGPoint *)points count:(unsigned)count;	// 0x1318d9
- (BOOL)acceptPolygon:(id)polygon;	// 0x131871
// declared property getter: - (float)acceptFactor;	// 0x131709
// declared property setter: - (void)setAcceptFactor:(float)factor;	// 0x131719
// declared property getter: - (unsigned)transformType;	// 0x131729
// declared property setter: - (void)setTransformType:(unsigned)type;	// 0x131739
@end
