/**
 * This header is generated by class-dump-z 0.2b.
 *
 * Source: (null)
 */

#import "SpringBoard-Structs.h"
#import "SBAlertDisplay.h"

@class UIView;

@interface SBUIFullscreenAlertViewAdapter : SBAlertDisplay {
	UIView *_alertView;	// 56 = 0x38
}
- (id)_alertAdapter;	// 0x12d8ad
- (id)initWithFrame:(CGRect)frame andContentView:(id)view;	// 0x12da45
- (void)dealloc;	// 0x12decd
- (BOOL)isReadyToBeRemovedFromView;	// 0x12d905
- (BOOL)displaysAboveStatusBar;	// 0x12d92d
- (void)alertDisplayWillBecomeVisible;	// 0x12d955
- (BOOL)shouldAnimateIconsIn;	// 0x12de7d
- (void)viewAnimatedOut;	// 0x12dd79
- (void)dismiss;	// 0x12dbe5
- (void)setShouldAnimateIn:(BOOL)animateIn;	// 0x12d9e9
- (void)alertWindowResizedFromContentFrame:(CGRect)contentFrame toContentFrame:(CGRect)contentFrame2;	// 0x12da15
- (void)willRotateToInterfaceOrientation:(int)interfaceOrientation duration:(double)duration;	// 0x12db79
- (void)willAnimateRotationToInterfaceOrientation:(int)interfaceOrientation duration:(double)duration;	// 0x12db0d
- (void)didRotateFromInterfaceOrientation:(int)interfaceOrientation;	// 0x12dab9
@end

