/**
 * This header is generated by class-dump-z 0.2b.
 *
 * Source: (null)
 */

#import "SpringBoard-Structs.h"
#import "SBUnknownSuperclass.h"


@interface SBUIRootView : SBUnknownSuperclass {
	BOOL _animatingAlpha;	// 46 = 0x2e
}
- (id)initWithFrame:(CGRect)frame;	// 0x159eb1
- (void)_actuallySetAlpha:(float)alpha;	// 0x159ba5
- (void)setAlpha:(float)alpha;	// 0x159c49
- (BOOL)_shouldAnimatePropertyWithKey:(id)key;	// 0x159be9
@end
