/**
 * This header is generated by class-dump-z 0.2b.
 *
 * Source: (null)
 */

#import "SBUnknownSuperclass.h"


@interface SBUserNotificationCenter : SBUnknownSuperclass {
}
+ (void)startUserNotificationCenter;	// 0x8f695
+ (void)_userNotificationDone:(id)done;	// 0x8fb35
@end
