/**
 * This header is generated by class-dump-z 0.2b.
 *
 * Source: (null)
 */

#import "SBApplicationIcon.h"


@interface SBUserInstalledApplicationIcon : SBApplicationIcon {
}
- (BOOL)allowsUninstall;	// 0xca11d
- (void)completeUninstall;	// 0xca1c5
- (BOOL)hasBeenSyncedBackToITunes;	// 0xca1fd
- (id)ratingsAlertTitle;	// 0xca28d
- (id)ratingsAlertBody;	// 0xca329
- (id)ratingsAlertSkipTitle;	// 0xca381
- (id)ratingsAlertRateButtonTitle;	// 0xca3d9
- (id)uninstallAlertTitle;	// 0xca431
- (id)uninstallAlertTitleForAppWithDocumentsInCloud;	// 0xca4cd
- (id)uninstallAlertTitleForAppWithDocumentUpdatesPending;	// 0xca569
- (id)uninstallAlertBody;	// 0xca605
- (id)uninstallAlertBodyForAppWithDocumentsInCloud;	// 0xca6a1
- (id)uninstallAlertBodyForAppWithDocumentUpdatesPending;	// 0xca76d
- (id)uninstallAlertConfirmTitle;	// 0xca809
- (id)uninstallAlertCancelTitle;	// 0xca861
@end

