/**
 * This header is generated by class-dump-z 0.2b.
 *
 * Source: (null)
 */

#import "SBUnknownSuperclass.h"

@class NSURL;

@interface SBVideoPermissionAlertItem : SBUnknownSuperclass {
	NSURL *_url;	// 16 = 0x10
}
- (id)initWithURL:(id)url;	// 0x121dc5
- (void)dealloc;	// 0x121ffd
- (void)alertView:(id)view clickedButtonAtIndex:(int)index;	// 0x121fad
- (void)configure:(BOOL)configure requirePasscodeForActions:(BOOL)actions;	// 0x121e1d
- (BOOL)shouldShowInLockScreen;	// 0x121db9
- (BOOL)dismissOnLock;	// 0x121dbd
- (BOOL)allowMenuButtonDismissal;	// 0x121dc1
@end
