/**
 * This header is generated by class-dump-z 0.2b.
 *
 * Source: (null)
 */

#import "SBVoiceControlAlertDisplay.h"


@interface SBVoiceControlMenuedAlertDisplay : SBVoiceControlAlertDisplay {
}
- (BOOL)_wasTriggeredByMenu;	// 0xd4919
@end

