/**
 * This header is generated by class-dump-z 0.2b.
 *
 * Source: (null)
 */

#import "SBHUDView.h"


@interface SBVolumeHUDView : SBHUDView {
	int _mode;	// 72 = 0x48
	BOOL _headphonesPresent;	// 76 = 0x4c
}
@property(assign, nonatomic) int mode;	// G=0x62275; S=0x637f5; @synthesize=_mode
@property(assign, nonatomic) BOOL headphonesPresent;	// G=0x62265; S=0x63835; @synthesize=_headphonesPresent
- (void)_updateImage;	// 0x622b9
- (void)_updateLabels;	// 0x634ad
- (id)init;	// 0x6379d
// declared property setter: - (void)setMode:(int)mode;	// 0x637f5
// declared property setter: - (void)setHeadphonesPresent:(BOOL)present;	// 0x63835
- (void)setProgress:(float)progress;	// 0x63865
// declared property getter: - (BOOL)headphonesPresent;	// 0x62265
// declared property getter: - (int)mode;	// 0x62275
@end

