/**
 * This header is generated by class-dump-z 0.2b.
 *
 * Source: (null)
 */

#import "SBUnknownSuperclass.h"


@interface SBVODController : SBUnknownSuperclass {
}
+ (id)sharedInstance;	// 0xc3231
- (id)init;	// 0xc31b9
- (void)dealloc;	// 0xc33bd
- (void)_launchIPodIfNecessary;	// 0xc3279
@end
