/**
 * This header is generated by class-dump-z 0.2b.
 *
 * Source: (null)
 */

#import "SBUnknownSuperclass.h"


@interface SBVoiceDisabledBundles : SBUnknownSuperclass {
}
+ (void)setAppDisabledVoiceControl:(BOOL)control bundleIdentifier:(id)identifier;	// 0x1a51cd
+ (BOOL)voiceControlDisabledByCurrentlyRunningApp;	// 0x1a5285
@end
