/**
 * This header is generated by class-dump-z 0.2b.
 *
 * Source: (null)
 */

#import "SBUnknownSuperclass.h"
#import "SpringBoard-Structs.h"

@class UIImageView;

@interface SBWallpaperView : SBUnknownSuperclass {
	int _orientation;	// 52 = 0x34
	int _variant;	// 56 = 0x38
	UIImageView *_topGradient;	// 60 = 0x3c
	UIImageView *_bottomGradient;	// 64 = 0x40
	BOOL _usesFilter;	// 68 = 0x44
	float _gradientAlpha;	// 72 = 0x48
	CGRect _wallpaperContentsRect;	// 76 = 0x4c
	BOOL _postsNotifications;	// 92 = 0x5c
	BOOL _flushWallpaperAutomatically;	// 93 = 0x5d
}
@property(assign, nonatomic) int orientation;	// G=0x112bb9; S=0x113269; @synthesize=_orientation
@property(readonly, assign, nonatomic) int variant;	// G=0x112ba9; @synthesize=_variant
@property(assign, nonatomic) float gradientAlpha;	// G=0x112b99; S=0x112d65; @synthesize=_gradientAlpha
@property(assign, nonatomic) BOOL postsNotifications;	// G=0x112b79; S=0x112b89; @synthesize=_postsNotifications
@property(assign, nonatomic) BOOL flushWallpaperAutomatically;	// G=0x112b59; S=0x112b69; @synthesize=_flushWallpaperAutomatically
@property(assign, nonatomic) BOOL usesFilter;	// G=0x112b49; S=0x1130f9; @synthesize=_usesFilter
@property(assign, nonatomic) float filterAlpha;	// G=0x113095; S=0x113015; 
@property(assign) float alpha;	// G=0x112fbd; S=0x112e1d; converted property
@property(readonly, assign) CGRect wallpaperContentsRect;	// G=0x112b25; converted property
- (id)initWithOrientation:(int)orientation variant:(int)variant;	// 0x1138dd
- (void)dealloc;	// 0x11384d
- (void)setImage:(id)image;	// 0x113779
- (void)_resetImage;	// 0x113745
- (void)_wallpaperChanged;	// 0x11370d
- (void)_setGradientImagesWithOrientation:(int)orientation;	// 0x1134d1
- (void)_setOrientation:(int)orientation duration:(double)duration force:(BOOL)force;	// 0x1132e9
// declared property setter: - (void)setOrientation:(int)orientation;	// 0x113269
- (void)setOrientation:(int)orientation duration:(double)duration;	// 0x113245
- (void)setViewAlpha:(float)alpha;	// 0x112bc9
// declared property setter: - (void)setUsesFilter:(BOOL)filter;	// 0x1130f9
// declared property getter: - (float)filterAlpha;	// 0x113095
// declared property setter: - (void)setFilterAlpha:(float)alpha;	// 0x113015
// converted property getter: - (float)alpha;	// 0x112fbd
// converted property setter: - (void)setAlpha:(float)alpha;	// 0x112e1d
// declared property setter: - (void)setGradientAlpha:(float)alpha;	// 0x112d65
- (BOOL)_shouldAnimatePropertyWithKey:(id)key;	// 0x112d05
- (id)gradientImageForInterfaceOrientation:(int)interfaceOrientation;	// 0x112cfd
// converted property getter: - (CGRect)wallpaperContentsRect;	// 0x112b25
- (void)replaceWallpaperWithImage:(id)image;	// 0x112ced
- (void)resetCurrentImageToWallpaper;	// 0x112cb5
- (void)didMoveToWindow;	// 0x112bf5
// declared property getter: - (BOOL)usesFilter;	// 0x112b49
// declared property getter: - (BOOL)flushWallpaperAutomatically;	// 0x112b59
// declared property setter: - (void)setFlushWallpaperAutomatically:(BOOL)automatically;	// 0x112b69
// declared property getter: - (BOOL)postsNotifications;	// 0x112b79
// declared property setter: - (void)setPostsNotifications:(BOOL)notifications;	// 0x112b89
// declared property getter: - (float)gradientAlpha;	// 0x112b99
// declared property getter: - (int)variant;	// 0x112ba9
// declared property getter: - (int)orientation;	// 0x112bb9
@end
