/**
 * This header is generated by class-dump-z 0.2b.
 *
 * Source: (null)
 */

#import "SBUnknownSuperclass.h"
#import "SpringBoard-Structs.h"

@class UIImageView, SBWallpaperView, UIView;

@interface SBWallpaperClipView : SBUnknownSuperclass {
	SBWallpaperView *_wallpaperView;	// 52 = 0x34
	UIImageView *_gradientView;	// 56 = 0x38
	int _orientation;	// 60 = 0x3c
	CGPoint _contentOffset;	// 64 = 0x40
	UIView *_maskView;	// 72 = 0x48
	BOOL _usesFilter;	// 76 = 0x4c
}
@property(retain, nonatomic) SBWallpaperView *wallpaperView;	// G=0x113a99; S=0x114141; @synthesize=_wallpaperView
@property(assign, nonatomic) CGPoint contentOffset;	// G=0x113a81; S=0x1140e5; @synthesize=_contentOffset
- (id)initWithFrame:(CGRect)frame wallpaperView:(id)view;	// 0x1142bd
- (void)dealloc;	// 0x113aa9
- (void)setFrame:(CGRect)frame;	// 0x1141f9
- (void)setWallpaperView:(id)view force:(BOOL)force;	// 0x114155
// declared property setter: - (void)setWallpaperView:(id)view;	// 0x114141
// declared property setter: - (void)setContentOffset:(CGPoint)offset;	// 0x1140e5
- (void)_setWallpaperAlpha:(float)alpha;	// 0x114055
- (void)_wallpaperImageChanged:(id)changed;	// 0x114015
- (void)_wallpaperFrameChanged:(id)changed;	// 0x113fd5
- (void)_wallpaperAlphaChanged:(id)changed;	// 0x113f7d
- (void)_gradientAlphaChanged:(id)changed;	// 0x113f15
- (void)_updateWallpaperImage;	// 0x113eb1
- (void)_updateMask;	// 0x113dc5
- (void)_recomputeGeometry;	// 0x113bc9
- (void)setMaskView:(id)view;	// 0x113b39
// declared property getter: - (CGPoint)contentOffset;	// 0x113a81
// declared property getter: - (id)wallpaperView;	// 0x113a99
@end
