/**
 * This header is generated by class-dump-z 0.2b.
 *
 * Source: (null)
 */

#import "SpringBoard-Structs.h"
#import "SBUnknownSuperclass.h"


@interface SBWaveView : SBUnknownSuperclass {
	float _phaseWidth;	// 48 = 0x30
	float _phaseShift;	// 52 = 0x34
	float _minAmplitude;	// 56 = 0x38
	float _maxAmplitude;	// 60 = 0x3c
	float _amplitude;	// 64 = 0x40
	float _levelDamping;	// 68 = 0x44
	double _phaseDuration;	// 72 = 0x48
	double _amplitudeChangeTime;	// 80 = 0x50
	double _amplitudeChangeDuration;	// 88 = 0x58
	float _lastAmplitude;	// 96 = 0x60
	float _level;	// 100 = 0x64
	BOOL _animating;	// 104 = 0x68
}
- (void)setFrame:(CGRect)frame;	// 0xe8d7d
- (void)setColor:(id)color;	// 0xe8ac1
- (void)setPhaseWidth:(float)width;	// 0xe8ae9
- (void)setPhaseShift:(float)shift;	// 0xe8b25
- (float)_phaseShift;	// 0xe9359
- (float)_currentAmplitude;	// 0xe92c1
- (void)_setAmplitude:(float)amplitude animated:(BOOL)animated;	// 0xe904d
- (void)setMinAmplitude:(float)amplitude;	// 0xe8b61
- (void)setMaxAmplitude:(float)amplitude;	// 0xe8bc9
- (void)setPhaseAnimationDuration:(double)duration;	// 0xe8ac5
- (void)setLevel:(float)level animated:(BOOL)animated;	// 0xe8c31
- (void)setLevelDamping:(float)damping;	// 0xe8ad9
- (float)_amplitudeForLevel:(float)level;	// 0xe9011
- (void)beginAnimating;	// 0xe8e15
- (void)stopAnimating;	// 0xe8c95
- (void)_finishedAnimating;	// 0xe8cf9
@end
