/**
 * This header is generated by class-dump-z 0.2b.
 *
 * Source: (null)
 */

#import "SBBulletinLinenBackedCell.h"

@class UIView, SBWeeApp;

@interface SBWeeAppCell : SBBulletinLinenBackedCell {
	SBWeeApp *_weeApp;	// 244 = 0xf4
	UIView *_weeAppView;	// 248 = 0xf8
	BOOL _useTopPadding;	// 252 = 0xfc
}
@property(retain, nonatomic) SBWeeApp *weeApp;	// G=0x153185; S=0x158531; @synthesize=_weeApp
+ (float)rowHeightForViewHeight:(float)viewHeight withTopPadding:(BOOL)topPadding;	// 0x15315d
- (id)initWithLinenView:(id)linenView reuseIdentifier:(id)identifier;	// 0x15815d
- (void)dealloc;	// 0x15864d
// declared property setter: - (void)setWeeApp:(id)app;	// 0x158531
- (void)setUsesTopPadding:(BOOL)padding;	// 0x158501
- (void)layoutSubviews;	// 0x158405
- (void)willMoveToWindow:(id)window;	// 0x1583a5
- (void)didMoveToWindow;	// 0x158335
- (void)prepareForReuse;	// 0x1582a1
- (void)_tapped:(id)tapped;	// 0x158209
// declared property getter: - (id)weeApp;	// 0x153185
@end

