/**
 * This header is generated by class-dump-z 0.2b.
 *
 * Source: (null)
 */

#import "SBApplicationIcon.h"


@interface SBWeatherApplicationIcon : SBApplicationIcon {
}
- (void)localeChanged;	// 0xc2571
@end

