/**
 * This header is generated by class-dump-z 0.2b.
 *
 * Source: (null)
 */

#import "SpringBoard-Structs.h"
#import "SBUnknownSuperclass.h"

@class NSString, NSRecursiveLock;

@interface SBWiFiManager : SBUnknownSuperclass {
	NSRecursiveLock *_lock;	// 4 = 0x4
	WiFiManagerClient *_manager;	// 8 = 0x8
	WiFiDeviceClient *_device;	// 12 = 0xc
	NSString *_deviceInterfaceName;	// 16 = 0x10
	WiFiNetwork *_currentNetwork;	// 20 = 0x14
	WiFiNetwork *_previousNetwork;	// 24 = 0x18
	BOOL _currentNetworkHasBeenSet;	// 28 = 0x1c
	BOOL _currentNetworkIsIOSHotspot;	// 29 = 0x1d
	BOOL _currentNetworkIsIOSHotspotHasBeenSet;	// 30 = 0x1e
	BOOL _powered;	// 31 = 0x1f
	BOOL _poweredHasBeenSet;	// 32 = 0x20
	int _rssiThreshold;	// 36 = 0x24
	int _signalStrengthBars;	// 40 = 0x28
	int _signalStrengthRSSI;	// 44 = 0x2c
	BOOL _signalStrengthHasBeenSet;	// 48 = 0x30
	BOOL _canPollSignalStrength;	// 49 = 0x31
	SCDynamicStoreRef _SCDynamicStoreNetworkState;	// 52 = 0x34
	dispatch_source_s *_SCUpdateTimeoutSource;	// 56 = 0x38
	WiFiNetwork *_primaryInterface;	// 60 = 0x3c
	BOOL _primaryInterfaceHasBeenSet;	// 64 = 0x40
	BOOL _isPrimaryInterface;	// 65 = 0x41
	BOOL _isPrimaryInterfaceChanging;	// 66 = 0x42
	double _lastSignalStrengthUpdateTime;	// 68 = 0x44
	dispatch_source_s *_signalStrengthTimerSource;	// 76 = 0x4c
}
@property(assign) BOOL wiFiEnabled;	// G=0x9d8e1; S=0x9d891; converted property
@property(readonly, assign, getter=isPowered) BOOL powered;	// G=0x9cdfd; converted property
@property(readonly, assign) int signalStrengthBars;	// G=0x9d821; converted property
@property(readonly, assign) int signalStrengthRSSI;	// G=0x9d7b1; converted property
@property(readonly, assign) BOOL isPrimaryInterface;	// G=0x9d1f9; converted property
+ (id)sharedInstance;	// 0x9d02d
- (id)init;	// 0x9e3f9
- (WiFiManagerClient *)_manager;	// 0x9e13d
- (void)_updateWiFiState;	// 0x9e04d
- (void)_powerStateDidChange;	// 0x9dfa9
- (void)_linkDidChange;	// 0x9df41
- (void)_updateWiFiDevice:(id)device;	// 0x9dda1
- (void)_updateCurrentNetwork;	// 0x9da11
- (BOOL)isAssociated;	// 0x9cd0d
- (BOOL)isAssociatedToIOSHotspot;	// 0x9d99d
- (BOOL)_cachedIsAssociated;	// 0x9cd85
- (id)currentNetworkName;	// 0x9d929
// converted property getter: - (BOOL)isPowered;	// 0x9cdfd
// converted property getter: - (BOOL)wiFiEnabled;	// 0x9d8e1
// converted property setter: - (void)setWiFiEnabled:(BOOL)enabled;	// 0x9d891
// converted property getter: - (int)signalStrengthBars;	// 0x9d821
// converted property getter: - (int)signalStrengthRSSI;	// 0x9d7b1
- (void)updateSignalStrength;	// 0x9d5a9
- (void)_updateSignalStrengthTimer;	// 0x9d411
- (id)knownNetworks;	// 0x9d3dd
- (void)resetSettings;	// 0x9d28d
// converted property getter: - (BOOL)isPrimaryInterface;	// 0x9d1f9
- (id)_wifiInterface;	// 0x9cf81
- (void)_primaryInterfaceChanged:(BOOL)changed;	// 0x9d059
@end
