/**
 * This header is generated by class-dump-z 0.2b.
 *
 * Source: (null)
 */

#import "SpringBoard-Structs.h"
#import "SBFolderNotchView.h"


@interface SBWoodNotchView : SBFolderNotchView {
}
+ (id)_keyComponentForNotchInfoRect:(CGRect)notchInfoRect;	// 0x14ae39
+ (id)_squareImageForNotchInfo:(XXStruct_9ihRqB)notchInfo orientation:(int)orientation;	// 0x14b0fd
@end

