/**
 * This header is generated by class-dump-z 0.2b.
 *
 * Source: (null)
 */

#import "SBUnknownSuperclass.h"
#import "SpringBoard-Structs.h"

@class NSMutableArray;

@interface SBZoomView : SBUnknownSuperclass {
	BOOL _hasImage;	// 46 = 0x2e
	BOOL _hasFullSizedImage;	// 47 = 0x2f
	BOOL _usesRoundedCorners;	// 48 = 0x30
	NSMutableArray *_cornerViews;	// 52 = 0x34
}
- (id)initWithFrame:(CGRect)frame;	// 0x58271
- (id)initWithSnapshotFrame:(CGRect)snapshotFrame image:(id)image originalImageOrientation:(int)orientation currentImageOrientation:(int)orientation4 interfaceOrientation:(int)orientation5 doubleHeightStatusBar:(BOOL)bar preventSplit:(BOOL)split chrome:(id)chrome chromeStatusBarHidden:(BOOL)hidden needsZoomFilter:(BOOL)filter;	// 0x575c9
- (id)initWithSnapshotFrame:(CGRect)snapshotFrame ioSurface:(void *)surface snapshotTransform:(CGAffineTransform)transform;	// 0x5746d
- (id)initWithImage:(id)image;	// 0x5733d
- (void)dealloc;	// 0x56f0d
- (int)_degreesForRotationFromInterfaceOrientation:(int)interfaceOrientation toInterfaceOrientation:(int)interfaceOrientation2;	// 0x56e31
- (int)_degreesForRotationFromOriginalImageOrientation:(int)originalImageOrientation toInterfaceOrientation:(int)interfaceOrientation;	// 0x56e71
- (CGSize)_rotateAndNormalizeSize:(CGSize)size withTransform:(CGAffineTransform)transform;	// 0x56e91
- (void)_createCornerViewsIfNecessaryWithCornersFrame:(CGRect)cornersFrame;	// 0x57131
- (void)setUsesRoundedCorners:(BOOL)corners withCornersFrame:(CGRect)cornersFrame;	// 0x56f9d
- (id)_chromeStatusBarImageForInterfaceOrientation:(int)interfaceOrientation;	// 0x56f59
@end
