/**
 * This header is generated by class-dump-z 0.2b.
 *
 * Source: (null)
 */




@protocol SUNetworkObserver <NSObject>
@optional
- (void)networkChangedFromNetworkType:(int)networkType toNetworkType:(int)networkType2;
- (void)cellularRoamingStatusChanged:(BOOL)changed;
- (void)carrierBundleChanged;
- (void)operatorBundleChanged;
@end

