/**
 * This header is generated by class-dump-z 0.2b.
 *
 * Source: (null)
 */




@protocol UIPopoverControllerDelegate <NSObject>
@optional
- (BOOL)popoverControllerShouldDismissPopover:(id)popoverController;
- (void)popoverControllerDidDismissPopover:(id)popoverController;
@end

