/**
 * This header is generated by class-dump-z 0.2b.
 *
 * Source: (null)
 */




@protocol UIPrintStatusDelegate <NSObject>
- (void)printStatusViewController:(id)controller didDismissWithCancel:(BOOL)cancel;
@optional
- (void)printStatusViewControllerJobDidCancel:(id)printStatusViewControllerJob;
@end

