/**
 * This header is generated by class-dump-z 0.2b.
 *
 * Source: (null)
 */




@protocol VSRecognitionSessionDelegate <NSObject>
@optional
- (BOOL)recognitionSessionWillBeginAction:(id)recognitionSession;
- (void)recognitionSessionDidBeginAction:(id)recognitionSession;
- (id)recognitionSession:(id)session openURL:(id)url;
- (void)recognitionSession:(id)session didFinishSpeakingFeedbackStringWithError:(id)error;
- (void)recognitionSession:(id)session didCompleteActionWithError:(id)error;
@end

