/**
 * This header is generated by class-dump-z 0.2b.
 *
 * Source: (null)
 */

#import "SpringBoard-Structs.h"
#import "SBManualKeyboardTextField.h"


@interface WhiteBorderedTextField : SBManualKeyboardTextField {
}
- (void)drawBorder:(CGRect)border;	// 0x59ec5
- (CGRect)textRect;	// 0x59e6d
- (void)drawRect:(CGRect)rect;	// 0x59e11
@end

